// Arabic meanings + common readings for the N5 kanji set (keyed by glyph).
// Consumed by buildKanjiStore (Phase 6 content layer) to enable real
// kanji → meaning recall. Readings are the most common on'yomi (katakana) /
// kun'yomi (hiragana); kept short.
export default {
  '一': { meaningAr: 'واحد', onyomi: ['イチ'], kunyomi: ['ひと-つ'] },
  '二': { meaningAr: 'اثنان', onyomi: ['ニ'], kunyomi: ['ふた-つ'] },
  '三': { meaningAr: 'ثلاثة', onyomi: ['サン'], kunyomi: ['みっ-つ'] },
  '四': { meaningAr: 'أربعة', onyomi: ['シ'], kunyomi: ['よん', 'よっ-つ'] },
  '五': { meaningAr: 'خمسة', onyomi: ['ゴ'], kunyomi: ['いつ-つ'] },
  '六': { meaningAr: 'ستة', onyomi: ['ロク'], kunyomi: ['むっ-つ'] },
  '七': { meaningAr: 'سبعة', onyomi: ['シチ'], kunyomi: ['なな', 'なな-つ'] },
  '八': { meaningAr: 'ثمانية', onyomi: ['ハチ'], kunyomi: ['やっ-つ'] },
  '九': { meaningAr: 'تسعة', onyomi: ['キュウ', 'ク'], kunyomi: ['ここの-つ'] },
  '十': { meaningAr: 'عشرة', onyomi: ['ジュウ'], kunyomi: ['とお'] },
  '百': { meaningAr: 'مئة', onyomi: ['ヒャク'], kunyomi: [] },
  '千': { meaningAr: 'ألف', onyomi: ['セン'], kunyomi: ['ち'] },
  '万': { meaningAr: 'عشرة آلاف', onyomi: ['マン', 'バン'], kunyomi: [] },
  '円': { meaningAr: 'ين / دائرة', onyomi: ['エン'], kunyomi: ['まる-い'] },
  '日': { meaningAr: 'يوم / شمس', onyomi: ['ニチ', 'ジツ'], kunyomi: ['ひ', 'か'] },
  '月': { meaningAr: 'شهر / قمر', onyomi: ['ゲツ', 'ガツ'], kunyomi: ['つき'] },
  '火': { meaningAr: 'نار', onyomi: ['カ'], kunyomi: ['ひ'] },
  '水': { meaningAr: 'ماء', onyomi: ['スイ'], kunyomi: ['みず'] },
  '木': { meaningAr: 'شجرة / خشب', onyomi: ['モク', 'ボク'], kunyomi: ['き'] },
  '金': { meaningAr: 'ذهب / مال', onyomi: ['キン', 'コン'], kunyomi: ['かね'] },
  '土': { meaningAr: 'تراب / أرض', onyomi: ['ド', 'ト'], kunyomi: ['つち'] },
  '曜': { meaningAr: 'يوم الأسبوع', onyomi: ['ヨウ'], kunyomi: [] },
  '年': { meaningAr: 'سنة', onyomi: ['ネン'], kunyomi: ['とし'] },
  '時': { meaningAr: 'وقت / ساعة', onyomi: ['ジ'], kunyomi: ['とき'] },
  '分': { meaningAr: 'دقيقة / يفهم', onyomi: ['ブン', 'フン'], kunyomi: ['わ-かる'] },
  '半': { meaningAr: 'نصف', onyomi: ['ハン'], kunyomi: ['なか-ば'] },
  '今': { meaningAr: 'الآن', onyomi: ['コン'], kunyomi: ['いま'] },
  '毎': { meaningAr: 'كل / كل مرة', onyomi: ['マイ'], kunyomi: [] },
  '何': { meaningAr: 'ماذا / كم', onyomi: ['カ'], kunyomi: ['なに', 'なん'] },
  '人': { meaningAr: 'شخص / إنسان', onyomi: ['ジン', 'ニン'], kunyomi: ['ひと'] },
  '男': { meaningAr: 'رجل / ذكر', onyomi: ['ダン', 'ナン'], kunyomi: ['おとこ'] },
  '女': { meaningAr: 'امرأة / أنثى', onyomi: ['ジョ'], kunyomi: ['おんな'] },
  '子': { meaningAr: 'طفل / ابن', onyomi: ['シ'], kunyomi: ['こ'] },
  '父': { meaningAr: 'أب', onyomi: ['フ'], kunyomi: ['ちち'] },
  '母': { meaningAr: 'أم', onyomi: ['ボ'], kunyomi: ['はは'] },
  '友': { meaningAr: 'صديق', onyomi: ['ユウ'], kunyomi: ['とも'] },
  '先': { meaningAr: 'قبل / سابق', onyomi: ['セン'], kunyomi: ['さき'] },
  '生': { meaningAr: 'حياة / يولد', onyomi: ['セイ', 'ショウ'], kunyomi: ['い-きる', 'う-まれる'] },
  '学': { meaningAr: 'دراسة / علم', onyomi: ['ガク'], kunyomi: ['まな-ぶ'] },
  '校': { meaningAr: 'مدرسة', onyomi: ['コウ'], kunyomi: [] },
  '本': { meaningAr: 'كتاب / أصل', onyomi: ['ホン'], kunyomi: ['もと'] },
  '語': { meaningAr: 'لغة / كلمة', onyomi: ['ゴ'], kunyomi: ['かた-る'] },
  '国': { meaningAr: 'دولة / بلد', onyomi: ['コク'], kunyomi: ['くに'] },
  '会': { meaningAr: 'اجتماع / يقابل', onyomi: ['カイ'], kunyomi: ['あ-う'] },
  '社': { meaningAr: 'شركة / معبد', onyomi: ['シャ'], kunyomi: ['やしろ'] },
  '店': { meaningAr: 'متجر', onyomi: ['テン'], kunyomi: ['みせ'] },
  '駅': { meaningAr: 'محطة', onyomi: ['エキ'], kunyomi: [] },
  '車': { meaningAr: 'سيارة / عربة', onyomi: ['シャ'], kunyomi: ['くるま'] },
  '電': { meaningAr: 'كهرباء', onyomi: ['デン'], kunyomi: [] },
  '気': { meaningAr: 'روح / مزاج / هواء', onyomi: ['キ', 'ケ'], kunyomi: [] },
  '天': { meaningAr: 'سماء', onyomi: ['テン'], kunyomi: ['あま'] },
  '雨': { meaningAr: 'مطر', onyomi: ['ウ'], kunyomi: ['あめ'] },
  '空': { meaningAr: 'سماء / فارغ', onyomi: ['クウ'], kunyomi: ['そら', 'あ-く'] },
  '山': { meaningAr: 'جبل', onyomi: ['サン'], kunyomi: ['やま'] },
  '川': { meaningAr: 'نهر', onyomi: ['セン'], kunyomi: ['かわ'] },
  '花': { meaningAr: 'زهرة', onyomi: ['カ'], kunyomi: ['はな'] },
  '魚': { meaningAr: 'سمك', onyomi: ['ギョ'], kunyomi: ['さかな', 'うお'] },
  '口': { meaningAr: 'فم', onyomi: ['コウ'], kunyomi: ['くち'] },
  '目': { meaningAr: 'عين', onyomi: ['モク'], kunyomi: ['め'] },
  '耳': { meaningAr: 'أذن', onyomi: ['ジ'], kunyomi: ['みみ'] },
  '手': { meaningAr: 'يد', onyomi: ['シュ'], kunyomi: ['て'] },
  '足': { meaningAr: 'قدم / يكفي', onyomi: ['ソク'], kunyomi: ['あし', 'た-りる'] },
  '力': { meaningAr: 'قوة', onyomi: ['リョク', 'リキ'], kunyomi: ['ちから'] },
  '上': { meaningAr: 'فوق / أعلى', onyomi: ['ジョウ'], kunyomi: ['うえ', 'あ-げる'] },
  '下': { meaningAr: 'تحت / أسفل', onyomi: ['カ', 'ゲ'], kunyomi: ['した', 'さ-げる'] },
  '中': { meaningAr: 'داخل / وسط', onyomi: ['チュウ'], kunyomi: ['なか'] },
  '外': { meaningAr: 'خارج', onyomi: ['ガイ'], kunyomi: ['そと', 'ほか'] },
  '右': { meaningAr: 'يمين', onyomi: ['ウ', 'ユウ'], kunyomi: ['みぎ'] },
  '左': { meaningAr: 'يسار', onyomi: ['サ'], kunyomi: ['ひだり'] },
  '前': { meaningAr: 'أمام / قبل', onyomi: ['ゼン'], kunyomi: ['まえ'] },
  '後': { meaningAr: 'خلف / بعد', onyomi: ['ゴ', 'コウ'], kunyomi: ['あと', 'うし-ろ'] },
  '北': { meaningAr: 'شمال', onyomi: ['ホク'], kunyomi: ['きた'] },
  '南': { meaningAr: 'جنوب', onyomi: ['ナン'], kunyomi: ['みなみ'] },
  '東': { meaningAr: 'شرق', onyomi: ['トウ'], kunyomi: ['ひがし'] },
  '西': { meaningAr: 'غرب', onyomi: ['セイ', 'サイ'], kunyomi: ['にし'] },
  '大': { meaningAr: 'كبير', onyomi: ['ダイ', 'タイ'], kunyomi: ['おお-きい'] },
  '小': { meaningAr: 'صغير', onyomi: ['ショウ'], kunyomi: ['ちい-さい', 'こ'] },
  '少': { meaningAr: 'قليل', onyomi: ['ショウ'], kunyomi: ['すく-ない', 'すこ-し'] },
  '多': { meaningAr: 'كثير', onyomi: ['タ'], kunyomi: ['おお-い'] },
  '長': { meaningAr: 'طويل / رئيس', onyomi: ['チョウ'], kunyomi: ['なが-い'] },
  '高': { meaningAr: 'عالٍ / غالٍ', onyomi: ['コウ'], kunyomi: ['たか-い'] },
  '安': { meaningAr: 'رخيص / آمن', onyomi: ['アン'], kunyomi: ['やす-い'] },
  '新': { meaningAr: 'جديد', onyomi: ['シン'], kunyomi: ['あたら-しい'] },
  '古': { meaningAr: 'قديم', onyomi: ['コ'], kunyomi: ['ふる-い'] },
  '白': { meaningAr: 'أبيض', onyomi: ['ハク'], kunyomi: ['しろ-い'] },
  '赤': { meaningAr: 'أحمر', onyomi: ['セキ'], kunyomi: ['あか-い'] },
  '青': { meaningAr: 'أزرق / أخضر', onyomi: ['セイ'], kunyomi: ['あお-い'] },
  '行': { meaningAr: 'يذهب', onyomi: ['コウ', 'ギョウ'], kunyomi: ['い-く', 'おこな-う'] },
  '来': { meaningAr: 'يأتي', onyomi: ['ライ'], kunyomi: ['く-る'] },
  '見': { meaningAr: 'يرى / ينظر', onyomi: ['ケン'], kunyomi: ['み-る'] },
  '聞': { meaningAr: 'يسمع / يسأل', onyomi: ['ブン'], kunyomi: ['き-く'] },
  '食': { meaningAr: 'يأكل / طعام', onyomi: ['ショク'], kunyomi: ['た-べる'] },
  '飲': { meaningAr: 'يشرب', onyomi: ['イン'], kunyomi: ['の-む'] },
  '読': { meaningAr: 'يقرأ', onyomi: ['ドク'], kunyomi: ['よ-む'] },
  '書': { meaningAr: 'يكتب', onyomi: ['ショ'], kunyomi: ['か-く'] },
  '話': { meaningAr: 'يتحدث / قصة', onyomi: ['ワ'], kunyomi: ['はな-す', 'はなし'] },
  '買': { meaningAr: 'يشتري', onyomi: ['バイ'], kunyomi: ['か-う'] },
  '休': { meaningAr: 'يستريح / إجازة', onyomi: ['キュウ'], kunyomi: ['やす-む'] },
  '出': { meaningAr: 'يخرج', onyomi: ['シュツ'], kunyomi: ['で-る', 'だ-す'] },
  '入': { meaningAr: 'يدخل', onyomi: ['ニュウ'], kunyomi: ['はい-る', 'い-れる'] },
  '立': { meaningAr: 'يقف', onyomi: ['リツ'], kunyomi: ['た-つ'] },
  '名': { meaningAr: 'اسم', onyomi: ['メイ', 'ミョウ'], kunyomi: ['な'] },
  '道': { meaningAr: 'طريق', onyomi: ['ドウ'], kunyomi: ['みち'] },
  '週': { meaningAr: 'أسبوع', onyomi: ['シュウ'], kunyomi: [] },
  '間': { meaningAr: 'بين / فترة', onyomi: ['カン', 'ケン'], kunyomi: ['あいだ', 'ま'] },
}
