export const lessonFifteen = {
  id: 15,
  title: { ar: 'الترتيب والإذن والمنع', en: 'Sequence, Permission, and Prohibition' },
  focus: 'てから للترتيب الزمني، てもいいです للإذن، و てはいけません للمنع',
  vocab: [
    { id: 'suimasu', type: 'verb', jp: '吸います', kanji: '吸います', hiragana: 'すいます', reading: 'suimasu', meaning: 'يدخّن / يستنشق' },
    { id: 'hairimasu', type: 'verb', jp: '入ります', kanji: '入ります', hiragana: 'はいります', reading: 'hairimasu', meaning: 'يدخل' },
    { id: 'demasu', type: 'verb', jp: '出ます', kanji: '出ます', hiragana: 'でます', reading: 'demasu', meaning: 'يخرج' },
    { id: 'suwarimasu', type: 'verb', jp: '座ります', kanji: '座ります', hiragana: 'すわります', reading: 'suwarimasu', meaning: 'يجلس' },
    { id: 'tachimasu', type: 'verb', jp: '立ちます', kanji: '立ちます', hiragana: 'たちます', reading: 'tachimasu', meaning: 'يقف' },
    { id: 'nugimasu', type: 'verb', jp: '脱ぎます', kanji: '脱ぎます', hiragana: 'ぬぎます', reading: 'nugimasu', meaning: 'يخلع (ملابس/حذاء)' },
    { id: 'tsukaimasu', type: 'verb', jp: '使います', kanji: '使います', hiragana: 'つかいます', reading: 'tsukaimasu', meaning: 'يستخدم' },
    { id: 'torimasu2', type: 'verb', jp: '撮ります', kanji: '撮ります', hiragana: 'とります', reading: 'torimasu', meaning: 'يلتقط (صورة)' },
    { id: 'kutsu', type: 'object', jp: '靴', kanji: '靴', hiragana: 'くつ', reading: 'kutsu', meaning: 'حذاء' },
    { id: 'toire', type: 'place', jp: 'トイレ', hiragana: 'トイレ', reading: 'toire', meaning: 'حمّام / دورة مياه' },
    { id: 'chuushajou', type: 'place', jp: '駐車場', kanji: '駐車場', hiragana: 'ちゅうしゃじょう', reading: 'chuushajou', meaning: 'موقف سيارات' },
    { id: 'chuusha_shimasu', type: 'verb', jp: '駐車します', kanji: '駐車します', hiragana: 'ちゅうしゃします', reading: 'chuusha shimasu', meaning: 'يوقف السيارة' },
    { id: 'roka', type: 'place', jp: '廊下', kanji: '廊下', hiragana: 'ろうか', reading: 'rouka', meaning: 'ممر / رواق' },
    { id: 'kega', type: 'noun', jp: 'けが', hiragana: 'けが', reading: 'kega', meaning: 'إصابة / جرح' },
    { id: 'shawaa', type: 'noun', jp: 'シャワー', hiragana: 'シャワー', reading: 'shawaa', meaning: 'دش' },
    { id: 'abimasu', type: 'verb', jp: '浴びます', kanji: '浴びます', hiragana: 'あびます', reading: 'abimasu', meaning: 'يستحم (تحت الدش)' },
    { id: 'arai_mono', type: 'verb', jp: '洗います', kanji: '洗います', hiragana: 'あらいます', reading: 'araimasu', meaning: 'يغسل' },
    { id: 'te_o_araimasu', type: 'expression', jp: '手を洗います', kanji: '手を洗います', hiragana: 'てをあらいます', reading: 'te o araimasu', meaning: 'يغسل يديه' },
    { id: 'shukudai2', type: 'noun', jp: '宿題', kanji: '宿題', hiragana: 'しゅくだい', reading: 'shukudai', meaning: 'واجب منزلي' },
    { id: 'denwa_bangou', type: 'noun', jp: '電話番号', kanji: '電話番号', hiragana: 'でんわばんごう', reading: 'denwa bangou', meaning: 'رقم الهاتف' },
    { id: 'yoyaku', type: 'noun', jp: '予約', kanji: '予約', hiragana: 'よやく', reading: 'yoyaku', meaning: 'حجز' },
    { id: 'kippu', type: 'object', jp: '切符', kanji: '切符', hiragana: 'きっぷ', reading: 'kippu', meaning: 'تذكرة' },
    { id: 'shashin_kinshi', type: 'expression', jp: '撮影禁止', kanji: '撮影禁止', hiragana: 'さつえいきんし', reading: 'satsuei kinshi', meaning: 'ممنوع التصوير' },
    { id: 'kinen', type: 'noun', jp: '禁煙', kanji: '禁煙', hiragana: 'きんえん', reading: 'kin\'en', meaning: 'ممنوع التدخين' },
  ],
  grammar: [
    {
      title: '〜てから — الترتيب الزمني',
      pattern: 'فعل1 て‐form + から、 فعل2',
      particle: 'てから',
      howItWorks: 'تستخدم てから لربط فعلين بحيث يحدث الفعل الأول أولا، ثم الفعل الثاني. تعني "بعد أن... / ثم".',
      explanation: 'تشبه から السببية في الشكل لكنها هنا تأتي مباشرة بعد صيغة て للفعل (وليس بعد جملة كاملة بـ です/ます).',
      example: { jp: '手 を 洗って から、 ご飯 を 食べます。', romaji: 'Te o aratte kara, gohan o tabemasu.', ar: 'بعد أن أغسل يدي، آكل الطعام.' },
      exercises: [
        {
          type: 'build',
          ar: 'بعد أن أنتهي من العمل، سأذهب إلى المنزل.',
          words: ['仕事', 'が', '終わって', 'から', '、', '家', 'へ', '帰ります', '。'],
          particles: ['が', 'から', 'へ'],
          answer: '仕事 が 終わって から 、 家 へ 帰ります 。',
        },
        {
          type: 'fill',
          ar: 'بعد أن أستحم، سأنام.',
          sentence: 'シャワー を 浴びて ___、 寝ます。',
          options: ['から', 'まで', 'ので', 'のに'],
          answer: 'から',
        },
        {
          type: 'meaning',
          sentence: '宿題 を して から、 テレビ を 見ます。',
          particle: 'てから',
          options: ['سأشاهد التلفاز بعد أن أنهي الواجب.', 'سأنهي الواجب بعد مشاهدة التلفاز.', 'لن أشاهد التلفاز ولن أنهي الواجب.', 'أشاهد التلفاز وأنا أحل الواجب.'],
          answer: 'سأشاهد التلفاز بعد أن أنهي الواجب.',
        },
        {
          type: 'error',
          ar: 'بعد أن أحجز، سأشتري التذكرة.',
          options: ['予約 して から、 切符 を 買います。', '予約 から して、 切符 を 買います。', '予約 して、 から 切符 を 買います。'],
          answer: '予約 して から、 切符 を 買います。',
        },
      ],
    },
    {
      title: '〜てもいいです — طلب الإذن',
      pattern: 'فعل て‐form + も + いいです (か)。',
      particle: 'てもいいです',
      howItWorks: 'تستخدم てもいいですか للسؤال عن الإذن "هل يجوز لي أن...؟"، والإجابة بالموافقة تكون بـ はい、いいです (نعم، لا بأس).',
      explanation: 'الترجمة الحرفية: "حتى لو فعلت كذا، فهو جيد" - أي لا مانع من فعله.',
      example: { jp: 'ここ で 写真 を 撮っても いいです か。', romaji: 'Koko de shashin o tottemo ii desu ka.', ar: 'هل يجوز أن ألتقط صورة هنا؟' },
      exercises: [
        {
          type: 'build',
          ar: 'هل يمكنني الجلوس هنا؟',
          words: ['ここ', 'に', '座っても', 'いいです', 'か', '。'],
          particles: ['に'],
          answer: 'ここ に 座っても いいです か 。',
        },
        {
          type: 'fill',
          ar: 'نعم، لا بأس. (إجابة بالموافقة)',
          sentence: 'はい、___ です。',
          options: ['いい', 'だめ', 'いけません', 'いきません'],
          answer: 'いい',
        },
        {
          type: 'meaning',
          sentence: 'A: この ペン を 使っても いいです か。 B: ええ、どうぞ。',
          particle: 'てもいいです',
          options: ['نعم، تفضل (يمكنك استخدامه).', 'لا، لا يمكن استخدامه.', 'لا أعرف من أين أحضرت القلم.', 'هذا القلم ليس لي.'],
          answer: 'نعم، تفضل (يمكنك استخدامه).',
        },
        {
          type: 'error',
          ar: 'هل يمكنني الدخول؟',
          options: ['入っても いいです か。', '入てもいいです か。', '入りてもいいです か。'],
          answer: '入っても いいです か。',
        },
      ],
    },
    {
      title: '〜てはいけません — المنع',
      pattern: 'فعل て‐form + は + いけません。',
      particle: 'てはいけません',
      howItWorks: 'تستخدم てはいけません للتعبير عن المنع القوي "ممنوع أن...". تستخدم في اللوائح والقوانين والتحذيرات.',
      explanation: 'في الكلام اليومي تُستبدل أحيانا بـ だめです (ممنوع/لا يصح) للتعبير غير الرسمي.',
      example: { jp: ' ここ で たばこ を 吸っては いけません。', romaji: 'Koko de tabako o suttewa ikemasen.', ar: 'ممنوع التدخين هنا.' },
      exercises: [
        {
          type: 'build',
          ar: 'ممنوع ركن السيارة هنا.',
          words: ['ここ', 'に', '駐車しては', 'いけません', '。'],
          particles: ['に'],
          answer: 'ここ に 駐車しては いけません 。',
        },
        {
          type: 'fill',
          ar: 'ممنوع الدخول إلى هذه الغرفة.',
          sentence: 'この 部屋 に 入って ___ いけません。',
          options: ['は', 'も', 'が', 'を'],
          answer: 'は',
        },
        {
          type: 'meaning',
          sentence: '図書館 で 大きい 声 で 話しては いけません。',
          particle: 'てはいけません',
          options: ['ممنوع التحدث بصوت عالٍ في المكتبة.', 'يمكن التحدث بصوت عالٍ في المكتبة.', 'المكتبة هادئة دائما.', 'لا يوجد أحد في المكتبة.'],
          answer: 'ممنوع التحدث بصوت عالٍ في المكتبة.',
        },
        {
          type: 'error',
          ar: 'ممنوع نسيان واجبك.',
          options: ['宿題 を 忘れては いけません。', '宿題 を 忘れて も いけません。', '宿題 を 忘れる は いけません。'],
          answer: '宿題 を 忘れては いけません。',
        },
      ],
    },
    {
      title: 'مراجعة て‐form في سياقات متعددة',
      pattern: 'てから／てもいいです／てはいけません',
      particle: 'て形 (مراجعة)',
      howItWorks: 'هذه الصيغ الثلاث جميعها تعتمد على إتقان تكوين て‐form بشكل صحيح. التدرب على التحويل السريع من الفعل الأساسي (ます‐form) إلى て‐form ضروري قبل استخدام أي من هذه القواعد.',
      explanation: 'نصيحة: احفظ الأفعال الشاذة أولا (します→して، 来ます→来て، 行きます→行って)، ثم اربط القواعد الثلاث بمواقف يومية: تعليمات (てください)، تسلسل (てから)، إذن (てもいいです)، منع (てはいけません).',
      example: { jp: 'シートベルト を して から、 運転して ください。 シートベルト を しなくては いけません。', romaji: 'Shiitoberuto o shite kara, unten shite kudasai.', ar: 'اربط حزام الأمان ثم قُد السيارة. يجب ربط حزام الأمان.' },
      exercises: [
        {
          type: 'build',
          ar: 'اخلع حذاءك قبل الدخول. (بعد الخلع، ادخل)',
          words: ['靴', 'を', '脱いで', 'から', '、', '入って', 'ください', '。'],
          particles: ['を', 'から'],
          answer: '靴 を 脱いで から 、 入って ください 。',
        },
        {
          type: 'fill',
          ar: 'هل يمكنني فتح النافذة؟',
          sentence: '窓 を 開けて ___ いいです か。',
          options: ['も', 'は', 'が', 'に'],
          answer: 'も',
        },
        {
          type: 'meaning',
          sentence: 'この 部屋 で 食べたり 飲んだり しては いけません。',
          particle: 'てはいけません',
          options: ['ممنوع الأكل أو الشرب في هذه الغرفة.', 'يمكن الأكل والشرب في هذه الغرفة.', 'هذه الغرفة مخصصة للأكل فقط.', 'لا يوجد طعام في هذه الغرفة.'],
          answer: 'ممنوع الأكل أو الشرب في هذه الغرفة.',
        },
        {
          type: 'error',
          ar: 'بعد أن تنتهي من القراءة، أعده لي من فضلك.',
          options: ['読んで から、 返して ください。', '読んでは から、 返して ください。', '読んでも から、 返して ください。'],
          answer: '読んで から、 返して ください。',
        },
      ],
    },
  ],
  examples: [
    { jp: '朝ご飯 を 食べて から、 学校 へ 行きます。', romaji: 'Asagohan o tabete kara, gakkou e ikimasu.', ar: 'بعد تناول الإفطار، أذهب إلى المدرسة.', en: 'After eating breakfast, I go to school.' },
    { jp: 'すみません、ここ に 座っても いいです か。', romaji: 'Sumimasen, koko ni suwattemo ii desu ka.', ar: 'عفوا، هل يمكنني الجلوس هنا؟', en: 'Excuse me, may I sit here?' },
    { jp: 'はい、どうぞ。', romaji: 'Hai, douzo.', ar: 'نعم، تفضل.', en: 'Yes, go ahead.' },
    { jp: 'すみません、ここ で たばこ を 吸っては いけません。', romaji: 'Sumimasen, koko de tabako o suttewa ikemasen.', ar: 'عفوا، ممنوع التدخين هنا.', en: 'Excuse me, you may not smoke here.' },
    { jp: '靴 を 脱いで から、 部屋 に 入って ください。', romaji: 'Kutsu o nuide kara, heya ni haitte kudasai.', ar: 'اخلع حذاءك ثم ادخل الغرفة من فضلك.', en: 'Please take off your shoes, then enter the room.' },
    { jp: 'この 中 で 写真 を 撮っても いいです か。 ／ いいえ、 撮っては いけません。', romaji: 'Kono naka de shashin o tottemo ii desu ka. / Iie, tottewa ikemasen.', ar: 'هل يجوز التصوير في الداخل؟ / لا، ممنوع التصوير.', en: 'May I take photos inside? / No, you may not.' },
    { jp: '電話 を かけて から、 行きます。', romaji: 'Denwa o kakete kara, ikimasu.', ar: 'سأذهب بعد أن أجري الاتصال.', en: 'I’ll go after making a phone call.' },
    { jp: 'テスト の 時 、 辞書 を 使っては いけません。', romaji: 'Tesuto no toki, jisho o tsukattewa ikemasen.', ar: 'ممنوع استخدام القاموس وقت الاختبار.', en: 'You may not use a dictionary during the test.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 宿題 を して から、 寝ます。', answer: 'سأنام بعد أن أنهي الواجب.', hint: 'てから للترتيب' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: ここ に 入っては いけません。', answer: 'ممنوع الدخول هنا.', hint: 'てはいけません للمنع' },
    { type: 'complete', prompt: 'أكمل: 名前 を 書いて ___ いいです か。', answer: 'も', hint: 'طلب الإذن' },
    { type: 'complete', prompt: 'أكمل: ここ で 走って ___ いけません。', answer: 'は', hint: 'المنع' },
    { type: 'complete', prompt: 'أكمل: 手 を 洗って ___、 食べます。', answer: 'から', hint: 'الترتيب الزمني' },
    { type: 'order', prompt: 'رتب: いいです / トイレ / を / 使っても / か', answer: 'トイレ を 使っても いいです か。', hint: 'طلب الإذن' },
    { type: 'order', prompt: 'رتب: シャワー / 浴びて / 寝ます / から / を', answer: 'シャワー を 浴びて から 寝ます。', hint: 'てから' },
    { type: 'answer', prompt: 'ここ で 写真 を 撮っても いいです か。 (はい)', answer: 'はい、いいです。', hint: 'الموافقة على الإذن' },
    { type: 'answer', prompt: 'ここ で たばこ を 吸っても いいです か。 (いいえ)', answer: 'いいえ、吸っては いけません。', hint: 'المنع' },
  ],
  videos: [],
}
