export const lessonEleven = {
  id: 11,
  title: { ar: 'المدة والسبب وحالة الإنجاز', en: 'Duration, Reason, and Completion' },
  focus: 'مدة الزمن بـ ぐらい، السبب بـ から، الموعد النهائي بـ までに، و もう/まだ',
  vocab: [
    { id: 'jikan', type: 'noun', jp: '時間', kanji: '時間', hiragana: 'じかん', reading: 'jikan', meaning: 'وقت / ساعة (مدة)' },
    { id: 'ichijikan', type: 'duration', jp: '一時間', kanji: '一時間', hiragana: 'いちじかん', reading: 'ichijikan', meaning: 'ساعة واحدة (مدة)' },
    { id: 'sanjuppun', type: 'duration', jp: '三十分', kanji: '三十分', hiragana: 'さんじゅっぷん', reading: 'sanjuppun', meaning: 'ثلاثون دقيقة' },
    { id: 'gurai', type: 'particle', jp: 'ぐらい', hiragana: 'ぐらい', reading: 'gurai', meaning: 'تقريبا / حوالي' },
    { id: 'kara2', type: 'particle', jp: 'から', hiragana: 'から', reading: 'kara', meaning: 'لأن (سبب)' },
    { id: 'mou', type: 'adverb', jp: 'もう', hiragana: 'もう', reading: 'mou', meaning: 'بالفعل / من الآن' },
    { id: 'mada', type: 'adverb', jp: 'まだ', hiragana: 'まだ', reading: 'mada', meaning: 'لم يزل / ليس بعد' },
    { id: 'made_ni', type: 'particle', jp: 'までに', hiragana: 'までに', reading: 'made ni', meaning: 'بحلول (موعد نهائي)' },
    { id: 'shukudai', type: 'noun', jp: '宿題', kanji: '宿題', hiragana: 'しゅくだい', reading: 'shukudai', meaning: 'واجب منزلي' },
    { id: 'owarimasu', type: 'verb', jp: '終わります', kanji: '終わります', hiragana: 'おわります', reading: 'owarimasu', meaning: 'ينتهي' },
    { id: 'hajimarimasu', type: 'verb', jp: '始まります', kanji: '始まります', hiragana: 'はじまります', reading: 'hajimarimasu', meaning: 'يبدأ' },
    { id: 'yasumimasu', type: 'verb', jp: '休みます', kanji: '休みます', hiragana: 'やすみます', reading: 'yasumimasu', meaning: 'يستريح / يتغيب' },
    { id: 'tsukaremasu', type: 'verb', jp: '疲れます', kanji: '疲れます', hiragana: 'つかれます', reading: 'tsukaremasu', meaning: 'يتعب' },
    { id: 'byouki', type: 'noun', jp: '病気', kanji: '病気', hiragana: 'びょうき', reading: 'byouki', meaning: 'مرض' },
    { id: 'kaigi', type: 'noun', jp: '会議', kanji: '会議', hiragana: 'かいぎ', reading: 'kaigi', meaning: 'اجتماع' },
    { id: 'repooto2', type: 'noun', jp: 'レポート', hiragana: 'レポート', reading: 'repooto', meaning: 'تقرير' },
    { id: 'hyaku', type: 'number', jp: '百', kanji: '百', hiragana: 'ひゃく', reading: 'hyaku', meaning: '100' },
    { id: 'sen', type: 'number', jp: '千', kanji: '千', hiragana: 'せん', reading: 'sen', meaning: '1000' },
    { id: 'man', type: 'number', jp: '万', kanji: '万', hiragana: 'まん', reading: 'man', meaning: '10000' },
    { id: 'isogashii2', type: 'i-adjective', jp: '忙しい', kanji: '忙しい', hiragana: 'いそがしい', reading: 'isogashii', meaning: 'مشغول' },
    { id: 'genki', type: 'na-adjective', jp: '元気', kanji: '元気', hiragana: 'げんき', reading: 'genki', meaning: 'بصحة جيدة / نشيط' },
    { id: 'netsu', type: 'noun', jp: '熱', kanji: '熱', hiragana: 'ねつ', reading: 'netsu', meaning: 'حمى' },
    { id: 'gakkou2', type: 'place', jp: '学校', kanji: '学校', hiragana: 'がっこう', reading: 'gakkou', meaning: 'مدرسة' },
    { id: 'shiken', type: 'noun', jp: '試験', kanji: '試験', hiragana: 'しけん', reading: 'shiken', meaning: 'امتحان' },
    { id: 'mou_ichido', type: 'expression', jp: 'もう一度', kanji: 'もう一度', hiragana: 'もういちど', reading: 'mou ichido', meaning: 'مرة أخرى' },
  ],
  grammar: [
    {
      title: 'ぐらい — التقريب الزمني',
      pattern: 'مدة + ぐらい',
      particle: 'ぐらい',
      howItWorks: 'تأتي ぐらい بعد مدة زمنية أو كمية للدلالة على "تقريبا" أو "حوالي". تستخدم مع المدد (一時間ぐらい) وليس مع نقاط الزمن المحددة.',
      explanation: 'لا تخلط بين ぐらい (تقريب الكمية/المدة) و ごろ (تقريب نقطة الزمن، مثل 7時ごろ - حوالي الساعة السابعة).',
      example: { jp: '毎日 一時間 ぐらい 勉強 します。', romaji: 'Mainichi ichijikan gurai benkyou shimasu.', ar: 'أدرس حوالي ساعة كل يوم.' },
      exercises: [
        {
          type: 'build',
          ar: 'انتظرت حوالي ثلاثين دقيقة.',
          words: ['三十分', 'ぐらい', '待ちました', '。'],
          particles: ['ぐらい'],
          answer: '三十分 ぐらい 待ちました 。',
        },
        {
          type: 'fill',
          ar: 'كم من الوقت تستغرق إلى المدرسة تقريبا؟',
          sentence: '学校 まで どの ぐらい ___ か。',
          options: ['かかります', '行きます', 'あります', 'します'],
          answer: 'かかります',
        },
        {
          type: 'meaning',
          sentence: '東京 から 大阪 まで 三時間 ぐらい かかります。',
          particle: 'ぐらい',
          options: ['تستغرق الرحلة من طوكيو إلى أوساكا حوالي ثلاث ساعات.', 'الرحلة من طوكيو إلى أوساكا ثلاث ساعات بالضبط.', 'لا أعرف المدة.', 'أوساكا أبعد من طوكيو بثلاث ساعات.'],
          answer: 'تستغرق الرحلة من طوكيو إلى أوساكا حوالي ثلاث ساعات.',
        },
        {
          type: 'error',
          ar: 'نمت حوالي سبع ساعات.',
          options: ['七時間 ぐらい 寝ました。', '七時 ぐらい 寝ました。', '七時間 ごろ 寝ました。'],
          answer: '七時間 ぐらい 寝ました。',
        },
      ],
    },
    {
      title: 'から — السبب',
      pattern: 'جملة1 (سبب) + から、 جملة2 (نتيجة)。',
      particle: 'から',
      howItWorks: 'تأتي から في نهاية الجملة الأولى التي تحوي السبب، تليها فاصلة ثم الجملة الثانية (النتيجة). الفعل في جملة السبب يبقى بصيغته العادية (です/ます).',
      explanation: 'الترتيب في اليابانية عكس العربية: السبب أولا ثم النتيجة. مثال: 忙しいですから、休みません (لأنني مشغول، لن أستريح).',
      example: { jp: '今日 は 忙しい です から、 行きません。', romaji: 'Kyou wa isogashii desu kara, ikimasen.', ar: 'لن أذهب لأنني مشغول اليوم.' },
      exercises: [
        {
          type: 'build',
          ar: 'لأنني متعب، سأستريح اليوم.',
          words: ['疲れました', 'から', '、', '今日', '休みます', '。'],
          particles: ['から'],
          answer: '疲れました から 、 今日 休みます 。',
        },
        {
          type: 'fill',
          ar: 'لأن هذا الكتاب صعب، لا أفهمه.',
          sentence: 'この 本 は 難しい です ___、 わかりません。',
          options: ['から', 'ので', 'まで', 'けど'],
          answer: 'から',
        },
        {
          type: 'meaning',
          sentence: '熱 が あります から、 休みます。',
          particle: 'から',
          options: ['سأستريح لأن لدي حمى.', 'سأذهب رغم الحمى.', 'الحمى انتهت.', 'لا أعرف سبب الحمى.'],
          answer: 'سأستريح لأن لدي حمى.',
        },
        {
          type: 'error',
          ar: 'لأن غدا اختبار، سأدرس الليلة.',
          options: ['明日 試験 です から、 今晩 勉強 します。', '今晩 勉強 します から、 明日 試験 です。', '明日 試験 から です、 今晩 勉強 します。'],
          answer: '明日 試験 です から、 今晩 勉強 します。',
        },
      ],
    },
    {
      title: 'もう と まだ — الإنجاز وعدمه',
      pattern: 'もう + فعل (مثبت) ／ まだ + فعل (منفي)',
      particle: 'もう・まだ',
      howItWorks: 'もう + جملة مثبتة تعني "بالفعل/سبق أن". まだ + جملة منفية تعني "ليس بعد". まだ وحدها (بدون فعل) تعني "لا يزال" بمعنى الاستمرار.',
      explanation: 'سؤال شائع: もう〜ましたか (هل فعلت كذا بالفعل؟). الجواب: はい、もう〜ました (نعم، فعلت بالفعل) أو いいえ、まだです (لا، ليس بعد).',
      example: { jp: 'A: もう 昼ご飯 を 食べました か。 B: いいえ、まだ です。', romaji: 'Mou hirugohan o tabemashita ka. / Iie, mada desu.', ar: 'هل تناولت الغداء بالفعل؟ / لا، ليس بعد.' },
      exercises: [
        {
          type: 'build',
          ar: 'انتهيت من الواجب بالفعل.',
          words: ['もう', '宿題', 'を', '終わりました', '。'],
          particles: [],
          answer: 'もう 宿題 を 終わりました 。',
        },
        {
          type: 'fill',
          ar: 'لم أقرأ هذا الكتاب بعد.',
          sentence: 'この 本 は ___ 読んで いません。',
          options: ['まだ', 'もう', 'ぐらい', 'だけ'],
          answer: 'まだ',
        },
        {
          type: 'meaning',
          sentence: 'A: レポート は もう 書きました か。 B: いいえ、まだ です。',
          particle: 'もう・まだ',
          options: ['لا، لم أكتب التقرير بعد.', 'نعم، كتبت التقرير بالفعل.', 'سأكتب التقرير غدا فقط.', 'التقرير مكتوب من قبل شخص آخر.'],
          answer: 'لا، لم أكتب التقرير بعد.',
        },
        {
          type: 'error',
          ar: 'الاجتماع لم ينته بعد.',
          options: ['会議 は まだ 終わって いません。', '会議 は もう 終わって いません。', '会議 は まだ 終わりました。'],
          answer: '会議 は まだ 終わって いません。',
        },
      ],
    },
    {
      title: 'までに — الموعد النهائي',
      pattern: 'وقت/زمن + までに + فعل',
      particle: 'までに',
      howItWorks: 'تختلف までに عن まで: まで تعني "حتى" (استمرارية)، بينما までに تعني "بحلول" أو "في موعد أقصاه" (يجب إنجاز الفعل قبل أو عند هذا الوقت).',
      explanation: 'مقارنة: 五時まで 働きます (أعمل حتى الساعة الخامسة - استمرار) مقابل 五時までに レポートを 出します (أسلّم التقرير في موعد أقصاه الساعة الخامسة - حدث نقطي).',
      example: { jp: '金曜日 までに レポート を 出して ください。', romaji: 'Kinyoubi made ni repooto o dashite kudasai.', ar: 'سلّم التقرير بحلول يوم الجمعة من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'سأنتهي من الواجب بحلول الغد.',
          words: ['明日', 'までに', '宿題', 'を', '終わります', '。'],
          particles: ['までに', 'を'],
          answer: '明日 までに 宿題 を 終わります 。',
        },
        {
          type: 'fill',
          ar: 'أعمل حتى الساعة الخامسة كل يوم. (استمرارية)',
          sentence: '毎日 五時 ___ 働きます。',
          options: ['まで', 'までに', 'ぐらい', 'から'],
          answer: 'まで',
        },
        {
          type: 'meaning',
          sentence: '九時 までに 来て ください。',
          particle: 'までに',
          options: ['تعال في موعد أقصاه التاسعة من فضلك.', 'تعال بعد التاسعة من فضلك.', 'انتظرني حتى التاسعة.', 'العمل ينتهي في التاسعة.'],
          answer: 'تعال في موعد أقصاه التاسعة من فضلك.',
        },
        {
          type: 'error',
          ar: 'يجب أن ينتهي الاجتماع بحلول الساعة الثالثة.',
          options: ['会議 は 三時 までに 終わります。', '会議 は 三時 まで 終わります。', '会議 は 三時 までに から 終わります。'],
          answer: '会議 は 三時 までに 終わります。',
        },
      ],
    },
  ],
  examples: [
    { jp: '駅 から 家 まで 二十分 ぐらい かかります。', romaji: 'Eki kara ie made nijuppun gurai kakarimasu.', ar: 'تستغرق الرحلة من المحطة إلى المنزل حوالي عشرين دقيقة.', en: 'It takes about 20 minutes from the station to my house.' },
    { jp: '熱 が あります から、 今日 は 学校 を 休みます。', romaji: 'Netsu ga arimasu kara, kyou wa gakkou o yasumimasu.', ar: 'سأتغيب عن المدرسة اليوم لأن لدي حمى.', en: 'I’ll be absent from school today because I have a fever.' },
    { jp: 'もう 宿題 を しました。', romaji: 'Mou shukudai o shimashita.', ar: 'فعلت الواجب بالفعل.', en: 'I’ve already done the homework.' },
    { jp: 'まだ 食べて いません。', romaji: 'Mada tabete imasen.', ar: 'لم آكل بعد.', en: 'I haven’t eaten yet.' },
    { jp: '来週 までに レポート を 書きます。', romaji: 'Raishuu made ni repooto o kakimasu.', ar: 'سأكتب التقرير بحلول الأسبوع القادم.', en: 'I’ll write the report by next week.' },
    { jp: '会議 は 二時間 ぐらい かかりました。', romaji: 'Kaigi wa nijikan gurai kakarimashita.', ar: 'استغرق الاجتماع حوالي ساعتين.', en: 'The meeting took about two hours.' },
    { jp: '試験 は もう 終わりました か。', romaji: 'Shiken wa mou owarimashita ka.', ar: 'هل انتهى الاختبار بالفعل؟', en: 'Has the exam already ended?' },
    { jp: '元気 です から、 心配 しないで ください。', romaji: 'Genki desu kara, shinpai shinaide kudasai.', ar: 'أنا بخير، فلا تقلق.', en: 'I’m fine, so please don’t worry.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 一時間 ぐらい 待ちました。', answer: 'انتظرت حوالي ساعة.', hint: 'ぐらい للمدة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: もう 終わりました。', answer: 'انتهيت بالفعل.', hint: 'もう للإنجاز' },
    { type: 'complete', prompt: 'أكمل: 病気 です ___、 病院 へ 行きます。', answer: 'から', hint: 'السبب' },
    { type: 'complete', prompt: 'أكمل: A: もう 食べました か。 B: いいえ、___ です。', answer: 'まだ', hint: 'النفي بـ まだ' },
    { type: 'complete', prompt: 'أكمل: 来月 ___ お金 を 返します。 (موعد نهائي)', answer: 'までに', hint: 'الموعد النهائي' },
    { type: 'order', prompt: 'رتب: ぐらい / かかります / どの / 学校 まで', answer: '学校 まで どの ぐらい かかります か。', hint: 'السؤال عن المدة (أضف か)' },
    { type: 'order', prompt: 'رتب: から / 忙しい / です / 休みません', answer: '忙しい です から、 休みません。', hint: 'السبب والنتيجة' },
    { type: 'answer', prompt: 'もう レポート を 出しました か。 (いいえ)', answer: 'いいえ、まだ です。', hint: 'الإجابة بالنفي' },
    { type: 'answer', prompt: 'どうして 休みます か。 (熱があります)', answer: '熱 が あります から、 休みます。', hint: 'الإجابة بالسبب' },
  ],
  videos: [],
}
