export const lessonFourteen = {
  id: 14,
  title: { ar: 'صيغة て والطلب والاستمرارية', en: 'The Te-Form, Requests, and Ongoing Actions' },
  focus: 'تكوين صيغة て للأفعال، استخدامها في てください للطلب، و ています للفعل المستمر أو الحالة',
  dialogue: {
    titleAr: 'لحظة من فضلك — طلبات في المكتب',
    lines: [
      { speaker: 'ساتو', jp: 'ミラーさん、ちょっと 待ってください。', romaji: 'Miraa-san, chotto matte kudasai.', ar: 'سيد ميلر، انتظر لحظة من فضلك.' },
      { speaker: 'ميلر', jp: 'はい、何ですか。', romaji: 'Hai, nan desu ka.', ar: 'نعم، ما الأمر؟' },
      { speaker: 'ساتو', jp: '暑いですね。エアコンを つけてください。', romaji: 'Atsui desu ne. Eakon o tsukete kudasai.', ar: 'الجو حار. شغّل المكيف من فضلك.' },
      { speaker: 'ميلر', jp: 'はい。窓も 開けましょうか。', romaji: 'Hai. Mado mo akemashou ka.', ar: 'حاضر. هل أفتح النافذة أيضًا؟' },
      { speaker: 'ساتو', jp: 'お願いします。今 何を していますか。', romaji: 'Onegai shimasu. Ima nani o shite imasu ka.', ar: 'من فضلك. ماذا تفعل الآن؟' },
      { speaker: 'ميلر', jp: 'レポートを 書いています。', romaji: 'Repooto o kaite imasu.', ar: 'أكتب التقرير.' },
    ],
  },
  reading: {
    titleAr: 'صديقي — أين يعيش وماذا يفعل',
    sentences: [
      { jp: '私の 友達は 東京に 住んでいます。', romaji: 'Watashi no tomodachi wa Toukyou ni sunde imasu.', ar: 'صديقي يعيش في طوكيو.' },
      { jp: '銀行で 働いています。', romaji: 'Ginkou de hataraite imasu.', ar: 'ويعمل في بنك.' },
      { jp: '彼は 結婚しています。', romaji: 'Kare wa kekkon shite imasu.', ar: 'إنه متزوج.' },
      { jp: '毎朝 新聞を 読んでいます。', romaji: 'Maiasa shinbun o yonde imasu.', ar: 'يقرأ الجريدة كل صباح.' },
      { jp: 'めがねを かけています。', romaji: 'Megane o kakete imasu.', ar: 'ويرتدي نظارة.' },
    ],
    questions: [
      { q: 'أين يعيش صديق الكاتب؟', options: ['في طوكيو', 'في كيوتو', 'في المطار'], answer: 'في طوكيو' },
      { q: 'أين يعمل؟', options: ['في بنك', 'في مدرسة', 'في مستشفى'], answer: 'في بنك' },
      { q: 'ماذا يقرأ كل صباح؟', options: ['الجريدة', 'كتابًا', 'رسالة'], answer: 'الجريدة' },
    ],
  },
  vocab: [
    { id: 'mochimasu', type: 'verb', jp: '持ちます', kanji: '持ちます', hiragana: 'もちます', reading: 'mochimasu', meaning: 'يحمل / يملك' },
    { id: 'machimasu', type: 'verb', jp: '待ちます', kanji: '待ちます', hiragana: 'まちます', reading: 'machimasu', meaning: 'ينتظر' },
    { id: 'isogimasu', type: 'verb', jp: '急ぎます', kanji: '急ぎます', hiragana: 'いそぎます', reading: 'isogimasu', meaning: 'يسرع' },
    { id: 'asobimasu2', type: 'verb', jp: '遊びます', kanji: '遊びます', hiragana: 'あそびます', reading: 'asobimasu', meaning: 'يلعب / يستمتع' },
    { id: 'shinimasu', type: 'verb', jp: '死にます', kanji: '死にます', hiragana: 'しにます', reading: 'shinimasu', meaning: 'يموت' },
    { id: 'keshimasu', type: 'verb', jp: '消します', kanji: '消します', hiragana: 'けします', reading: 'keshimasu', meaning: 'يطفئ / يحذف' },
    { id: 'tsukemasu', type: 'verb', jp: 'つけます', hiragana: 'つけます', reading: 'tsukemasu', meaning: 'يشغّل (جهاز)' },
    { id: 'akemasu', type: 'verb', jp: '開けます', kanji: '開けます', hiragana: 'あけます', reading: 'akemasu', meaning: 'يفتح' },
    { id: 'shimemasu2', type: 'verb', jp: '閉めます', kanji: '閉めます', hiragana: 'しめます', reading: 'shimemasu', meaning: 'يغلق' },
    { id: 'sumimasu', type: 'verb', jp: '住みます', kanji: '住みます', hiragana: 'すみます', reading: 'sumimasu', meaning: 'يسكن / يعيش' },
    { id: 'shirimasu', type: 'verb', jp: '知ります', kanji: '知ります', hiragana: 'しります', reading: 'shirimasu', meaning: 'يعرف (يكتسب معرفة)' },
    { id: 'kekkon_shiteimasu', type: 'expression', jp: '結婚しています', kanji: '結婚しています', hiragana: 'けっこんしています', reading: 'kekkon shiteimasu', meaning: 'متزوج (حالة)' },
    { id: 'eakon', type: 'object', jp: 'エアコン', hiragana: 'エアコン', reading: 'eakon', meaning: 'مكيف هواء' },
    { id: 'erebeetaa', type: 'object', jp: 'エレベーター', hiragana: 'エレベーター', reading: 'erebeetaa', meaning: 'مصعد' },
    { id: 'shashin2', type: 'noun', jp: '写真', kanji: '写真', hiragana: 'しゃしん', reading: 'shashin', meaning: 'صورة' },
    { id: 'denki', type: 'object', jp: '電気', kanji: '電気', hiragana: 'でんき', reading: 'denki', meaning: 'كهرباء / إضاءة' },
    { id: 'shokuji', type: 'noun', jp: '食事', kanji: '食事', hiragana: 'しょくじ', reading: 'shokuji', meaning: 'وجبة' },
    { id: 'mou_sukoshi', type: 'expression', jp: 'もう少し', kanji: 'もう少し', hiragana: 'もうすこし', reading: 'mou sukoshi', meaning: 'القليل بعد' },
    { id: 'kekka', type: 'noun', jp: '結果', kanji: '結果', hiragana: 'けっか', reading: 'kekka', meaning: 'نتيجة' },
    { id: 'media2', type: 'noun', jp: '新聞', kanji: '新聞', hiragana: 'しんぶん', reading: 'shinbun', meaning: 'جريدة' },
    { id: 'kuukou2', type: 'place', jp: '空港', kanji: '空港', hiragana: 'くうこう', reading: 'kuukou', meaning: 'مطار' },
    { id: 'megane', type: 'object', jp: 'めがね', hiragana: 'めがね', reading: 'megane', meaning: 'نظارة' },
    { id: 'kakemasu', type: 'verb', jp: 'かけます', hiragana: 'かけます', reading: 'kakemasu', meaning: 'يضع/يرتدي (نظارة، الخ)' },
    { id: 'shitsumon', type: 'noun', jp: '質問', kanji: '質問', hiragana: 'しつもん', reading: 'shitsumon', meaning: 'سؤال' },
  ],
  grammar: [
    {
      title: 'تكوين صيغة て (グループ１)',
      pattern: 'فعل ます‐stem → て‐form',
      particle: 'て形',
      howItWorks: 'الأفعال من المجموعة الأولى (う-verbs) تتحول حسب نهايتها: う/つ/る → って، ぬ/ぶ/む → んで، く → いて (استثناء: 行きます→行って)، ぐ → いで، す → して.',
      explanation: 'أمثلة: 待ちます→待って، 飲みます→飲んで، 書きます→書いて، 急ぎます→急いで، 話します→話して، 行きます→行って (شاذ).',
      example: { jp: '待ちます → 待って', romaji: 'machimasu → matte', ar: 'ينتظر → (صيغة て)' },
      exercises: [
        {
          type: 'build',
          ar: 'حول 飲みます إلى صيغة て.',
          words: ['飲みます', '→', '飲んで'],
          particles: [],
          answer: '飲みます → 飲んで',
        },
        {
          type: 'fill',
          ar: '書きます في صيغة て هي؟',
          sentence: '書きます → ___',
          options: ['書いて', '書んで', '書って', '書きて'],
          answer: '書いて',
        },
        {
          type: 'meaning',
          sentence: '行きます → 行って (شكل شاذ)',
          particle: 'て形',
          options: ['行きます استثناء، تصبح 行って وليس 行いて.', '行きます مثل باقي الأفعال المنتهية بـ く.', '行きます من المجموعة الثانية.', '行きます لا تتحول إلى صيغة て.'],
          answer: '行きます استثناء، تصبح 行って وليس 行いて.',
        },
        {
          type: 'error',
          ar: 'حول 急ぎます (يسرع) إلى صيغة て.',
          options: ['急いで', '急して', '急いて', '急んで'],
          answer: '急いで',
        },
      ],
    },
    {
      title: 'تكوين صيغة て (グループ２・３)',
      pattern: 'る-verb (group 2): る → て ／ します→して、 来ます→来て',
      particle: 'て形',
      howItWorks: 'الأفعال من المجموعة الثانية (る-verbs) تحذف る وتضيف て مباشرة: 食べます→食べて، 見ます→見て. الأفعال غير المنتظمة (المجموعة الثالثة): します→して، 来ます→来て.',
      explanation: 'تذكر دائما الفعلين الشاذين الأساسيين: します (يفعل) → して، و来ます (يأتي) → 来て (きて).',
      example: { jp: '食べます → 食べて', romaji: 'tabemasu → tabete', ar: 'يأكل → (صيغة て)' },
      exercises: [
        {
          type: 'build',
          ar: 'حول 見ます إلى صيغة て.',
          words: ['見ます', '→', '見て'],
          particles: [],
          answer: '見ます → 見て',
        },
        {
          type: 'fill',
          ar: 'します في صيغة て هي؟',
          sentence: 'します → ___',
          options: ['して', 'しって', 'しいて', 'すて'],
          answer: 'して',
        },
        {
          type: 'meaning',
          sentence: '来ます → 来て (きて)',
          particle: 'て形',
          options: ['来ます فعل شاذ، صيغة て هي 来て (きて).', '来ます من المجموعة الأولى.', '来ます تتحول مثل 行きます.', '来ます لا تستخدم في صيغة て.'],
          answer: '来ます فعل شاذ، صيغة て هي 来て (きて).',
        },
        {
          type: 'error',
          ar: 'حول 起きます (يستيقظ) إلى صيغة て.',
          options: ['起きて', '起きって', '起いて', '起きいて'],
          answer: '起きて',
        },
      ],
    },
    {
      title: '〜てください — الطلب المهذب',
      pattern: 'فعل て‐form + ください。',
      particle: 'てください',
      howItWorks: 'تستخدم てください لإعطاء أمر أو طلب مهذب، بمعنى "من فضلك افعل...". تأتي بعد صيغة て للفعل مباشرة.',
      explanation: 'يمكن جعلها أكثر تهذيبا بحذف ください والاكتفاء بصيغة て مع نبرة لطيفة في الكلام اليومي بين الأصدقاء.',
      example: { jp: 'ここ に 名前 を 書いて ください。', romaji: 'Koko ni namae o kaite kudasai.', ar: 'اكتب اسمك هنا من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'افتح النافذة من فضلك.',
          words: ['窓', 'を', '開けて', 'ください', '。'],
          particles: ['を'],
          answer: '窓 を 開けて ください 。',
        },
        {
          type: 'fill',
          ar: 'انتظر قليلا من فضلك.',
          sentence: 'ちょっと ___ ください。',
          options: ['待って', '待ちて', '待んで', '待たって'],
          answer: '待って',
        },
        {
          type: 'meaning',
          sentence: 'すみません、もう一度 言って ください。',
          particle: 'てください',
          options: ['عفوا، قل ذلك مرة أخرى من فضلك.', 'عفوا، لا تقل ذلك مرة أخرى.', 'عفوا، ماذا قلت؟', 'عفوا، لم أسمعك.'],
          answer: 'عفوا، قل ذلك مرة أخرى من فضلك.',
        },
        {
          type: 'error',
          ar: 'أطفئ التلفاز من فضلك.',
          options: ['テレビ を 消して ください。', 'テレビ を 消んで ください。', 'テレビ が 消して ください。'],
          answer: 'テレビ を 消して ください。',
        },
      ],
    },
    {
      title: '〜ています — الفعل المستمر والحالة',
      pattern: 'فعل て‐form + います。',
      particle: 'ています',
      howItWorks: 'لها معنيان: (1) فعل يحدث الآن (مستمر): 今 本 を 読んでいます (أنا أقرأ كتابا الآن). (2) حالة دائمة بعد فعل تغيير: 結婚しています (متزوج)، 住んでいます (يسكن في)، 知っています (يعرف).',
      explanation: 'في حالة 知る، النفي 知りません (وليس 知っていません) يعني "لا أعرف" - حالة خاصة يجب حفظها.',
      example: { jp: '田中さん は 今 電話 を かけています。', romaji: 'Tanaka-san wa ima denwa o kaketeimasu.', ar: 'السيد تاناكا يجري مكالمة هاتفية الآن.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعيش في طوكيو الآن.',
          words: ['私', 'は', '今', '東京', 'に', '住んでいます', '。'],
          particles: ['は', 'に'],
          answer: '私 は 今 東京 に 住んでいます 。',
        },
        {
          type: 'fill',
          ar: 'أخي يقرأ جريدة الآن.',
          sentence: '兄 は 今 新聞 を 読んで ___。',
          options: ['います', 'です', 'ます', 'いません'],
          answer: 'います',
        },
        {
          type: 'meaning',
          sentence: 'A: 山田さん を 知っていますか。 B: いいえ、知りません。',
          particle: 'ています',
          options: ['لا، لا أعرف السيد ياماموتو.', 'نعم، أعرفه جيدا.', 'سأتعرف عليه قريبا.', 'هو يعرفني.'],
          answer: 'لا، لا أعرف السيد ياماموتو.',
        },
        {
          type: 'error',
          ar: 'هي ترتدي نظارة.',
          options: ['彼女 は めがね を かけています。', '彼女 は めがね が かけます。', '彼女 は めがね を かけます いる。'],
          answer: '彼女 は めがね を かけています。',
        },
      ],
    },
  ],
  examples: [
    { jp: '電気 を つけて ください。', romaji: 'Denki o tsukete kudasai.', ar: 'شغّل الإضاءة من فضلك.', en: 'Please turn on the light.' },
    { jp: 'ちょっと 待って ください。', romaji: 'Chotto matte kudasai.', ar: 'انتظر قليلا من فضلك.', en: 'Please wait a moment.' },
    { jp: '今 雨 が 降っています。', romaji: 'Ima ame ga futteimasu.', ar: 'تمطر الآن.', en: 'It’s raining now.' },
    { jp: '私 は 大阪 に 住んでいます。', romaji: 'Watashi wa Oosaka ni sundeimasu.', ar: 'أنا أعيش في أوساكا.', en: 'I live in Osaka.' },
    { jp: '兄 は 結婚しています。', romaji: 'Ani wa kekkon shiteimasu.', ar: 'أخي الكبير متزوج.', en: 'My older brother is married.' },
    { jp: 'すみません、写真 を 撮って ください。', romaji: 'Sumimasen, shashin o totte kudasai.', ar: 'عفوا، التقط لنا صورة من فضلك.', en: 'Excuse me, please take a photo.' },
    { jp: '今 何 を していますか。', romaji: 'Ima nani o shiteimasu ka.', ar: 'ماذا تفعل الآن؟', en: 'What are you doing now?' },
    { jp: 'レポート を 書いています。', romaji: 'Repooto o kaiteimasu.', ar: 'أنا أكتب تقريرا.', en: 'I’m writing a report.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: ドア を 閉めて ください。', answer: 'أغلق الباب من فضلك.', hint: 'てください' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 弟 は テレビ を 見ています。', answer: 'أخي الصغير يشاهد التلفاز الآن.', hint: 'ています للفعل المستمر' },
    { type: 'complete', prompt: 'أكمل: 飲みます → ___ (て形)', answer: '飲んで', hint: 'む → んで' },
    { type: 'complete', prompt: 'أكمل: ここ で ___ ください。 (待ちます)', answer: '待って', hint: 'つ → って' },
    { type: 'complete', prompt: 'أكمل: 私 は 田中さん を 知って ___。', answer: 'います', hint: 'حالة المعرفة' },
    { type: 'order', prompt: 'رتب: ください / もう一度 / て / 言っ', answer: 'もう一度 言って ください。', hint: 'てください' },
    { type: 'order', prompt: 'رتب: います / 今 / 食べて / 私 / は / ご飯 / を', answer: '私 は 今 ご飯 を 食べています。', hint: 'ています المستمر' },
    { type: 'answer', prompt: 'すみません、エアコン を つけて くれます か。 (はい)', answer: 'はい、わかりました。', hint: 'الموافقة على الطلب' },
    { type: 'answer', prompt: '今 何 を していますか。 (宿題をします)', answer: '宿題 を しています。', hint: 'الإجابة بـ ています' },
  ],
  videos: [],
}
