export const lessonTwentyThree = {
  id: 23,
  title: { ar: 'صيغة المبني للمجهول والنية', en: 'Passive Form and Intention' },
  focus: 'مقدمة عن 受身形 (المبني للمجهول) و つもりです للتعبير عن النية/الخطة',
  dialogue: {
    titleAr: 'حديث عن المهرجان والخطط المستقبلية',
    lines: [
      { speaker: 'ساتو', jp: 'この 祭り は 毎年 行われますか。', romaji: 'Kono matsuri wa maitoshi okonawaremasu ka.', ar: 'هل يُقام هذا المهرجان كل سنة؟' },
      { speaker: 'ميلر', jp: 'はい。 この 祭り は 100年前 から 行われています。', romaji: 'Hai. Kono matsuri wa hyaku-nen mae kara okonawarete imasu.', ar: 'نعم. هذا المهرجان يُقام منذ 100 سنة.' },
      { speaker: 'ساتو', jp: 'すごいですね。 私 は 友達 に 誘われました。', romaji: 'Sugoi desu ne. Watashi wa tomodachi ni sasowaremashita.', ar: 'رائع. لقد دعاني صديقي.' },
      { speaker: 'ميلر', jp: '私 も 見に行く つもりです。', romaji: 'Watashi mo mi ni iku tsumori desu.', ar: 'أنا أيضا أنوي الذهاب لمشاهدته.' },
      { speaker: 'ساتو', jp: 'ミラーさん は 卒業 した あと で、 何 を する つもりですか。', romaji: 'Miraa-san wa sotsugyou shita ato de, nani o suru tsumori desu ka.', ar: 'سيد ميلر، ماذا تنوي أن تفعل بعد التخرج؟' },
      { speaker: 'ميلر', jp: '日本 で 就職する つもりです。 国 に 帰らない つもりです。', romaji: 'Nihon de shuushoku suru tsumori desu. Kuni ni kaeranai tsumori desu.', ar: 'أنوي الالتحاق بعمل في اليابان. أنوي ألا أعود إلى وطني.' },
      { speaker: 'ساتو', jp: 'いい ですね。 将来 は 経済学 の 研究 を する つもりですか。', romaji: 'Ii desu ne. Shourai wa keizaigaku no kenkyuu o suru tsumori desu ka.', ar: 'جميل. هل تنوي إجراء بحث في علم الاقتصاد في المستقبل؟' },
      { speaker: 'ميلر', jp: 'はい、 その つもりです。', romaji: 'Hai, sono tsumori desu.', ar: 'نعم، هذه نيتي.' },
    ],
  },
  reading: {
    titleAr: 'المهرجان وخطتي',
    sentences: [
      { jp: '私 の 町 の 祭り は 毎年 行われます。', romaji: 'Watashi no machi no matsuri wa maitoshi okonawaremasu.', ar: 'مهرجان مدينتي يُقام كل سنة.' },
      { jp: 'この 祭り は 世界中 で 知られています。', romaji: 'Kono matsuri wa sekaijuu de shirarete imasu.', ar: 'هذا المهرجان معروف في جميع أنحاء العالم.' },
      { jp: '今年 私 は 友達 に 誘われました。', romaji: 'Kotoshi watashi wa tomodachi ni sasowaremashita.', ar: 'هذا العام دعاني صديقي.' },
      { jp: '私 は 友達 と 一緒に 見に行く つもりです。', romaji: 'Watashi wa tomodachi to issho ni mi ni iku tsumori desu.', ar: 'أنوي الذهاب لمشاهدته مع صديقي.' },
      { jp: '卒業 した あと で、 日本 で 就職する つもりです。', romaji: 'Sotsugyou shita ato de, nihon de shuushoku suru tsumori desu.', ar: 'بعد التخرج، أنوي الالتحاق بعمل في اليابان.' },
    ],
    questions: [
      { q: 'متى يُقام مهرجان المدينة؟', options: ['كل سنة', 'مرة واحدة فقط', 'كل عشر سنوات'], answer: 'كل سنة' },
      { q: 'من الذي دعا الكاتب هذا العام؟', options: ['صديقه', 'المعلم', 'أخوه'], answer: 'صديقه' },
      { q: 'ماذا ينوي الكاتب أن يفعل بعد التخرج؟', options: ['الالتحاق بعمل في اليابان', 'العودة إلى وطنه', 'دراسة علم الاقتصاد'], answer: 'الالتحاق بعمل في اليابان' },
    ],
  },
  vocab: [
    { id: 'sasoimasu', type: 'verb', jp: '誘います', kanji: '誘います', hiragana: 'さそいます', reading: 'sasoimasu', meaning: 'يدعو' },
    { id: 'shikarimasu', type: 'verb', jp: '叱ります', kanji: '叱ります', hiragana: 'しかります', reading: 'shikarimasu', meaning: 'يوبخ' },
    { id: 'homemasu', type: 'verb', jp: '褒めます', kanji: '褒めます', hiragana: 'ほめます', reading: 'homemasu', meaning: 'يمدح' },
    { id: 'nusumimasu', type: 'verb', jp: '盗みます', kanji: '盗みます', hiragana: 'ぬすみます', reading: 'nusumimasu', meaning: 'يسرق' },
    { id: 'tatemasu', type: 'verb', jp: '建てます', kanji: '建てます', hiragana: 'たてます', reading: 'tatemasu', meaning: 'يبني' },
    { id: 'nenmae', type: 'expression', jp: '〜年前', kanji: '〜年前', hiragana: '〜ねんまえ', reading: '~nen mae', meaning: 'منذ ... سنة' },
    { id: 'sekai_jyu', type: 'expression', jp: '世界中', kanji: '世界中', hiragana: 'せかいじゅう', reading: 'sekaijuu', meaning: 'في جميع أنحاء العالم' },
    { id: 'yomaremasu', type: 'verb', jp: '読まれます', kanji: '読まれます', hiragana: 'よまれます', reading: 'yomaremasu', meaning: 'يُقرأ (مبني للمجهول)' },
    { id: 'tsukuraremasu', type: 'verb', jp: '作られます', kanji: '作られます', hiragana: 'つくられます', reading: 'tsukuraremasu', meaning: 'يُصنع (مبني للمجهول)' },
    { id: 'okonawaremasu', type: 'verb', jp: '行われます', kanji: '行われます', hiragana: 'おこなわれます', reading: 'okonawaremasu', meaning: 'يُقام / يُجرى (حدث)' },
    { id: 'matsuri', type: 'noun', jp: '祭り', kanji: '祭り', hiragana: 'まつり', reading: 'matsuri', meaning: 'مهرجان' },
    { id: 'maitoshi', type: 'noun', jp: '毎年', kanji: '毎年', hiragana: 'まいとし', reading: 'maitoshi', meaning: 'كل سنة' },
    { id: 'gakkari', type: 'expression', jp: 'がっかりします', kanji: 'がっかりします', hiragana: 'がっかりします', reading: 'gakkari shimasu', meaning: 'يشعر بخيبة أمل' },
    { id: 'tsumori', type: 'expression', jp: 'つもりです', hiragana: 'つもりです', reading: 'tsumori desu', meaning: 'ينوي / يخطط لـ' },
    { id: 'shuushoku', type: 'noun', jp: '就職', kanji: '就職', hiragana: 'しゅうしょく', reading: 'shuushoku', meaning: 'التوظيف / الالتحاق بعمل' },
    { id: 'sotsugyou2', type: 'noun', jp: '卒業', kanji: '卒業', hiragana: 'そつぎょう', reading: 'sotsugyou', meaning: 'تخرج' },
    { id: 'kekkonshimasu', type: 'verb', jp: '結婚します', kanji: '結婚します', hiragana: 'けっこんします', reading: 'kekkonshimasu', meaning: 'يتزوج' },
    { id: 'shourai', type: 'noun', jp: '将来', kanji: '将来', hiragana: 'しょうらい', reading: 'shourai', meaning: 'المستقبل' },
    { id: 'kuni_ni_kaeru', type: 'expression', jp: '国に帰ります', kanji: '国に帰ります', hiragana: 'くににかえります', reading: 'kuni ni kaerimasu', meaning: 'يعود إلى وطنه' },
    { id: 'keizaigaku', type: 'noun', jp: '経済学', kanji: '経済学', hiragana: 'けいざいがく', reading: 'keizaigaku', meaning: 'علم الاقتصاد' },
    { id: 'kenkyuu', type: 'noun', jp: '研究', kanji: '研究', hiragana: 'けんきゅう', reading: 'kenkyuu', meaning: 'بحث' },
    { id: 'eikaiwa', type: 'noun', jp: '英会話', kanji: '英会話', hiragana: 'えいかいわ', reading: 'eikaiwa', meaning: 'محادثة إنجليزية' },
    { id: 'kayoimasu', type: 'verb', jp: '通います', kanji: '通います', hiragana: 'かよいます', reading: 'kayoimasu', meaning: 'يتردد على (مكان بانتظام)' },
    { id: 'osowarimasu', type: 'verb', jp: '教わります', kanji: '教わります', hiragana: 'おそわります', reading: 'osowarimasu', meaning: 'يتعلم من (شخص)' },
  ],
  grammar: [
    {
      title: '受身形 (المبني للمجهول) — تكوين الفعل',
      pattern: 'グループ1: あ段+れます ／ グループ2: 〜られます ／ グループ3: されます・来られます',
      particle: '受身形',
      howItWorks: 'لتكوين صيغة المبني للمجهول: المجموعة الأولى (う-verbs) نغير آخر حرف من الصف う إلى الصف あ ونضيف れます (例: 読む → 読まれます). المجموعة الثانية (る-verbs) نحذف ます ونضيف られます (見ます → 見られます). الفعلان الشاذان: します → されます، 来ます → 来られます.',
      explanation: 'الفعل المبني للمجهول يحول الجملة بحيث يصبح المفعول به (الشيء الذي وقع عليه الفعل) هو موضوع الجملة، والفاعل الأصلي يصبح مع に.',
      example: { jp: 'この 本 は 有名な 作家 に 書かれました。', romaji: 'Kono hon wa yuumeina sakka ni kakaremashita.', ar: 'هذا الكتاب كُتب من قبل كاتب مشهور.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذه القلعة بُنيت منذ 400 سنة.',
          words: ['この', '城', 'は', '400年前', 'に', '建てられました', '。'],
          particles: ['は', 'に'],
          answer: 'この 城 は 400年前 に 建てられました 。',
        },
        {
          type: 'fill',
          ar: 'هذه اللغة تُستخدم في جميع أنحاء العالم.',
          sentence: 'この 言語 は 世界中 で ___。',
          options: ['使われています', '使います', '使って います', '使う'],
          answer: '使われています',
        },
        {
          type: 'meaning',
          sentence: 'この 歌 は みんな に 知られて います。',
          particle: '受身形',
          options: ['هذه الأغنية معروفة لدى الجميع.', 'لا أحد يعرف هذه الأغنية.', 'سأغني هذه الأغنية غدا.', 'هذه الأغنية صعبة.'],
          answer: 'هذه الأغنية معروفة لدى الجميع.',
        },
        {
          type: 'error',
          ar: 'هذه السيارات تُصنع في اليابان.',
          options: ['この 車 は 日本 で 作ります。', 'この 車 は 日本 で 作られて います。', 'この 車 は 日本 で 作る られます。'],
          answer: 'この 車 は 日本 で 作られて います。',
        },
      ],
    },
    {
      title: '受身形 — التأثر بفعل شخص آخر (مبني للمجهول الإزعاجي)',
      pattern: 'شخص(は) + شخص آخر(に) + فعل مبني للمجهول',
      particle: '受身形 (迷惑)',
      howItWorks: 'يستخدم المبني للمجهول أيضا للتعبير عن تأثر شخص (غالبا سلبيا) بفعل شخص آخر، حتى لو كان الفعل في الأصل لازما (لا يأخذ مفعولا به). الشخص المتأثر يصبح موضوع الجملة بـ は، والفاعل الأصلي يأخذ に.',
      explanation: 'مثال: 私 は 兄 に ケーキ を 食べられました (أكل أخي الكيكة - وأنا تأثرت سلبا، ربما كانت كيكتي). لاحظ أن هذا تركيب خاص باليابانية يصعب ترجمته حرفيا.',
      example: { jp: '私 は 先生 に 叱られました。', romaji: 'Watashi wa sensei ni shikararemashita.', ar: 'تم توبيخي من قبل المعلم (المعلم وبخني).' },
      exercises: [
        {
          type: 'build',
          ar: 'مدحني المعلم.',
          words: ['私', 'は', '先生', 'に', '褒められました', '。'],
          particles: ['は', 'に'],
          answer: '私 は 先生 に 褒められました 。',
        },
        {
          type: 'fill',
          ar: 'سُرقت محفظتي (تم سرقة محفظتي مني).',
          sentence: '私 は 財布 を ___。',
          options: ['盗まれました', '盗みました', '盗んで います', '盗む'],
          answer: '盗まれました',
        },
        {
          type: 'meaning',
          sentence: '弟 に ケーキ を 食べられました。',
          particle: '受身形 (迷惑)',
          options: ['أخي أكل الكيكة (وأنا تضايقت من ذلك).', 'أكلت كيكة أخي.', 'لم يأكل أخي شيئا.', 'سأعطي أخي كيكة.'],
          answer: 'أخي أكل الكيكة (وأنا تضايقت من ذلك).',
        },
        {
          type: 'error',
          ar: 'في طفولتي، كان والدي يوبخني كثيرا.',
          options: ['子供 の とき、 よく 父 に 叱られました。', '子供 の とき、 よく 父 を 叱りました。', '子供 の とき、 よく 父 が 叱られました。'],
          answer: '子供 の とき、 よく 父 に 叱られました。',
        },
      ],
    },
    {
      title: '〜つもりです — النية/الخطة',
      pattern: 'فعل (辞書形/ない形) + つもりです',
      particle: 'つもりです',
      howItWorks: 'تستخدم つもりです بعد الفعل في صيغة القاموس للتعبير عن نية أو خطة مستقبلية (أقوى من ます العادية في التعبير عن "أنوي/أخطط"). للنفي: 行かない つもりです (أنوي ألا أذهب).',
      explanation: 'الفرق بين つもりです و ます: ます تخبر فقط بفعل مستقبلي، أما つもりです تؤكد أن هذا قرار/نية مدروسة من المتكلم.',
      example: { jp: '卒業 した あと で、 国 に 帰る つもりです。', romaji: 'Sotsugyou shita ato de, kuni ni kaeru tsumori desu.', ar: 'بعد التخرج، أنوي العودة إلى وطني.' },
      exercises: [
        {
          type: 'build',
          ar: 'أنوي دراسة الاقتصاد في الجامعة.',
          words: ['大学', 'で', '経済学', 'を', '勉強する', 'つもりです', '。'],
          particles: ['で', 'を'],
          answer: '大学 で 経済学 を 勉強する つもりです 。',
        },
        {
          type: 'fill',
          ar: 'أنوي ألا أشرب الخمر بعد الآن.',
          sentence: 'もう お酒 を ___ つもりです。',
          options: ['飲まない', '飲みません', '飲んで', '飲む'],
          answer: '飲まない',
        },
        {
          type: 'meaning',
          sentence: '来年 結婚する つもりです。',
          particle: 'つもりです',
          options: ['أنوي الزواج العام القادم.', 'تزوجت العام الماضي.', 'لن أتزوج أبدا.', 'أخي سيتزوج.'],
          answer: 'أنوي الزواج العام القادم.',
        },
        {
          type: 'error',
          ar: 'في المستقبل، أنوي العمل في اليابان.',
          options: ['将来、 日本 で 働きます つもりです。', '将来、 日本 で 働く つもりです。', '将来、 日本 で 働いた つもりです。'],
          answer: '将来、 日本 で 働く つもりです。',
        },
      ],
    },
    {
      title: 'مراجعة شاملة: 受身形 و つもりです',
      pattern: 'دمج القاعدتين في جمل',
      particle: 'مراجعة',
      howItWorks: 'في هذا الدرس تعلمنا تكوين المبني للمجهول لوصف الأحداث/الأشياء (هذا الكتاب كُتب...) وللتعبير عن التأثر السلبي (تم توبيخي)، بالإضافة إلى つもりです للتعبير عن النوايا والخطط المستقبلية.',
      explanation: 'مثال مدمج: 来年 も この 祭り は 行われる でしょう。 私 は 見に行く つもりです (سيُقام هذا المهرجان العام القادم أيضا على الأرجح. أنوي الذهاب لمشاهدته).',
      example: { jp: 'この 祭り は 毎年 行われます。 来年 も 見に行く つもりです。', romaji: 'Kono matsuri wa maitoshi okonawaremasu. Rainen mo mi ni iku tsumori desu.', ar: 'هذا المهرجان يُقام كل سنة. أنوي الذهاب لمشاهدته العام القادم أيضا.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذه الجامعة تأسست منذ 100 سنة.',
          words: ['この', '大学', 'は', '100年前', 'に', '建てられました', '。'],
          particles: ['は', 'に'],
          answer: 'この 大学 は 100年前 に 建てられました 。',
        },
        {
          type: 'fill',
          ar: 'بعد التخرج، أنوي الالتحاق بعمل.',
          sentence: '卒業 した あと で、 ___ つもりです。',
          options: ['就職する', '就職します', '就職した', '就職して'],
          answer: '就職する',
        },
        {
          type: 'meaning',
          sentence: '私 は 兄 に 宿題 を 手伝って もらいました が、 でも まだ がっかりして います。',
          particle: '受身形/もらう',
          options: ['أخي ساعدني في الواجب، لكنني ما زلت محبطا.', 'أخي لم يساعدني أبدا.', 'أنا ساعدت أخي في الواجب.', 'انتهى الواجب بسهولة دون مشاكل.'],
          answer: 'أخي ساعدني في الواجب، لكنني ما زلت محبطا.',
        },
        {
          type: 'error',
          ar: 'أنوي الذهاب إلى محادثة اللغة الإنجليزية كل أسبوع.',
          options: ['毎週 英会話 に 通う つもりです。', '毎週 英会話 に 通います つもりです。', '毎週 英会話 に 通った つもりです。'],
          answer: '毎週 英会話 に 通う つもりです。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'この 本 は 有名な 作家 に 書かれました。', romaji: 'Kono hon wa yuumeina sakka ni kakaremashita.', ar: 'هذا الكتاب كُتب من قبل كاتب مشهور.', en: 'This book was written by a famous author.' },
    { jp: '私 は 先生 に 褒められました。', romaji: 'Watashi wa sensei ni homeraremashita.', ar: 'مدحني المعلم.', en: 'I was praised by the teacher.' },
    { jp: '私 は 電車 の 中 で 足 を 踏まれました。', romaji: 'Watashi wa densha no naka de ashi o fumaremashita.', ar: 'تم دوس قدمي في القطار.', en: 'My foot was stepped on in the train.' },
    { jp: 'この 祭り は 毎年 行われます。', romaji: 'Kono matsuri wa maitoshi okonawaremasu.', ar: 'هذا المهرجان يُقام كل سنة.', en: 'This festival is held every year.' },
    { jp: '来年 大学院 で 研究 を する つもりです。', romaji: 'Rainen daigakuin de kenkyuu o suru tsumori desu.', ar: 'أنوي إجراء بحث في الدراسات العليا العام القادم.', en: 'I plan to do research in graduate school next year.' },
    { jp: '今年 は 国 に 帰らない つもりです。', romaji: 'Kotoshi wa kuni ni kaeranai tsumori desu.', ar: 'أنوي ألا أعود إلى وطني هذا العام.', en: 'I plan not to go back to my country this year.' },
    { jp: 'この 寺 は 何年 前 に 建てられました か。', romaji: 'Kono tera wa nan-nen mae ni tateraremashita ka.', ar: 'منذ كم سنة بُني هذا المعبد؟', en: 'How many years ago was this temple built?' },
    { jp: '弟 に パソコン を 壊されました。', romaji: 'Otouto ni pasokon o kowasaremashita.', ar: 'أخي كسر حاسوبي (تأثرت سلبا).', en: 'My brother broke my computer (and I was inconvenienced).' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: この 歌 は 世界中 で 歌われて います。', answer: 'هذه الأغنية تُغنى في جميع أنحاء العالم.', hint: '受身形' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 来年 結婚する つもりです。', answer: 'أنوي الزواج العام القادم.', hint: 'つもりです' },
    { type: 'complete', prompt: 'أكمل: この 本 は たくさん の 人 に ___。 (يُقرأ)', answer: '読まれています', hint: '受身形' },
    { type: 'complete', prompt: 'أكمل: 私 は 兄 に ケーキ を ___。 (تأثر سلبي بأكل الكيكة)', answer: '食べられました', hint: '受身形(迷惑)' },
    { type: 'complete', prompt: 'أكمل: 卒業 した あと で、 日本 で 働く ___。', answer: 'つもりです', hint: 'النية' },
    { type: 'order', prompt: 'رتب: に / 私 / 先生 / は / 褒められました', answer: '私 は 先生 に 褒められました。', hint: '受身形' },
    { type: 'order', prompt: 'رتب: つもりです / 経済学 / を / 勉強する / 大学 / で', answer: '大学 で 経済学 を 勉強する つもりです。', hint: 'つもりです' },
    { type: 'answer', prompt: 'この 城 は いつ 建てられました か。 (400年前)', answer: 'この 城 は 400年前 に 建てられました。', hint: 'الإجابة بـ 受身形' },
    { type: 'answer', prompt: '卒業 した あと で、 何 を する つもりです か。 (就職します)', answer: '卒業 した あと で、 就職する つもりです。', hint: 'الإجابة بـ つもりです' },
  ],
  videos: [],
}
