export const lessonEight = {
  id: 8,
  title: { ar: 'الصفات والإعجاب', en: 'Adjectives and Likes/Dislikes' },
  focus: 'الصفات من نوع い والصفات من نوع な، とても/あまり، どんな، وأفعال الإعجاب مع が',
  vocab: [
    { id: 'ookii', type: 'i-adjective', jp: '大きい', kanji: '大きい', hiragana: 'おおきい', reading: 'ookii', meaning: 'كبير' },
    { id: 'chiisai', type: 'i-adjective', jp: '小さい', kanji: '小さい', hiragana: 'ちいさい', reading: 'chiisai', meaning: 'صغير' },
    { id: 'atarashii', type: 'i-adjective', jp: '新しい', kanji: '新しい', hiragana: 'あたらしい', reading: 'atarashii', meaning: 'جديد' },
    { id: 'furui', type: 'i-adjective', jp: '古い', kanji: '古い', hiragana: 'ふるい', reading: 'furui', meaning: 'قديم' },
    { id: 'ii', type: 'i-adjective', jp: 'いい', kanji: 'いい', hiragana: 'いい', reading: 'ii', meaning: 'جيد' },
    { id: 'atsui', type: 'i-adjective', jp: '暑い', kanji: '暑い', hiragana: 'あつい', reading: 'atsui', meaning: 'حار (الجو)' },
    { id: 'samui', type: 'i-adjective', jp: '寒い', kanji: '寒い', hiragana: 'さむい', reading: 'samui', meaning: 'بارد (الجو)' },
    { id: 'muzukashii', type: 'i-adjective', jp: '難しい', kanji: '難しい', hiragana: 'むずかしい', reading: 'muzukashii', meaning: 'صعب' },
    { id: 'yasashii', type: 'i-adjective', jp: '易しい', kanji: '易しい', hiragana: 'やさしい', reading: 'yasashii', meaning: 'سهل' },
    { id: 'takai', type: 'i-adjective', jp: '高い', kanji: '高い', hiragana: 'たかい', reading: 'takai', meaning: 'غالي / عالي' },
    { id: 'yasui', type: 'i-adjective', jp: '安い', kanji: '安い', hiragana: 'やすい', reading: 'yasui', meaning: 'رخيص' },
    { id: 'omoshiroi', type: 'i-adjective', jp: '面白い', kanji: '面白い', hiragana: 'おもしろい', reading: 'omoshiroi', meaning: 'ممتع / مثير للاهتمام' },
    { id: 'oishii', type: 'i-adjective', jp: 'おいしい', hiragana: 'おいしい', reading: 'oishii', meaning: 'لذيذ' },
    { id: 'isogashii', type: 'i-adjective', jp: '忙しい', kanji: '忙しい', hiragana: 'いそがしい', reading: 'isogashii', meaning: 'مشغول' },
    { id: 'kirei', type: 'na-adjective', jp: 'きれい', hiragana: 'きれい', reading: 'kirei', meaning: 'جميل / نظيف' },
    { id: 'shizuka', type: 'na-adjective', jp: '静か', kanji: '静か', hiragana: 'しずか', reading: 'shizuka', meaning: 'هادئ' },
    { id: 'nigiyaka', type: 'na-adjective', jp: 'にぎやか', hiragana: 'にぎやか', reading: 'nigiyaka', meaning: 'صاخب / حيوي' },
    { id: 'shinsetsu', type: 'na-adjective', jp: '親切', kanji: '親切', hiragana: 'しんせつ', reading: 'shinsetsu', meaning: 'لطيف / كريم' },
    { id: 'yuumei', type: 'na-adjective', jp: '有名', kanji: '有名', hiragana: 'ゆうめい', reading: 'yuumei', meaning: 'مشهور' },
    { id: 'benri', type: 'na-adjective', jp: '便利', kanji: '便利', hiragana: 'べんり', reading: 'benri', meaning: 'مريح / عملي' },
    { id: 'suki', type: 'na-adjective', jp: '好き', kanji: '好き', hiragana: 'すき', reading: 'suki', meaning: 'محبوب / يحب' },
    { id: 'kirai', type: 'na-adjective', jp: '嫌い', kanji: '嫌い', hiragana: 'きらい', reading: 'kirai', meaning: 'مكروه / يكره' },
    { id: 'jouzu', type: 'na-adjective', jp: '上手', kanji: '上手', hiragana: 'じょうず', reading: 'jouzu', meaning: 'ماهر' },
    { id: 'machi', type: 'noun', jp: '町', kanji: '町', hiragana: 'まち', reading: 'machi', meaning: 'مدينة / بلدة' },
    { id: 'donna', type: 'question-word', jp: 'どんな', hiragana: 'どんな', reading: 'donna', meaning: 'أي نوع من' },
  ],
  grammar: [
    {
      title: 'الصفات من نوع い (い形容詞)',
      pattern: 'اسم + は + い-صفة + です。',
      particle: 'い형容詞',
      howItWorks: 'الصفات المنتهية بـ い (مثل 大きい، おいしい) تُستخدم مباشرة قبل です دون الحاجة لأي رابط، وتُصرّف للنفي بحذف い وإضافة くない.',
      explanation: 'النفي: 大きい → 大きくない. الماضي: 大きい → 大きかった. الاستثناء: いい → よくない (ماضيها よかった).',
      example: { jp: 'この 部屋 は 大きい です。', romaji: 'Kono heya wa ookii desu.', ar: 'هذه الغرفة كبيرة.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذا الكتاب صعب.',
          words: ['この', '本', 'は', '難しい', 'です', '。'],
          particles: ['は'],
          answer: 'この 本 は 難しい です 。',
        },
        {
          type: 'fill',
          ar: 'هذا المطعم ليس غاليا. (نفي)',
          sentence: 'この レストラン は 高く ___。',
          options: ['ない です', 'です', 'じゃない です', 'ません'],
          answer: 'ない です',
        },
        {
          type: 'meaning',
          sentence: '昨日 は 寒かった です。',
          particle: 'かった',
          options: ['كان الجو باردا أمس.', 'الجو بارد اليوم.', 'سيكون الجو باردا غدا.', 'الجو ليس باردا أمس.'],
          answer: 'كان الجو باردا أمس.',
        },
        {
          type: 'error',
          ar: 'هذه الزهرة ليست جميلة. (تحذير: きれい صفة な)',
          options: ['この 食べ物 は おいしくない です。', 'この 食べ物 は おいしいない です。', 'この 食べ物 は おいしいじゃない です。'],
          answer: 'この 食べ物 は おいしくない です。',
        },
      ],
    },
    {
      title: 'الصفات من نوع な (な形容詞)',
      pattern: 'اسم + は + な-صفة + です。 ／ な-صفة + な + اسم',
      particle: 'な形容詞',
      howItWorks: 'صفات な تتصرف مثل الأسماء: تأتي مع です مباشرة في الجملة الخبرية، لكن عند وصف اسم بعدها مباشرة تحتاج إلى な (مثل きれいな町).',
      explanation: 'النفي: きれい です → きれい じゃない です. لاحظ عدم وجود な قبل です، لكنها تظهر فقط قبل اسم.',
      example: { jp: '京都 は きれいな 町 です。', romaji: 'Kyouto wa kireina machi desu.', ar: 'كيوتو مدينة جميلة.' },
      exercises: [
        {
          type: 'build',
          ar: 'السيدة تاناكا لطيفة.',
          words: ['田中さん', 'は', '親切', 'です', '。'],
          particles: ['は'],
          answer: '田中さん は 親切 です 。',
        },
        {
          type: 'fill',
          ar: 'هذا مكان هادئ.',
          sentence: 'ここ は 静か___ 所 です。',
          options: ['な', 'い', 'の', 'だ'],
          answer: 'な',
        },
        {
          type: 'meaning',
          sentence: 'この 図書館 は 静か じゃない です。',
          particle: 'じゃない',
          options: ['هذه المكتبة ليست هادئة.', 'هذه المكتبة هادئة جدا.', 'هذه المكتبة جميلة.', 'هذه المكتبة مغلقة.'],
          answer: 'هذه المكتبة ليست هادئة.',
        },
        {
          type: 'error',
          ar: 'إنه مطعم مشهور.',
          options: ['有名な レストラン です。', '有名 レストラン です。', '有名い レストラン です。'],
          answer: '有名な レストラン です。',
        },
      ],
    },
    {
      title: 'とても と あまり〜ない',
      pattern: 'とても + صفة／ あまり + صفة (نفي)',
      particle: 'とても・あまり',
      howItWorks: 'とても تعني "جدا" وتأتي مع الجملة المثبتة. あまり تعني "ليس كثيرا" وتأتي دائما مع صيغة النفي.',
      explanation: 'لا يصح قول あまり مع جملة مثبتة. مثال: あまり 高くない です (ليس غاليا جدا) - صحيح. あまり 高い です - خطأ.',
      example: { jp: 'この 映画 は あまり 面白くない です。', romaji: 'Kono eiga wa amari omoshirokunai desu.', ar: 'هذا الفيلم ليس ممتعا كثيرا.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذا الطعام لذيذ جدا.',
          words: ['この', '食べ物', 'は', 'とても', 'おいしい', 'です', '。'],
          particles: ['は'],
          answer: 'この 食べ物 は とても おいしい です 。',
        },
        {
          type: 'fill',
          ar: 'الجو ليس باردا كثيرا اليوم.',
          sentence: '今日 は ___ 寒くない です。',
          options: ['あまり', 'とても', 'よく', 'すこし'],
          answer: 'あまり',
        },
        {
          type: 'meaning',
          sentence: '日本語 は とても 面白い です。',
          particle: 'とても',
          options: ['اللغة اليابانية ممتعة جدا.', 'اللغة اليابانية ليست ممتعة.', 'اللغة اليابانية صعبة قليلا.', 'لا أحب اللغة اليابانية.'],
          answer: 'اللغة اليابانية ممتعة جدا.',
        },
        {
          type: 'error',
          ar: 'هذا الشارع ليس مزدحما (صاخبا) كثيرا.',
          options: ['この 道 は あまり にぎやか じゃない です。', 'この 道 は とても にぎやか じゃない です。', 'この 道 は あまり にぎやか です。'],
          answer: 'この 道 は あまり にぎやか じゃない です。',
        },
      ],
    },
    {
      title: 'どんな と 好き／嫌い／上手 + が',
      pattern: 'どんな + اسم ／ شخص + は + شيء + が + 好き／嫌い／上手 です。',
      particle: 'が',
      howItWorks: 'どんな تُستخدم للسؤال عن "أي نوع من...". أما مع 好き (يحب) و 嫌い (يكره) و 上手 (ماهر في) و 下手 (ضعيف في)، فإن الشيء المحبوب/المُتقَن يُعلَّم بـ が.',
      explanation: 'مثال: 私 は 寿司 が 好き です (أنا أحب السوشي). الفاعل (الشخص) يأخذ は، والشيء المحبوب يأخذ が.',
      example: { jp: 'A: どんな 食べ物 が 好き です か。 B: 寿司 が 好き です。', romaji: 'Donna tabemono ga suki desu ka. / Sushi ga suki desu.', ar: 'أي طعام تحب؟ / أحب السوشي.' },
      exercises: [
        {
          type: 'build',
          ar: 'أي نوع من الموسيقى تحب؟',
          words: ['どんな', '音楽', 'が', '好き', 'です', 'か', '。'],
          particles: ['が'],
          answer: 'どんな 音楽 が 好き です か 。',
        },
        {
          type: 'fill',
          ar: 'أنا ماهر في كرة القدم.',
          sentence: '私 は サッカー ___ 上手 です。',
          options: ['が', 'を', 'に', 'は'],
          answer: 'が',
        },
        {
          type: 'meaning',
          sentence: '弟 は 野菜 が 嫌い です。',
          particle: '嫌い',
          options: ['أخي الصغير يكره الخضار.', 'أخي الصغير يحب الخضار.', 'أخي الصغير ماهر في الطبخ.', 'أخي الصغير لا يأكل اللحم.'],
          answer: 'أخي الصغير يكره الخضار.',
        },
        {
          type: 'error',
          ar: 'أنا لست ماهرا في الرياضة.',
          options: ['私 は スポーツ が 上手 じゃない です。', '私 は スポーツ を 上手 じゃない です。', '私 は スポーツ が 上手 ない です。'],
          answer: '私 は スポーツ が 上手 じゃない です。',
        },
      ],
    },
  ],
  examples: [
    { jp: '富士山 は 高い です。', romaji: 'Fujisan wa takai desu.', ar: 'جبل فوجي عالٍ.', en: 'Mt. Fuji is tall.' },
    { jp: 'この カメラ は 古い です が、いい カメラ です。', romaji: 'Kono kamera wa furui desu ga, ii kamera desu.', ar: 'هذه الكاميرا قديمة، لكنها كاميرا جيدة.', en: 'This camera is old, but it’s a good camera.' },
    { jp: '奈良 は 静かな 町 です。', romaji: 'Nara wa shizukana machi desu.', ar: 'نارا مدينة هادئة.', en: 'Nara is a quiet town.' },
    { jp: '東京 は あまり 静か じゃない です。', romaji: 'Toukyou wa amari shizuka janai desu.', ar: 'طوكيو ليست هادئة كثيرا.', en: 'Tokyo isn’t very quiet.' },
    { jp: 'A: どんな 映画 が 好き です か。 B: アクション映画 が 好き です。', romaji: 'Donna eiga ga suki desu ka. / Akushon eiga ga suki desu.', ar: 'أي أفلام تحب؟ / أحب أفلام الأكشن.', en: 'What kind of movies do you like? / I like action movies.' },
    { jp: '私 は 歌 が 上手 じゃない です。', romaji: 'Watashi wa uta ga jouzu janai desu.', ar: 'أنا لست ماهرا في الغناء.', en: 'I’m not good at singing.' },
    { jp: 'このレストランの料理はとてもおいしいです。', romaji: 'Kono resutoran no ryouri wa totemo oishii desu.', ar: 'طعام هذا المطعم لذيذ جدا.', en: 'This restaurant’s food is very delicious.' },
    { jp: '昨日のテストは難しかったです。', romaji: 'Kinou no tesuto wa muzukashikatta desu.', ar: 'كان اختبار الأمس صعبا.', en: 'Yesterday’s test was difficult.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: この 部屋 は 小さい です。', answer: 'هذه الغرفة صغيرة.', hint: 'صفة い' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 私 は ピアノ が 好き です。', answer: 'أنا أحب البيانو.', hint: 'الإعجاب بـ が' },
    { type: 'complete', prompt: 'أكمل: この パン は 安___ です。 (نفي)', answer: 'くない', hint: 'نفي صفة い' },
    { type: 'complete', prompt: 'أكمل: 大阪 は にぎやか___ 町 です。', answer: 'な', hint: 'صفة な قبل الاسم' },
    { type: 'complete', prompt: 'أكمل: 兄 は サッカー ___ 上手 です。', answer: 'が', hint: 'الإعجاب/المهارة بـ が' },
    { type: 'order', prompt: 'رتب: 高い / は / です / この / かばん', answer: 'この かばん は 高い です。', hint: 'صفة い كمسند' },
    { type: 'order', prompt: 'رتب: が / どんな / 好き / 食べ物 / です / か', answer: 'どんな 食べ物 が 好き です か。', hint: 'السؤال بـ どんな' },
    { type: 'answer', prompt: '日本語 は 難しい です か。 (はい、少し)', answer: 'はい、少し 難しい です。', hint: 'الإجابة بصفة い' },
    { type: 'answer', prompt: 'どんな 音楽 が 好き です か。 (ジャズ)', answer: 'ジャズ が 好き です。', hint: 'الإجابة بـ が好き' },
  ],
  videos: [],
}
