export const lessonNineteen = {
  id: 19,
  title: { ar: 'الصيغة العادية والرأي والنقل', en: 'Plain Form, Opinions, and Reported Speech' },
  focus: 'مراجعة الصيغة العادية (普通形)، と思います لإبداء الرأي، و と言っていました لنقل كلام الآخرين',
  vocab: [
    { id: 'omoimasu', type: 'verb', jp: '思います', kanji: '思います', hiragana: 'おもいます', reading: 'omoimasu', meaning: 'يعتقد / يظن' },
    { id: 'iimasu', type: 'verb', jp: '言います', kanji: '言います', hiragana: 'いいます', reading: 'iimasu', meaning: 'يقول' },
    { id: 'tabun', type: 'adverb', jp: '多分', kanji: '多分', hiragana: 'たぶん', reading: 'tabun', meaning: 'ربما / غالبا' },
    { id: 'kitto', type: 'adverb', jp: 'きっと', hiragana: 'きっと', reading: 'kitto', meaning: 'بالتأكيد / لا بد' },
    { id: 'zettai', type: 'adverb', jp: '絶対', kanji: '絶対', hiragana: 'ぜったい', reading: 'zettai', meaning: 'بشكل قاطع / مطلقا' },
    { id: 'tenkin', type: 'noun', jp: '転勤', kanji: '転勤', hiragana: 'てんきん', reading: 'tenkin', meaning: 'نقل وظيفي' },
    { id: 'kekkonshiki', type: 'noun', jp: '結婚式', kanji: '結婚式', hiragana: 'けっこんしき', reading: 'kekkonshiki', meaning: 'حفل زفاف' },
    { id: 'tenkou', type: 'noun', jp: '天候', kanji: '天候', hiragana: 'てんこう', reading: 'tenkou', meaning: 'حالة الطقس' },
    { id: 'kaigi2', type: 'noun', jp: '会議', kanji: '会議', hiragana: 'かいぎ', reading: 'kaigi', meaning: 'اجتماع' },
    { id: 'shusseki', type: 'verb', jp: '出席します', kanji: '出席します', hiragana: 'しゅっせきします', reading: 'shusseki shimasu', meaning: 'يحضر (اجتماعا)' },
    { id: 'kesseki', type: 'verb', jp: '欠席します', kanji: '欠席します', hiragana: 'けっせきします', reading: 'kesseki shimasu', meaning: 'يتغيب' },
    { id: 'tenshoku', type: 'noun', jp: '転職', kanji: '転職', hiragana: 'てんしょく', reading: 'tenshoku', meaning: 'تغيير الوظيفة' },
    { id: 'koibito', type: 'noun', jp: '恋人', kanji: '恋人', hiragana: 'こいびと', reading: 'koibito', meaning: 'حبيب/حبيبة' },
    { id: 'shiawase', type: 'na-adjective', jp: '幸せ', kanji: '幸せ', hiragana: 'しあわせ', reading: 'shiawase', meaning: 'سعيد' },
    { id: 'taifuu', type: 'noun', jp: '台風', kanji: '台風', hiragana: 'たいふう', reading: 'taifuu', meaning: 'إعصار' },
    { id: 'kuru2', type: 'verb', jp: '来る', kanji: '来る', hiragana: 'くる', reading: 'kuru', meaning: 'يأتي (قاموسي)' },
    { id: 'tabako', type: 'noun', jp: 'たばこ', hiragana: 'たばこ', reading: 'tabako', meaning: 'سجائر' },
    { id: 'yameru', type: 'verb', jp: 'やめる', hiragana: 'やめる', reading: 'yameru', meaning: 'يتوقف عن / يقلع' },
    { id: 'gakusei2', type: 'person', jp: '学生', kanji: '学生', hiragana: 'がくせい', reading: 'gakusei', meaning: 'طالب' },
    { id: 'kachou', type: 'person', jp: '課長', kanji: '課長', hiragana: 'かちょう', reading: 'kachou', meaning: 'رئيس قسم' },
    { id: 'shussha', type: 'verb', jp: '出社します', kanji: '出社します', hiragana: 'しゅっしゃします', reading: 'shussha shimasu', meaning: 'يحضر إلى الشركة' },
    { id: 'rainen', type: 'noun', jp: '来年', kanji: '来年', hiragana: 'らいねん', reading: 'rainen', meaning: 'العام القادم' },
    { id: 'keizai', type: 'noun', jp: '経済', kanji: '経済', hiragana: 'けいざい', reading: 'keizai', meaning: 'اقتصاد' },
    { id: 'yoku_naru', type: 'expression', jp: 'よくなる', kanji: 'よくなる', hiragana: 'よくなる', reading: 'yoku naru', meaning: 'يتحسن' },
  ],
  grammar: [
    {
      title: 'مراجعة الصيغة العادية (普通形) — الأفعال',
      pattern: '辞書形 / ない形 / た形 / なかった形',
      particle: '普通形',
      howItWorks: 'الصيغة العادية للأفعال لها أربعة أشكال: المضارع المثبت (辞書形: 行く)، المضارع المنفي (ない形: 行かない)، الماضي المثبت (た形: 行った)، الماضي المنفي (なかった形: 行かなかった).',
      explanation: 'الصيغة العادية تُستخدم في الكلام بين الأصدقاء، وكذلك داخل جمل أكبر مثل と思います و と言っていました، حيث يجب تحويل الفعل إلى صيغته العادية قبل と.',
      example: { jp: '行きます → 行く・行かない・行った・行かなかった', romaji: 'ikimasu → iku, ikanai, itta, ikanakatta', ar: 'يذهب → الأشكال العادية الأربعة' },
      exercises: [
        {
          type: 'build',
          ar: 'صيغة الماضي العادي لـ 食べます هي 食べた.',
          words: ['食べます', '→', '食べた'],
          particles: [],
          answer: '食べます → 食べた',
        },
        {
          type: 'fill',
          ar: 'صيغة الماضي المنفي العادي لـ 行きます هي؟',
          sentence: '行きます → ___',
          options: ['行かなかった', '行きませんでした', '行かない', '行った'],
          answer: '行かなかった',
        },
        {
          type: 'meaning',
          sentence: '飲む・飲まない・飲んだ・飲まなかった',
          particle: '普通形',
          options: ['هذه الأشكال الأربعة العادية لفعل 飲みます.', 'هذه الأشكال الأربعة الرسمية لفعل 飲みます.', 'هذه أشكال مختلفة لأربعة أفعال.', 'هذه أشكال خاصة بصيغة الأمر فقط.'],
          answer: 'هذه الأشكال الأربعة العادية لفعل 飲みます.',
        },
        {
          type: 'error',
          ar: 'الصيغة العادية الحاضرة المنفية لـ します هي؟',
          options: ['しない', 'します ない', 'しません', 'しなくて'],
          answer: 'しない',
        },
      ],
    },
    {
      title: 'الصيغة العادية للصفات والأسماء',
      pattern: 'い-adj (普通形) / な-adj + だ ／ じゃない ／ だった ／ じゃなかった',
      particle: '普通形',
      howItWorks: 'صفات い في صيغتها العادية لا تتغير في المضارع المثبت (高い)، وتتبع نفس قواعد الماضي والنفي (高くない، 高かった، 高くなかった). صفات な والأسماء تستخدم だ بدلا من です في المضارع المثبت العادي، وتُحذف だ غالبا قبل と.',
      explanation: 'مهم: عند استخدام صفة な أو اسم قبل と思います/と言っていました في المضارع المثبت، تُحذف だ تماما (وليس だ思います بل ببساطة 静かだと思います تبقى だ هنا لأنها قبل と وليس です). القاعدة: 静かだ + と = 静かだと.',
      example: { jp: '田中さん は 学生 だ と 思います。', romaji: 'Tanaka-san wa gakusei da to omoimasu.', ar: 'أعتقد أن السيد تاناكا طالب.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعتقد أن هذا الفيلم ممتع.',
          words: ['この', '映画', 'は', '面白い', 'と', '思います', '。'],
          particles: ['と'],
          answer: 'この 映画 は 面白い と 思います 。',
        },
        {
          type: 'fill',
          ar: 'أعتقد أن الجو سيكون باردا غدا.',
          sentence: '明日 は 寒い ___ 思います。',
          options: ['と', 'が', 'を', 'に'],
          answer: 'と',
        },
        {
          type: 'meaning',
          sentence: 'この 部屋 は 静か だ と 思います。',
          particle: 'だと',
          options: ['أعتقد أن هذه الغرفة هادئة.', 'هذه الغرفة هادئة بالتأكيد.', 'لا أعرف إذا كانت هذه الغرفة هادئة.', 'هذه الغرفة ليست هادئة أبدا.'],
          answer: 'أعتقد أن هذه الغرفة هادئة.',
        },
        {
          type: 'error',
          ar: 'أعتقد أنه ليس طالبا.',
          options: ['彼 は 学生 じゃない と 思います。', '彼 は 学生 ではない です と 思います。', '彼 は 学生 じゃ と 思いません。'],
          answer: '彼 は 学生 じゃない と 思います。',
        },
      ],
    },
    {
      title: '〜と思います — إبداء الرأي',
      pattern: 'جملة (普通形) + と思います。',
      particle: 'と思います',
      howItWorks: 'تستخدم と思います لإبداء رأي أو توقع شخصي، بمعنى "أعتقد أن...". الجملة قبل と يجب أن تكون بالصيغة العادية (普通形).',
      explanation: 'للنفي على مستوى الجملة الكاملة "لا أعتقد أن..."، اليابانية تفضل نفي الفعل داخل الجملة قبل と وليس نفي 思います نفسها (مثال: 雨は降らないと思います أفضل من 雨は降ると思いません).',
      example: { jp: '明日 雨 が 降る と 思います。', romaji: 'Ashita ame ga furu to omoimasu.', ar: 'أعتقد أن المطر سيهطل غدا.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعتقد أن السيد تاناكا سيأتي.',
          words: ['田中さん', 'は', '来る', 'と', '思います', '。'],
          particles: ['は', 'と'],
          answer: '田中さん は 来る と 思います 。',
        },
        {
          type: 'fill',
          ar: 'أعتقد أن الإعصار لن يأتي.',
          sentence: '台風 は ___ と 思います。',
          options: ['来ない', '来ません', '来ないだ', '来なかったです'],
          answer: '来ない',
        },
        {
          type: 'meaning',
          sentence: '彼女 は たぶん 来ない と 思います。',
          particle: 'と思います',
          options: ['أعتقد أنها على الأرجح لن تأتي.', 'أعتقد أنها ستأتي بالتأكيد.', 'هي قالت إنها لن تأتي.', 'لا أعرف إن كانت ستأتي.'],
          answer: 'أعتقد أنها على الأرجح لن تأتي.',
        },
        {
          type: 'error',
          ar: 'أعتقد أن الاقتصاد سيتحسن العام القادم.',
          options: ['来年 、 経済 が よくなる と 思います。', '来年 、 経済 が よくなります と 思います。', '来年 、 経済 が よくなる です と 思います。'],
          answer: '来年 、 経済 が よくなる と 思います。',
        },
      ],
    },
    {
      title: '〜と言っていました — نقل كلام الآخرين',
      pattern: 'شخص + は + جملة (普通形) + と 言っていました。',
      particle: 'と言っていました',
      howItWorks: 'تستخدم لنقل ما قاله شخص آخر (في الماضي)، بمعنى "قال إن...". الجملة المنقولة تكون بالصيغة العادية متبوعة بـ と言っていました.',
      explanation: 'فرق بسيط: と思います رأي المتكلم نفسه، أما と言っていました فهي نقل لكلام شخص ثالث سمعه المتكلم.',
      example: { jp: '田中さん は 来週 旅行する と 言っていました。', romaji: 'Tanaka-san wa raishuu ryokou suru to itte imashita.', ar: 'قال السيد تاناكا إنه سيسافر الأسبوع القادم.' },
      exercises: [
        {
          type: 'build',
          ar: 'قال أخي إنه متعب.',
          words: ['兄', 'は', '疲れた', 'と', '言っていました', '。'],
          particles: ['は', 'と'],
          answer: '兄 は 疲れた と 言っていました 。',
        },
        {
          type: 'fill',
          ar: 'قالت السيدة تاناكا إن الاجتماع سيُلغى.',
          sentence: '田中さん は 会議 が 中止 だ ___ 言っていました。',
          options: ['と', 'を', 'に', 'が'],
          answer: 'と',
        },
        {
          type: 'meaning',
          sentence: '課長 は あした 休み だ と 言っていました。',
          particle: 'と言っていました',
          options: ['قال رئيس القسم إن غدا إجازة.', 'سيكون رئيس القسم في إجازة وحده.', 'رئيس القسم لا يعرف عن الإجازة.', 'رئيس القسم سيلغي الإجازة.'],
          answer: 'قال رئيس القسم إن غدا إجازة.',
        },
        {
          type: 'error',
          ar: 'قال صديقي إنه أقلع عن التدخين.',
          options: ['友達 は たばこ を やめた と 言っていました。', '友達 は たばこ を やめました と 言っていました。', '友達 は たばこ を やめる と 言いました でした。'],
          answer: '友達 は たばこ を やめた と 言っていました。',
        },
      ],
    },
  ],
  examples: [
    { jp: '私 は 明日 雨 が 降る と 思います。', romaji: 'Watashi wa ashita ame ga furu to omoimasu.', ar: 'أعتقد أن المطر سيهطل غدا.', en: 'I think it will rain tomorrow.' },
    { jp: 'この 問題 は 難しい と 思います。', romaji: 'Kono mondai wa muzukashii to omoimasu.', ar: 'أعتقد أن هذه المشكلة صعبة.', en: 'I think this problem is difficult.' },
    { jp: '山田さん は 来年 結婚する と 言っていました。', romaji: 'Yamada-san wa rainen kekkon suru to itte imashita.', ar: 'قال السيد ياماموتو إنه سيتزوج العام القادم.', en: 'Mr. Yamada said he’ll get married next year.' },
    { jp: '天気予報 は 明日 晴れる と 言っていました。', romaji: 'Tenkiyohou wa ashita hareru to itte imashita.', ar: 'قالت نشرة الطقس إن الغد سيكون مشمسا.', en: 'The weather forecast said it will be sunny tomorrow.' },
    { jp: '彼女 は 元気 だ と 思います。', romaji: 'Kanojo wa genki da to omoimasu.', ar: 'أعتقد أنها بخير.', en: 'I think she’s fine.' },
    { jp: '先生 は 試験 が 簡単 だ と 言っていました。', romaji: 'Sensei wa shiken ga kantan da to itte imashita.', ar: 'قال المعلم إن الاختبار سهل.', en: 'The teacher said the exam is easy.' },
    { jp: '彼 は その 話 を 知らない と 思います。', romaji: 'Kare wa sono hanashi o shiranai to omoimasu.', ar: 'أعتقد أنه لا يعرف بهذا الأمر.', en: 'I think he doesn’t know about that.' },
    { jp: 'ニュース で 台風 が 来る と 言っていました。', romaji: 'Nyuusu de taifuu ga kuru to itte imashita.', ar: 'قالت الأخبار إن إعصارا قادم.', en: 'The news said a typhoon is coming.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 彼 は 忙しい と 思います。', answer: 'أعتقد أنه مشغول.', hint: 'と思います' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 田中さん は 病気 だ と 言っていました。', answer: 'قال السيد تاناكا إنه مريض.', hint: 'と言っていました' },
    { type: 'complete', prompt: 'أكمل: 行きます → ___ (普通形・過去)', answer: '行った', hint: 'الماضي العادي' },
    { type: 'complete', prompt: 'أكمل: 明日 は 晴れる ___ 思います。', answer: 'と', hint: 'と思います' },
    { type: 'complete', prompt: 'أكمل: 彼女 は 来ない ___ 言っていました。', answer: 'と', hint: 'と言っていました' },
    { type: 'order', prompt: 'رتب: 思います / と / 高い / は / この / 本', answer: 'この 本 は 高い と 思います。', hint: 'الرأي بـ と思います' },
    { type: 'order', prompt: 'رتب: 言っていました / は / 来る / と / 友達 / 明日', answer: '友達 は 明日 来る と 言っていました。', hint: 'نقل الكلام' },
    { type: 'answer', prompt: 'この 映画 は どう です か。 (面白いと思います)', answer: '面白い と 思います。', hint: 'الإجابة بالرأي' },
    { type: 'answer', prompt: '田中さん は 何 と 言っていました か。 (忙しい)', answer: '忙しい と 言っていました。', hint: 'الإجابة بنقل الكلام' },
  ],
  videos: [],
}
