export const lessonThirteen = {
  id: 13,
  title: { ar: 'الرغبات والأهداف', en: 'Wants and Purposes' },
  focus: '〜たいです للرغبة، へ〜に行きます للهدف من الذهاب، ましょうか للعرض، وどうして〜から للسؤال عن السبب',
  dialogue: {
    titleAr: 'ماذا تريد أن تفعل؟ — خطط العطلة',
    lines: [
      { speaker: 'ساتو', jp: '夏休みに 何が したいですか。', romaji: 'Natsuyasumi ni nani ga shitai desu ka.', ar: 'ماذا تريد أن تفعل في عطلة الصيف؟' },
      { speaker: 'ميلر', jp: '富士山に 登りたいです。', romaji: 'Fujisan ni noboritai desu.', ar: 'أريد أن أتسلق جبل فوجي.' },
      { speaker: 'ساتو', jp: 'いいですね。どうして 富士山ですか。', romaji: 'Ii desu ne. Doushite Fujisan desu ka.', ar: 'جميل! لماذا جبل فوجي؟' },
      { speaker: 'ميلر', jp: '写真を 撮りたいですから。', romaji: 'Shashin o toritai desu kara.', ar: 'لأنني أريد أن ألتقط صورًا.' },
      { speaker: 'ساتو', jp: '荷物を 持ちましょうか。', romaji: 'Nimotsu o mochimashou ka.', ar: 'هل أحمل لك الأمتعة؟' },
      { speaker: 'ميلر', jp: 'ありがとうございます。お願いします。', romaji: 'Arigatou gozaimasu. Onegai shimasu.', ar: 'شكرًا، من فضلك.' },
      { speaker: 'ساتو', jp: '一緒に 海でも 泳ぎたいです。', romaji: 'Issho ni umi demo oyogitai desu.', ar: 'أريد أيضًا أن نسبح في البحر معًا.' },
    ],
  },
  reading: {
    titleAr: 'حلمي — الدراسة في اليابان',
    sentences: [
      { jp: '私は 日本へ 留学したいです。', romaji: 'Watashi wa Nihon e ryuugaku shitai desu.', ar: 'أريد أن أدرس في اليابان.' },
      { jp: '温泉に 入りたいです。', romaji: 'Onsen ni hairitai desu.', ar: 'أريد أن أدخل الينابيع الحارة.' },
      { jp: '祭りで 遊びたいです。', romaji: 'Matsuri de asobitai desu.', ar: 'أريد أن أستمتع في المهرجانات.' },
      { jp: '日本語を もっと 勉強したいですから、毎日 練習します。', romaji: 'Nihongo o motto benkyou shitai desu kara, mainichi renshuu shimasu.', ar: 'لأنني أريد دراسة اليابانية أكثر، أتدرب كل يوم.' },
      { jp: '友達と 一緒に 旅行したいです。', romaji: 'Tomodachi to issho ni ryokou shitai desu.', ar: 'أريد أن أسافر مع أصدقائي.' },
    ],
    questions: [
      { q: 'ما حلم الكاتب؟', options: ['الدراسة في اليابان', 'العمل في اليابان', 'الزواج'], answer: 'الدراسة في اليابان' },
      { q: 'لماذا يتدرب كل يوم؟', options: ['لأنه يريد دراسة اليابانية أكثر', 'لأنه متعب', 'لأن عنده امتحان'], answer: 'لأنه يريد دراسة اليابانية أكثر' },
      { q: 'مع من يريد أن يسافر؟', options: ['مع أصدقائه', 'مع عائلته', 'وحده'], answer: 'مع أصدقائه' },
    ],
  },
  vocab: [
    { id: 'ryokou', type: 'noun', jp: '旅行', kanji: '旅行', hiragana: 'りょこう', reading: 'ryokou', meaning: 'سفر / رحلة' },
    { id: 'ryokou_shimasu', type: 'verb', jp: '旅行します', kanji: '旅行します', hiragana: 'りょこうします', reading: 'ryokou shimasu', meaning: 'يسافر' },
    { id: 'kaimono', type: 'noun', jp: '買い物', kanji: '買い物', hiragana: 'かいもの', reading: 'kaimono', meaning: 'تسوق' },
    { id: 'oyogimasu', type: 'verb', jp: '泳ぎます', kanji: '泳ぎます', hiragana: 'およぎます', reading: 'oyogimasu', meaning: 'يسبح' },
    { id: 'onsen', type: 'place', jp: '温泉', kanji: '温泉', hiragana: 'おんせん', reading: 'onsen', meaning: 'ينبوع حار (أونسن)' },
    { id: 'fujisan', type: 'place', jp: '富士山', kanji: '富士山', hiragana: 'ふじさん', reading: 'fujisan', meaning: 'جبل فوجي' },
    { id: 'ryuugaku', type: 'noun', jp: '留学します', kanji: '留学します', hiragana: 'りゅうがくします', reading: 'ryuugaku shimasu', meaning: 'يدرس بالخارج' },
    { id: 'kekkon', type: 'verb', jp: '結婚します', kanji: '結婚します', hiragana: 'けっこんします', reading: 'kekkon shimasu', meaning: 'يتزوج' },
    { id: 'doushite', type: 'question-word', jp: 'どうして', hiragana: 'どうして', reading: 'doushite', meaning: 'لماذا' },
    { id: 'tabetai', type: 'expression', jp: '〜たいです', hiragana: '〜たいです', reading: '~tai desu', meaning: 'أريد أن...' },
    { id: 'noboru', type: 'verb', jp: '登ります', kanji: '登ります', hiragana: 'のぼります', reading: 'noborimasu', meaning: 'يتسلق / يصعد' },
    { id: 'umi', type: 'noun', jp: '海', kanji: '海', hiragana: 'うみ', reading: 'umi', meaning: 'بحر' },
    { id: 'yama', type: 'noun', jp: '山', kanji: '山', hiragana: 'やま', reading: 'yama', meaning: 'جبل' },
    { id: 'shashin_torimasu', type: 'expression', jp: '写真を撮ります', kanji: '写真を撮ります', hiragana: 'しゃしんをとります', reading: 'shashin o torimasu', meaning: 'يلتقط صورة' },
    { id: 'okurimasu', type: 'verb', jp: '送ります', kanji: '送ります', hiragana: 'おくります', reading: 'okurimasu', meaning: 'يرسل' },
    { id: 'tetsudaimasu', type: 'verb', jp: '手伝います', kanji: '手伝います', hiragana: 'てつだいます', reading: 'tetsudaimasu', meaning: 'يساعد' },
    { id: 'nimotsu', type: 'noun', jp: '荷物', kanji: '荷物', hiragana: 'にもつ', reading: 'nimotsu', meaning: 'أمتعة / حقائب' },
    { id: 'mado_akemasu', type: 'expression', jp: '窓を開けます', kanji: '窓を開けます', hiragana: 'まどをあけます', reading: 'mado o akemasu', meaning: 'يفتح النافذة' },
    { id: 'shimemasu', type: 'verb', jp: '閉めます', kanji: '閉めます', hiragana: 'しめます', reading: 'shimemasu', meaning: 'يغلق' },
    { id: 'tsukaremashita', type: 'verb', jp: '疲れました', kanji: '疲れました', hiragana: 'つかれました', reading: 'tsukaremashita', meaning: 'تعبت' },
    { id: 'naze', type: 'question-word', jp: 'なぜ', hiragana: 'なぜ', reading: 'naze', meaning: 'لماذا (رسمي)' },
    { id: 'oishasan', type: 'place', jp: '病院', kanji: '病院', hiragana: 'びょういん', reading: 'byouin', meaning: 'مستشفى' },
    { id: 'asobimasu', type: 'verb', jp: '遊びます', kanji: '遊びます', hiragana: 'あそびます', reading: 'asobimasu', meaning: 'يلعب / يقضي وقتا ممتعا' },
    { id: 'matsuri', type: 'noun', jp: '祭り', kanji: '祭り', hiragana: 'まつり', reading: 'matsuri', meaning: 'مهرجان' },
    { id: 'isshoni', type: 'adverb', jp: '一緒に', kanji: '一緒に', hiragana: 'いっしょに', reading: 'issho ni', meaning: 'معا' },
  ],
  grammar: [
    {
      title: '〜たいです — التعبير عن الرغبة',
      pattern: 'فعل (ます‐stem) + たいです',
      particle: 'たい',
      howItWorks: 'لإسقاط حرف ます من الفعل وإضافة たいです نحصل على معنى "أريد أن أفعل...". تتصرف たい مثل صفة い (たかったです في الماضي، たくないです في النفي).',
      explanation: 'عند ذكر المفعول به مع たい، غالبا تُستبدل を بـ が، مثال: 水 が 飲みたい です (أريد أن أشرب ماء)، رغم أن を لا تزال مقبولة.',
      example: { jp: '日本 へ 行きたい です。', romaji: 'Nihon e ikitai desu.', ar: 'أريد أن أذهب إلى اليابان.' },
      exercises: [
        {
          type: 'build',
          ar: 'أريد أن آكل السوشي.',
          words: ['寿司', 'が', '食べたい', 'です', '。'],
          particles: ['が'],
          answer: '寿司 が 食べたい です 。',
        },
        {
          type: 'fill',
          ar: 'لا أريد أن أعمل اليوم. (نفي)',
          sentence: '今日 は 仕事 を し___ です。',
          options: ['たくない', 'たい', 'ません', 'ない'],
          answer: 'たくない',
        },
        {
          type: 'meaning',
          sentence: '去年 、 富士山 に 登りたかった です。',
          particle: 'たかった',
          options: ['أردت تسلق جبل فوجي العام الماضي.', 'سأتسلق جبل فوجي العام القادم.', 'تسلقت جبل فوجي العام الماضي.', 'لا أريد تسلق جبل فوجي.'],
          answer: 'أردت تسلق جبل فوجي العام الماضي.',
        },
        {
          type: 'error',
          ar: 'أريد أن أشتري حقيبة جديدة.',
          options: ['新しい かばん が 買いたい です。', '新しい かばん は 買いますたい です。', '新しい かばん を 買いますたい です。'],
          answer: '新しい かばん が 買いたい です。',
        },
      ],
    },
    {
      title: 'へ／に + 行きます／来ます — الهدف من الذهاب',
      pattern: 'مكان + へ + فعل (ます‐stem) + に + 行きます／来ます／帰ります',
      particle: 'に',
      howItWorks: 'لوصف الهدف من الذهاب إلى مكان، نأخذ جذع الفعل (ます‐stem) ونضيف に قبل 行きます/来ます/帰ります، مثل 食べに行きます (أذهب لآكل).',
      explanation: 'إذا كان الفعل من نوع します (مثل 買い物します)، يمكن تحويله إلى اسم + に行きます مباشرة: 買い物に行きます.',
      example: { jp: '海 へ 泳ぎ に 行きます。', romaji: 'Umi e oyogi ni ikimasu.', ar: 'أذهب إلى البحر للسباحة.' },
      exercises: [
        {
          type: 'build',
          ar: 'سأذهب إلى المتجر للتسوق.',
          words: ['デパート', 'へ', '買い物', 'に', '行きます', '。'],
          particles: ['へ', 'に'],
          answer: 'デパート へ 買い物 に 行きます 。',
        },
        {
          type: 'fill',
          ar: 'جاء صديقي إلى اليابان للدراسة.',
          sentence: '友達 は 日本 へ 勉強 ___ 来ました。',
          options: ['に', 'へ', 'で', 'を'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: '来週 、 京都 へ 写真 を 撮り に 行きます。',
          particle: 'に',
          options: ['سأذهب إلى كيوتو الأسبوع القادم لالتقاط الصور.', 'التقطت صورا لكيوتو الأسبوع الماضي.', 'سأرسل صورا إلى كيوتو.', 'كيوتو مشهورة بالصور.'],
          answer: 'سأذهب إلى كيوتو الأسبوع القادم لالتقاط الصور.',
        },
        {
          type: 'error',
          ar: 'عدت إلى المنزل لتناول الغداء.',
          options: ['昼ご飯 を 食べ に 家 へ 帰りました。', '昼ご飯 を 食べ ます に 家 へ 帰りました。', '家 へ 食べ に 昼ご飯 帰りました。'],
          answer: '昼ご飯 を 食べ に 家 へ 帰りました。',
        },
      ],
    },
    {
      title: 'ましょうか — عرض المساعدة',
      pattern: 'فعل (ます‐stem) + ましょうか。',
      particle: 'ましょうか',
      howItWorks: 'تستخدم ましょうか لتقديم عرض مهذب بمعنى "هل أفعل لك كذا؟". الرد بالقبول يكون بـ お願いします أو すみません، والرفض بـ いいえ、結構です.',
      explanation: 'الفرق بين ましょう (هيا بنا) و ましょうか (هل أفعل ذلك؟ - عرض من المتكلم وحده).',
      example: { jp: '荷物 を 持ちましょう か。', romaji: 'Nimotsu o mochimashou ka.', ar: 'هل أحمل لك الأمتعة؟' },
      exercises: [
        {
          type: 'build',
          ar: 'هل أفتح النافذة؟',
          words: ['窓', 'を', '開けましょう', 'か', '。'],
          particles: ['を'],
          answer: '窓 を 開けましょう か 。',
        },
        {
          type: 'fill',
          ar: 'نعم، من فضلك. (الموافقة على عرض)',
          sentence: 'はい、___ します。',
          options: ['お願い', 'ください', 'もちろん', 'どうも'],
          answer: 'お願い',
        },
        {
          type: 'meaning',
          sentence: 'A: 手伝いましょう か。 B: いいえ、結構 です。',
          particle: 'ましょうか',
          options: ['لا، شكرا، لا داعي.', 'نعم، ساعدني من فضلك.', 'سأساعدك بدلا منك.', 'لا أعرف كيف أساعد.'],
          answer: 'لا، شكرا، لا داعي.',
        },
        {
          type: 'error',
          ar: 'هل أتصل بك غدا؟',
          options: ['明日 電話 しましょう か。', '明日 電話 ましょうか します。', '明日 電話 しません か しましょう。'],
          answer: '明日 電話 しましょう か。',
        },
      ],
    },
    {
      title: 'どうして と から — السؤال عن السبب',
      pattern: 'どうして + جملة + か。 ／ جملة + から です。',
      particle: 'どうして・から',
      howItWorks: 'どうして (لماذا) تأتي في بداية السؤال. الجواب يكون بذكر السبب متبوعا بـ からです (وذلك لأن...) دون الحاجة لإعادة الفعل الرئيسي.',
      explanation: 'يمكن أيضا الإجابة بجملة كاملة تنتهي بـ から كما تعلمنا في الدرس 11، أو الاكتفاء بالسبب + からです كإجابة مختصرة.',
      example: { jp: 'A: どうして 休みました か。 B: 頭 が 痛かった から です。', romaji: 'Doushite yasumimashita ka. / Atama ga itakatta kara desu.', ar: 'لماذا تغيبت؟ / لأن رأسي كان يؤلمني.' },
      exercises: [
        {
          type: 'build',
          ar: 'لماذا تريد الذهاب إلى اليابان؟',
          words: ['どうして', '日本', 'へ', '行きたい', 'です', 'か', '。'],
          particles: ['へ'],
          answer: 'どうして 日本 へ 行きたい です か 。',
        },
        {
          type: 'fill',
          ar: 'لأنني أحب اليابانية. (إجابة مختصرة)',
          sentence: '日本語 が 好き ___ です。',
          options: ['だから', 'から', 'ので', 'のに'],
          answer: 'だから',
        },
        {
          type: 'meaning',
          sentence: 'A: どうして 遅かった です か。 B: 電車 が 遅れた から です。',
          particle: 'から',
          options: ['لأن القطار تأخر.', 'لأنني نسيت الساعة.', 'لأن المحطة بعيدة.', 'لأن القطار سريع جدا.'],
          answer: 'لأن القطار تأخر.',
        },
        {
          type: 'error',
          ar: 'لماذا لا تأكل اللحم؟',
          options: ['どうして 肉 を 食べません か。', 'どうして 肉 が 食べません か。', '肉 を どうして 食べません。'],
          answer: 'どうして 肉 を 食べません か。',
        },
      ],
    },
  ],
  examples: [
    { jp: '夏休み に 海 へ 行きたい です。', romaji: 'Natsuyasumi ni umi e ikitai desu.', ar: 'أريد الذهاب إلى البحر في عطلة الصيف.', en: 'I want to go to the beach during summer vacation.' },
    { jp: '図書館 へ 本 を 借り に 行きます。', romaji: 'Toshokan e hon o kari ni ikimasu.', ar: 'سأذهب إلى المكتبة لاستعارة كتاب.', en: 'I’m going to the library to borrow a book.' },
    { jp: 'A: コーヒー を 入れましょう か。 B: ええ、お願いします。', romaji: 'Koohii o iremashou ka. / Ee, onegai shimasu.', ar: 'هل أحضّر القهوة؟ / نعم، من فضلك.', en: 'Shall I make coffee? / Yes, please.' },
    { jp: 'どうして 日本語 を 勉強 して います か。', romaji: 'Doushite nihongo o benkyou shite imasu ka.', ar: 'لماذا تدرس اللغة اليابانية؟', en: 'Why are you studying Japanese?' },
    { jp: '仕事 が 面白い から です。', romaji: 'Shigoto ga omoshiroi kara desu.', ar: 'لأن العمل ممتع.', en: 'Because the work is interesting.' },
    { jp: '疲れました から、 もう 寝たい です。', romaji: 'Tsukaremashita kara, mou netai desu.', ar: 'تعبت، لذلك أريد أن أنام الآن.', en: 'I’m tired, so I want to sleep now.' },
    { jp: '今度 の 休み に 何 が したい です か。', romaji: 'Kondo no yasumi ni nani ga shitai desu ka.', ar: 'ماذا تريد أن تفعل في العطلة القادمة؟', en: 'What do you want to do during the next vacation?' },
    { jp: '友達 と 一緒に 祭り へ 行きたい です。', romaji: 'Tomodachi to issho ni matsuri e ikitai desu.', ar: 'أريد الذهاب إلى المهرجان مع صديقي.', en: 'I want to go to the festival with my friend.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 新しい 車 が 欲しい です。', answer: 'أريد سيارة جديدة.', hint: 'الرغبة بالامتلاك (欲しい)' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 公園 へ 散歩 に 行きます。', answer: 'سأذهب إلى الحديقة للتنزه.', hint: 'الهدف من الذهاب' },
    { type: 'complete', prompt: 'أكمل: 寿司 が 食べ___ です。 (أريد)', answer: 'たい', hint: 'صيغة الرغبة' },
    { type: 'complete', prompt: 'أكمل: 友達 に 会い ___ 行きます。 (هدف)', answer: 'に', hint: 'الهدف من الذهاب' },
    { type: 'complete', prompt: 'أكمل: A: 写真 を 撮りましょう か。 B: はい、___ します。', answer: 'お願い', hint: 'الموافقة على العرض' },
    { type: 'order', prompt: 'رتب: たい / 私 / は / 旅行 / です / したい / が', answer: '私 は 旅行 が したい です。', hint: 'الرغبة في فعل شيء' },
    { type: 'order', prompt: 'رتب: どうして / です / か / 休みました', answer: 'どうして 休みました か。', hint: 'السؤال بـ どうして' },
    { type: 'answer', prompt: 'どこ へ 行きたい です か。 (日本)', answer: '日本 へ 行きたい です。', hint: 'الإجابة بـ たい' },
    { type: 'answer', prompt: 'どうして 日本語 を 勉強 します か。 (好きだから)', answer: '好き だから です。', hint: 'الإجابة بالسبب' },
  ],
  videos: [],
}
