export const lessonTwentyTwo = {
  id: 22,
  title: { ar: 'حتى لو... وأفعال العطاء', en: 'Even If... and Giving/Receiving Verbs' },
  focus: '〜ても للتعبير عن "حتى لو/مهما"، وتوسيع أفعال あげます/もらいます/くれます مع الأفعال الأخرى',
  vocab: [
    { id: 'isoide', type: 'expression', jp: '急いで', kanji: '急いで', hiragana: 'いそいで', reading: 'isoide', meaning: 'بسرعة / مستعجلا' },
    { id: 'maniaimasu', type: 'verb', jp: '間に合います', kanji: '間に合います', hiragana: 'まにあいます', reading: 'maniaimasu', meaning: 'يصل في الوقت المناسب' },
    { id: 'ikura_temo', type: 'expression', jp: 'いくら〜ても', kanji: 'いくら〜ても', hiragana: 'いくら〜ても', reading: 'ikura ~temo', meaning: 'مهما كان...' },
    { id: 'setsumeishimasu', type: 'verb', jp: '説明します', kanji: '説明します', hiragana: 'せつめいします', reading: 'setsumeishimasu', meaning: 'يشرح' },
    { id: 'wakarimasen2', type: 'verb', jp: 'わかりません', hiragana: 'わかりません', reading: 'wakarimasen', meaning: 'لا يفهم / لا يعرف' },
    { id: 'tetsudaimasu', type: 'verb', jp: '手伝います', kanji: '手伝います', hiragana: 'てつだいます', reading: 'tetsudaimasu', meaning: 'يساعد' },
    { id: 'naoshimasu', type: 'verb', jp: '直します', kanji: '直します', hiragana: 'なおします', reading: 'naoshimasu', meaning: 'يصلح / يصحح' },
    { id: 'okutte_moraimasu', type: 'expression', jp: '送ってもらいます', kanji: '送ってもらいます', hiragana: 'おくってもらいます', reading: 'okutte moraimasu', meaning: 'يحصل على توصيلة/إرسال من شخص' },
    { id: 'kashite_kuremasu', type: 'expression', jp: '貸してくれます', kanji: '貸してくれます', hiragana: 'かしてくれます', reading: 'kashite kuremasu', meaning: 'يقرضه (لي/لنا)' },
    { id: 'tsukutte_agemasu', type: 'expression', jp: '作ってあげます', kanji: '作ってあげます', hiragana: 'つくってあげます', reading: 'tsukutte agemasu', meaning: 'يصنع له (كمعروف)' },
    { id: 'oshiete_moraimasu', type: 'expression', jp: '教えてもらいます', kanji: '教えてもらいます', hiragana: 'おしえてもらいます', reading: 'oshiete moraimasu', meaning: 'يحصل على شرح/تعليم من شخص' },
    { id: 'mochimasu', type: 'verb', jp: '持ちます', kanji: '持ちます', hiragana: 'もちます', reading: 'mochimasu', meaning: 'يحمل' },
    { id: 'nimotsu', type: 'noun', jp: '荷物', kanji: '荷物', hiragana: 'にもつ', reading: 'nimotsu', meaning: 'أمتعة' },
    { id: 'okutte_kuremasu', type: 'expression', jp: '送ってくれます', kanji: '送ってくれます', hiragana: 'おくってくれます', reading: 'okutte kuremasu', meaning: 'يوصلني/يرسل لي' },
    { id: 'kaze2', type: 'noun', jp: '風', kanji: '風', hiragana: 'かぜ', reading: 'kaze', meaning: 'ريح' },
    { id: 'tsuyoi', type: 'i-adjective', jp: '強い', kanji: '強い', hiragana: 'つよい', reading: 'tsuyoi', meaning: 'قوي' },
    { id: 'nemui', type: 'i-adjective', jp: '眠い', kanji: '眠い', hiragana: 'ねむい', reading: 'nemui', meaning: 'نعسان' },
    { id: 'ganbarimasu', type: 'verb', jp: '頑張ります', kanji: '頑張ります', hiragana: 'がんばります', reading: 'ganbarimasu', meaning: 'يبذل جهده' },
    { id: 'takakute', type: 'i-adjective', jp: '高くて', kanji: '高くて', hiragana: 'たかくて', reading: 'takakute', meaning: 'غالٍ (て形)' },
    { id: 'kaimasen', type: 'verb', jp: '買いません', kanji: '買いません', hiragana: 'かいません', reading: 'kaimasen', meaning: 'لا يشتري' },
    { id: 'donna_ni', type: 'expression', jp: 'どんなに', hiragana: 'どんなに', reading: 'donna ni', meaning: 'مهما / إلى أي مدى' },
    { id: 'ame2', type: 'noun', jp: '雨', kanji: '雨', hiragana: 'あめ', reading: 'ame', meaning: 'مطر' },
    { id: 'shiken2', type: 'noun', jp: '試験', kanji: '試験', hiragana: 'しけん', reading: 'shiken', meaning: 'اختبار' },
    { id: 'gomi', type: 'noun', jp: 'ごみ', hiragana: 'ごみ', reading: 'gomi', meaning: 'قمامة' },
    { id: 'sutemasu', type: 'verb', jp: '捨てます', kanji: '捨てます', hiragana: 'すてます', reading: 'sutemasu', meaning: 'يرمي / يتخلص من' },
  ],
  grammar: [
    {
      title: '〜ても — حتى لو / مهما',
      pattern: 'فعل/صفة (て形) + も، جملة',
      particle: 'ても',
      howItWorks: 'تتكون ても من て形 + も، وتعني "حتى لو/مع أن... فإن النتيجة لا تتغير". تستخدم للتعبير عن نتيجة غير متوقعة أو ثابتة رغم الشرط.',
      explanation: 'مثال: 雨 が 降っても、 行きます (حتى لو أمطرت، سأذهب). تختلف عن から/ので لأنها لا تعطي سببا بل تنفي تأثير الشرط على النتيجة.',
      example: { jp: '高くても、 買います。', romaji: 'Takakutemo, kaimasu.', ar: 'حتى لو كان غاليا، سأشتريه.' },
      exercises: [
        {
          type: 'build',
          ar: 'حتى لو استعجلت، لن أصل في الوقت المناسب.',
          words: ['急いでも', '、', '間に合いません', '。'],
          particles: [],
          answer: '急いでも 、 間に合いません 。',
        },
        {
          type: 'fill',
          ar: 'حتى لو كان الجو باردا، سأخرج.',
          sentence: '寒く ___、 出かけます。',
          options: ['ても', 'から', 'ので', 'のに'],
          answer: 'ても',
        },
        {
          type: 'meaning',
          sentence: '何度 説明しても、 わかりません。',
          particle: 'ても',
          options: ['مهما شرحت مرات عديدة، لا يفهم.', 'شرحت مرة واحدة وفهم فورا.', 'لن أشرح مرة أخرى أبدا.', 'الشرح سهل جدا.'],
          answer: 'مهما شرحت مرات عديدة، لا يفهم.',
        },
        {
          type: 'error',
          ar: 'حتى لو كان مشغولا، يساعدني دائما.',
          options: ['忙しいても、 いつも 手伝って くれます。', '忙しくても、 いつも 手伝って くれます。', '忙しいくても、 いつも 手伝って くれます。'],
          answer: '忙しくても、 いつも 手伝って くれます。',
        },
      ],
    },
    {
      title: 'いくら/どんなに 〜 ても — مهما (تأكيد)',
      pattern: 'いくら/どんなに + フレーズ (て形) + も',
      particle: 'いくら〜ても',
      howItWorks: 'إضافة いくら أو どんなに في بداية الجملة قبل ても تزيد التأكيد على معنى "مهما/أيا كان مدى". تستخدم غالبا للتعبير عن استمرار حالة رغم محاولات متكررة.',
      explanation: 'مثال: いくら 寝ても、 眠い です (مهما نمت، أشعر بالنعاس). どんなに 頑張っても、 できません (مهما حاولت، لا أستطيع).',
      example: { jp: 'いくら 寝ても、 眠い です。', romaji: 'Ikura netemo, nemui desu.', ar: 'مهما نمت، أشعر بالنعاس.' },
      exercises: [
        {
          type: 'build',
          ar: 'مهما حاولت بجد، لا أستطيع التحدث باليابانية بشكل جيد.',
          words: ['どんなに', '頑張っても', '、', '日本語', 'が', '上手に', '話せません', '。'],
          particles: ['が'],
          answer: 'どんなに 頑張っても 、 日本語 が 上手に 話せません 。',
        },
        {
          type: 'fill',
          ar: 'مهما كان رخيصا، لن أشتري ذلك.',
          sentence: 'いくら 安くても、 それ は ___。',
          options: ['買いません', '買います', '買って', '買う'],
          answer: '買いません',
        },
        {
          type: 'meaning',
          sentence: 'いくら 呼んでも、 返事 が ありません。',
          particle: 'いくら〜ても',
          options: ['مهما ناديت، لا يوجد رد.', 'ناديت مرة واحدة فقط ورد علي.', 'لم أنادِ أبدا.', 'الرد جاء بسرعة.'],
          answer: 'مهما ناديت، لا يوجد رد.',
        },
        {
          type: 'error',
          ar: 'مهما درست، لا أتذكر الكانجي.',
          options: ['いくら 勉強しても、 漢字 を 覚えられません。', 'いくら 勉強するても、 漢字 を 覚えられません。', 'いくら 勉強ても、 漢字 を 覚えられません。'],
          answer: 'いくら 勉強しても、 漢字 を 覚えられません。',
        },
      ],
    },
    {
      title: 'あげます/もらいます/くれます مع الأفعال (て形 + あげます/もらいます/くれます)',
      pattern: 'て形 + あげます／もらいます／くれます',
      particle: 'てあげる/てもらう/てくれる',
      howItWorks: 'هذه الأفعال المساعدة تضاف إلى て形 لفعل آخر للتعبير عن "تقديم/تلقي معروف". てあげます: أنا أفعل شيئا للآخر. てもらいます: أحصل على فعل من شخص لصالحي. てくれます: شخص آخر يفعل شيئا لصالحي/لنا.',
      explanation: 'الفرق المهم: てもらいます يركز على "أنا" كمستفيد وموضوع الجملة هو من يطلب/يحصل على الفعل، بينما てくれます موضوع الجملة هو من يقوم بالفعل تلقائيا لصالح المتكلم.',
      example: { jp: '友達 が 荷物 を 持って くれました。', romaji: 'Tomodachi ga nimotsu o motte kuremashita.', ar: 'صديقي حمل أمتعتي (لصالحي).' },
      exercises: [
        {
          type: 'build',
          ar: 'أصلحت السيارة لصديقي.',
          words: ['友達', 'に', '車', 'を', '直して', 'あげました', '。'],
          particles: ['に', 'を'],
          answer: '友達 に 車 を 直して あげました 。',
        },
        {
          type: 'fill',
          ar: 'حصلت على شرح من السيد تاناكا.',
          sentence: '田中さん に 説明して ___。',
          options: ['もらいました', 'あげました', 'くれました', 'いました'],
          answer: 'もらいました',
        },
        {
          type: 'meaning',
          sentence: '弟 が 宿題 を 手伝って くれました。',
          particle: 'てくれました',
          options: ['أخي الصغير ساعدني في الواجب (لصالحي).', 'ساعدت أخي الصغير في الواجب.', 'طلبت من أخي مساعدتي ولكنه رفض.', 'أخي لم يساعد أحدا.'],
          answer: 'أخي الصغير ساعدني في الواجب (لصالحي).',
        },
        {
          type: 'error',
          ar: 'السيد تاناكا أقرضني الكتاب (لصالحي).',
          options: ['田中さん は 本 を 貸して くれました。', '田中さん は 本 を 貸して もらいました。', '田中さん は 本 を 貸して あげました。'],
          answer: '田中さん は 本 を 貸して くれました。',
        },
      ],
    },
    {
      title: 'مراجعة شاملة: ても و てあげる/もらう/くれる',
      pattern: 'دمج القاعدتين في جمل مركبة',
      particle: 'مراجعة',
      howItWorks: 'يمكن دمج ても مع أفعال العطاء، مثل: 忙しくても、 友達 が 手伝って くれました (حتى لو كان مشغولا، صديقي ساعدني). هذا يظهر مدى تطور الجمل في N5 مع الحفاظ على نفس القواعد الأساسية.',
      explanation: 'مراجعة الفرق بين あげます (أنا → آخر)، もらいます (أنا أحصل من آخر)، くれます (آخر → أنا)، مع إضافة て形 لتوسيع المعنى لأفعال أخرى غير 与える.',
      example: { jp: '雨 が 降っても、 友達 が 駅 まで 送って くれました。', romaji: 'Ame ga futtemo, tomodachi ga eki made okutte kuremashita.', ar: 'حتى لو كانت تمطر، صديقي أوصلني إلى المحطة.' },
      exercises: [
        {
          type: 'build',
          ar: 'حتى لو لم يكن لدي وقت، سأساعدك.',
          words: ['時間', 'が', 'なくても', '、', '手伝って', 'あげます', '。'],
          particles: ['が'],
          answer: '時間 が なくても 、 手伝って あげます 。',
        },
        {
          type: 'fill',
          ar: 'حصلت على توصيلة من السيد تاناكا إلى المطار.',
          sentence: '田中さん に 空港 まで 送って ___。',
          options: ['もらいました', 'くれました', 'あげました', 'いました'],
          answer: 'もらいました',
        },
        {
          type: 'meaning',
          sentence: 'いくら 高くても、 母 は 私 に 買って くれます。',
          particle: 'てくれます',
          options: ['مهما كان غاليا، أمي تشتريه لي.', 'لن تشتري أمي أي شيء أبدا.', 'اشتريت لأمي شيئا غاليا.', 'الأشياء الرخيصة فقط تشتريها أمي.'],
          answer: 'مهما كان غاليا، أمي تشتريه لي.',
        },
        {
          type: 'error',
          ar: 'حتى لو كانت ريحا قوية، الأطفال يلعبون في الخارج.',
          options: ['風 が 強くても、 子供たち は 外 で 遊びます。', '風 が 強いても、 子供たち は 外 で 遊びます。', '風 が 強くて も、 子供たち は 外 で 遊びました。'],
          answer: '風 が 強くても、 子供たち は 外 で 遊びます。',
        },
      ],
    },
  ],
  examples: [
    { jp: '雨 が 降っても、 行きます。', romaji: 'Ame ga futtemo, ikimasu.', ar: 'حتى لو أمطرت، سأذهب.', en: 'Even if it rains, I’ll go.' },
    { jp: '高くても、 買います。', romaji: 'Takakutemo, kaimasu.', ar: 'حتى لو كان غاليا، سأشتريه.', en: 'Even if it’s expensive, I’ll buy it.' },
    { jp: 'いくら 説明しても、 わかりません。', romaji: 'Ikura setsumeishitemo, wakarimasen.', ar: 'مهما شرحت، لا يفهم.', en: 'No matter how much I explain, he doesn’t understand.' },
    { jp: 'どんなに 頑張っても、 だめ でした。', romaji: 'Donna ni ganbattemo, dame deshita.', ar: 'مهما حاولت بجد، لم ينفع.', en: 'No matter how hard I tried, it didn’t work.' },
    { jp: '友達 に 本 を 貸して もらいました。', romaji: 'Tomodachi ni hon o kashite moraimashita.', ar: 'استعرت كتابا من صديقي (حصلت على إعارة).', en: 'I had a friend lend me a book.' },
    { jp: '田中さん が 駅 まで 送って くれました。', romaji: 'Tanaka-san ga eki made okutte kuremashita.', ar: 'السيد تاناكا أوصلني إلى المحطة.', en: 'Mr. Tanaka gave me a ride to the station.' },
    { jp: '私 は 弟 に 宿題 を 教えて あげました。', romaji: 'Watashi wa otouto ni shukudai o oshiete agemashita.', ar: 'علمت أخي الصغير في الواجب (كمعروف).', en: 'I taught my brother with his homework.' },
    { jp: '風 が 強くても、 試合 は あります。', romaji: 'Kaze ga tsuyokutemo, shiai wa arimasu.', ar: 'حتى لو كانت الريح قوية، المباراة ستقام.', en: 'Even if the wind is strong, the match will happen.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 忙しくても、 来て ください。', answer: 'حتى لو كنت مشغولا، تعال من فضلك.', hint: 'ても بعد صفة い' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 友達 が 手伝って くれました。', answer: 'صديقي ساعدني (لصالحي).', hint: 'てくれます' },
    { type: 'complete', prompt: 'أكمل: 雨 が 降っ___、 出かけます。', answer: 'ても', hint: 'ても بعد て形' },
    { type: 'complete', prompt: 'أكمل: いくら 寝___、 眠い です。', answer: 'ても', hint: 'いくら〜ても' },
    { type: 'complete', prompt: 'أكمل: 田中さん に 漢字 を 教えて ___。 (حصلت على)', answer: 'もらいました', hint: 'てもらいます' },
    { type: 'order', prompt: 'رتب: ても / 高く / 買います', answer: '高くても、 買います。', hint: 'ても بعد صفة い' },
    { type: 'order', prompt: 'رتب: くれました / 友達 / が / 手伝って', answer: '友達 が 手伝って くれました。', hint: 'てくれます' },
    { type: 'answer', prompt: '雨 が 降っても、 行きますか。 (はい)', answer: 'はい、 雨 が 降っても、 行きます。', hint: 'الإجابة بـ ても' },
    { type: 'answer', prompt: '誰 が 荷物 を 持って くれましたか。 (友達)', answer: '友達 が 荷物 を 持って くれました。', hint: 'الإجابة بـ てくれます' },
  ],
  videos: [],
}
