export const lessonTwentyFour = {
  id: 24,
  title: { ar: 'يبدو أن... ومراجعة التغيير', en: 'Looking Like... and Review of Change' },
  focus: '〜そうです (様態 - المظهر/الانطباع) ومراجعة شاملة لتعبيرات التغيير بـ なります',
  vocab: [
    { id: 'oishisou', type: 'expression', jp: 'おいしそう', kanji: 'おいしそう', hiragana: 'おいしそう', reading: 'oishisou', meaning: 'يبدو لذيذا' },
    { id: 'omosou', type: 'expression', jp: '重そう', kanji: '重そう', hiragana: 'おもそう', reading: 'omosou', meaning: 'يبدو ثقيلا' },
    { id: 'taoresou', type: 'expression', jp: '倒れそう', kanji: '倒れそう', hiragana: 'たおれそう', reading: 'taoresou', meaning: 'يبدو على وشك السقوط' },
    { id: 'amesou', type: 'expression', jp: '雨が降りそう', kanji: '雨が降りそう', hiragana: 'あめがふりそう', reading: 'ame ga furisou', meaning: 'يبدو أنه سيمطر' },
    { id: 'genkisou', type: 'expression', jp: '元気そう', kanji: '元気そう', hiragana: 'げんきそう', reading: 'genkisou', meaning: 'يبدو نشيطا' },
    { id: 'shinpaisou', type: 'expression', jp: '心配そう', kanji: '心配そう', hiragana: 'しんぱいそう', reading: 'shinpaisou', meaning: 'يبدو قلقا' },
    { id: 'tanoshisou', type: 'expression', jp: '楽しそう', kanji: '楽しそう', hiragana: 'たのしそう', reading: 'tanoshisou', meaning: 'يبدو ممتعا' },
    { id: 'kowaresou', type: 'expression', jp: '壊れそう', kanji: '壊れそう', hiragana: 'こわれそう', reading: 'kowaresou', meaning: 'يبدو على وشك الانكسار' },
    { id: 'fuyu_ni_narimasu', type: 'expression', jp: '冬になります', kanji: '冬になります', hiragana: 'ふゆになります', reading: 'fuyu ni narimasu', meaning: 'يصبح الشتاء' },
    { id: 'byouki_ni_narimasu', type: 'expression', jp: '病気になります', kanji: '病気になります', hiragana: 'びょうきになります', reading: 'byouki ni narimasu', meaning: 'يمرض' },
    { id: 'jouzu_ni_narimasu', type: 'expression', jp: '上手になります', kanji: '上手になります', hiragana: 'じょうずになります', reading: 'jouzu ni narimasu', meaning: 'يصبح ماهرا' },
    { id: 'akaku_narimasu', type: 'expression', jp: '赤くなります', kanji: '赤くなります', hiragana: 'あかくなります', reading: 'akaku narimasu', meaning: 'يصبح أحمر' },
    { id: 'shizuka_ni_narimasu', type: 'expression', jp: '静かになります', kanji: '静かになります', hiragana: 'しずかになります', reading: 'shizuka ni narimasu', meaning: 'يصبح هادئا' },
    { id: 'samuku_narimasu', type: 'expression', jp: '寒くなります', kanji: '寒くなります', hiragana: 'さむくなります', reading: 'samuku narimasu', meaning: 'يصبح باردا' },
    { id: 'kumo', type: 'noun', jp: '雲', kanji: '雲', hiragana: 'くも', reading: 'kumo', meaning: 'سحابة' },
    { id: 'kuroi', type: 'i-adjective', jp: '黒い', kanji: '黒い', hiragana: 'くろい', reading: 'kuroi', meaning: 'أسود' },
    { id: 'nimotsu2', type: 'noun', jp: '荷物', kanji: '荷物', hiragana: 'にもつ', reading: 'nimotsu', meaning: 'أمتعة' },
    { id: 'hashiru', type: 'verb', jp: '走ります', kanji: '走ります', hiragana: 'はしります', reading: 'hashirimasu', meaning: 'يجري' },
    { id: 'kaeru2', type: 'verb', jp: '変わります', kanji: '変わります', hiragana: 'かわります', reading: 'kawarimasu', meaning: 'يتغير' },
    { id: 'sekkaku', type: 'adverb', jp: 'せっかく', hiragana: 'せっかく', reading: 'sekkaku', meaning: 'بمناسبة (جهد مبذول)' },
    { id: 'oishii_kaori', type: 'expression', jp: 'いい匂い', kanji: 'いい匂い', hiragana: 'いいにおい', reading: 'ii nioi', meaning: 'رائحة جميلة' },
    { id: 'kawaisou', type: 'expression', jp: 'かわいそう', hiragana: 'かわいそう', reading: 'kawaisou', meaning: 'مسكين / يثير الشفقة' },
    { id: 'nodo', type: 'noun', jp: '喉', kanji: '喉', hiragana: 'のど', reading: 'nodo', meaning: 'حلق / حنجرة' },
    { id: 'kawaku', type: 'verb', jp: '渇きます', kanji: '渇きます', hiragana: 'かわきます', reading: 'kawakimasu', meaning: 'يعطش / يجف' },
  ],
  grammar: [
    {
      title: '〜そうです (様態) — يبدو أن... (من الشكل الخارجي)',
      pattern: 'い形容詞(-い) + そうです ／ な形容詞 + そうです ／ 動詞(ます形) + そうです',
      particle: 'そうです (様態)',
      howItWorks: 'تستخدم そうです بعد جذع الصفة (بدون い في صفات い، ماعدا いい تصبح よさそう) أو جذع الفعل (ます形 بدون ます) للتعبير عن انطباع بصري/حدسي "يبدو أن...". تعبر عن ملاحظة فورية بناء على ما نراه.',
      explanation: 'أمثلة: おいしい → おいしそう (يبدو لذيذا)، 元気 → 元気そう (يبدو نشيطا)، 降ります → 降りそう (يبدو أنه سيهطل). ملاحظة خاصة: いい → よさそう، ない → なさそう.',
      example: { jp: 'この ケーキ は おいしそう です。', romaji: 'Kono keeki wa oishisou desu.', ar: 'هذه الكيكة تبدو لذيذة.' },
      exercises: [
        {
          type: 'build',
          ar: 'تلك الحقيبة تبدو ثقيلة.',
          words: ['あの', 'かばん', 'は', '重そう', 'です', '。'],
          particles: ['は'],
          answer: 'あの かばん は 重そう です 。',
        },
        {
          type: 'fill',
          ar: 'يبدو أنه سيمطر، لذا سآخذ مظلة.',
          sentence: '雨 が ___ から、 傘 を 持って いきます。',
          options: ['降りそうです', '降ります', '降って います', '降りました'],
          answer: '降りそうです',
        },
        {
          type: 'meaning',
          sentence: 'あの 子 は 元気そう です ね。',
          particle: 'そうです (様態)',
          options: ['ذلك الطفل يبدو نشيطا.', 'ذلك الطفل ليس نشيطا أبدا.', 'ذلك الطفل سيصبح نشيطا غدا.', 'لا أعرف ذلك الطفل.'],
          answer: 'ذلك الطفل يبدو نشيطا.',
        },
        {
          type: 'error',
          ar: 'هذا الطعام يبدو لذيذا.',
          options: ['この 料理 は おいしいそう です。', 'この 料理 は おいしそう です。', 'この 料理 は おいしくそう です。'],
          answer: 'この 料理 は おいしそう です。',
        },
      ],
    },
    {
      title: '〜そうです — حالات خاصة (いい・ない) واستخدامات إضافية',
      pattern: 'いい → よさそう ／ ない → なさそう ／ فعل + そう (وشيك الحدوث)',
      particle: 'そうです (استثناءات)',
      howItWorks: 'الصفة いい تتحول إلى よさそう (وليس いいそう). الصفة ない تتحول إلى なさそう. عند استخدامها مع أفعال مثل 倒れます/壊れます، تعني أن الحدث على وشك الوقوع "يبدو على وشك أن...".',
      explanation: 'مثال: この 天気 は よさそう です (يبدو هذا الطقس جيدا). この 本棚 は 倒れそう です (يبدو هذا الرف على وشك السقوط).',
      example: { jp: 'この 本棚 は 倒れそう です。', romaji: 'Kono hondana wa taoresou desu.', ar: 'يبدو هذا الرف على وشك السقوط.' },
      exercises: [
        {
          type: 'build',
          ar: 'يبدو هذا الطقس جيدا.',
          words: ['この', '天気', 'は', 'よさそう', 'です', '。'],
          particles: ['は'],
          answer: 'この 天気 は よさそう です 。',
        },
        {
          type: 'fill',
          ar: 'يبدو أنه ليس لديه وقت.',
          sentence: '時間 が ___ です。',
          options: ['なさそう', 'ないそう', 'なそう', 'なくそう'],
          answer: 'なさそう',
        },
        {
          type: 'meaning',
          sentence: 'この コップ は 壊れそう です から、 気をつけて ください。',
          particle: 'そうです (وشيك)',
          options: ['هذا الكوب يبدو على وشك الانكسار، فانتبه من فضلك.', 'هذا الكوب انكسر بالفعل.', 'هذا الكوب قوي جدا ولن ينكسر.', 'لا تلمس هذا الكوب أبدا.'],
          answer: 'هذا الكوب يبدو على وشك الانكسار، فانتبه من فضلك.',
        },
        {
          type: 'error',
          ar: 'تلك الأمتعة تبدو ثقيلة، دعني أساعدك.',
          options: ['その 荷物 は 重いそう です ね、 持ちましょう か。', 'その 荷物 は 重そう です ね、 持ちましょう か。', 'その 荷物 は 重く そう です ね、 持ちましょう か。'],
          answer: 'その 荷物 は 重そう です ね、 持ちましょう か。',
        },
      ],
    },
    {
      title: 'مراجعة: 〜くなります／〜になります — تعبيرات التغيير',
      pattern: 'い形容詞(-く) + なります ／ な形容詞・名詞 + に + なります',
      particle: 'なります',
      howItWorks: 'مراجعة: الصفات い تتحول بإسقاط い وإضافة く قبل なります (寒い → 寒くなります). الصفات な والأسماء تأخذ に قبل なります (静か → 静かになります، 冬 → 冬になります).',
      explanation: 'هذه القاعدة تم تقديمها في الدرس 16، وهنا نراجعها مع أمثلة جديدة وندمجها مع そうです: 空 が 暗くなって きました。 雨 が 降りそう です (أصبحت السماء مظلمة. يبدو أنه سيمطر).',
      example: { jp: '日本語 が 上手に なりました。', romaji: 'Nihongo ga jouzu ni narimashita.', ar: 'أصبحت ماهرا في اليابانية.' },
      exercises: [
        {
          type: 'build',
          ar: 'في الشتاء، يصبح الجو باردا.',
          words: ['冬', 'に', 'なる', 'と', '、', '寒くなります', '。'],
          particles: ['に', 'と'],
          answer: '冬 に なる と 、 寒くなります 。',
        },
        {
          type: 'fill',
          ar: 'وجهي أصبح أحمر.',
          sentence: '顔 が ___ なりました。',
          options: ['赤く', '赤い', '赤くて', '赤の'],
          answer: '赤く',
        },
        {
          type: 'meaning',
          sentence: '夜 に なると、 この 道 は 静かに なります。',
          particle: 'になります',
          options: ['عندما يحل الليل، يصبح هذا الطريق هادئا.', 'هذا الطريق صاخب دائما.', 'لن يأتي الليل أبدا.', 'أنا لا أمشي في هذا الطريق ليلا.'],
          answer: 'عندما يحل الليل، يصبح هذا الطريق هادئا.',
        },
        {
          type: 'error',
          ar: 'بعد أن مرضت، أصبحت أهتم بصحتي.',
          options: ['病気 に なって から、 健康 を 気をつけるように なりました。', '病気 に なって から、 健康 を 気をつける に なりました。', '病気 に なって から、 健康 を 気をつけて なりました。'],
          answer: '病気 に なって から、 健康 を 気をつけるように なりました。',
        },
      ],
    },
    {
      title: 'مراجعة شاملة: そうです (様態) و なります',
      pattern: 'دمج التعبيرين في وصف المشاهد والتغيرات',
      particle: 'مراجعة',
      howItWorks: 'دمج そうです (وصف الانطباع الحالي) مع なります (وصف التغير عبر الزمن) يسمح بوصف مشاهد ديناميكية: 空 が 暗く なって きました。雨 が 降りそうです (أصبحت السماء مظلمة، يبدو أنه سيمطر).',
      explanation: 'هذا الدرس يربط المهارات: そうです تعتمد على ملاحظة فورية، بينما なります تصف انتقالا من حالة إلى أخرى. كلاهما أساسي للمحادثة الطبيعية في اليابانية.',
      example: { jp: '空 が 暗くなって きました。 雨 が 降りそう です。', romaji: 'Sora ga kurakunatte kimashita. Ame ga furisou desu.', ar: 'أصبحت السماء مظلمة. يبدو أنه سيمطر.' },
      exercises: [
        {
          type: 'build',
          ar: 'الطفل يبدو سعيدا، أصبح يضحك كثيرا.',
          words: ['子供', 'は', '楽しそう', 'です', '、', 'よく', '笑う', 'ように', 'なりました', '。'],
          particles: ['は', 'よく'],
          answer: '子供 は 楽しそう です 、 よく 笑う ように なりました 。',
        },
        {
          type: 'fill',
          ar: 'السماء أصبحت سوداء، يبدو أنه سيمطر قريبا.',
          sentence: '空 が 黒く なりました。 もうすぐ 雨 が ___。',
          options: ['降りそうです', '降ります', '降りました', '降る'],
          answer: '降りそうです',
        },
        {
          type: 'meaning',
          sentence: '最近、 寒く なって きました。 そろそろ 冬 に なりそう です。',
          particle: 'مراجعة',
          options: ['أصبح الجو باردا مؤخرا، يبدو أن الشتاء سيأتي قريبا.', 'الجو حار جدا الآن.', 'الشتاء انتهى بالفعل.', 'لا تغيير في الطقس مؤخرا.'],
          answer: 'أصبح الجو باردا مؤخرا، يبدو أن الشتاء سيأتي قريبا.',
        },
        {
          type: 'error',
          ar: 'يبدو أن ذلك الكلب عطشان، دعنا نعطه ماء.',
          options: ['あの 犬 は 喉 が 渇きそう です、 水 を あげましょう。', 'あの 犬 は 喉 が 渇いたそう です、 水 を あげましょう。', 'あの 犬 は 喉 が 渇くそう です、 水 を あげましょう。'],
          answer: 'あの 犬 は 喉 が 渇きそう です、 水 を あげましょう。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'この ケーキ は おいしそう です。', romaji: 'Kono keeki wa oishisou desu.', ar: 'هذه الكيكة تبدو لذيذة.', en: 'This cake looks delicious.' },
    { jp: '雨 が 降りそう です。', romaji: 'Ame ga furisou desu.', ar: 'يبدو أنه سيمطر.', en: 'It looks like it’s going to rain.' },
    { jp: 'この 本棚 は 倒れそう です。', romaji: 'Kono hondana wa taoresou desu.', ar: 'يبدو هذا الرف على وشك السقوط.', en: 'This bookshelf looks like it’s about to fall.' },
    { jp: 'この 天気 は よさそう です。', romaji: 'Kono tenki wa yosasou desu.', ar: 'يبدو هذا الطقس جيدا.', en: 'This weather looks good.' },
    { jp: '時間 が なさそう です。', romaji: 'Jikan ga nasasou desu.', ar: 'يبدو أنه ليس لدي وقت.', en: 'It looks like there’s no time.' },
    { jp: '冬 に なると、 寒く なります。', romaji: 'Fuyu ni naru to, samuku narimasu.', ar: 'عندما يأتي الشتاء، يصبح الجو باردا.', en: 'When winter comes, it gets cold.' },
    { jp: '日本語 が 上手に なりました。', romaji: 'Nihongo ga jouzu ni narimashita.', ar: 'أصبحت ماهرا في اليابانية.', en: 'I’ve become good at Japanese.' },
    { jp: '空 が 暗くなって きました。 雨 が 降りそう です。', romaji: 'Sora ga kurakunatte kimashita. Ame ga furisou desu.', ar: 'أصبحت السماء مظلمة. يبدو أنه سيمطر.', en: 'The sky has gotten dark. It looks like it’s going to rain.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: あの 子 は 元気そう です。', answer: 'ذلك الطفل يبدو نشيطا.', hint: 'そうです (様態)' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 日本語 が 上手に なりました。', answer: 'أصبحت ماهرا في اليابانية.', hint: 'になります' },
    { type: 'complete', prompt: 'أكمل: この ケーキ は おい___です。', answer: 'しそう', hint: 'そうです بعد صفة い' },
    { type: 'complete', prompt: 'أكمل: この 天気 は ___です。 (いい)', answer: 'よさそう', hint: 'استثناء いい' },
    { type: 'complete', prompt: 'أكمل: 顔 が 赤く ___。', answer: 'なりました', hint: 'くなります' },
    { type: 'order', prompt: 'رتب: です / 重そう / は / その 荷物', answer: 'その 荷物 は 重そう です。', hint: 'そうです' },
    { type: 'order', prompt: 'رتب: なります / と / 寒く / 冬 / に / なる', answer: '冬 に なると、 寒く なります。', hint: 'なります مع と' },
    { type: 'answer', prompt: 'この 料理 は どうですか。 (おいしい - يبدو)', answer: 'この 料理 は おいしそう です。', hint: 'الإجابة بـ そうです' },
    { type: 'answer', prompt: '冬 に なると、 どう なりますか。 (寒い)', answer: '冬 に なると、 寒く なります。', hint: 'الإجابة بـ なります' },
  ],
  videos: [],
}
