export const lessonThree = {
  id: 3,
  title: { ar: 'الأماكن والاتجاهات والأسعار', en: 'Places, Directions and Prices' },
  focus: 'استخدام ここ・そこ・あそこ و こちら・そちら・あちら، و の للانتماء/المنشأ، والسؤال عن السعر بـ いくら',
  dialogue: {
    titleAr: 'في المجمع التجاري — ميلر يسأل عن الأقسام',
    lines: [
      { speaker: 'ميلر', jp: 'すみません。靴売り場は どこですか。', romaji: 'Sumimasen. Kutsu uriba wa doko desu ka.', ar: 'عفوًا، أين قسم الأحذية؟' },
      { speaker: 'الموظفة', jp: '靴売り場は 2階です。', romaji: 'Kutsu uriba wa ni-kai desu.', ar: 'قسم الأحذية في الطابق الثاني.' },
      { speaker: 'ميلر', jp: 'お手洗いは どこですか。', romaji: 'Otearai wa doko desu ka.', ar: 'وأين دورة المياه؟' },
      { speaker: 'الموظفة', jp: 'あそこです。', romaji: 'Asoko desu.', ar: 'هناك.' },
      { speaker: 'ميلر', jp: 'この財布は いくらですか。', romaji: 'Kono saifu wa ikura desu ka.', ar: 'كم سعر هذه المحفظة؟' },
      { speaker: 'الموظفة', jp: '3000円です。', romaji: 'Sanzen-en desu.', ar: 'ثلاثة آلاف ين.' },
      { speaker: 'ميلر', jp: 'どうもありがとうございます。', romaji: 'Doumo arigatou gozaimasu.', ar: 'شكرًا جزيلًا.' },
    ],
  },
  reading: {
    titleAr: 'شركتي — جولة في المبنى',
    sentences: [
      { jp: 'ここは 私の 会社です。', romaji: 'Koko wa watashi no kaisha desu.', ar: 'هنا شركتي.' },
      { jp: '受付は 1階です。', romaji: 'Uketsuke wa ik-kai desu.', ar: 'الاستقبال في الطابق الأول.' },
      { jp: '会議室は 3階です。', romaji: 'Kaigishitsu wa san-gai desu.', ar: 'قاعة الاجتماعات في الطابق الثالث.' },
      { jp: '食堂は あそこです。', romaji: 'Shokudou wa asoko desu.', ar: 'الكافتيريا هناك.' },
      { jp: '銀行は あちらです。', romaji: 'Ginkou wa achira desu.', ar: 'البنك في تلك الجهة.' },
    ],
    questions: [
      { q: 'في أي طابق يقع الاستقبال؟', options: ['الطابق الأول', 'الطابق الثاني', 'الطابق الثالث'], answer: 'الطابق الأول' },
      { q: 'في أي طابق قاعة الاجتماعات؟', options: ['الثالث', 'الأول', 'الثاني'], answer: 'الثالث' },
      { q: 'أين الكافتيريا؟', options: ['هناك', 'في الطابق الثاني', 'في البنك'], answer: 'هناك' },
    ],
  },
  vocab: [
    { id: 'koko', type: 'place', jp: 'ここ', hiragana: 'ここ', reading: 'koko', meaning: 'هنا' },
    { id: 'soko', type: 'place', jp: 'そこ', hiragana: 'そこ', reading: 'soko', meaning: 'هناك (قريب منك)' },
    { id: 'asoko', type: 'place', jp: 'あそこ', hiragana: 'あそこ', reading: 'asoko', meaning: 'هناك (بعيد عن الطرفين)' },
    { id: 'doko', type: 'question-word', jp: 'どこ', hiragana: 'どこ', reading: 'doko', meaning: 'أين' },
    { id: 'kochira', type: 'place', jp: 'こちら', hiragana: 'こちら', reading: 'kochira', meaning: 'هنا (مهذبة) / هذه الجهة' },
    { id: 'sochira', type: 'place', jp: 'そちら', hiragana: 'そちら', reading: 'sochira', meaning: 'هناك (مهذبة) / تلك الجهة' },
    { id: 'achira', type: 'place', jp: 'あちら', hiragana: 'あちら', reading: 'achira', meaning: 'هناك بعيدا (مهذبة)' },
    { id: 'dochira', type: 'question-word', jp: 'どちら', hiragana: 'どちら', reading: 'dochira', meaning: 'أين / أي جهة (مهذبة)' },
    { id: 'kuni', type: 'place', jp: '国', kanji: '国', hiragana: 'くに', reading: 'kuni', meaning: 'بلد / دولة' },
    { id: 'kaisha', type: 'place', jp: '会社', kanji: '会社', hiragana: 'かいしゃ', reading: 'kaisha', meaning: 'شركة' },
    { id: 'depart', type: 'place', jp: 'デパート', hiragana: 'デパート', reading: 'depaato', meaning: 'مجمع تجاري' },
    { id: 'ginkou', type: 'place', jp: '銀行', kanji: '銀行', hiragana: 'ぎんこう', reading: 'ginkou', meaning: 'بنك' },
    { id: 'yuubinkyoku', type: 'place', jp: '郵便局', kanji: '郵便局', hiragana: 'ゆうびんきょく', reading: 'yuubinkyoku', meaning: 'مكتب بريد' },
    { id: 'toilet', type: 'place', jp: 'お手洗い', kanji: 'お手洗い', hiragana: 'おてあらい', reading: 'otearai', meaning: 'حمام / دورة مياه' },
    { id: 'denwa', type: 'object', jp: '電話', kanji: '電話', hiragana: 'でんわ', reading: 'denwa', meaning: 'هاتف' },
    { id: 'kaigishitsu', type: 'place', jp: '会議室', kanji: '会議室', hiragana: 'かいぎしつ', reading: 'kaigishitsu', meaning: 'قاعة اجتماعات' },
    { id: 'uketsuke', type: 'place', jp: '受付', kanji: '受付', hiragana: 'うけつけ', reading: 'uketsuke', meaning: 'الاستقبال' },
    { id: 'shokudou', type: 'place', jp: '食堂', kanji: '食堂', hiragana: 'しょくどう', reading: 'shokudou', meaning: 'مطعم / كافتيريا' },
    { id: 'kai', type: 'counter', jp: '〜階', kanji: '〜階', hiragana: '〜かい', reading: '~kai', meaning: 'الطابق رقم ~' },
    { id: 'ikura', type: 'question-word', jp: 'いくら', hiragana: 'いくら', reading: 'ikura', meaning: 'كم السعر' },
    { id: 'en', type: 'currency', jp: '円', kanji: '円', hiragana: 'えん', reading: 'en', meaning: 'ين ياباني' },
    { id: 'uriba', type: 'place', jp: '売り場', kanji: '売り場', hiragana: 'うりば', reading: 'uriba', meaning: 'قسم البيع' },
    { id: 'kutsu', type: 'object', jp: '靴', kanji: '靴', hiragana: 'くつ', reading: 'kutsu', meaning: 'حذاء' },
    { id: 'saifu', type: 'object', jp: '財布', kanji: '財布', hiragana: 'さいふ', reading: 'saifu', meaning: 'محفظة' },
    { id: 'sumimasen', type: 'expression', jp: 'すみません', hiragana: 'すみません', reading: 'sumimasen', meaning: 'عفوا / آسف' },
    { id: 'doumo-arigatou', type: 'expression', jp: 'どうもありがとうございます', hiragana: 'どうもありがとうございます', reading: 'doumo arigatou gozaimasu', meaning: 'شكرا جزيلا' },
  ],
  grammar: [
    {
      title: 'ここ・そこ・あそこ・どこ — أسماء الإشارة للأماكن',
      pattern: 'ここ／そこ／あそこ + は + اسم مكان + です',
      particle: 'は',
      howItWorks: 'تعمل ここ/そこ/あそこ بنفس منطق これ/それ/あれ لكن للأماكن بدل الأشياء: ここ مكان قريب من المتكلم، そこ قريب من المستمع، あそこ بعيد عن الاثنين، و どこ للسؤال عن المكان.',
      explanation: 'تُستخدم هذه الكلمات كموضوع للجملة مع は، ويُجاب عن どこ بذكر اسم المكان مع です.',
      example: { jp: 'ここ は 受付 です。', romaji: 'Koko wa uketsuke desu.', ar: 'هنا الاستقبال.' },
      exercises: [
        {
          type: 'build',
          ar: 'هناك (البعيد) قاعة الاجتماعات.',
          words: ['あそこ', 'は', '会議室', 'です', '。'],
          particles: ['は'],
          answer: 'あそこ は 会議室 です 。',
        },
        {
          type: 'fill',
          ar: 'أين البنك؟',
          sentence: '銀行 は ___ ですか。',
          options: ['どこ', 'いくら', 'なん', 'だれ'],
          answer: 'どこ',
        },
        {
          type: 'meaning',
          sentence: 'お手洗い は そこ です。',
          particle: 'は',
          options: ['الحمام هناك (قريب منك).', 'أين الحمام؟', 'هذا حمام.', 'الحمام في الطابق الأول.'],
          answer: 'الحمام هناك (قريب منك).',
        },
        {
          type: 'error',
          ar: 'هنا مكتب البريد.',
          options: ['ここ の 郵便局 です。', 'ここ は 郵便局 です。', 'これ は 郵便局 ここ です。'],
          answer: 'ここ は 郵便局 です。',
        },
      ],
    },
    {
      title: 'こちら・そちら・あちら・どちら — صيغة مهذبة للاتجاهات',
      pattern: 'こちら／そちら／あちら／どちら + です',
      particle: 'こちら',
      howItWorks: 'こちら/そちら/あちら/どちら أكثر تهذيبا من ここ/そこ/あそこ/どこ، وتُستخدم أيضا للإشارة المهذبة لشخص أو جهة (مثل تقديم شخص: こちらは〜さんです).',
      explanation: 'في المواقف الرسمية (الفنادق، الشركات) تُفضَّل こちら وأخواتها على ここ وأخواتها، كما تُستخدم للإشارة لشخص بأدب.',
      example: { jp: 'エレベーター は あちら です。', romaji: 'Erebeetaa wa achira desu.', ar: 'المصعد من تلك الجهة.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذا السيد ميلر. (تقديم بأدب)',
          words: ['こちら', 'は', 'ミラーさん', 'です', '。'],
          particles: ['こちら'],
          answer: 'こちら は ミラーさん です 。',
        },
        {
          type: 'fill',
          ar: 'من أين أنت؟ (بأدب)',
          sentence: '失礼 です が、お国 は ___ です か。',
          options: ['どちら', 'どこ', 'いくら', 'なに'],
          answer: 'どちら',
        },
        {
          type: 'meaning',
          sentence: '会議室 は そちら です。',
          particle: 'そちら',
          options: ['قاعة الاجتماعات من تلك الجهة.', 'أين قاعة الاجتماعات؟', 'هذه قاعة اجتماعات.', 'قاعة الاجتماعات هنا.'],
          answer: 'قاعة الاجتماعات من تلك الجهة.',
        },
        {
          type: 'error',
          ar: 'المصعد من هذه الجهة من فضلك.',
          options: ['エレベーター は こちら です。', 'エレベーター こちら は です。', 'こちら は エレベーター を です。'],
          answer: 'エレベーター は こちら です。',
        },
      ],
    },
    {
      title: 'の — بلد المنشأ والشركة المصنّعة',
      pattern: 'بلد/شركة + の + اسم',
      particle: 'の',
      howItWorks: 'بالإضافة إلى الملكية، تُستخدم の للربط بين الشيء وبلد أو جهة صنعه أو انتمائه، مثل フランス の かばん (حقيبة فرنسية الصنع).',
      explanation: 'N1 の N2 حيث N1 يحدد منشأ أو نوع N2 — يمكن أن يكون بلدا، شركة، أو مادة (مثال: 革 の 靴 = حذاء جلدي).',
      example: { jp: 'これ は フランス の かばん です。', romaji: 'Kore wa Furansu no kaban desu.', ar: 'هذه حقيبة فرنسية الصنع.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذه ساعة سويسرية.',
          words: ['これ', 'は', 'スイス', 'の', '時計', 'です', '。'],
          particles: ['の'],
          answer: 'これ は スイス の 時計 です 。',
        },
        {
          type: 'fill',
          ar: 'هذا حذاء جلدي.',
          sentence: 'これ は 革 ___ 靴 です。',
          options: ['の', 'は', 'を', 'と'],
          answer: 'の',
        },
        {
          type: 'meaning',
          sentence: 'それ は どこ の ワイン です か。',
          particle: 'の',
          options: ['من أين هذا النبيذ (من أي بلد)؟', 'كم سعر هذا النبيذ؟', 'هذا نبيذ ياباني.', 'هل هذا نبيذ؟'],
          answer: 'من أين هذا النبيذ (من أي بلد)؟',
        },
        {
          type: 'error',
          ar: 'هذه شنطة شركة IMC.',
          options: ['これ は IMC かばん の です。', 'これ は IMC の かばん です。', 'これ の は IMC かばん です。'],
          answer: 'これ は IMC の かばん です。',
        },
      ],
    },
    {
      title: 'いくらですか — السؤال عن السعر',
      pattern: 'これ／それ／あれ + は + いくら ですか。',
      particle: 'いくら',
      howItWorks: 'いくら كلمة سؤال تعني "كم السعر"، تأتي مكان です مباشرة بعد は. الجواب يكون برقم + 円 (ين).',
      explanation: 'تُستخدم いくら حصرا للسؤال عن الأسعار أو الكميات غير المعدودة، بخلاف 何 (ماذا) و だれ (من).',
      example: { jp: 'この 傘 は いくら です か。 ／ 2,000円 です。', romaji: 'Kono kasa wa ikura desu ka. / Nisen-en desu.', ar: 'كم سعر هذه المظلة؟ / 2000 ين.' },
      exercises: [
        {
          type: 'build',
          ar: 'كم سعر هذه الحقيبة؟',
          words: ['この', 'かばん', 'は', 'いくら', 'です', 'か', '。'],
          particles: ['いくら'],
          answer: 'この かばん は いくら です か 。',
        },
        {
          type: 'fill',
          ar: 'هذا القاموس بـ 3000 ين.',
          sentence: 'この 辞書 は 3,000 ___ です。',
          options: ['円', 'いくら', 'の', 'です'],
          answer: '円',
        },
        {
          type: 'meaning',
          sentence: 'すみません、この 靴 は いくら です か。',
          particle: 'いくら',
          options: ['عفوا، كم سعر هذا الحذاء؟', 'عفوا، أين هذا الحذاء؟', 'هذا الحذاء غالٍ.', 'هل هذا حذائي؟'],
          answer: 'عفوا، كم سعر هذا الحذاء؟',
        },
        {
          type: 'error',
          ar: 'كم سعر تلك الساعة (البعيدة)؟',
          options: ['あの 時計 は いくら です か。', 'あの 時計 いくら は です か。', 'あれ の 時計 は いくら です か。'],
          answer: 'あの 時計 は いくら です か。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'すみません、お手洗い は どこ です か。', romaji: 'Sumimasen, otearai wa doko desu ka.', ar: 'عفوا، أين الحمام؟', en: 'Excuse me, where is the restroom?' },
    { jp: 'あそこ です。', romaji: 'Asoko desu.', ar: 'هناك.', en: 'It is over there.' },
    { jp: 'エレベーター は あちら です。', romaji: 'Erebeetaa wa achira desu.', ar: 'المصعد من تلك الجهة.', en: 'The elevator is that way.' },
    { jp: '失礼 です が、お国 は どちら です か。', romaji: 'Shitsurei desu ga, okuni wa dochira desu ka.', ar: 'عفوا، من أي بلد أنت؟', en: 'Excuse me, where are you from?' },
    { jp: 'インド です。', romaji: 'Indo desu.', ar: 'من الهند.', en: 'From India.' },
    { jp: 'これ は ブラジル の コーヒー です。', romaji: 'Kore wa Burajiru no koohii desu.', ar: 'هذه قهوة برازيلية.', en: 'This is Brazilian coffee.' },
    { jp: 'この 時計 は いくら です か。', romaji: 'Kono tokei wa ikura desu ka.', ar: 'كم سعر هذه الساعة؟', en: 'How much is this watch?' },
    { jp: '18,000円 です。', romaji: 'Ichiman-hassen-en desu.', ar: '18000 ين.', en: 'It is 18,000 yen.' },
    { jp: ' 靴 売り場 は 2階 です。', romaji: 'Kutsu uriba wa nikai desu.', ar: 'قسم بيع الأحذية في الطابق الثاني.', en: 'The shoe department is on the 2nd floor.' },
    { jp: 'どうも ありがとう ございます。', romaji: 'Doumo arigatou gozaimasu.', ar: 'شكرا جزيلا.', en: 'Thank you very much.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: お手洗い は あそこ です。', answer: 'الحمام هناك (بعيد).', hint: 'ترجمة الجملة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: これ は どこ の 時計 です か。', answer: 'من أي بلد هذه الساعة؟', hint: 'ترجمة الجملة' },
    { type: 'complete', prompt: 'أكمل: 銀行 は ___ ですか。', answer: 'どこ', hint: 'السؤال عن المكان' },
    { type: 'complete', prompt: 'أكمل: お国 は ___ です か。 (بأدب)', answer: 'どちら', hint: 'السؤال المهذب عن البلد' },
    { type: 'complete', prompt: 'أكمل: この かばん は ___ です か。 (السؤال عن السعر)', answer: 'いくら', hint: 'السؤال عن السعر' },
    { type: 'order', prompt: 'رتب: です / 会議室 / そちら / は', answer: '会議室 は そちら です。', hint: 'استخدام そちら' },
    { type: 'order', prompt: 'رتب: の / です / かばん / これ / フランス / は', answer: 'これ は フランス の かばん です。', hint: 'استخدام の للمنشأ' },
    { type: 'answer', prompt: 'すみません、お手洗い は どこ です か。 (جاوب: そこ)', answer: 'そこ です。', hint: 'الإجابة عن مكان' },
    { type: 'answer', prompt: 'この 靴 は いくら です か。 (5,000円)', answer: '5,000円 です。', hint: 'الإجابة عن السعر' },
  ],
  videos: [],
}
