export const lessonTwentyOne = {
  id: 21,
  title: { ar: 'الشرط ب たら و なら', en: 'Conditionals: たら and なら' },
  focus: '〜たら للتعبير عن الشرط/التتابع الزمني، و なら لتقديم اقتراح بناء على ما قاله المتحدث الآخر',
  vocab: [
    { id: 'okimasu2', type: 'verb', jp: '起きます', kanji: '起きます', hiragana: 'おきます', reading: 'okimasu', meaning: 'يستيقظ' },
    { id: 'tsukimasu', type: 'verb', jp: '着きます', kanji: '着きます', hiragana: 'つきます', reading: 'tsukimasu', meaning: 'يصل' },
    { id: 'takarakuji', type: 'noun', jp: '宝くじ', kanji: '宝くじ', hiragana: 'たからくじ', reading: 'takarakuji', meaning: 'يانصيب' },
    { id: 'atarimasu', type: 'verb', jp: '当たります', kanji: '当たります', hiragana: 'あたります', reading: 'atarimasu', meaning: 'يفوز / يصيب' },
    { id: 'kaigi2', type: 'noun', jp: '会議', kanji: '会議', hiragana: 'かいぎ', reading: 'kaigi', meaning: 'اجتماع' },
    { id: 'owarimasu2', type: 'verb', jp: '終わります', kanji: '終わります', hiragana: 'おわります', reading: 'owarimasu', meaning: 'ينتهي' },
    { id: 'denwa_bangou', type: 'noun', jp: '電話番号', kanji: '電話番号', hiragana: 'でんわばんごう', reading: 'denwa bangou', meaning: 'رقم الهاتف' },
    { id: 'wakarimasu2', type: 'verb', jp: 'わかります', hiragana: 'わかります', reading: 'wakarimasu', meaning: 'يفهم / يعرف' },
    { id: 'oshiete_kudasai', type: 'expression', jp: '教えてください', kanji: '教えてください', hiragana: 'おしえてください', reading: 'oshiete kudasai', meaning: 'من فضلك علمني / أخبرني' },
    { id: 'kuukou', type: 'place', jp: '空港', kanji: '空港', hiragana: 'くうこう', reading: 'kuukou', meaning: 'مطار' },
    { id: 'kankoku', type: 'place', jp: '韓国', kanji: '韓国', hiragana: 'かんこく', reading: 'kankoku', meaning: 'كوريا' },
    { id: 'okinawa', type: 'place', jp: '沖縄', kanji: '沖縄', hiragana: 'おきなわ', reading: 'okinawa', meaning: 'أوكيناوا' },
    { id: 'hokkaidou', type: 'place', jp: '北海道', kanji: '北海道', hiragana: 'ほっかいどう', reading: 'hokkaidou', meaning: 'هوكايدو' },
    { id: 'oishii_mise', type: 'expression', jp: 'おいしい店', kanji: 'おいしい店', hiragana: 'おいしいみせ', reading: 'oishii mise', meaning: 'مطعم لذيذ' },
    { id: 'osusume', type: 'noun', jp: 'おすすめ', hiragana: 'おすすめ', reading: 'osusume', meaning: 'توصية / مقترح' },
    { id: 'sake', type: 'noun', jp: 'お酒', kanji: 'お酒', hiragana: 'おさけ', reading: 'osake', meaning: 'كحول / خمر' },
    { id: 'tsukaremasu', type: 'verb', jp: '疲れます', kanji: '疲れます', hiragana: 'つかれます', reading: 'tsukaremasu', meaning: 'يتعب' },
    { id: 'yasumimasu', type: 'verb', jp: '休みます', kanji: '休みます', hiragana: 'やすみます', reading: 'yasumimasu', meaning: 'يستريح / يأخذ إجازة' },
    { id: 'gohan_taberu', type: 'expression', jp: 'ご飯を食べます', kanji: 'ご飯を食べます', hiragana: 'ごはんをたべます', reading: 'gohan o tabemasu', meaning: 'يأكل الطعام' },
    { id: 'shukudai2', type: 'noun', jp: '宿題', kanji: '宿題', hiragana: 'しゅくだい', reading: 'shukudai', meaning: 'واجب منزلي' },
    { id: 'sugu', type: 'adverb', jp: 'すぐ', hiragana: 'すぐ', reading: 'sugu', meaning: 'فورا / حالا' },
    { id: 'tenki2', type: 'noun', jp: '天気', kanji: '天気', hiragana: 'てんき', reading: 'tenki', meaning: 'طقس' },
    { id: 'pikunikku', type: 'noun', jp: 'ピクニック', hiragana: 'ピクニック', reading: 'pikunikku', meaning: 'نزهة' },
    { id: 'okane2', type: 'noun', jp: 'お金', kanji: 'お金', hiragana: 'おかね', reading: 'okane', meaning: 'مال' },
  ],
  grammar: [
    {
      title: '〜たら (て形 الماضي + ら) — الشرط/عند حدوث',
      pattern: 'فعل/صفة (た形) + ら、 جملة',
      particle: 'たら',
      howItWorks: 'تتكون たら بإضافة ら إلى صيغة た الماضي للفعل أو الصفة. تستخدم للتعبير عن "إذا/عندما يحدث X، فسيحدث Y" — قد تكون شرطا افتراضيا أو تتابعا زمنيا طبيعيا.',
      explanation: 'مثال: 雨 が 降ったら、 ピクニック を しません (إذا أمطرت، لن نقوم بالنزهة). أو للتتابع: 家 に 着いたら、 電話 します (عندما أصل إلى البيت، سأتصل).',
      example: { jp: '宝くじ が 当たったら、 旅行 します。', romaji: 'Takarakuji ga atattara, ryokou shimasu.', ar: 'إذا فزت باليانصيب، سأسافر.' },
      exercises: [
        {
          type: 'build',
          ar: 'إذا انتهى الاجتماع، سأتصل بك.',
          words: ['会議', 'が', '終わったら', '、', '電話', 'します', '。'],
          particles: ['が', '電話'],
          answer: '会議 が 終わったら 、 電話 します 。',
        },
        {
          type: 'fill',
          ar: 'إذا استيقظت مبكرا، سأذهب للجري.',
          sentence: '早く ___ 、 走りに 行きます。',
          options: ['起きたら', '起きます', '起きて', '起きる'],
          answer: '起きたら',
        },
        {
          type: 'meaning',
          sentence: '家 に 着いたら、 メール を 送ります。',
          particle: 'たら',
          options: ['عندما أصل إلى البيت، سأرسل بريدا إلكترونيا.', 'لن أصل إلى البيت أبدا.', 'وصلت إلى البيت وأرسلت البريد بالفعل.', 'البيت بعيد عن المكتب.'],
          answer: 'عندما أصل إلى البيت، سأرسل بريدا إلكترونيا.',
        },
        {
          type: 'error',
          ar: 'إذا كان الجو جميلا غدا، سنذهب في نزهة.',
          options: ['明日 天気 が よかったら、 ピクニック を します。', '明日 天気 が いいたら、 ピクニック を します。', '明日 天気 が よくたら、 ピクニック を します。'],
          answer: '明日 天気 が よかったら、 ピクニック を します。',
        },
      ],
    },
    {
      title: '〜たら للأوامر والاقتراحات والنتائج المفاجئة',
      pattern: 'جملة + たら، جملة (أمر/اقتراح/نتيجة)',
      particle: 'たら',
      howItWorks: 'يمكن أن يأتي بعد たら أمر (てください/ましょう) أو اقتراح، أو وصف لنتيجة فوجئنا بها عند حدوث الشرط.',
      explanation: 'مثال للاقتراح: 疲れたら、 休んでください (إذا تعبت، استرح من فضلك). مثال للمفاجأة: ドア を 開けたら、 猫 が いました (عندما فتحت الباب، كانت هناك قطة).',
      example: { jp: '疲れたら、 休んで ください。', romaji: 'Tsukaretara, yasunde kudasai.', ar: 'إذا تعبت، استرح من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'إذا انتهيت من الواجب، العب.',
          words: ['宿題', 'が', '終わったら', '、', '遊んで', 'ください', '。'],
          particles: ['が'],
          answer: '宿題 が 終わったら 、 遊んで ください 。',
        },
        {
          type: 'fill',
          ar: 'إذا وصلت إلى المطار، اتصل بي من فضلك.',
          sentence: '空港 に ___ 、 電話して ください。',
          options: ['着いたら', '着きます', '着いて', '着く'],
          answer: '着いたら',
        },
        {
          type: 'meaning',
          sentence: '窓 を 開けたら、 鳥 が 入って きました。',
          particle: 'たら',
          options: ['عندما فتحت النافذة، دخل طائر.', 'لن أفتح النافذة أبدا.', 'الطائر فتح النافذة.', 'النافذة مكسورة.'],
          answer: 'عندما فتحت النافذة، دخل طائر.',
        },
        {
          type: 'error',
          ar: 'إذا كان لديك وقت، تعال إلى بيتي.',
          options: ['暇 が あったら、 うち へ 来て ください。', '暇 が あるたら、 うち へ 来て ください。', '暇 が あって たら、 うち へ 来て ください。'],
          answer: '暇 が あったら、 うち へ 来て ください。',
        },
      ],
    },
    {
      title: '〜なら — تقديم اقتراح بناء على موضوع مذكور',
      pattern: 'اسم/جملة (普通形) + なら、 جملة (اقتراح)',
      particle: 'なら',
      howItWorks: 'تستخدم なら عندما يذكر شخص موضوعا، فيقوم المستمع بتقديم اقتراح أو معلومة متعلقة بهذا الموضوع تحديدا. تأتي بعد الاسم مباشرة أو بعد جملة بصيغتها العادية.',
      explanation: 'الفرق بين たら و なら: たら شرط زمني (إذا/عندما X، فY بعده)، أما なら فهي تعليق على موضوع مذكور وتقديم اقتراح بشأنه فورا، وليس بالضرورة بعد حدوثه.',
      example: { jp: 'A: 韓国 へ 行きます。 B: 韓国 なら、 キムチ が おいしいです よ。', romaji: 'Kankoku e ikimasu. / Kankoku nara, kimuchi ga oishii desu yo.', ar: 'سأذهب إلى كوريا. / إذا كانت كوريا، فالكيمتشي لذيذ هناك.' },
      exercises: [
        {
          type: 'build',
          ar: 'إذا كانت اليابانية، السيد تاناكا يعرفها جيدا.',
          words: ['日本語', 'なら', '、', '田中さん', 'が', 'よく', '知って', 'います', '。'],
          particles: ['なら', 'が'],
          answer: '日本語 なら 、 田中さん が よく 知って います 。',
        },
        {
          type: 'fill',
          ar: 'إذا كان الأمر عن أوكيناوا، الطقس جميل في الصيف.',
          sentence: '沖縄 ___ 、 夏 は 天気 が いいです。',
          options: ['なら', 'たら', 'ても', 'ので'],
          answer: 'なら',
        },
        {
          type: 'meaning',
          sentence: 'A: いい カメラ が 欲しい です。 B: カメラ なら、 あの 店 が いいです。',
          particle: 'なら',
          options: ['إذا كان الأمر عن كاميرا، فذلك المتجر جيد.', 'لا توجد كاميرات في هذا المتجر.', 'الكاميرا غالية جدا.', 'سأشتري كاميرا غدا فقط.'],
          answer: 'إذا كان الأمر عن كاميرا، فذلك المتجر جيد.',
        },
        {
          type: 'error',
          ar: 'إذا أردت الذهاب إلى هناك، القطار أسرع.',
          options: ['そこ へ 行く なら、 電車 の ほうが 速いです。', 'そこ へ 行く たら、 電車 の ほうが 速いです。', 'そこ へ 行きます なら、 電車 の ほうが 速いです。'],
          answer: 'そこ へ 行く なら、 電車 の ほうが 速いです。',
        },
      ],
    },
    {
      title: 'مراجعة شاملة: たら مقابل なら',
      pattern: 'مقارنة الاستخدام في سياقات مختلفة',
      particle: 'مراجعة',
      howItWorks: 'たら: شرط/تتابع زمني — "عندما/إذا حدث X (في المستقبل)، سيحدث Y". なら: تعليق فوري على موضوع ذكره المتحدث الآخر وتقديم اقتراح بشأنه.',
      explanation: 'مثال للمقارنة: 雨 が 降ったら、 家 に います (إذا أمطرت، سأبقى في البيت - شرط مستقبلي). مقابل: 雨 なら、 傘 を 持って いきます (إذا كان (الجو) ممطرا (الآن)، سآخذ مظلة - تعليق على وضع حالي).',
      example: { jp: 'A: 来週 旅行 します。 B: 旅行 なら、 沖縄 が いい です よ。', romaji: 'Raishuu ryokou shimasu. / Ryokou nara, Okinawa ga ii desu yo.', ar: 'سأسافر الأسبوع القادم. / إذا كان الأمر عن السفر، فأوكيناوا جيدة.' },
      exercises: [
        {
          type: 'build',
          ar: 'إذا انتهى العمل، سأذهب لشرب الخمر.',
          words: ['仕事', 'が', '終わったら', '、', 'お酒', 'を', '飲みに', '行きます', '。'],
          particles: ['が', 'を'],
          answer: '仕事 が 終わったら 、 お酒 を 飲みに 行きます 。',
        },
        {
          type: 'fill',
          ar: 'إذا كان الأمر عن مطعم لذيذ، أعرف مكانا جيدا.',
          sentence: 'おいしい 店 ___ 、 いい ところ を 知って います。',
          options: ['なら', 'たら', 'ては', 'ながら'],
          answer: 'なら',
        },
        {
          type: 'meaning',
          sentence: 'お金 が あったら、 新しい 車 を 買います。',
          particle: 'たら',
          options: ['إذا كان لدي مال، سأشتري سيارة جديدة.', 'ليس لدي مال أبدا.', 'اشتريت سيارة جديدة بالفعل.', 'السيارة القديمة أفضل.'],
          answer: 'إذا كان لدي مال، سأشتري سيارة جديدة.',
        },
        {
          type: 'error',
          ar: 'إذا أردت معرفة رقم هاتفه، اسأل السيد تاناكا.',
          options: ['電話番号 が わかりたい なら、 田中さん に 聞いて ください。', '電話番号 が 知りたい なら、 田中さん に 聞いて ください。', '電話番号 が 知りたい たら、 田中さん に 聞いて ください。'],
          answer: '電話番号 が 知りたい なら、 田中さん に 聞いて ください。',
        },
      ],
    },
  ],
  examples: [
    { jp: '雨 が 降ったら、 ピクニック を しません。', romaji: 'Ame ga futtara, pikunikku o shimasen.', ar: 'إذا أمطرت، لن نقوم بالنزهة.', en: 'If it rains, we won’t have the picnic.' },
    { jp: '家 に 着いたら、 電話 します。', romaji: 'Ie ni tsuitara, denwa shimasu.', ar: 'عندما أصل إلى البيت، سأتصل.', en: 'When I get home, I’ll call.' },
    { jp: '宝くじ が 当たったら、 何 を しますか。', romaji: 'Takarakuji ga atattara, nani o shimasu ka.', ar: 'إذا فزت باليانصيب، ماذا ستفعل؟', en: 'If you won the lottery, what would you do?' },
    { jp: '疲れたら、 休んで ください。', romaji: 'Tsukaretara, yasunde kudasai.', ar: 'إذا تعبت، استرح من فضلك.', en: 'If you get tired, please rest.' },
    { jp: 'A: 北海道 へ 行きます。 B: 北海道 なら、 冬 が いいです よ。', romaji: 'Hokkaidou e ikimasu. / Hokkaidou nara, fuyu ga ii desu yo.', ar: 'سأذهب إلى هوكايدو. / إذا كان الأمر عن هوكايدو، الشتاء جميل هناك.', en: 'I’m going to Hokkaido. / For Hokkaido, winter is nice.' },
    { jp: 'カメラ なら、 あの 店 が 安いです。', romaji: 'Kamera nara, ano mise ga yasui desu.', ar: 'إذا كان الأمر عن الكاميرا، ذلك المتجر رخيص.', en: 'If it’s about cameras, that store is cheap.' },
    { jp: 'ご飯 を 食べたら、 すぐ 寝ます。', romaji: 'Gohan o tabetara, sugu nemasu.', ar: 'بعد أن آكل، سأنام فورا.', en: 'After I eat, I’ll sleep right away.' },
    { jp: '日本語 が わからなかったら、 教えて ください。', romaji: 'Nihongo ga wakaranakattara, oshiete kudasai.', ar: 'إذا لم تفهم اليابانية، أخبرني من فضلك.', en: 'If you don’t understand Japanese, please tell me.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 暇 だったら、 来て ください。', answer: 'إذا كنت فارغا، تعال من فضلك.', hint: 'たら بعد الاسم/الصفة な' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 旅行 なら、 沖縄 が いいです。', answer: 'إذا كان الأمر عن السفر، فأوكيناوا جيدة.', hint: 'なら للاقتراح' },
    { type: 'complete', prompt: 'أكمل: 空港 に 着い___、 電話 します。', answer: 'たら', hint: 'たら بعد た形' },
    { type: 'complete', prompt: 'أكمل: 天気 が よ___、 ピクニック を します。', answer: 'かったら', hint: 'たら للصفة い' },
    { type: 'complete', prompt: 'أكمل: 韓国 ___ 、 キムチ が 有名 です。', answer: 'なら', hint: 'なら للموضوع' },
    { type: 'order', prompt: 'رتب: ください / 休んで / たら / 疲れ', answer: '疲れたら、 休んで ください。', hint: 'اقتراح بـ たら' },
    { type: 'order', prompt: 'رتب: が / 当たったら / 宝くじ / 旅行 / します', answer: '宝くじ が 当たったら、 旅行 します。', hint: 'たら شرطي' },
    { type: 'answer', prompt: '宝くじ が 当たったら、 何 を しますか。 (旅行します)', answer: '宝くじ が 当たったら、 旅行 します。', hint: 'الإجابة بـ たら' },
    { type: 'answer', prompt: 'いい レストラン が 知りたい です。 (おすすめ: イタリア料理の店)', answer: 'レストラン なら、 イタリア料理 の 店 が いいです。', hint: 'الإجابة بـ なら' },
  ],
  videos: [],
}
