export const lessonTwelve = {
  id: 12,
  title: { ar: 'الماضي والمقارنة', en: 'Past Adjectives and Comparison' },
  focus: 'الصفات في الماضي، が للتضاد، ほうがいい للنصيحة، وどちら للمقارنة',
  vocab: [
    { id: 'suzushii', type: 'i-adjective', jp: '涼しい', kanji: '涼しい', hiragana: 'すずしい', reading: 'suzushii', meaning: 'منعش / بارد قليلا' },
    { id: 'atatakai', type: 'i-adjective', jp: '暖かい', kanji: '暖かい', hiragana: 'あたたかい', reading: 'atatakai', meaning: 'دافئ' },
    { id: 'usui', type: 'i-adjective', jp: '薄い', kanji: '薄い', hiragana: 'うすい', reading: 'usui', meaning: 'رقيق / خفيف (سائل)' },
    { id: 'atsui2', type: 'i-adjective', jp: '厚い', kanji: '厚い', hiragana: 'あつい', reading: 'atsui', meaning: 'سميك' },
    { id: 'karui', type: 'i-adjective', jp: '軽い', kanji: '軽い', hiragana: 'かるい', reading: 'karui', meaning: 'خفيف الوزن' },
    { id: 'omoi', type: 'i-adjective', jp: '重い', kanji: '重い', hiragana: 'おもい', reading: 'omoi', meaning: 'ثقيل' },
    { id: 'akarui', type: 'i-adjective', jp: '明るい', kanji: '明るい', hiragana: 'あかるい', reading: 'akarui', meaning: 'مضيء / مرح' },
    { id: 'kurai', type: 'i-adjective', jp: '暗い', kanji: '暗い', hiragana: 'くらい', reading: 'kurai', meaning: 'مظلم' },
    { id: 'nagai', type: 'i-adjective', jp: '長い', kanji: '長い', hiragana: 'ながい', reading: 'nagai', meaning: 'طويل' },
    { id: 'mijikai', type: 'i-adjective', jp: '短い', kanji: '短い', hiragana: 'みじかい', reading: 'mijikai', meaning: 'قصير' },
    { id: 'mazui', type: 'i-adjective', jp: 'まずい', hiragana: 'まずい', reading: 'mazui', meaning: 'سيء الطعم' },
    { id: 'natsu', type: 'noun', jp: '夏', kanji: '夏', hiragana: 'なつ', reading: 'natsu', meaning: 'صيف' },
    { id: 'fuyu', type: 'noun', jp: '冬', kanji: '冬', hiragana: 'ふゆ', reading: 'fuyu', meaning: 'شتاء' },
    { id: 'kisetsu', type: 'noun', jp: '季節', kanji: '季節', hiragana: 'きせつ', reading: 'kisetsu', meaning: 'فصل (موسم)' },
    { id: 'tenki', type: 'noun', jp: '天気', kanji: '天気', hiragana: 'てんき', reading: 'tenki', meaning: 'طقس' },
    { id: 'houga_ii', type: 'expression', jp: 'ほうがいい', hiragana: 'ほうがいい', reading: 'hou ga ii', meaning: 'من الأفضل' },
    { id: 'dochira', type: 'question-word', jp: 'どちら', hiragana: 'どちら', reading: 'dochira', meaning: 'أيهما' },
    { id: 'hou', type: 'noun', jp: 'ほう', kanji: '方', hiragana: 'ほう', reading: 'hou', meaning: 'الجانب / الجهة' },
    { id: 'densha', type: 'noun', jp: '電車', kanji: '電車', hiragana: 'でんしゃ', reading: 'densha', meaning: 'قطار' },
    { id: 'basu', type: 'noun', jp: 'バス', hiragana: 'バス', reading: 'basu', meaning: 'حافلة' },
    { id: 'kekkou', type: 'na-adjective', jp: '結構', kanji: '結構', hiragana: 'けっこう', reading: 'kekkou', meaning: 'جيد بما فيه الكفاية / لا داعي' },
    { id: 'kantan', type: 'na-adjective', jp: '簡単', kanji: '簡単', hiragana: 'かんたん', reading: 'kantan', meaning: 'سهل / بسيط' },
    { id: 'taihen', type: 'na-adjective', jp: '大変', kanji: '大変', hiragana: 'たいへん', reading: 'taihen', meaning: 'صعب جدا / شاق' },
    { id: 'kuukou', type: 'place', jp: '空港', kanji: '空港', hiragana: 'くうこう', reading: 'kuukou', meaning: 'مطار' },
    { id: 'norimasu', type: 'verb', jp: '乗ります', kanji: '乗ります', hiragana: 'のります', reading: 'norimasu', meaning: 'يركب' },
  ],
  grammar: [
    {
      title: 'ماضي صفات い',
      pattern: 'صفة い (بدون い) + かった です ／ くなかった です',
      particle: 'かった',
      howItWorks: 'لتحويل صفة い إلى الماضي المثبت: نحذف い ونضيف かった です. للنفي في الماضي: نحذف い ونضيف くなかった です.',
      explanation: 'الاستثناء: いい في الماضي تصبح よかった (وليس いかった). مثال: 天気 が よかった です (كان الطقس جيدا).',
      example: { jp: '昨日 は 寒かった です。', romaji: 'Kinou wa samukatta desu.', ar: 'كان الجو باردا أمس.' },
      exercises: [
        {
          type: 'build',
          ar: 'الفيلم الذي شاهدته أمس كان ممتعا.',
          words: ['昨日', '見た', '映画', 'は', '面白かった', 'です', '。'],
          particles: [],
          answer: '昨日 見た 映画 は 面白かった です 。',
        },
        {
          type: 'fill',
          ar: 'الاختبار لم يكن صعبا. (ماضي منفي)',
          sentence: '試験 は 難し___ です。',
          options: ['くなかった', 'かった', 'じゃなかった', 'ではなかった'],
          answer: 'くなかった',
        },
        {
          type: 'meaning',
          sentence: '先週 は とても 忙しかった です。',
          particle: 'かった',
          options: ['كنت مشغولا جدا الأسبوع الماضي.', 'سأكون مشغولا الأسبوع القادم.', 'الأسبوع الماضي كان هادئا.', 'لا أتذكر الأسبوع الماضي.'],
          answer: 'كنت مشغولا جدا الأسبوع الماضي.',
        },
        {
          type: 'error',
          ar: 'الطقس كان جيدا أمس.',
          options: ['昨日 は 天気 が よかった です。', '昨日 は 天気 が いかった です。', '昨日 は 天気 が いいでした。'],
          answer: '昨日 は 天気 が よかった です。',
        },
      ],
    },
    {
      title: 'ماضي صفات な',
      pattern: 'صفة な + でした ／ じゃなかった です',
      particle: 'でした',
      howItWorks: 'صفات な في الماضي تتبع نفس قاعدة الأسماء: المثبت + でした، والمنفي + じゃなかった です (أو ではありませんでした بشكل أكثر رسمية).',
      explanation: 'لاحظ الفرق عن صفات い: لا حذف ولا إضافة لاحقة على الصفة نفسها، فقط تغيير です إلى でした.',
      example: { jp: '学生 の 時 、 部屋 は きれい じゃなかった です。', romaji: 'Gakusei no toki, heya wa kirei janakatta desu.', ar: 'عندما كنت طالبا، لم تكن غرفتي نظيفة.' },
      exercises: [
        {
          type: 'build',
          ar: 'الاجتماع كان مهما.',
          words: ['会議', 'は', '大切', 'でした', '。'],
          particles: [],
          answer: '会議 は 大切 でした 。',
        },
        {
          type: 'fill',
          ar: 'تلك المدينة لم تكن هادئة.',
          sentence: 'あの 町 は 静か___ です。',
          options: ['じゃなかった', 'くなかった', 'でした', 'かった'],
          answer: 'じゃなかった',
        },
        {
          type: 'meaning',
          sentence: '昔 、 この 辺 は にぎやか じゃなかった です。',
          particle: 'じゃなかった',
          options: ['في الماضي، لم تكن هذه المنطقة صاخبة.', 'هذه المنطقة صاخبة الآن أيضا.', 'هذه المنطقة كانت مشهورة.', 'لا أعرف هذه المنطقة.'],
          answer: 'في الماضي، لم تكن هذه المنطقة صاخبة.',
        },
        {
          type: 'error',
          ar: 'الامتحان كان سهلا.',
          options: ['試験 は 簡単 でした。', '試験 は 簡単かった です。', '試験 は 簡単 ました。'],
          answer: '試験 は 簡単 でした。',
        },
      ],
    },
    {
      title: 'が — التضاد (لكن)',
      pattern: 'جملة1 + が、 جملة2',
      particle: 'が',
      howItWorks: 'تستخدم が في نهاية الجملة الأولى لربطها بجملة ثانية متناقضة أو متباينة معها، بمعنى "لكن".',
      explanation: 'تختلف عن が علامة الفاعل؛ هنا تأتي بعد جملة كاملة (تنتهي بـ です/ます) وتعمل كأداة ربط مثل けど (الأكثر عامية).',
      example: { jp: 'この 服 は 高い です が、 質 が いい です。', romaji: 'Kono fuku wa takai desu ga, shitsu ga ii desu.', ar: 'هذا الثوب غالٍ، لكن جودته عالية.' },
      exercises: [
        {
          type: 'build',
          ar: 'أحب القهوة، لكنني لا أحب الشاي.',
          words: ['コーヒー', 'は', '好き', 'です', 'が', '、', 'お茶', 'は', '好き', 'じゃない', 'です', '。'],
          particles: ['が'],
          answer: 'コーヒー は 好き です が 、 お茶 は 好き じゃない です 。',
        },
        {
          type: 'fill',
          ar: 'هذا المطعم بعيد، لكن لذيذ.',
          sentence: 'この レストラン は 遠い です ___、 おいしい です。',
          options: ['が', 'から', 'ので', 'まで'],
          answer: 'が',
        },
        {
          type: 'meaning',
          sentence: '日本語 は 難しい です が、 面白い です。',
          particle: 'が',
          options: ['اللغة اليابانية صعبة، لكنها ممتعة.', 'اللغة اليابانية صعبة وممتعة معا دائما.', 'اللغة اليابانية ليست صعبة ولا ممتعة.', 'اللغة اليابانية ممتعة لذلك هي صعبة.'],
          answer: 'اللغة اليابانية صعبة، لكنها ممتعة.',
        },
        {
          type: 'error',
          ar: 'هذه الحقيبة خفيفة لكنها صغيرة.',
          options: ['この かばん は 軽い です が、 小さい です。', 'この かばん は 軽い が です、 小さい です。', 'この かばん は 軽い です けど から 小さい です。'],
          answer: 'この かばん は 軽い です が、 小さい です。',
        },
      ],
    },
    {
      title: 'ほうがいい と どちら — النصيحة والمقارنة',
      pattern: 'A と B と どちら が + صفة + ですか ／ Aの ほうが + صفة です',
      particle: 'ほう・どちら',
      howItWorks: 'どちら تستخدم للسؤال عن أفضلية بين شيئين (أيهما...؟). الجواب يكون بـ Aのほうが〜です (A أفضل/أكثر). أما ほうがいい بعد الفعل الماضي (في الدروس اللاحقة) أو الاسم تعني "من الأفضل أن...".',
      explanation: 'مثال للمقارنة: 電車 と バス と どちら が 速い です か。 ／ 電車 の ほう が 速い です。',
      example: { jp: '夏 と 冬 と どちら が 好き です か。 ／ 冬 の ほう が 好き です。', romaji: 'Natsu to fuyu to dochira ga suki desu ka. / Fuyu no hou ga suki desu.', ar: 'أيهما تفضل، الصيف أم الشتاء؟ / أفضل الشتاء.' },
      exercises: [
        {
          type: 'build',
          ar: 'أيهما أسرع، القطار أم الحافلة؟',
          words: ['電車', 'と', 'バス', 'と', 'どちら', 'が', '速い', 'です', 'か', '。'],
          particles: ['と', 'が'],
          answer: '電車 と バス と どちら が 速い です か 。',
        },
        {
          type: 'fill',
          ar: 'القطار أسرع. (الإجابة)',
          sentence: '電車 の ___ が 速い です。',
          options: ['ほう', 'どちら', 'もの', 'こと'],
          answer: 'ほう',
        },
        {
          type: 'meaning',
          sentence: '日本語 と 英語 と どちら が 簡単 です か。',
          particle: 'どちら',
          options: ['أيهما أسهل، اليابانية أم الإنجليزية؟', 'اليابانية والإنجليزية كلاهما سهل.', 'لا أتحدث اليابانية ولا الإنجليزية.', 'اليابانية أسهل من الإنجليزية بالتأكيد.'],
          answer: 'أيهما أسهل، اليابانية أم الإنجليزية؟',
        },
        {
          type: 'error',
          ar: 'أوساكا أكبر.',
          options: ['大阪 の ほう が 大きい です。', '大阪 は ほう が 大きい です。', '大阪 の どちら が 大きい です。'],
          answer: '大阪 の ほう が 大きい です。',
        },
      ],
    },
  ],
  examples: [
    { jp: '先月 は 寒かった です が、 今月 は 暖かい です。', romaji: 'Sengetsu wa samukatta desu ga, kongetsu wa atatakai desu.', ar: 'كان الشهر الماضي باردا، لكن هذا الشهر دافئ.', en: 'Last month was cold, but this month is warm.' },
    { jp: '昨日 の パーティー は 楽しかった です。', romaji: 'Kinou no paatii wa tanoshikatta desu.', ar: 'كانت حفلة الأمس ممتعة.', en: 'Yesterday’s party was fun.' },
    { jp: 'この 部屋 は 静か でした。', romaji: 'Kono heya wa shizuka deshita.', ar: 'كانت هذه الغرفة هادئة.', en: 'This room was quiet.' },
    { jp: 'テスト は 簡単 じゃなかった です。', romaji: 'Tesuto wa kantan janakatta desu.', ar: 'لم يكن الاختبار سهلا.', en: 'The test wasn’t easy.' },
    { jp: '日本料理 は おいしい です が、 ちょっと 高い です。', romaji: 'Nihon ryouri wa oishii desu ga, chotto takai desu.', ar: 'الطعام الياباني لذيذ، لكنه غالٍ بعض الشيء.', en: 'Japanese food is delicious, but a bit expensive.' },
    { jp: '北海道 と 沖縄 と どちら が 寒い です か。', romaji: 'Hokkaidou to Okinawa to dochira ga samui desu ka.', ar: 'أيهما أبرد، هوكايدو أم أوكيناوا؟', en: 'Which is colder, Hokkaido or Okinawa?' },
    { jp: '北海道 の ほう が 寒い です。', romaji: 'Hokkaidou no hou ga samui desu.', ar: 'هوكايدو أبرد.', en: 'Hokkaido is colder.' },
    { jp: 'この かばん は 重い です が、 丈夫 です。', romaji: 'Kono kaban wa omoi desu ga, joubu desu.', ar: 'هذه الحقيبة ثقيلة، لكنها متينة.', en: 'This bag is heavy, but it’s sturdy.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 旅行 は 楽しかった です。', answer: 'كانت الرحلة ممتعة.', hint: 'ماضي صفة い' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: あの 店 は 親切 じゃなかった です。', answer: 'لم يكن ذلك المتجر لطيفا.', hint: 'ماضي صفة な منفي' },
    { type: 'complete', prompt: 'أكمل: 去年 の 冬 は 寒___ です。', answer: 'かった', hint: 'ماضي صفة い' },
    { type: 'complete', prompt: 'أكمل: この 仕事 は 大変 です ___、 楽しい です。', answer: 'が', hint: 'التضاد' },
    { type: 'complete', prompt: 'أكمل: 肉 と 魚 と ___ が 好き です か。', answer: 'どちら', hint: 'السؤال عن المقارنة' },
    { type: 'order', prompt: 'رتب: でした / 先生 / は / 親切', answer: '先生 は 親切 でした。', hint: 'ماضي صفة な' },
    { type: 'order', prompt: 'رتب: が / 高い / の / 富士山 / です / ほう', answer: '富士山 の ほう が 高い です。', hint: 'إجابة المقارنة' },
    { type: 'answer', prompt: '昨日 の 天気 は どう でした か。 (いい)', answer: '天気 は よかった です。', hint: 'ماضي いい (شاذ)' },
    { type: 'answer', prompt: '電車 と バス と どちら が 便利 です か。 (電車)', answer: '電車 の ほう が 便利 です。', hint: 'إجابة المقارنة' },
  ],
  videos: [],
}
