export const lessonEighteen = {
  id: 18,
  title: { ar: 'صيغة النفي والواجب', en: 'Negative Form and Obligation' },
  focus: 'تكوين صيغة ない، ないでください للنهي، なければなりません للواجب، و なくてもいいです لعدم الضرورة',
  vocab: [
    { id: 'shinpai_shimasu', type: 'verb', jp: '心配します', kanji: '心配します', hiragana: 'しんぱいします', reading: 'shinpai shimasu', meaning: 'يقلق' },
    { id: 'wasuremasu', type: 'verb', jp: '忘れます', kanji: '忘れます', hiragana: 'わすれます', reading: 'wasuremasu', meaning: 'ينسى' },
    { id: 'okuremasu', type: 'verb', jp: '遅れます', kanji: '遅れます', hiragana: 'おくれます', reading: 'okuremasu', meaning: 'يتأخر' },
    { id: 'shukkin_shimasu', type: 'verb', jp: '出勤します', kanji: '出勤します', hiragana: 'しゅっきんします', reading: 'shukkin shimasu', meaning: 'يذهب للعمل' },
    { id: 'kusuri', type: 'noun', jp: '薬', kanji: '薬', hiragana: 'くすり', reading: 'kusuri', meaning: 'دواء' },
    { id: 'nomimasu2', type: 'verb', jp: '飲みます', kanji: '飲みます', hiragana: 'のみます', reading: 'nomimasu', meaning: 'يشرب / يتناول (دواء)' },
    { id: 'kibun', type: 'noun', jp: '気分', kanji: '気分', hiragana: 'きぶん', reading: 'kibun', meaning: 'شعور / مزاج' },
    { id: 'shukin_bi', type: 'noun', jp: '出勤日', kanji: '出勤日', hiragana: 'しゅっきんび', reading: 'shukkinbi', meaning: 'يوم عمل' },
    { id: 'kuukou4', type: 'place', jp: '空港', kanji: '空港', hiragana: 'くうこう', reading: 'kuukou', meaning: 'مطار' },
    { id: 'pasupooto', type: 'object', jp: 'パスポート', hiragana: 'パスポート', reading: 'pasupooto', meaning: 'جواز سفر' },
    { id: 'mochimasu2', type: 'verb', jp: '持ちます', kanji: '持ちます', hiragana: 'もちます', reading: 'mochimasu', meaning: 'يحمل' },
    { id: 'kitsuen', type: 'noun', jp: '喫煙', kanji: '喫煙', hiragana: 'きつえん', reading: 'kitsuen', meaning: 'تدخين' },
    { id: 'kakimasu2', type: 'verb', jp: '書きます', kanji: '書きます', hiragana: 'かきます', reading: 'kakimasu', meaning: 'يكتب' },
    { id: 'shomei', type: 'noun', jp: '署名', kanji: '署名', hiragana: 'しょめい', reading: 'shomei', meaning: 'توقيع' },
    { id: 'kibishii', type: 'i-adjective', jp: '厳しい', kanji: '厳しい', hiragana: 'きびしい', reading: 'kibishii', meaning: 'صارم' },
    { id: 'kisoku', type: 'noun', jp: '規則', kanji: '規則', hiragana: 'きそく', reading: 'kisoku', meaning: 'قاعدة / لائحة' },
    { id: 'shukudai3', type: 'noun', jp: '宿題', kanji: '宿題', hiragana: 'しゅくだい', reading: 'shukudai', meaning: 'واجب منزلي' },
    { id: 'shiken2', type: 'noun', jp: '試験', kanji: '試験', hiragana: 'しけん', reading: 'shiken', meaning: 'امتحان' },
    { id: 'fuku', type: 'noun', jp: '服', kanji: '服', hiragana: 'ふく', reading: 'fuku', meaning: 'ملابس' },
    { id: 'seifuku', type: 'noun', jp: '制服', kanji: '制服', hiragana: 'せいふく', reading: 'seifuku', meaning: 'زي رسمي' },
    { id: 'kimasu', type: 'verb', jp: '着ます', kanji: '着ます', hiragana: 'きます', reading: 'kimasu', meaning: 'يرتدي (ملابس)' },
    { id: 'genkin', type: 'noun', jp: '現金', kanji: '現金', hiragana: 'げんきん', reading: 'genkin', meaning: 'نقد' },
    { id: 'kaado', type: 'noun', jp: 'カード', hiragana: 'カード', reading: 'kaado', meaning: 'بطاقة (ائتمان)' },
    { id: 'tetsuzuki', type: 'noun', jp: '手続き', kanji: '手続き', hiragana: 'てつづき', reading: 'tetsuzuki', meaning: 'إجراء (رسمي)' },
  ],
  grammar: [
    {
      title: 'تكوين صيغة ない (ない形)',
      pattern: 'ます‐form → ない形',
      particle: 'ない形',
      howItWorks: 'للمجموعة 2 (る-verbs): نستبدل ます بـ ない (食べます→食べない). للمجموعة 1 (う-verbs): نحول الحرف قبل ます إلى عمود あ ونضيف ない (飲みます→飲まない، 書きます→書かない).',
      explanation: 'استثناءات: します→しない، 来ます→来ない (こない). والأفعال المنتهية بـ う وحدها (買います) تتحول إلى わ + ない: 買わない (وليس 買あない).',
      example: { jp: '飲みます → 飲まない', romaji: 'nomimasu → nomanai', ar: 'يشرب → (صيغة النفي)' },
      exercises: [
        {
          type: 'build',
          ar: 'حول 食べます إلى صيغة ない.',
          words: ['食べます', '→', '食べない'],
          particles: [],
          answer: '食べます → 食べない',
        },
        {
          type: 'fill',
          ar: '買います في صيغة ない هي؟',
          sentence: '買います → ___',
          options: ['買わない', '買いない', '買あない', '買ない'],
          answer: '買わない',
        },
        {
          type: 'meaning',
          sentence: '来ます → 来ない (こない)',
          particle: 'ない形',
          options: ['来ます فعل شاذ، صيغة ない هي 来ない (こない).', '来ます تتبع نفس قاعدة 飲みます.', '来ます لا تملك صيغة نفي.', '来ます تصبح 来あない.'],
          answer: '来ます فعل شاذ، صيغة ない هي 来ない (こない).',
        },
        {
          type: 'error',
          ar: 'حول 書きます إلى صيغة ない.',
          options: ['書かない', '書きない', '書くない', '書かありません'],
          answer: '書かない',
        },
      ],
    },
    {
      title: '〜ないでください — النهي المهذب',
      pattern: 'فعل (ない形) + で + ください。',
      particle: 'ないでください',
      howItWorks: 'تستخدم لإعطاء طلب بعدم فعل شيء بأدب، بمعنى "من فضلك لا تفعل...". تتكون من صيغة ない + で + ください.',
      explanation: 'تشبه في البنية てください لكن بدلا من て نستخدم ないで.',
      example: { jp: '心配しないで ください。', romaji: 'Shinpai shinaide kudasai.', ar: 'لا تقلق من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'لا تنس جواز سفرك من فضلك.',
          words: ['パスポート', 'を', '忘れないで', 'ください', '。'],
          particles: ['を'],
          answer: 'パスポート を 忘れないで ください 。',
        },
        {
          type: 'fill',
          ar: 'لا تتأخر من فضلك.',
          sentence: '___ で ください。',
          options: ['遅れない', '遅れます', '遅れて', '遅れた'],
          answer: '遅れない',
        },
        {
          type: 'meaning',
          sentence: 'ここ で 写真 を 撮らないで ください。',
          particle: 'ないでください',
          options: ['لا تلتقط صورا هنا من فضلك.', 'التقط صورا هنا من فضلك.', 'لا توجد صور هنا.', 'الصور ممنوعة في كل مكان.'],
          answer: 'لا تلتقط صورا هنا من فضلك.',
        },
        {
          type: 'error',
          ar: 'لا تأكل في الفصل من فضلك.',
          options: ['教室 で 食べないで ください。', '教室 で 食べないでは ください。', '教室 で 食べてないで ください。'],
          answer: '教室 で 食べないで ください。',
        },
      ],
    },
    {
      title: '〜なければなりません — الواجب',
      pattern: 'فعل (ない形 بدون い) + ければ + なりません。',
      particle: 'なければなりません',
      howItWorks: 'تستخدم للتعبير عن الواجب أو الإلزام "يجب أن...". نأخذ صيغة ない، نحذف い الأخيرة، ونضيف ければなりません.',
      explanation: 'مثال: 飲まない → 飲まなければなりません (يجب أن أشرب). شكل أكثر عامية: なきゃいけません.',
      example: { jp: '薬 を 飲まなければ なりません。', romaji: 'Kusuri o nomanakereba narimasen.', ar: 'يجب أن أتناول الدواء.' },
      exercises: [
        {
          type: 'build',
          ar: 'يجب أن أنهي الواجب اليوم.',
          words: ['今日', '宿題', 'を', '終わらなければ', 'なりません', '。'],
          particles: ['を'],
          answer: '今日 宿題 を 終わらなければ なりません 。',
        },
        {
          type: 'fill',
          ar: 'يجب أن أرتدي الزي الرسمي.',
          sentence: '制服 を 着___ なりません。',
          options: ['なければ', 'ないで', 'なくて', 'ました'],
          answer: 'なければ',
        },
        {
          type: 'meaning',
          sentence: '九時 までに 出勤しなければ なりません。',
          particle: 'なければなりません',
          options: ['يجب أن أصل إلى العمل بحلول التاسعة.', 'لا داعي للذهاب إلى العمل قبل التاسعة.', 'العمل ينتهي في التاسعة.', 'لا أعمل يوم التاسع.'],
          answer: 'يجب أن أصل إلى العمل بحلول التاسعة.',
        },
        {
          type: 'error',
          ar: 'يجب أن أوقع هنا.',
          options: ['ここ に 署名 しなければ なりません。', 'ここ に 署名 しなくては なります。', 'ここ に 署名 しなければ ありません。'],
          answer: 'ここ に 署名 しなければ なりません。',
        },
      ],
    },
    {
      title: '〜なくてもいいです — عدم الضرورة',
      pattern: 'فعل (ない形 بدون い) + くても + いいです。',
      particle: 'なくてもいいです',
      howItWorks: 'تستخدم للتعبير عن "لا داعي لفعل..." أو "ليس من الضروري أن...". نأخذ صيغة ない، نحذف い الأخيرة، ونضيف くてもいいです.',
      explanation: 'هي عكس てもいいです (الإذن بالفعل) من حيث المعنى، لكنها ليست منعا - فقط عدم إلزام.',
      example: { jp: '今日 は 来なくても いいです。', romaji: 'Kyou wa konakutemo ii desu.', ar: 'لا داعي لأن تأتي اليوم.' },
      exercises: [
        {
          type: 'build',
          ar: 'لا داعي لدفع نقدا (يمكن استخدام البطاقة).',
          words: ['現金', 'で', '払わなくても', 'いいです', '。'],
          particles: ['で'],
          answer: '現金 で 払わなくても いいです 。',
        },
        {
          type: 'fill',
          ar: 'لا داعي لإحضار الكتاب غدا.',
          sentence: '明日 、 本 を 持って ___ いいです。',
          options: ['こなくても', 'きても', 'こなければ', 'きなくては'],
          answer: 'こなくても',
        },
        {
          type: 'meaning',
          sentence: '今日 は 仕事 に 行かなくても いいです。',
          particle: 'なくてもいいです',
          options: ['لا داعي للذهاب إلى العمل اليوم.', 'يجب الذهاب إلى العمل اليوم.', 'العمل ممنوع اليوم.', 'لا يوجد عمل أصلا.'],
          answer: 'لا داعي للذهاب إلى العمل اليوم.',
        },
        {
          type: 'error',
          ar: 'لا داعي للقلق.',
          options: ['心配 しなくても いいです。', '心配 なくてもいいです。', '心配 しないでも いいです。'],
          answer: '心配 しなくても いいです。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'ここ に 車 を 止めないで ください。', romaji: 'Koko ni kuruma o tomenaide kudasai.', ar: 'لا توقف السيارة هنا من فضلك.', en: 'Please don’t park the car here.' },
    { jp: '毎日 薬 を 飲まなければ なりません。', romaji: 'Mainichi kusuri o nomanakereba narimasen.', ar: 'يجب أن أتناول الدواء كل يوم.', en: 'I have to take medicine every day.' },
    { jp: '明日 は 休み です から、 早く 起きなくても いいです。', romaji: 'Ashita wa yasumi desu kara, hayaku okinakutemo ii desu.', ar: 'غدا إجازة، فلا داعي للاستيقاظ مبكرا.', en: 'Tomorrow is a holiday, so I don’t have to wake up early.' },
    { jp: '空港 で パスポート を 見せなければ なりません。', romaji: 'Kuukou de pasupooto o misenakereba narimasen.', ar: 'يجب إظهار جواز السفر في المطار.', en: 'You have to show your passport at the airport.' },
    { jp: '宿題 を 忘れないで ください。', romaji: 'Shukudai o wasurenaide kudasai.', ar: 'لا تنس واجبك من فضلك.', en: 'Please don’t forget your homework.' },
    { jp: '今日 は 残業 しなくても いいです。', romaji: 'Kyou wa zangyou shinakutemo ii desu.', ar: 'لا داعي للعمل الإضافي اليوم.', en: 'You don’t have to work overtime today.' },
    { jp: '会議 に 遅れないで ください。', romaji: 'Kaigi ni okurenaide kudasai.', ar: 'لا تتأخر عن الاجتماع من فضلك.', en: 'Please don’t be late for the meeting.' },
    { jp: '日曜日 は 仕事 に 行かなくても いいです。', romaji: 'Nichiyoubi wa shigoto ni ikanakutemo ii desu.', ar: 'لا داعي للذهاب إلى العمل يوم الأحد.', en: 'You don’t have to go to work on Sunday.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: ここ で 泳がないで ください。', answer: 'لا تسبح هنا من فضلك.', hint: 'النهي بـ ないでください' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 制服 を 着なければ なりません。', answer: 'يجب ارتداء الزي الرسمي.', hint: 'الواجب' },
    { type: 'complete', prompt: 'أكمل: 飲みます → ___ (ない形)', answer: '飲まない', hint: 'تحويل صيغة う-verb' },
    { type: 'complete', prompt: 'أكمل: 明日 早く 起き___、 いいです。', answer: 'なくても', hint: 'عدم الضرورة' },
    { type: 'complete', prompt: 'أكمل: パスポート を 見せ___、 なりません。', answer: 'なければ', hint: 'الواجب' },
    { type: 'order', prompt: 'رتب: ここ / 吸わないで / で / たばこ / を / ください', answer: 'ここ で たばこ を 吸わないで ください。', hint: 'النهي' },
    { type: 'order', prompt: 'رتب: なければ / 毎日 / 行か / なりません / 学校 / に / へ', answer: '毎日 学校 へ 行かなければ なりません。', hint: 'الواجب اليومي' },
    { type: 'answer', prompt: '今日 仕事 に 行かなければ なりません か。 (いいえ)', answer: 'いいえ、行かなくても いいです。', hint: 'عدم الضرورة' },
    { type: 'answer', prompt: '何 を 忘れないで ください か。 (パスポート)', answer: 'パスポート を 忘れないで ください。', hint: 'الإجابة بالنهي' },
  ],
  videos: [],
}
