export const lessonTwo = {
  id: 2,
  title: { ar: 'الإشارة إلى الأشياء', en: 'Pointing at Things' },
  focus: 'استخدام これ・それ・あれ و この・その・あの و の للملكية، والتأكيد بـ そうです',
  vocab: [
    { id: 'kore', type: 'pronoun', jp: 'これ', hiragana: 'これ', reading: 'kore', meaning: 'هذا (شيء قريب من المتكلم)' },
    { id: 'sore', type: 'pronoun', jp: 'それ', hiragana: 'それ', reading: 'sore', meaning: 'ذلك (شيء قريب من المستمع)' },
    { id: 'are', type: 'pronoun', jp: 'あれ', hiragana: 'あれ', reading: 'are', meaning: 'ذلك هناك (بعيد عن الطرفين)' },
    { id: 'kono', type: 'determiner', jp: 'この', hiragana: 'この', reading: 'kono', meaning: 'هذا الـ (+ اسم)' },
    { id: 'sono', type: 'determiner', jp: 'その', hiragana: 'その', reading: 'sono', meaning: 'ذلك الـ (+ اسم)' },
    { id: 'ano', type: 'determiner', jp: 'あの', hiragana: 'あの', reading: 'ano', meaning: 'ذلك هناك الـ (+ اسم)' },
    { id: 'hon', type: 'object', jp: '本', kanji: '本', hiragana: 'ほん', reading: 'hon', meaning: 'كتاب' },
    { id: 'jisho', type: 'object', jp: '辞書', kanji: '辞書', hiragana: 'じしょ', reading: 'jisho', meaning: 'قاموس' },
    { id: 'zasshi', type: 'object', jp: '雑誌', kanji: '雑誌', hiragana: 'ざっし', reading: 'zasshi', meaning: 'مجلة' },
    { id: 'shinbun', type: 'object', jp: '新聞', kanji: '新聞', hiragana: 'しんぶん', reading: 'shinbun', meaning: 'جريدة' },
    { id: 'note', type: 'object', jp: 'ノート', hiragana: 'ノート', reading: 'nooto', meaning: 'دفتر' },
    { id: 'techo', type: 'object', jp: '手帳', kanji: '手帳', hiragana: 'てちょう', reading: 'techou', meaning: 'مفكرة جيب' },
    { id: 'meishi', type: 'object', jp: '名刺', kanji: '名刺', hiragana: 'めいし', reading: 'meishi', meaning: 'بطاقة تعريف' },
    { id: 'card', type: 'object', jp: 'カード', hiragana: 'カード', reading: 'kaado', meaning: 'بطاقة' },
    { id: 'enpitsu', type: 'object', jp: '鉛筆', kanji: '鉛筆', hiragana: 'えんぴつ', reading: 'enpitsu', meaning: 'قلم رصاص' },
    { id: 'ballpen', type: 'object', jp: 'ボールペン', hiragana: 'ボールペン', reading: 'boorupen', meaning: 'قلم حبر جاف' },
    { id: 'kagi', type: 'object', jp: '鍵', kanji: '鍵', hiragana: 'かぎ', reading: 'kagi', meaning: 'مفتاح' },
    { id: 'tokei', type: 'object', jp: '時計', kanji: '時計', hiragana: 'とけい', reading: 'tokei', meaning: 'ساعة' },
    { id: 'kasa', type: 'object', jp: '傘', kanji: '傘', hiragana: 'かさ', reading: 'kasa', meaning: 'مظلة' },
    { id: 'kaban', type: 'object', jp: '鞄', kanji: '鞄', hiragana: 'かばん', reading: 'kaban', meaning: 'حقيبة' },
    { id: 'tsukue', type: 'object', jp: '机', kanji: '机', hiragana: 'つくえ', reading: 'tsukue', meaning: 'مكتب / طاولة' },
    { id: 'isu', type: 'object', jp: '椅子', kanji: '椅子', hiragana: 'いす', reading: 'isu', meaning: 'كرسي' },
    { id: 'chocolate', type: 'food', jp: 'チョコレート', hiragana: 'チョコレート', reading: 'chokoreeto', meaning: 'شوكولاتة' },
    { id: 'omiyage', type: 'object', jp: 'お土産', kanji: 'お土産', hiragana: 'おみやげ', reading: 'omiyage', meaning: 'هدية تذكارية' },
    { id: 'nan', type: 'question-word', jp: '何', kanji: '何', hiragana: 'なん', reading: 'nan', meaning: 'ماذا / ما' },
    { id: 'sou-desu', type: 'response', jp: 'そうです', hiragana: 'そうです', reading: 'sou desu', meaning: 'نعم، هذا صحيح' },
    { id: 'chigaimasu', type: 'response', jp: '違います', kanji: '違います', hiragana: 'ちがいます', reading: 'chigaimasu', meaning: 'لا، هذا خطأ / مختلف' },
  ],
  grammar: [
    {
      title: 'これ・それ・あれ — أسماء الإشارة للأشياء',
      pattern: 'これ／それ／あれ + は + اسم + です',
      particle: 'は',
      howItWorks: 'これ تشير إلى شيء قريب من المتكلم، それ إلى شيء قريب من المستمع، あれ إلى شيء بعيد عن الاثنين. هذه الكلمات تأتي بمفردها (لا تتبعها كلمة) وتُستخدم كموضوع للجملة مع は.',
      explanation: 'تُستخدم これ/それ/あれ بدل اسم الشيء نفسه عندما نشير إليه، ثم نضيف は ثم اسم الشيء و です.',
      example: { jp: 'これ は 本 です。', romaji: 'Kore wa hon desu.', ar: 'هذا كتاب.' },
      exercises: [
        {
          type: 'build',
          ar: 'ذلك (البعيد) قاموس.',
          words: ['あれ', 'は', '辞書', 'です', '。'],
          particles: ['は'],
          answer: 'あれ は 辞書 です 。',
        },
        {
          type: 'fill',
          ar: 'ذلك (القريب منك) جريدة.',
          sentence: 'それ ___ 新聞 です。',
          options: ['は', 'が', 'も', 'の'],
          answer: 'は',
        },
        {
          type: 'meaning',
          sentence: 'これ は 鉛筆 です。',
          particle: 'は',
          options: ['هذا قلم رصاص.', 'ذلك مظلة.', 'هل هذا مفتاح؟', 'تلك ليست مجلة.'],
          answer: 'هذا قلم رصاص.',
        },
        {
          type: 'error',
          ar: 'هذا (الشيء البعيد) ساعة.',
          options: ['あの は 時計 です。', 'あれ は 時計 です。', 'あれ の 時計 です。'],
          answer: 'あれ は 時計 です。',
        },
      ],
    },
    {
      title: 'この・その・あの + اسم — صفات الإشارة',
      pattern: 'この／その／あの + اسم + は + اسم + です',
      particle: 'の',
      howItWorks: 'بعكس これ/それ/あれ، هذه الكلمات لا تُستخدم وحدها — يجب أن يأتي بعدها اسم مباشرة (مثل この本 = هذا الكتاب). تُستخدم لوصف شيء معين قريب من المتكلم أو المستمع أو بعيد عنهما.',
      explanation: 'この/その/あの + اسم تشكل وحدة واحدة تعمل كموضوع الجملة، ثم تأتي は للموضوع الثاني و です.',
      example: { jp: 'この 本 は 私 の 辞書 です。', romaji: 'Kono hon wa watashi no jisho desu.', ar: 'هذا الكتاب هو قاموسي.' },
      exercises: [
        {
          type: 'build',
          ar: 'تلك المجلة (القريبة منك) لي.',
          words: ['その', '雑誌', 'は', '私', 'の', 'です', '。'],
          particles: ['の'],
          answer: 'その 雑誌 は 私 の です 。',
        },
        {
          type: 'fill',
          ar: 'ذلك القلم (البعيد) قلم السيد ميلر.',
          sentence: 'あの ___ は ミラーさん の ボールペン です。',
          options: ['ボールペン', 'これ', 'それ', 'あれ'],
          answer: 'ボールペン',
        },
        {
          type: 'meaning',
          sentence: 'この かばん は 私 の です。',
          particle: 'の',
          options: ['هذه الحقيبة لي.', 'تلك الحقيبة لك.', 'تلك الحقيبة هناك ليست حقيبة.', 'هذه الحقيبة جديدة.'],
          answer: 'هذه الحقيبة لي.',
        },
        {
          type: 'error',
          ar: 'تلك المفكرة (البعيدة) مفكرة السيدة تانكا.',
          options: ['あれ 手帳 は タナカさん の です。', 'あの 手帳 は タナカさん の です。', 'あの は 手帳 タナカさん の です。'],
          answer: 'あの 手帳 は タナカさん の です。',
        },
      ],
    },
    {
      title: 'の — الملكية والانتماء',
      pattern: 'اسم 1 + の + اسم 2',
      particle: 'の',
      howItWorks: 'تربط の بين اسمين: الاسم الأول يملك أو ينتمي إليه الاسم الثاني (عكس ترتيب "كتاب أحمد" بالعربي — هنا نقول 「أحمد の كتاب」). كما يمكن حذف الاسم الثاني إذا كان مفهوماً من السياق.',
      explanation: 'تشبه の في الإنجليزية كلمة "of" أو "’s"، فمثلاً 私の本 = كتابي، و IMCの社員 = موظف شركة IMC.',
      example: { jp: 'これ は IMC の カード です。', romaji: 'Kore wa IMC no kaado desu.', ar: 'هذه بطاقة شركة IMC.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذا قاموس السيد ميلر.',
          words: ['これ', 'は', 'ミラーさん', 'の', '辞書', 'です', '。'],
          particles: ['の'],
          answer: 'これ は ミラーさん の 辞書 です 。',
        },
        {
          type: 'fill',
          ar: 'أنا موظف في شركة كهرباء.',
          sentence: 'わたし は でんき ___ しゃいん です。',
          options: ['の', 'は', 'を', 'に'],
          answer: 'の',
        },
        {
          type: 'meaning',
          sentence: 'それ は 先生 の 本 です。',
          particle: 'の',
          options: ['ذلك كتاب الأستاذ.', 'هذا أنا.', 'تلك ليست مجلة.', 'هل ذلك قاموسك؟'],
          answer: 'ذلك كتاب الأستاذ.',
        },
        {
          type: 'error',
          ar: 'هذه مظلتي.',
          options: ['これ は 私 傘 です。', 'これ は 私 の 傘 です。', 'これ の 私 は 傘 です。'],
          answer: 'これ は 私 の 傘 です。',
        },
      ],
    },
    {
      title: 'そうです・違います — التأكيد والنفي على معلومة',
      pattern: 'N ですか。 はい、そうです。 ／ いいえ、違います。',
      particle: 'か',
      howItWorks: 'عند السؤال عن هوية شيء بصيغة N ですか نجيب بـ はい、そうです (نعم صحيح) لو كانت المعلومة صحيحة، أو いいえ、違います (لا، خطأ) إذا كانت غير صحيحة، ثم نذكر التصحيح إن أردنا.',
      explanation: 'そうです تُستخدم لتأكيد كلام الطرف الآخر دون تكرار الجملة كاملة، بينما 違います تنفيها.',
      example: { jp: 'それ は 辞書 ですか。 ／ はい、そうです。', romaji: 'Sore wa jisho desu ka. / Hai, sou desu.', ar: 'هل ذلك قاموس؟ / نعم، هذا صحيح.' },
      exercises: [
        {
          type: 'build',
          ar: 'لا، هذا ليس كتابي.',
          words: ['いいえ', '、', 'これ', 'は', '私', 'の', 'じゃありません', '。'],
          particles: ['の'],
          answer: 'いいえ 、 これ は 私 の じゃありません 。',
        },
        {
          type: 'fill',
          ar: 'هل هذه مجلتك؟ نعم، صحيح.',
          sentence: 'これ は あなた の 雑誌 ですか。 はい、___。',
          options: ['そうです', '違います', 'です', 'なん'],
          answer: 'そうです',
        },
        {
          type: 'meaning',
          sentence: 'いいえ、違います。それ は 新聞 です。',
          particle: '違います',
          options: ['لا، هذا خطأ. تلك جريدة.', 'نعم، صحيح. هذه مجلة.', 'هل هذه جريدتك؟', 'تلك ليست جريدة.'],
          answer: 'لا، هذا خطأ. تلك جريدة.',
        },
        {
          type: 'error',
          ar: 'هل تلك (البعيدة) مفكرتك؟',
          options: ['あれ は あなた の 手帳 ですか。', 'あれ の あなた は 手帳 ですか。', 'あの は あなた の 手帳 ですか。'],
          answer: 'あれ は あなた の 手帳 ですか。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'これ は 本 です。', romaji: 'Kore wa hon desu.', ar: 'هذا كتاب.', en: 'This is a book.' },
    { jp: 'それ は 辞書 です か。', romaji: 'Sore wa jisho desu ka.', ar: 'هل ذلك قاموس؟', en: 'Is that a dictionary?' },
    { jp: 'はい、そうです。', romaji: 'Hai, sou desu.', ar: 'نعم، هذا صحيح.', en: 'Yes, that is right.' },
    { jp: 'あれ は 雑誌 です か。', romaji: 'Are wa zasshi desu ka.', ar: 'هل ذلك (هناك) مجلة؟', en: 'Is that (over there) a magazine?' },
    { jp: 'いいえ、違います。 新聞 です。', romaji: 'Iie, chigaimasu. Shinbun desu.', ar: 'لا، خطأ. هي جريدة.', en: 'No, that is wrong. It is a newspaper.' },
    { jp: 'この 本 は 私 の です。', romaji: 'Kono hon wa watashi no desu.', ar: 'هذا الكتاب لي.', en: 'This book is mine.' },
    { jp: 'それ は ミラーさん の ボールペン です。', romaji: 'Sore wa Miraa-san no boorupen desu.', ar: 'ذلك قلم السيد ميلر.', en: 'That is Mr. Miller’s pen.' },
    { jp: 'これ は IMC の カード です。', romaji: 'Kore wa IMC no kaado desu.', ar: 'هذه بطاقة شركة IMC.', en: 'This is an IMC card.' },
    { jp: 'あの 時計 は 私 の です。', romaji: 'Ano tokei wa watashi no desu.', ar: 'تلك الساعة (هناك) لي.', en: 'That clock over there is mine.' },
    { jp: 'これ は 何 です か。', romaji: 'Kore wa nan desu ka.', ar: 'ما هذا؟', en: 'What is this?' },
    { jp: 'それ は 手帳 です。', romaji: 'Sore wa techou desu.', ar: 'هذه مفكرة.', en: 'This is a notebook.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: これ は 辞書 です。', answer: 'هذا قاموس.', hint: 'ترجمة الجملة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: あれ は 私 の かばん です。', answer: 'تلك (البعيدة) حقيبتي.', hint: 'ترجمة الجملة' },
    { type: 'complete', prompt: 'أكمل: それ ___ 新聞 です。', answer: 'は', hint: 'أداة الموضوع' },
    { type: 'complete', prompt: 'أكمل: これ は ミラーさん ___ 辞書 です。', answer: 'の', hint: 'أداة الملكية' },
    { type: 'complete', prompt: 'أكمل الجواب: それ は 雑誌 ですか。 はい、___。', answer: 'そうです', hint: 'تأكيد' },
    { type: 'order', prompt: 'رتب: です / 本 / これ / は', answer: 'これ は 本 です。', hint: 'استخدام これ' },
    { type: 'order', prompt: 'رتب: の / です / かばん / その / 私', answer: 'その かばん は 私 の です。', hint: 'استخدام その و の' },
    { type: 'answer', prompt: 'あれ は 辞書 ですか。 جواب بالنفي وصحح: 雑誌.', answer: 'いいえ、違います。 雑誌 です。', hint: 'النفي والتصحيح' },
    { type: 'answer', prompt: 'これ は 何 ですか。 (傘)', answer: 'それ は 傘 です。', hint: 'السؤال عن الاسم' },
  ],
  videos: [],
}
