export const lessonSix = {
  id: 6,
  title: { ar: 'الأفعال والمفعول به', en: 'Verbs and Direct Objects' },
  focus: 'استخدام を مع أفعال الأكل والشرب والقراءة وغيرها، والسؤال بـ 何を، والدعوة بـ ませんか و ましょう',
  vocab: [
    { id: 'tabemasu', type: 'verb', jp: '食べます', kanji: '食べます', hiragana: 'たべます', reading: 'tabemasu', meaning: 'يأكل' },
    { id: 'nomimasu', type: 'verb', jp: '飲みます', kanji: '飲みます', hiragana: 'のみます', reading: 'nomimasu', meaning: 'يشرب' },
    { id: 'mimasu', type: 'verb', jp: '見ます', kanji: '見ます', hiragana: 'みます', reading: 'mimasu', meaning: 'يشاهد / ينظر' },
    { id: 'kikimasu', type: 'verb', jp: '聞きます', kanji: '聞きます', hiragana: 'ききます', reading: 'kikimasu', meaning: 'يستمع / يسأل' },
    { id: 'yomimasu', type: 'verb', jp: '読みます', kanji: '読みます', hiragana: 'よみます', reading: 'yomimasu', meaning: 'يقرأ' },
    { id: 'kakimasu', type: 'verb', jp: '書きます', kanji: '書きます', hiragana: 'かきます', reading: 'kakimasu', meaning: 'يكتب' },
    { id: 'kaimasu', type: 'verb', jp: '買います', kanji: '買います', hiragana: 'かいます', reading: 'kaimasu', meaning: 'يشتري' },
    { id: 'torimasu', type: 'verb', jp: '撮ります', kanji: '撮ります', hiragana: 'とります', reading: 'torimasu', meaning: 'يلتقط (صورة)' },
    { id: 'shimasu', type: 'verb', jp: 'します', hiragana: 'します', reading: 'shimasu', meaning: 'يفعل / يعمل' },
    { id: 'gohan', type: 'food', jp: 'ご飯', kanji: 'ご飯', hiragana: 'ごはん', reading: 'gohan', meaning: 'أرز / وجبة' },
    { id: 'pan', type: 'food', jp: 'パン', hiragana: 'パン', reading: 'pan', meaning: 'خبز' },
    { id: 'tamago', type: 'food', jp: '卵', kanji: '卵', hiragana: 'たまご', reading: 'tamago', meaning: 'بيض' },
    { id: 'niku', type: 'food', jp: '肉', kanji: '肉', hiragana: 'にく', reading: 'niku', meaning: 'لحم' },
    { id: 'sakana', type: 'food', jp: '魚', kanji: '魚', hiragana: 'さかな', reading: 'sakana', meaning: 'سمك' },
    { id: 'yasai', type: 'food', jp: '野菜', kanji: '野菜', hiragana: 'やさい', reading: 'yasai', meaning: 'خضار' },
    { id: 'kudamono', type: 'food', jp: '果物', kanji: '果物', hiragana: 'くだもの', reading: 'kudamono', meaning: 'فواكه' },
    { id: 'mizu', type: 'drink', jp: '水', kanji: '水', hiragana: 'みず', reading: 'mizu', meaning: 'ماء' },
    { id: 'ocha', type: 'drink', jp: 'お茶', kanji: 'お茶', hiragana: 'おちゃ', reading: 'ocha', meaning: 'شاي' },
    { id: 'biiru', type: 'drink', jp: 'ビール', hiragana: 'ビール', reading: 'biiru', meaning: 'بيرة' },
    { id: 'terebi', type: 'object', jp: 'テレビ', hiragana: 'テレビ', reading: 'terebi', meaning: 'تلفاز' },
    { id: 'ongaku', type: 'object', jp: '音楽', kanji: '音楽', hiragana: 'おんがく', reading: 'ongaku', meaning: 'موسيقى' },
    { id: 'eiga', type: 'object', jp: '映画', kanji: '映画', hiragana: 'えいが', reading: 'eiga', meaning: 'فيلم' },
    { id: 'shashin', type: 'object', jp: '写真', kanji: '写真', hiragana: 'しゃしん', reading: 'shashin', meaning: 'صورة' },
    { id: 'tegami', type: 'object', jp: '手紙', kanji: '手紙', hiragana: 'てがみ', reading: 'tegami', meaning: 'رسالة' },
    { id: 'nani', type: 'question-word', jp: '何', kanji: '何', hiragana: 'なに', reading: 'nani', meaning: 'ماذا' },
  ],
  grammar: [
    {
      title: 'を — المفعول به المباشر',
      pattern: 'مفعول به + を + فعل متعدٍ',
      particle: 'を',
      howItWorks: 'تأتي を بعد الاسم الذي يقع عليه فعل الفاعل مباشرة (المفعول به)، مثل 水 を 飲みます (أشرب ماء). تُلفظ "o".',
      explanation: 'الترتيب الأساسي: فاعل + は، مفعول به + を، ثم الفعل في النهاية. الفعل دائما يأتي آخر الجملة في اليابانية.',
      example: { jp: '私 は ご飯 を 食べます。', romaji: 'Watashi wa gohan o tabemasu.', ar: 'أنا آكل الأرز.' },
      exercises: [
        {
          type: 'build',
          ar: 'أشرب القهوة كل صباح.',
          words: ['毎朝', 'コーヒー', 'を', '飲みます', '。'],
          particles: ['を'],
          answer: '毎朝 コーヒー を 飲みます 。',
        },
        {
          type: 'fill',
          ar: 'أشاهد التلفاز الليلة.',
          sentence: '今晩 テレビ ___ 見ます。',
          options: ['を', 'は', 'に', 'で'],
          answer: 'を',
        },
        {
          type: 'meaning',
          sentence: '彼 は 新聞 を 読みます。',
          particle: 'を',
          options: ['هو يقرأ الجريدة.', 'هو يكتب جريدة.', 'هل تقرأ الجريدة؟', 'هذه جريدته.'],
          answer: 'هو يقرأ الجريدة.',
        },
        {
          type: 'error',
          ar: 'أكتب رسالة.',
          options: ['手紙 を 書きます。', '手紙 は 書きます。', '手紙 書きます を。'],
          answer: '手紙 を 書きます。',
        },
      ],
    },
    {
      title: '何を — السؤال عن المفعول به',
      pattern: '何を + فعل + か。',
      particle: '何を',
      howItWorks: '何 (ماذا) + を تُستخدم للسؤال عن الشيء الذي يقع عليه الفعل. تأتي عادة في بداية الجملة.',
      explanation: 'يمكن أيضا حذف を بشكل غير رسمي في الكلام اليومي (何 食べますか)، لكن في الكتابة الرسمية تبقى を.',
      example: { jp: '朝 何 を 食べます か。 ／ パン を 食べます。', romaji: 'Asa nani o tabemasu ka. / Pan o tabemasu.', ar: 'ماذا تأكل في الصباح؟ / آكل خبزا.' },
      exercises: [
        {
          type: 'build',
          ar: 'ماذا ستشتري في المجمع التجاري؟',
          words: ['デパート', 'で', '何', 'を', '買います', 'か', '。'],
          particles: ['を', 'で'],
          answer: 'デパート で 何 を 買います か 。',
        },
        {
          type: 'fill',
          ar: 'ماذا فعلت يوم الأحد؟',
          sentence: '日曜日 ___ 何 を しました か。',
          options: ['に', 'を', 'へ', 'と'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: '休み の 日 に 何 を しました か。',
          particle: '何を',
          options: ['ماذا فعلت في يوم الإجازة؟', 'متى الإجازة؟', 'لماذا أنت في إجازة؟', 'أين قضيت الإجازة؟'],
          answer: 'ماذا فعلت في يوم الإجازة؟',
        },
        {
          type: 'error',
          ar: 'ماذا تشاهد الآن؟',
          options: ['今 何 を 見ます か。', '何 今 を 見ます か。', '今 何 見ます を か。'],
          answer: '今 何 を 見ます か。',
        },
      ],
    },
    {
      title: '〜ませんか — الدعوة',
      pattern: 'فعل (ます‐negative) + か。',
      particle: 'ませんか',
      howItWorks: 'نستخدم صيغة النفي المضارع للفعل + か لتقديم دعوة مهذبة، بمعنى "ألا تريد أن...؟" أو "هل تود أن...؟".',
      explanation: 'هذه الصيغة أكثر تهذيبا وتترك للطرف الآخر حرية الرفض بسهولة، شائعة جدا في الدعوات الاجتماعية.',
      example: { jp: '一緒に 映画 を 見ません か。', romaji: 'Issho ni eiga o mimasen ka.', ar: 'ألا تريد أن نشاهد فيلما معا؟' },
      exercises: [
        {
          type: 'build',
          ar: 'ألا تشرب الشاي معي؟',
          words: ['一緒に', 'お茶', 'を', '飲みません', 'か', '。'],
          particles: ['ませんか'],
          answer: '一緒に お茶 を 飲みません か 。',
        },
        {
          type: 'fill',
          ar: 'ألا تأكل معنا الليلة؟',
          sentence: '今晩 一緒に 晩ご飯 を 食べ___ か。',
          options: ['ません', 'ます', 'ましょう', 'たい'],
          answer: 'ません',
        },
        {
          type: 'meaning',
          sentence: '一緒に 京都 へ 行きません か。',
          particle: 'ませんか',
          options: ['ألا تذهب معي إلى كيوتو؟', 'ذهبت إلى كيوتو وحدي.', 'متى ذهبت إلى كيوتو؟', 'لن أذهب إلى كيوتو.'],
          answer: 'ألا تذهب معي إلى كيوتو؟',
        },
        {
          type: 'error',
          ar: 'ألا نستمع إلى الموسيقى معا؟',
          options: ['一緒に 音楽 を 聞きません か。', '一緒に 音楽 を 聞きます か。', '音楽 一緒に を 聞きません か。'],
          answer: '一緒に 音楽 を 聞きません か。',
        },
      ],
    },
    {
      title: '〜ましょう — الاقتراح المشترك',
      pattern: 'فعل (ます‐stem) + ましょう。',
      particle: 'ましょう',
      howItWorks: '〜ましょう تعني "هيا بنا..." وتُستخدم عند الموافقة على دعوة أو اقتراح فعل شيء معا. ましょうか تعني "هل أفعل لك...؟" (عرض مساعدة).',
      explanation: 'غالبا ما تأتي ましょう كرد على ませんか: A: 〜ませんか。 B: ええ、〜ましょう。',
      example: { jp: 'ええ、行きましょう。', romaji: 'Ee, ikimashou.', ar: 'نعم، هيا بنا نذهب.' },
      exercises: [
        {
          type: 'build',
          ar: 'هيا بنا نأكل الغداء معا.',
          words: ['一緒に', '昼ご飯', 'を', '食べましょう', '。'],
          particles: ['ましょう'],
          answer: '一緒に 昼ご飯 を 食べましょう 。',
        },
        {
          type: 'fill',
          ar: 'هل أحضر لك الشاي؟',
          sentence: 'お茶 を 持って 来___ か。',
          options: ['ましょう', 'ません', 'ます', 'ました'],
          answer: 'ましょう',
        },
        {
          type: 'meaning',
          sentence: 'A: 公園 へ 行きません か。 B: ええ、行きましょう。',
          particle: 'ましょう',
          options: ['نعم، هيا بنا نذهب.', 'لا، لن أذهب.', 'متى نذهب؟', 'الحديقة بعيدة.'],
          answer: 'نعم، هيا بنا نذهب.',
        },
        {
          type: 'error',
          ar: 'هيا بنا نلتقط صورة.',
          options: ['写真 を 撮りましょう。', '写真 ましょう を 撮ります。', '写真 を 撮りますましょう。'],
          answer: '写真 を 撮りましょう。',
        },
      ],
    },
  ],
  examples: [
    { jp: '毎朝 パン を 食べます。', romaji: 'Maiasa pan o tabemasu.', ar: 'أتناول الخبز كل صباح.', en: 'I eat bread every morning.' },
    { jp: '昨日 友達 に 手紙 を 書きました。', romaji: 'Kinou tomodachi ni tegami o kakimashita.', ar: 'كتبت رسالة لصديقي أمس.', en: 'I wrote a letter to my friend yesterday.' },
    { jp: '何 を 飲みます か。', romaji: 'Nani o nomimasu ka.', ar: 'ماذا تشرب؟', en: 'What will you drink?' },
    { jp: 'コーヒー を 飲みます。', romaji: 'Koohii o nomimasu.', ar: 'سأشرب قهوة.', en: 'I will drink coffee.' },
    { jp: '一緒に 昼ご飯 を 食べません か。', romaji: 'Issho ni hirugohan o tabemasen ka.', ar: 'ألا تتناول الغداء معي؟', en: 'Won’t you have lunch with me?' },
    { jp: 'ええ、食べましょう。', romaji: 'Ee, tabemashou.', ar: 'نعم، هيا نأكل.', en: 'Yes, let’s eat.' },
    { jp: '日曜日 に 何 を しました か。', romaji: 'Nichiyoubi ni nani o shimashita ka.', ar: 'ماذا فعلت يوم الأحد؟', en: 'What did you do on Sunday?' },
    { jp: '映画 を 見ました。', romaji: 'Eiga o mimashita.', ar: 'شاهدت فيلما.', en: 'I watched a movie.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 私 は 魚 を 食べません。', answer: 'أنا لا آكل السمك.', hint: 'ترجمة الجملة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 一緒に 音楽 を 聞きません か。', answer: 'ألا نستمع للموسيقى معا؟', hint: 'ترجمة الجملة' },
    { type: 'complete', prompt: 'أكمل: 私 は 毎日 野菜 ___ 食べます。', answer: 'を', hint: 'المفعول به' },
    { type: 'complete', prompt: 'أكمل: 公園 で 写真 を 撮り___ か。 (دعوة)', answer: 'ません', hint: 'صيغة الدعوة' },
    { type: 'complete', prompt: 'أكمل: ええ、一緒に 行き___。 (موافقة)', answer: 'ましょう', hint: 'صيغة الموافقة على الاقتراح' },
    { type: 'order', prompt: 'رتب: 食べます / 朝ご飯 / 私 / は / を', answer: '私 は 朝ご飯 を 食べます。', hint: 'فاعل + مفعول به + فعل' },
    { type: 'order', prompt: 'رتب: か / 何 / を / 買います / デパート で', answer: 'デパート で 何 を 買います か。', hint: 'السؤال بـ 何を' },
    { type: 'answer', prompt: '何 を 飲みます か。 (お茶)', answer: 'お茶 を 飲みます。', hint: 'الإجابة عن المفعول به' },
    { type: 'answer', prompt: '一緒に 映画 を 見ません か。 (موافقة)', answer: 'ええ、見ましょう。', hint: 'الموافقة على الدعوة' },
  ],
  videos: [],
}
