export const lessonFive = {
  id: 5,
  title: { ar: 'الذهاب والإياب ووسائل النقل', en: 'Going, Coming and Transportation' },
  focus: 'استخدام 行きます・来ます・帰ります مع へ، ووسيلة النقل بـ で، والمرافقة بـ と، والسؤال بـ いつ',
  dialogue: {
    titleAr: 'إلى أين تذهب؟ — خطة رحلة ميلر',
    lines: [
      { speaker: 'ساتو', jp: 'ミラーさん、明日 どこへ 行きますか。', romaji: 'Miraa-san, ashita doko e ikimasu ka.', ar: 'سيد ميلر، إلى أين تذهب غدًا؟' },
      { speaker: 'ميلر', jp: '京都へ 行きます。', romaji: 'Kyouto e ikimasu.', ar: 'أذهب إلى كيوتو.' },
      { speaker: 'ساتو', jp: '何で 行きますか。', romaji: 'Nan de ikimasu ka.', ar: 'بماذا تذهب؟' },
      { speaker: 'ميلر', jp: '電車で 行きます。', romaji: 'Densha de ikimasu.', ar: 'أذهب بالقطار.' },
      { speaker: 'ساتو', jp: '一人で 行きますか。', romaji: 'Hitori de ikimasu ka.', ar: 'هل تذهب وحدك؟' },
      { speaker: 'ميلر', jp: 'いいえ、友達と 行きます。', romaji: 'Iie, tomodachi to ikimasu.', ar: 'لا، أذهب مع صديق.' },
      { speaker: 'ساتو', jp: 'いつ 帰りますか。', romaji: 'Itsu kaerimasu ka.', ar: 'ومتى تعود؟' },
      { speaker: 'ميلر', jp: '日曜日に 帰ります。', romaji: 'Nichiyoubi ni kaerimasu.', ar: 'أعود يوم الأحد.' },
    ],
  },
  reading: {
    titleAr: 'رحلتي — سفر مع العائلة',
    sentences: [
      { jp: '来週、家族と 東京へ 行きます。', romaji: 'Raishuu, kazoku to Toukyou e ikimasu.', ar: 'الأسبوع القادم أذهب مع عائلتي إلى طوكيو.' },
      { jp: '飛行機で 行きます。', romaji: 'Hikouki de ikimasu.', ar: 'نذهب بالطائرة.' },
      { jp: '友達は 電車で 来ます。', romaji: 'Tomodachi wa densha de kimasu.', ar: 'صديقي يأتي بالقطار.' },
      { jp: '私たちは バスで 駅へ 行きます。', romaji: 'Watashitachi wa basu de eki e ikimasu.', ar: 'نذهب إلى المحطة بالحافلة.' },
      { jp: '来月、家へ 帰ります。', romaji: 'Raigetsu, uchi e kaerimasu.', ar: 'نعود إلى البيت الشهر القادم.' },
    ],
    questions: [
      { q: 'إلى أين يذهب الكاتب الأسبوع القادم؟', options: ['إلى طوكيو', 'إلى كيوتو', 'إلى المدرسة'], answer: 'إلى طوكيو' },
      { q: 'بماذا يذهب؟', options: ['بالطائرة', 'بالقطار', 'بالسيارة'], answer: 'بالطائرة' },
      { q: 'متى يعودون إلى البيت؟', options: ['الشهر القادم', 'غدًا', 'يوم الأحد'], answer: 'الشهر القادم' },
    ],
  },
  vocab: [
    { id: 'ikimasu', type: 'verb', jp: '行きます', kanji: '行きます', hiragana: 'いきます', reading: 'ikimasu', meaning: 'يذهب' },
    { id: 'kimasu', type: 'verb', jp: '来ます', kanji: '来ます', hiragana: 'きます', reading: 'kimasu', meaning: 'يأتي' },
    { id: 'kaerimasu', type: 'verb', jp: '帰ります', kanji: '帰ります', hiragana: 'かえります', reading: 'kaerimasu', meaning: 'يعود / يرجع' },
    { id: 'gakkou', type: 'place', jp: '学校', kanji: '学校', hiragana: 'がっこう', reading: 'gakkou', meaning: 'مدرسة' },
    { id: 'uchi', type: 'place', jp: '家', kanji: '家', hiragana: 'うち', reading: 'uchi', meaning: 'البيت' },
    { id: 'eki', type: 'place', jp: '駅', kanji: '駅', hiragana: 'えき', reading: 'eki', meaning: 'محطة' },
    { id: 'hikouki', type: 'transport', jp: '飛行機', kanji: '飛行機', hiragana: 'ひこうき', reading: 'hikouki', meaning: 'طائرة' },
    { id: 'densha', type: 'transport', jp: '電車', kanji: '電車', hiragana: 'でんしゃ', reading: 'densha', meaning: 'قطار كهربائي' },
    { id: 'chikatetsu', type: 'transport', jp: '地下鉄', kanji: '地下鉄', hiragana: 'ちかてつ', reading: 'chikatetsu', meaning: 'مترو الأنفاق' },
    { id: 'basu', type: 'transport', jp: 'バス', hiragana: 'バス', reading: 'basu', meaning: 'حافلة' },
    { id: 'takushi', type: 'transport', jp: 'タクシー', hiragana: 'タクシー', reading: 'takushii', meaning: 'تاكسي' },
    { id: 'jitensha', type: 'transport', jp: '自転車', kanji: '自転車', hiragana: 'じてんしゃ', reading: 'jitensha', meaning: 'دراجة هوائية' },
    { id: 'kuruma', type: 'transport', jp: '車', kanji: '車', hiragana: 'くるま', reading: 'kuruma', meaning: 'سيارة' },
    { id: 'aruite', type: 'transport', jp: '歩いて', kanji: '歩いて', hiragana: 'あるいて', reading: 'aruite', meaning: 'سيرا على الأقدام' },
    { id: 'hitori', type: 'expression', jp: '一人で', kanji: '一人で', hiragana: 'ひとりで', reading: 'hitori de', meaning: 'بمفردي' },
    { id: 'tomodachi', type: 'person', jp: '友達', kanji: '友達', hiragana: 'ともだち', reading: 'tomodachi', meaning: 'صديق' },
    { id: 'kazoku', type: 'person', jp: '家族', kanji: '家族', hiragana: 'かぞく', reading: 'kazoku', meaning: 'عائلة' },
    { id: 'kare', type: 'pronoun', jp: '彼', kanji: '彼', hiragana: 'かれ', reading: 'kare', meaning: 'هو' },
    { id: 'kanojo', type: 'pronoun', jp: '彼女', kanji: '彼女', hiragana: 'かのじょ', reading: 'kanojo', meaning: 'هي' },
    { id: 'senshuu', type: 'time', jp: '先週', kanji: '先週', hiragana: 'せんしゅう', reading: 'senshuu', meaning: 'الأسبوع الماضي' },
    { id: 'raishuu', type: 'time', jp: '来週', kanji: '来週', hiragana: 'らいしゅう', reading: 'raishuu', meaning: 'الأسبوع القادم' },
    { id: 'kongetsu', type: 'time', jp: '今月', kanji: '今月', hiragana: 'こんげつ', reading: 'kongetsu', meaning: 'هذا الشهر' },
    { id: 'raigetsu', type: 'time', jp: '来月', kanji: '来月', hiragana: 'らいげつ', reading: 'raigetsu', meaning: 'الشهر القادم' },
    { id: 'itsu', type: 'question-word', jp: 'いつ', hiragana: 'いつ', reading: 'itsu', meaning: 'متى' },
    { id: 'isshoni', type: 'expression', jp: '一緒に', kanji: '一緒に', hiragana: 'いっしょに', reading: 'issho ni', meaning: 'معا' },
  ],
  grammar: [
    {
      title: 'へ — اتجاه الحركة',
      pattern: 'مكان + へ + 行きます／来ます／帰ります',
      particle: 'へ',
      howItWorks: 'تشير へ (تُلفظ "e") إلى اتجاه الحركة — إلى أين نذهب أو نأتي أو نعود. تأتي بعد اسم المكان مباشرة وقبل الفعل.',
      explanation: 'يمكن استبدال へ بـ に بنفس المعنى تقريبا في هذا السياق، لكن へ أكثر شيوعا للتأكيد على "الاتجاه".',
      example: { jp: '私 は 日本 へ 行きます。', romaji: 'Watashi wa Nihon e ikimasu.', ar: 'أنا أذهب إلى اليابان.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعود إلى البيت الساعة 6.',
          words: ['6時', 'に', '家', 'へ', '帰ります', '。'],
          particles: ['へ', 'に'],
          answer: '6時 に 家 へ 帰ります 。',
        },
        {
          type: 'fill',
          ar: 'السيد ميلر يأتي إلى اليابان غدا.',
          sentence: 'ミラーさん は 明日 日本 ___ 来ます。',
          options: ['へ', 'を', 'で', 'と'],
          answer: 'へ',
        },
        {
          type: 'meaning',
          sentence: '来週 大阪 へ 行きます。',
          particle: 'へ',
          options: ['سأذهب إلى أوساكا الأسبوع القادم.', 'جئت من أوساكا الأسبوع الماضي.', 'أوساكا بعيدة.', 'متى تذهب إلى أوساكا؟'],
          answer: 'سأذهب إلى أوساكا الأسبوع القادم.',
        },
        {
          type: 'error',
          ar: 'غدا أذهب إلى الشركة.',
          options: ['明日 会社 へ 行きます。', '明日 会社 を 行きます。', '会社 明日 へ 行きます。'],
          answer: '明日 会社 へ 行きます。',
        },
      ],
    },
    {
      title: 'で — وسيلة النقل',
      pattern: 'وسيلة نقل + で + 行きます／来ます／帰ります',
      particle: 'で',
      howItWorks: 'تشير で بعد وسيلة النقل (قطار، باص، سيارة...) إلى "بواسطة" تلك الوسيلة. الاستثناء: المشي يُعبَّر عنه بـ 歩いて (بدون で).',
      explanation: 'الترتيب المعتاد: مكان + へ، ثم وسيلة النقل + で، ثم الفعل. مثال: 大阪 へ 新幹線 で 行きます。',
      example: { jp: '電車 で 会社 へ 行きます。', romaji: 'Densha de kaisha e ikimasu.', ar: 'أذهب إلى الشركة بالقطار.' },
      exercises: [
        {
          type: 'build',
          ar: 'أذهب إلى المدرسة بالحافلة.',
          words: ['バス', 'で', '学校', 'へ', '行きます', '。'],
          particles: ['で', 'へ'],
          answer: 'バス で 学校 へ 行きます 。',
        },
        {
          type: 'fill',
          ar: 'أذهب إلى المحطة سيرا على الأقدام.',
          sentence: '駅 まで ___ 行きます。',
          options: ['歩いて', '歩いてで', '歩き', 'あるいて で'],
          answer: '歩いて',
        },
        {
          type: 'meaning',
          sentence: '飛行機 で 日本 へ 来ました。',
          particle: 'で',
          options: ['جئت إلى اليابان بالطائرة.', 'سأذهب إلى اليابان بالطائرة.', 'الطائرة ذهبت إلى اليابان.', 'هل أتيت بالطائرة؟'],
          answer: 'جئت إلى اليابان بالطائرة.',
        },
        {
          type: 'error',
          ar: 'أعود إلى البيت بالتاكسي.',
          options: ['タクシー で 家 へ 帰ります。', 'タクシー へ 家 で 帰ります。', '家 で タクシー へ 帰ります。'],
          answer: 'タクシー で 家 へ 帰ります。',
        },
      ],
    },
    {
      title: 'と — المرافقة (مع شخص)',
      pattern: 'شخص + と + 行きます／来ます／帰ります',
      particle: 'と',
      howItWorks: 'تشير と بعد اسم شخص إلى "مع" ذلك الشخص. إذا كان الشخص بمفرده نستخدم 一人で بدلا من と.',
      explanation: 'الترتيب: شخص + と، ثم مكان + へ (أو العكس)، ثم الفعل. مثال: 友達 と 京都 へ 行きます。',
      example: { jp: '家族 と 旅行 します。', romaji: 'Kazoku to ryokou shimasu.', ar: 'أسافر مع عائلتي.' },
      exercises: [
        {
          type: 'build',
          ar: 'أذهب إلى السينما مع صديقي.',
          words: ['友達', 'と', '映画館', 'へ', '行きます', '。'],
          particles: ['と', 'へ'],
          answer: '友達 と 映画館 へ 行きます 。',
        },
        {
          type: 'fill',
          ar: 'أذهب بمفردي. (بدون مرافقة)',
          sentence: '私 は 一人 ___ 行きます。',
          options: ['で', 'と', 'へ', 'の'],
          answer: 'で',
        },
        {
          type: 'meaning',
          sentence: '彼女 と 一緒に 来ました。',
          particle: 'と',
          options: ['جئت معها.', 'هي جاءت بمفردها.', 'هل أتت؟', 'سآتي معها لاحقا.'],
          answer: 'جئت معها.',
        },
        {
          type: 'error',
          ar: 'أعود إلى البيت مع عائلتي.',
          options: ['家族 と 家 へ 帰ります。', '家族 へ 家 と 帰ります。', '家族 帰ります と 家 へ。'],
          answer: '家族 と 家 へ 帰ります。',
        },
      ],
    },
    {
      title: 'いつ — السؤال عن الزمن',
      pattern: 'いつ + 行きます／来ます か。',
      particle: 'いつ',
      howItWorks: 'いつ كلمة سؤال تعني "متى"، تأتي عادة في بداية الجملة وتُجاب بكلمة زمنية (今週،来週،月曜日...) بدون أداة.',
      explanation: 'لاحظ أن الكلمات الزمنية النسبية (来週،明日،今月...) لا تأخذ に بعدها، تماما كما رأينا في الدرس السابق مع 毎日.',
      example: { jp: '来週 京都 へ 行きます。 ／ いつ 行きます か。', romaji: 'Raishuu Kyouto e ikimasu. / Itsu ikimasu ka.', ar: 'سأذهب إلى كيوتو الأسبوع القادم. / متى ستذهب؟' },
      exercises: [
        {
          type: 'build',
          ar: 'متى ستعود إلى بلدك؟',
          words: ['いつ', '国', 'へ', '帰ります', 'か', '。'],
          particles: ['いつ', 'へ'],
          answer: 'いつ 国 へ 帰ります か 。',
        },
        {
          type: 'fill',
          ar: 'متى أتيت إلى اليابان؟ الشهر الماضي.',
          sentence: 'いつ 日本 へ 来ました か。 ___。',
          options: ['先月 です', '先月 に です', '先月 へ です', '先月 を です'],
          answer: '先月 です',
        },
        {
          type: 'meaning',
          sentence: 'いつ 大阪 へ 行きます か。',
          particle: 'いつ',
          options: ['متى ستذهب إلى أوساكا؟', 'كيف ستذهب إلى أوساكا؟', 'مع من ستذهب إلى أوساكا؟', 'لماذا تذهب إلى أوساكا؟'],
          answer: 'متى ستذهب إلى أوساكا؟',
        },
        {
          type: 'error',
          ar: 'متى تأتي عائلتك إلى اليابان؟',
          options: ['いつ 家族 は 日本 へ 来ます か。', '家族 は いつ に 日本 へ 来ます か。', '日本 いつ は 家族 へ 来ます か。'],
          answer: 'いつ 家族 は 日本 へ 来ます か。',
        },
      ],
    },
  ],
  examples: [
    { jp: '私 は 京都 へ 行きます。', romaji: 'Watashi wa Kyouto e ikimasu.', ar: 'أنا أذهب إلى كيوتو.', en: 'I am going to Kyoto.' },
    { jp: '田中さん は 来月 国 へ 帰ります。', romaji: 'Tanaka-san wa raigetsu kuni e kaerimasu.', ar: 'السيد تاناكا سيعود إلى بلده الشهر القادم.', en: 'Mr. Tanaka will return to his country next month.' },
    { jp: '新幹線 で 東京 へ 行きます。', romaji: 'Shinkansen de Toukyou e ikimasu.', ar: 'أذهب إلى طوكيو بقطار الشينكانسن.', en: 'I go to Tokyo by Shinkansen.' },
    { jp: '駅 まで 歩いて 行きます。', romaji: 'Eki made aruite ikimasu.', ar: 'أذهب إلى المحطة سيرا على الأقدام.', en: 'I walk to the station.' },
    { jp: '家族 と 旅行 します。', romaji: 'Kazoku to ryokou shimasu.', ar: 'أسافر مع عائلتي.', en: 'I travel with my family.' },
    { jp: '一人 で 来ました。', romaji: 'Hitori de kimashita.', ar: 'جئت بمفردي.', en: 'I came alone.' },
    { jp: 'いつ 日本 へ 来ました か。', romaji: 'Itsu Nihon e kimashita ka.', ar: 'متى أتيت إلى اليابان؟', en: 'When did you come to Japan?' },
    { jp: '先週 来ました。', romaji: 'Senshuu kimashita.', ar: 'أتيت الأسبوع الماضي.', en: 'I came last week.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 私 は 電車 で 会社 へ 行きます。', answer: 'أذهب إلى الشركة بالقطار.', hint: 'ترجمة الجملة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 友達 と 京都 へ 行きます。', answer: 'أذهب إلى كيوتو مع صديقي.', hint: 'ترجمة الجملة' },
    { type: 'complete', prompt: 'أكمل: 私 は 日本 ___ 来ました。', answer: 'へ', hint: 'اتجاه الحركة' },
    { type: 'complete', prompt: 'أكمل: バス ___ 学校 へ 行きます。', answer: 'で', hint: 'وسيلة النقل' },
    { type: 'complete', prompt: 'أكمل: 家族 ___ 旅行 します。', answer: 'と', hint: 'المرافقة' },
    { type: 'order', prompt: 'رتب: 行きます / で / 大阪 / へ / 新幹線', answer: '新幹線 で 大阪 へ 行きます。', hint: 'وسيلة + اتجاه' },
    { type: 'order', prompt: 'رتب: か / 帰ります / いつ / 国 / へ', answer: 'いつ 国 へ 帰ります か。', hint: 'السؤال بـ いつ' },
    { type: 'answer', prompt: 'いつ 日本 へ 来ました か。 (先週)', answer: '先週 来ました。', hint: 'الإجابة عن الزمن' },
    { type: 'answer', prompt: '何 で 学校 へ 行きます か。 (自転車)', answer: '自転車 で 行きます。', hint: 'الإجابة عن وسيلة النقل' },
  ],
  videos: [],
}
