export const lessonSeven = {
  id: 7,
  title: { ar: 'الوسيلة والهدايا والفهم', en: 'Means, Giving/Receiving, and Understanding' },
  focus: 'استخدام で للوسيلة/الأداة، を ください للطلب، あげます/もらいます للهدايا، が わかります/あります للفهم والامتلاك',
  vocab: [
    { id: 'agemasu', type: 'verb', jp: 'あげます', kanji: 'あげます', hiragana: 'あげます', reading: 'agemasu', meaning: 'يعطي (لشخص آخر)' },
    { id: 'moraimasu', type: 'verb', jp: 'もらいます', kanji: 'もらいます', hiragana: 'もらいます', reading: 'moraimasu', meaning: 'يستلم / يحصل على' },
    { id: 'kashimasu', type: 'verb', jp: '貸します', kanji: '貸します', hiragana: 'かします', reading: 'kashimasu', meaning: 'يُعير' },
    { id: 'karimasu', type: 'verb', jp: '借ります', kanji: '借ります', hiragana: 'かります', reading: 'karimasu', meaning: 'يستعير' },
    { id: 'oshiemasu', type: 'verb', jp: '教えます', kanji: '教えます', hiragana: 'おしえます', reading: 'oshiemasu', meaning: 'يعلّم / يخبر' },
    { id: 'naraimasu', type: 'verb', jp: '習います', kanji: '習います', hiragana: 'ならいます', reading: 'naraimasu', meaning: 'يتعلم (من معلم)' },
    { id: 'wakarimasu', type: 'verb', jp: 'わかります', kanji: 'わかります', hiragana: 'わかります', reading: 'wakarimasu', meaning: 'يفهم' },
    { id: 'arimasu', type: 'verb', jp: 'あります', kanji: 'あります', hiragana: 'あります', reading: 'arimasu', meaning: 'يوجد (لغير الحي) / يملك' },
    { id: 'kudasai', type: 'expression', jp: 'ください', kanji: 'ください', hiragana: 'ください', reading: 'kudasai', meaning: 'من فضلك أعطني' },
    { id: 'hasami', type: 'object', jp: 'はさみ', hiragana: 'はさみ', reading: 'hasami', meaning: 'مقص' },
    { id: 'boorupen', type: 'object', jp: 'ボールペン', hiragana: 'ボールペン', reading: 'boorupen', meaning: 'قلم حبر جاف' },
    { id: 'naifu', type: 'object', jp: 'ナイフ', hiragana: 'ナイフ', reading: 'naifu', meaning: 'سكين' },
    { id: 'shouyu', type: 'food', jp: 'しょうゆ', hiragana: 'しょうゆ', reading: 'shouyu', meaning: 'صلصة الصويا' },
    { id: 'video', type: 'object', jp: 'ビデオ', hiragana: 'ビデオ', reading: 'bideo', meaning: 'فيديو' },
    { id: 'computer', type: 'object', jp: 'コンピューター', hiragana: 'コンピューター', reading: 'konpyuutaa', meaning: 'حاسوب' },
    { id: 'jitensha', type: 'object', jp: '自転車', kanji: '自転車', hiragana: 'じてんしゃ', reading: 'jitensha', meaning: 'دراجة هوائية' },
    { id: 'inu', type: 'animal', jp: '犬', kanji: '犬', hiragana: 'いぬ', reading: 'inu', meaning: 'كلب' },
    { id: 'hana', type: 'object', jp: '花', kanji: '花', hiragana: 'はな', reading: 'hana', meaning: 'زهرة' },
    { id: 'eigo', type: 'language', jp: '英語', kanji: '英語', hiragana: 'えいご', reading: 'eigo', meaning: 'اللغة الإنجليزية' },
    { id: 'furansugo', type: 'language', jp: 'フランス語', kanji: 'フランス語', hiragana: 'フランスご', reading: 'furansugo', meaning: 'اللغة الفرنسية' },
    { id: 'kazoku', type: 'person', jp: '家族', kanji: '家族', hiragana: 'かぞく', reading: 'kazoku', meaning: 'العائلة' },
    { id: 'otousan', type: 'person', jp: 'お父さん', kanji: 'お父さん', hiragana: 'おとうさん', reading: 'otousan', meaning: 'الأب (لشخص آخر)' },
    { id: 'okaasan', type: 'person', jp: 'お母さん', kanji: 'お母さん', hiragana: 'おかあさん', reading: 'okaasan', meaning: 'الأم (لشخص آخر)' },
    { id: 'tanjoubi', type: 'noun', jp: '誕生日', kanji: '誕生日', hiragana: 'たんじょうび', reading: 'tanjoubi', meaning: 'عيد ميلاد' },
    { id: 'jisho', type: 'object', jp: '辞書', kanji: '辞書', hiragana: 'じしょ', reading: 'jisho', meaning: 'قاموس' },
  ],
  grammar: [
    {
      title: 'で — الوسيلة أو الأداة',
      pattern: 'اسم (أداة/وسيلة) + で + فعل',
      particle: 'で',
      howItWorks: 'تستخدم で بعد اسم الأداة أو الوسيلة التي يتم بها الفعل، بمعنى "بواسطة" أو "بـ".',
      explanation: 'مثل ペンで書きます (أكتب بالقلم)، はさみで切ります (أقص بالمقص). تختلف عن で الخاصة بالمكان (في الفصل السابع نركز على معنى الأداة).',
      example: { jp: 'はし で 食べます。', romaji: 'Hashi de tabemasu.', ar: 'آكل بعيدان الطعام (تشوبستيكس).' },
      exercises: [
        {
          type: 'build',
          ar: 'أكتب بالقلم الرصاص.',
          words: ['鉛筆', 'で', '書きます', '。'],
          particles: ['で'],
          answer: '鉛筆 で 書きます 。',
        },
        {
          type: 'fill',
          ar: 'أقص الورقة بالمقص.',
          sentence: '紙 を はさみ ___ 切ります。',
          options: ['で', 'を', 'に', 'と'],
          answer: 'で',
        },
        {
          type: 'meaning',
          sentence: '日本語 で 手紙 を 書きます。',
          particle: 'で',
          options: ['أكتب الرسالة باللغة اليابانية.', 'أكتب رسالة عن اليابان.', 'أتعلم اليابانية من الرسالة.', 'أرسل رسالة إلى اليابان.'],
          answer: 'أكتب الرسالة باللغة اليابانية.',
        },
        {
          type: 'error',
          ar: 'آكل الأرز بالملعقة.',
          options: ['スプーン で ご飯 を 食べます。', 'スプーン を ご飯 で 食べます。', 'ご飯 で スプーン を 食べます。'],
          answer: 'スプーン で ご飯 を 食べます。',
        },
      ],
    },
    {
      title: '〜を ください — من فضلك أعطني',
      pattern: 'اسم + を + ください。',
      particle: 'を ください',
      howItWorks: 'تستخدم を ください لطلب شيء بأدب، مثل عند التسوق أو الطلب في مطعم.',
      explanation: 'الصيغة بسيطة: اسم الشيء + を + ください. يمكن إضافة عدد بعدها مباشرة دون を مثل りんごを2つください.',
      example: { jp: 'コーヒー を ください。', romaji: 'Koohii o kudasai.', ar: 'قهوة من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعطني هذا القاموس من فضلك.',
          words: ['この', '辞書', 'を', 'ください', '。'],
          particles: ['を'],
          answer: 'この 辞書 を ください 。',
        },
        {
          type: 'fill',
          ar: 'ماء من فضلك.',
          sentence: '水 ___ ください。',
          options: ['を', 'に', 'で', 'は'],
          answer: 'を',
        },
        {
          type: 'meaning',
          sentence: 'すみません、塩 を ください。',
          particle: 'を ください',
          options: ['عفوا، أعطني الملح من فضلك.', 'عفوا، أين الملح؟', 'الملح ليس لذيذا.', 'لا أحتاج إلى الملح.'],
          answer: 'عفوا، أعطني الملح من فضلك.',
        },
        {
          type: 'error',
          ar: 'أعطني هذه الزهرة من فضلك.',
          options: ['この 花 を ください。', 'この 花 ください を。', 'を この 花 ください。'],
          answer: 'この 花 を ください。',
        },
      ],
    },
    {
      title: 'あげます と もらいます — الإعطاء والاستلام',
      pattern: 'A は B に 物 を あげます／もらいます。',
      particle: 'に',
      howItWorks: 'あげます = "أعطي" (الفاعل يعطي شخصا آخر)، もらいます = "أستلم" (الفاعل يستلم من شخص آخر). الشخص الذي يُعطى/منه يُستلم يُعلَّم بـ に.',
      explanation: 'لا تُستخدم あげます عندما يعطيك أنت شخص أعلى مكانة (يُستخدم くださいます)، لكن في هذا المستوى نكتفي بالأساسيات.',
      example: { jp: '私 は 田中さん に 花 を あげました。', romaji: 'Watashi wa Tanaka-san ni hana o agemashita.', ar: 'أعطيت السيد تاناكا زهرة.' },
      exercises: [
        {
          type: 'build',
          ar: 'استلمت كتابا من صديقي.',
          words: ['私', 'は', '友達', 'に', '本', 'を', 'もらいました', '。'],
          particles: ['に', 'を'],
          answer: '私 は 友達 に 本 を もらいました 。',
        },
        {
          type: 'fill',
          ar: 'أعطيت أمي زهورا.',
          sentence: '私 は お母さん ___ 花 を あげました。',
          options: ['に', 'を', 'で', 'と'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: '誕生日 に 兄 に 時計 を もらいました。',
          particle: 'もらいます',
          options: ['استلمت ساعة من أخي في عيد ميلادي.', 'أعطيت أخي ساعة في عيد ميلاده.', 'اشتريت ساعة لأخي.', 'أخي اشترى ساعة.'],
          answer: 'استلمت ساعة من أخي في عيد ميلادي.',
        },
        {
          type: 'error',
          ar: 'أعرت صديقي قاموسي.',
          options: ['私 は 友達 に 辞書 を 貸しました。', '私 は 友達 を 辞書 に 貸しました。', '友達 は 私 に 辞書 を 貸しました に。'],
          answer: '私 は 友達 に 辞書 を 貸しました。',
        },
      ],
    },
    {
      title: 'が わかります／あります — الفهم والامتلاك',
      pattern: 'اسم + が + わかります／あります。',
      particle: 'が',
      howItWorks: 'مع أفعال مثل わかります (يفهم) و あります (يوجد/يملك) و できます (يستطيع)، يُعلَّم الشيء المفهوم/الموجود بـ が بدلا من を.',
      explanation: 'مثال: 日本語 が わかります (أفهم اليابانية)، 車 が あります (لدي سيارة/توجد سيارة).',
      example: { jp: '私 は 英語 が わかります。', romaji: 'Watashi wa eigo ga wakarimasu.', ar: 'أنا أفهم الإنجليزية.' },
      exercises: [
        {
          type: 'build',
          ar: 'لدي دراجة هوائية.',
          words: ['私', 'は', '自転車', 'が', 'あります', '。'],
          particles: ['が'],
          answer: '私 は 自転車 が あります 。',
        },
        {
          type: 'fill',
          ar: 'هل تفهم اللغة الفرنسية؟',
          sentence: 'フランス語 ___ わかります か。',
          options: ['が', 'を', 'に', 'は'],
          answer: 'が',
        },
        {
          type: 'meaning',
          sentence: 'すみません、時間 が ありません。',
          particle: 'が',
          options: ['عفوا، ليس لدي وقت.', 'عفوا، لا أعرف الوقت.', 'عفوا، تأخر الوقت.', 'عفوا، الوقت مبكر.'],
          answer: 'عفوا، ليس لدي وقت.',
        },
        {
          type: 'error',
          ar: 'لا أفهم اليابانية جيدا.',
          options: ['日本語 が あまり わかりません。', '日本語 を あまり わかりません。', 'あまり 日本語 わかりません が。'],
          answer: '日本語 が あまり わかりません。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'はし で ご飯 を 食べます。', romaji: 'Hashi de gohan o tabemasu.', ar: 'آكل الأرز بعيدان الطعام.', en: 'I eat rice with chopsticks.' },
    { jp: 'すみません、コーヒー を ください。', romaji: 'Sumimasen, koohii o kudasai.', ar: 'عفوا، قهوة من فضلك.', en: 'Excuse me, coffee please.' },
    { jp: '私 は 友達 に 誕生日 の プレゼント を あげました。', romaji: 'Watashi wa tomodachi ni tanjoubi no purezento o agemashita.', ar: 'أعطيت صديقي هدية عيد ميلاد.', en: 'I gave my friend a birthday present.' },
    { jp: '私 は 田中さん に 本 を もらいました。', romaji: 'Watashi wa Tanaka-san ni hon o moraimashita.', ar: 'استلمت كتابا من السيد تاناكا.', en: 'I received a book from Mr. Tanaka.' },
    { jp: '山田さん は 英語 が わかります。', romaji: 'Yamada-san wa eigo ga wakarimasu.', ar: 'السيد ياماموتو يفهم الإنجليزية.', en: 'Mr. Yamada understands English.' },
    { jp: '私 は 車 が あります。', romaji: 'Watashi wa kuruma ga arimasu.', ar: 'لدي سيارة.', en: 'I have a car.' },
    { jp: '日本語 で 名前 を 書いて ください。', romaji: 'Nihongo de namae o kaite kudasai.', ar: 'اكتب اسمك باليابانية من فضلك.', en: 'Please write your name in Japanese.' },
    { jp: '弟 に 自転車 を 貸しました。', romaji: 'Otouto ni jitensha o kashimashita.', ar: 'أعرت أخي الصغير دراجتي.', en: 'I lent my bicycle to my younger brother.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: ナイフ で 切ります。', answer: 'أقص بالسكين.', hint: 'الوسيلة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 塩 を ください。', answer: 'أعطني الملح من فضلك.', hint: 'الطلب المهذب' },
    { type: 'complete', prompt: 'أكمل: ボールペン ___ 名前 を 書きます。', answer: 'で', hint: 'الأداة' },
    { type: 'complete', prompt: 'أكمل: 私 は 妹 ___ 花 を あげました。', answer: 'に', hint: 'من يستقبل الهدية' },
    { type: 'complete', prompt: 'أكمل: 私 は スペイン語 ___ わかりません。', answer: 'が', hint: 'مع わかります' },
    { type: 'order', prompt: 'رتب: を / ください / この / 辞書', answer: 'この 辞書 を ください。', hint: 'الطلب المهذب' },
    { type: 'order', prompt: 'رتب: もらいました / 友達 / に / 私 / 本 / は / を', answer: '私 は 友達 に 本 を もらいました。', hint: 'هيكل もらいます' },
    { type: 'answer', prompt: '誰 に 花 を あげました か。 (お母さん)', answer: 'お母さん に 花 を あげました。', hint: 'الإجابة بـ に' },
    { type: 'answer', prompt: '日本語 が わかります か。 (はい)', answer: 'はい、わかります。', hint: 'الإجابة بنعم' },
  ],
  videos: [],
}
