export const lessonTwentyFive = {
  id: 25,
  title: { ar: 'مراجعة شاملة لمستوى N5', en: 'Comprehensive N5 Review' },
  focus: 'مراجعة وتجميع أهم القواعد التي تمت دراستها في المستوى N5 من خلال أمثلة وتمارين متنوعة',
  vocab: [
    { id: 'fukushuu', type: 'noun', jp: '復習', kanji: '復習', hiragana: 'ふくしゅう', reading: 'fukushuu', meaning: 'مراجعة' },
    { id: 'goukaku', type: 'noun', jp: '合格', kanji: '合格', hiragana: 'ごうかく', reading: 'goukaku', meaning: 'النجاح / اجتياز اختبار' },
    { id: 'jisshoku', type: 'noun', jp: '実力', kanji: '実力', hiragana: 'じつりょく', reading: 'jitsuryoku', meaning: 'القدرة الحقيقية / المستوى' },
    { id: 'mondai', type: 'noun', jp: '問題', kanji: '問題', hiragana: 'もんだい', reading: 'mondai', meaning: 'سؤال / مشكلة' },
    { id: 'kotae', type: 'noun', jp: '答え', kanji: '答え', hiragana: 'こたえ', reading: 'kotae', meaning: 'إجابة' },
    { id: 'bunpou', type: 'noun', jp: '文法', kanji: '文法', hiragana: 'ぶんぽう', reading: 'bunpou', meaning: 'قواعد اللغة' },
    { id: 'tango', type: 'noun', jp: '単語', kanji: '単語', hiragana: 'たんご', reading: 'tango', meaning: 'مفردة / كلمة' },
    { id: 'renshuu', type: 'noun', jp: '練習', kanji: '練習', hiragana: 'れんしゅう', reading: 'renshuu', meaning: 'تمرين' },
    { id: 'jikan_wari', type: 'noun', jp: '時間割', kanji: '時間割', hiragana: 'じかんわり', reading: 'jikanwari', meaning: 'جدول زمني' },
    { id: 'jisho2', type: 'noun', jp: '辞書', kanji: '辞書', hiragana: 'じしょ', reading: 'jisho', meaning: 'قاموس' },
    { id: 'noukai', type: 'noun', jp: '能力試験', kanji: '能力試験', hiragana: 'のうりょくしけん', reading: 'nouryoku shiken', meaning: 'اختبار الكفاءة' },
    { id: 'tsuzukemasu', type: 'verb', jp: '続けます', kanji: '続けます', hiragana: 'つづけます', reading: 'tsuzukemasu', meaning: 'يستمر' },
    { id: 'akiramemasu', type: 'verb', jp: '諦めます', kanji: '諦めます', hiragana: 'あきらめます', reading: 'akiramemasu', meaning: 'يستسلم / يتخلى' },
    { id: 'doryoku', type: 'noun', jp: '努力', kanji: '努力', hiragana: 'どりょく', reading: 'doryoku', meaning: 'جهد / مثابرة' },
    { id: 'jishin', type: 'noun', jp: '自信', kanji: '自信', hiragana: 'じしん', reading: 'jishin', meaning: 'ثقة بالنفس' },
    { id: 'subarashii', type: 'i-adjective', jp: '素晴らしい', kanji: '素晴らしい', hiragana: 'すばらしい', reading: 'subarashii', meaning: 'رائع' },
    { id: 'mokuhyou', type: 'noun', jp: '目標', kanji: '目標', hiragana: 'もくひょう', reading: 'mokuhyou', meaning: 'هدف' },
    { id: 'tassei', type: 'noun', jp: '達成', kanji: '達成', hiragana: 'たっせい', reading: 'tassei', meaning: 'تحقيق (هدف)' },
    { id: 'omoide', type: 'noun', jp: '思い出', kanji: '思い出', hiragana: 'おもいで', reading: 'omoide', meaning: 'ذكرى' },
    { id: 'korekara', type: 'adverb', jp: 'これから', hiragana: 'これから', reading: 'korekara', meaning: 'من الآن فصاعدا' },
    { id: 'mata_ne', type: 'expression', jp: 'またね', hiragana: 'またね', reading: 'mata ne', meaning: 'إلى اللقاء' },
    { id: 'omedetou', type: 'expression', jp: 'おめでとう', hiragana: 'おめでとう', reading: 'omedetou', meaning: 'تهانينا' },
    { id: 'ganbatte', type: 'expression', jp: '頑張って', kanji: '頑張って', hiragana: 'がんばって', reading: 'ganbatte', meaning: 'بالتوفيق / استمر' },
    { id: 'tsuzuki', type: 'noun', jp: '続き', kanji: '続き', hiragana: 'つづき', reading: 'tsuzuki', meaning: 'تتمة / استمرار' },
  ],
  grammar: [
    {
      title: 'مراجعة الجمل الأساسية: は・です・じゃありません・か・も',
      pattern: 'الدروس 1-3: الجمل الاسمية والوصفية الأساسية',
      particle: 'は / です / か / も',
      howItWorks: 'مراجعة شاملة لتركيب الجملة الاسمية الأساسية: は لتحديد الموضوع، です للجملة الإيجابية المهذبة، じゃありません للنفي، か للسؤال، も لـ"أيضا"، و こ/そ/あ/ど للإشارة (これ/それ/あれ/どれ).',
      explanation: 'هذه القواعد هي الأساس الذي بُني عليه كل شيء آخر. مثال شامل: あれ は 私 の 本 じゃありません。 それ は 田中さん の です か。',
      example: { jp: 'これ は 私 の カメラ です。 それ は 田中さん の じゃありません。', romaji: 'Kore wa watashi no kamera desu. Sore wa Tanaka-san no ja arimasen.', ar: 'هذه كاميرتي. تلك ليست كاميرا السيد تاناكا.' },
      exercises: [
        {
          type: 'build',
          ar: 'أنا لست طالبا، أنا موظف شركة.',
          words: ['私', 'は', '学生', 'じゃありません', '、', '会社員', 'です', '。'],
          particles: ['は'],
          answer: '私 は 学生 じゃありません 、 会社員 です 。',
        },
        {
          type: 'fill',
          ar: 'هل ذلك المكتب أيضا مكتب السيد تاناكا؟',
          sentence: 'あの 机 ___ 田中さん の 机 です か。',
          options: ['も', 'は', 'が', 'を'],
          answer: 'も',
        },
        {
          type: 'meaning',
          sentence: 'これ は 何 です か。 それ は 辞書 です。',
          particle: 'مراجعة',
          options: ['ما هذا؟ ذلك قاموس.', 'أين القاموس؟', 'القاموس مفقود.', 'هذا ليس قاموسا.'],
          answer: 'ما هذا؟ ذلك قاموس.',
        },
        {
          type: 'error',
          ar: 'هل أنت أيضا طالب؟',
          options: ['あなた も 学生 ですか。', 'あなた は も 学生 ですか。', 'あなた も 学生 か。'],
          answer: 'あなた も 学生 ですか。',
        },
      ],
    },
    {
      title: 'مراجعة الأفعال والأماكن: へ・で・に・を・ます/ません',
      pattern: 'الدروس 4-9: تصريف الأفعال المهذب وحروف الجر الأساسية',
      particle: 'へ / で / に / を',
      howItWorks: 'مراجعة: へ لاتجاه الحركة، で لمكان حدوث الفعل أو الأداة، に لمكان التواجد/الوقت المحدد/المستلم، を للمفعول به. تصريف الأفعال: ます (مضارع/مستقبل مهذب)، ません (نفي)، ました (ماضي)، ませんでした (نفي ماضي).',
      explanation: 'مثال شامل يجمع كل الحروف: 私 は 毎朝 9時 に 電車 で 大学 へ 行きます。 そして 図書館 で 本 を 読みます。',
      example: { jp: '昨日 デパート へ 行って、 友達 に プレゼント を あげました。', romaji: 'Kinou depaato e itte, tomodachi ni purezento o agemashita.', ar: 'أمس ذهبت إلى المتجر وأعطيت صديقي هدية.' },
      exercises: [
        {
          type: 'build',
          ar: 'في الصباح، أذهب إلى الجامعة بالحافلة.',
          words: ['朝', '、', 'バス', 'で', '大学', 'へ', '行きます', '。'],
          particles: ['で', 'へ'],
          answer: '朝 、 バス で 大学 へ 行きます 。',
        },
        {
          type: 'fill',
          ar: 'هناك قطة تحت الطاولة.',
          sentence: '机 の 下 ___ 猫 が います。',
          options: ['に', 'で', 'を', 'へ'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: '図書館 で 本 を 三冊 借りました。',
          particle: 'مراجعة',
          options: ['استعرت ثلاثة كتب من المكتبة.', 'بعت ثلاثة كتب في المكتبة.', 'المكتبة بها ثلاثة كتب فقط.', 'لم أذهب إلى المكتبة.'],
          answer: 'استعرت ثلاثة كتب من المكتبة.',
        },
        {
          type: 'error',
          ar: 'أمس لم أذهب إلى المدرسة.',
          options: ['昨日 学校 へ 行きませんでした。', '昨日 学校 へ 行きません。', '昨日 学校 を 行きませんでした。'],
          answer: '昨日 学校 へ 行きませんでした。',
        },
      ],
    },
    {
      title: 'مراجعة て形 وتطبيقاتها: てください・ています・てもいい・てはいけない',
      pattern: 'الدروس 14-18: て形 واستخداماتها المتعددة',
      particle: 'て形',
      howItWorks: 'て形 هي بوابة لكثير من التراكيب: てください (طلب)، ています (حالة مستمرة/عادة)، てもいいです (إذن)، てはいけません (منع)، てから (تتابع)، てしまいます، وغيرها. إتقان تكوينها (مجموعات 1، 2، 3) أساسي.',
      explanation: 'مثال شامل: ここ で 写真 を 撮っても いいです か。 いいえ、 撮っては いけません。 でも、 ここ で 待っても いいです。',
      example: { jp: '今 何 を して いますか。 宿題 を して います。', romaji: 'Ima nani o shite imasu ka. Shukudai o shite imasu.', ar: 'ماذا تفعل الآن؟ أقوم بالواجب.' },
      exercises: [
        {
          type: 'build',
          ar: 'من فضلك انتظر هنا قليلا.',
          words: ['ここ', 'で', '少し', '待って', 'ください', '。'],
          particles: ['で'],
          answer: 'ここ で 少し 待って ください 。',
        },
        {
          type: 'fill',
          ar: 'لا يمكنك التدخين هنا.',
          sentence: 'ここ で たばこ を 吸って ___。',
          options: ['は いけません', 'は います', 'も いいです', 'から いいです'],
          answer: 'は いけません',
        },
        {
          type: 'meaning',
          sentence: '田中さん は 今 電話 で 話して います。',
          particle: 'ています',
          options: ['السيد تاناكا يتحدث في الهاتف الآن.', 'السيد تاناكا لا يستخدم الهاتف أبدا.', 'السيد تاناكا سيتصل غدا.', 'هاتف السيد تاناكا معطل.'],
          answer: 'السيد تاناكا يتحدث في الهاتف الآن.',
        },
        {
          type: 'error',
          ar: 'بعد أن أغسل يدي، آكل.',
          options: ['手 を 洗って から、 ご飯 を 食べます。', '手 を 洗う から、 ご飯 を 食べます。', '手 を 洗ってから、 ご飯 を 食べました から。'],
          answer: '手 を 洗って から、 ご飯 を 食べます。',
        },
      ],
    },
    {
      title: 'مراجعة الصيغ المتقدمة: 普通形・んです・たら/なら・ても・受身形・つもり・そうです',
      pattern: 'الدروس 19-24: القواعد المتقدمة في N5',
      particle: 'مراجعة شاملة',
      howItWorks: 'الصيغة العادية (普通形) هي أساس كل القواعد المتقدمة: と思います، と言っていました، んです، でしょう، 〜とき، たら، なら، ても، 受身形، つもりです، そうです. هذه القواعد تضيف للجمل البسيطة طبقات من المعنى: الرأي، التفسير، الاحتمال، الشرط، والانطباع.',
      explanation: 'مثال شامل يجمع عدة قواعد: 雨 が 降りそう です ね。 もし 降ったら、 試合 は 中止 に なる でしょう。 でも、 私 は 行く つもりです。',
      example: { jp: '田中さん は 来ない と 言って いました。 でも、 もし 来たら、 一緒に 食べましょう。', romaji: 'Tanaka-san wa konai to itte imashita. Demo, moshi kitara, issho ni tabemashou.', ar: 'قال السيد تاناكا إنه لن يأتي. لكن إذا أتى، فلنأكل معا.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعتقد أن الاختبار صعب على الأرجح.',
          words: ['試験', 'は', '難しい', 'と', '思います', '。'],
          particles: ['は', 'と'],
          answer: '試験 は 難しい と 思います 。',
        },
        {
          type: 'fill',
          ar: 'مهما درست، لا أتذكر الكانجي.',
          sentence: 'いくら 勉強___、 漢字 を 覚えられません。',
          options: ['しても', 'したら', 'するなら', 'すると'],
          answer: 'しても',
        },
        {
          type: 'meaning',
          sentence: '将来、 国 へ 帰る つもりです が、 今 は 日本 で 働く つもりです。',
          particle: 'つもりです',
          options: ['أنوي العودة لوطني مستقبلا، لكن الآن أنوي العمل في اليابان.', 'لن أعود إلى وطني أبدا.', 'سأعود إلى وطني غدا.', 'لا أنوي العمل في اليابان أبدا.'],
          answer: 'أنوي العودة لوطني مستقبلا، لكن الآن أنوي العمل في اليابان.',
        },
        {
          type: 'error',
          ar: 'يبدو أنه سيمطر، إذا أمطرت، لن نذهب في نزهة.',
          options: ['雨 が 降りそうです。 雨 が 降ったら、 ピクニック を しません。', '雨 が 降るそうです。 雨 が 降るなら、 ピクニック を しません。', '雨 が 降りそうです。 雨 が 降っても、 ピクニック を しません。'],
          answer: '雨 が 降りそうです。 雨 が 降ったら、 ピクニック を しません。',
        },
      ],
    },
  ],
  examples: [
    { jp: '私 は エジプト人 です。 学生 です。', romaji: 'Watashi wa Ejiputo-jin desu. Gakusei desu.', ar: 'أنا مصري. أنا طالب.', en: 'I am Egyptian. I am a student.' },
    { jp: '毎朝 7時 に 起きて、 朝ご飯 を 食べて、 学校 へ 行きます。', romaji: 'Maiasa shichiji ni okite, asagohan o tabete, gakkou e ikimasu.', ar: 'كل صباح أستيقظ الساعة السابعة، آكل الفطور، وأذهب إلى المدرسة.', en: 'Every morning I wake up at 7, eat breakfast, and go to school.' },
    { jp: 'もし 時間 が あったら、 一緒に 映画 を 見に 行きませんか。', romaji: 'Moshi jikan ga attara, issho ni eiga o mi ni ikimasen ka.', ar: 'إذا كان لديك وقت، ألا تريد الذهاب لمشاهدة فيلم معا؟', en: 'If you have time, would you like to go watch a movie together?' },
    { jp: '日本語 の 勉強 は 難しい です が、 とても 面白い と 思います。', romaji: 'Nihongo no benkyou wa muzukashii desu ga, totemo omoshiroi to omoimasu.', ar: 'دراسة اللغة اليابانية صعبة، لكنني أعتقد أنها ممتعة جدا.', en: 'Studying Japanese is hard, but I think it’s very interesting.' },
    { jp: 'これ から も 日本語 の 勉強 を 続ける つもりです。', romaji: 'Korekara mo nihongo no benkyou o tsuzukeru tsumori desu.', ar: 'أنوي الاستمرار في دراسة اللغة اليابانية من الآن فصاعدا أيضا.', en: 'I plan to continue studying Japanese from now on too.' },
    { jp: 'N5 に 合格したら、 N4 を 勉強する つもりです。', romaji: 'N5 ni goukaku shitara, N4 o benkyou suru tsumori desu.', ar: 'إذا اجتزت N5، أنوي دراسة N4.', en: 'If I pass N5, I plan to study N4.' },
    { jp: '日本語 が 上手に なりました ね。 おめでとう ございます！', romaji: 'Nihongo ga jouzu ni narimashita ne. Omedetou gozaimasu!', ar: 'أصبحت ماهرا في اليابانية! تهانينا!', en: 'You’ve become good at Japanese! Congratulations!' },
    { jp: '頑張って ください。 応援して います。', romaji: 'Ganbatte kudasai. Ouenshite imasu.', ar: 'بالتوفيق. أنا أدعمك.', en: 'Good luck. I’m cheering for you.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 私 は 毎日 漢字 を 勉強して います。', answer: 'أنا أدرس الكانجي كل يوم.', hint: 'ています للعادة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: N5 に 合格したい です。', answer: 'أريد اجتياز N5.', hint: 'たいです' },
    { type: 'complete', prompt: 'أكمل: 毎日 単語 を ___ から、 たくさん 覚えました。 (يحفظ)', answer: '覚えた', hint: 'مراجعة الماضي' },
    { type: 'complete', prompt: 'أكمل: 試験 が 終わっ___、 旅行 します。', answer: 'たら', hint: 'たら' },
    { type: 'complete', prompt: 'أكمل: いくら 難しく___、 諦めません。', answer: 'ても', hint: 'ても' },
    { type: 'order', prompt: 'رتب: です / 大切 / 努力 / は / と / 思います', answer: '努力 は 大切 だ と 思います。', hint: 'と思います مع な-adj' },
    { type: 'order', prompt: 'رتب: つもりです / これから / 勉強 / 続ける / も', answer: 'これから も 勉強 を 続ける つもりです。', hint: 'つもりです' },
    { type: 'answer', prompt: 'N5 の 勉強 は 終わりましたか。 (はい)', answer: 'はい、 N5 の 勉強 は 終わりました。', hint: 'استخدام です/ました' },
    { type: 'answer', prompt: 'これから 何 を する つもりです か。 (N4を勉強します)', answer: 'これから N4 を 勉強する つもりです。', hint: 'الإجابة بـ つもりです' },
  ],
  videos: [],
}
