export const lessonSixteen = {
  id: 16,
  title: { ar: 'الوصف المركب والتغير والإفراط', en: 'Combining Descriptions, Change, and Excess' },
  focus: 'て للوصف المتعدد والسبب، なります للتغير، すぎます للإفراط، و まえに قبل الفعل',
  dialogue: {
    titleAr: 'هل أنت بخير؟ — معدة تؤلم',
    lines: [
      { speaker: 'ساتو', jp: 'ミラーさん、元気が ないですね。', romaji: 'Miraa-san, genki ga nai desu ne.', ar: 'سيد ميلر، تبدو متعبًا.' },
      { speaker: 'ميلر', jp: 'おなかが 痛いです。食べすぎました。', romaji: 'Onaka ga itai desu. Tabesugimashita.', ar: 'معدتي تؤلمني. أكلت كثيرًا.' },
      { speaker: 'ساتو', jp: '寝る まえに 薬を 飲んでください。', romaji: 'Neru mae ni kusuri o nonde kudasai.', ar: 'خذ الدواء قبل أن تنام.' },
      { speaker: 'ميلر', jp: 'はい。最近 寒くなりましたね。', romaji: 'Hai. Saikin samuku narimashita ne.', ar: 'حسنًا. أصبح الجو باردًا مؤخرًا.' },
      { speaker: 'ساتو', jp: 'そうですね。健康に 気をつけてください。', romaji: 'Sou desu ne. Kenkou ni ki o tsukete kudasai.', ar: 'نعم. اعتنِ بصحتك.' },
    ],
  },
  reading: {
    titleAr: 'دراستي للغة اليابانية',
    sentences: [
      { jp: '日本語の 勉強は 楽しくて、おもしろいです。', romaji: 'Nihongo no benkyou wa tanoshikute, omoshiroi desu.', ar: 'دراسة اليابانية ممتعة وشيّقة.' },
      { jp: '毎日 練習しますから、上手に なりました。', romaji: 'Mainichi renshuu shimasu kara, jouzu ni narimashita.', ar: 'لأنني أتدرب كل يوم، أصبحت ماهرًا.' },
      { jp: '寝る まえに 単語を 覚えます。', romaji: 'Neru mae ni tango o oboemasu.', ar: 'أحفظ المفردات قبل النوم.' },
      { jp: 'でも、ときどき 勉強しすぎます。', romaji: 'Demo, tokidoki benkyou shisugimasu.', ar: 'لكن أحيانًا أدرس بإفراط.' },
      { jp: 'これから 医者に なりたいです。', romaji: 'Korekara isha ni naritai desu.', ar: 'مستقبلًا أريد أن أصبح طبيبًا.' },
    ],
    questions: [
      { q: 'كيف يصف الكاتب دراسة اليابانية؟', options: ['ممتعة وشيّقة', 'صعبة ومملة', 'سهلة جدًا'], answer: 'ممتعة وشيّقة' },
      { q: 'متى يحفظ المفردات؟', options: ['قبل النوم', 'بعد الاستيقاظ', 'أثناء الأكل'], answer: 'قبل النوم' },
      { q: 'ماذا يريد أن يصبح؟', options: ['طبيبًا', 'مغنيًا', 'معلمًا'], answer: 'طبيبًا' },
    ],
  },
  vocab: [
    { id: 'narimasu', type: 'verb', jp: 'なります', kanji: 'なります', hiragana: 'なります', reading: 'narimasu', meaning: 'يصبح' },
    { id: 'sugimasu', type: 'verb', jp: 'すぎます', kanji: 'すぎます', hiragana: 'すぎます', reading: 'sugimasu', meaning: 'يفرط في / يتجاوز الحد' },
    { id: 'mae_ni', type: 'particle', jp: 'まえに', kanji: '前に', hiragana: 'まえに', reading: 'mae ni', meaning: 'قبل أن...' },
    { id: 'ato_de', type: 'particle', jp: 'あとで', kanji: '後で', hiragana: 'あとで', reading: 'ato de', meaning: 'بعد ذلك' },
    { id: 'samuku_narimasu', type: 'expression', jp: '寒くなります', kanji: '寒くなります', hiragana: 'さむくなります', reading: 'samuku narimasu', meaning: 'يصبح باردا' },
    { id: 'jouzu_ni_narimasu', type: 'expression', jp: '上手になります', kanji: '上手になります', hiragana: 'じょうずになります', reading: 'jouzu ni narimasu', meaning: 'يصبح ماهرا' },
    { id: 'isha', type: 'person', jp: '医者', kanji: '医者', hiragana: 'いしゃ', reading: 'isha', meaning: 'طبيب' },
    { id: 'kashu', type: 'person', jp: '歌手', kanji: '歌手', hiragana: 'かしゅ', reading: 'kashu', meaning: 'مغني' },
    { id: 'kenkou', type: 'noun', jp: '健康', kanji: '健康', hiragana: 'けんこう', reading: 'kenkou', meaning: 'صحة' },
    { id: 'tabesugimasu', type: 'expression', jp: '食べすぎます', kanji: '食べすぎます', hiragana: 'たべすぎます', reading: 'tabesugimasu', meaning: 'يأكل بإفراط' },
    { id: 'nomisugimasu', type: 'expression', jp: '飲みすぎます', kanji: '飲みすぎます', hiragana: 'のみすぎます', reading: 'nomisugimasu', meaning: 'يشرب بإفراط' },
    { id: 'hatarakisugimasu', type: 'expression', jp: '働きすぎます', kanji: '働きすぎます', hiragana: 'はたらきすぎます', reading: 'hatarakisugimasu', meaning: 'يعمل بإفراط' },
    { id: 'onaka', type: 'noun', jp: 'おなか', hiragana: 'おなか', reading: 'onaka', meaning: 'بطن / معدة' },
    { id: 'itai', type: 'i-adjective', jp: '痛い', kanji: '痛い', hiragana: 'いたい', reading: 'itai', meaning: 'مؤلم' },
    { id: 'nemasu', type: 'verb', jp: '寝ます', kanji: '寝ます', hiragana: 'ねます', reading: 'nemasu', meaning: 'ينام' },
    { id: 'okimasu', type: 'verb', jp: '起きます', kanji: '起きます', hiragana: 'おきます', reading: 'okimasu', meaning: 'يستيقظ' },
    { id: 'dekakemasu', type: 'verb', jp: '出かけます', kanji: '出かけます', hiragana: 'でかけます', reading: 'dekakemasu', meaning: 'يخرج (من المنزل)' },
    { id: 'haburashi', type: 'object', jp: '歯を磨きます', kanji: '歯を磨きます', hiragana: 'はをみがきます', reading: 'ha o migakimasu', meaning: 'يغسل أسنانه' },
    { id: 'shokuji_shimasu', type: 'verb', jp: '食事します', kanji: '食事します', hiragana: 'しょくじします', reading: 'shokuji shimasu', meaning: 'يتناول وجبة' },
    { id: 'samusa', type: 'noun', jp: '寒さ', kanji: '寒さ', hiragana: 'さむさ', reading: 'samusa', meaning: 'البرودة' },
    { id: 'natsuyasumi2', type: 'noun', jp: '夏休み', kanji: '夏休み', hiragana: 'なつやすみ', reading: 'natsuyasumi', meaning: 'عطلة الصيف' },
    { id: 'sensei2', type: 'person', jp: '先生', kanji: '先生', hiragana: 'せんせい', reading: 'sensei', meaning: 'معلم/أستاذ' },
    { id: 'shizuka2', type: 'na-adjective', jp: '静か', kanji: '静か', hiragana: 'しずか', reading: 'shizuka', meaning: 'هادئ' },
    { id: 'hiroi', type: 'i-adjective', jp: '広い', kanji: '広い', hiragana: 'ひろい', reading: 'hiroi', meaning: 'واسع' },
  ],
  grammar: [
    {
      title: 'صفة い + くて — الوصف المتعدد والسبب',
      pattern: 'صفة い (بدون い) + くて + جملة أخرى',
      particle: 'くて',
      howItWorks: 'لربط صفتين من نوع い في جملة واحدة (هذا جميل و... )، نحذف い من الصفة الأولى ونضيف くて. يمكن أيضا أن تحمل くて معنى السبب (لأن... فـ...).',
      explanation: 'استثناء: いい → よくて. مثال: この 部屋 は 広くて、 明るい です (هذه الغرفة واسعة ومضيئة).',
      example: { jp: 'この レストラン は 安くて、 おいしい です。', romaji: 'Kono resutoran wa yasukute, oishii desu.', ar: 'هذا المطعم رخيص ولذيذ.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذه الغرفة واسعة ومضيئة.',
          words: ['この', '部屋', 'は', '広くて', '、', '明るい', 'です', '。'],
          particles: ['は'],
          answer: 'この 部屋 は 広くて 、 明るい です 。',
        },
        {
          type: 'fill',
          ar: 'لأن جسمي يؤلمني، سأذهب إلى المستشفى. (سبب)',
          sentence: 'おなか が 痛___、 病院 へ 行きます。',
          options: ['くて', 'いです', 'かった', 'です'],
          answer: 'くて',
        },
        {
          type: 'meaning',
          sentence: 'この かばん は 軽くて、 便利 です。',
          particle: 'くて',
          options: ['هذه الحقيبة خفيفة ومريحة.', 'هذه الحقيبة ثقيلة وغير مريحة.', 'هذه الحقيبة خفيفة لكن غير مريحة.', 'هذه الحقيبة ليست خفيفة.'],
          answer: 'هذه الحقيبة خفيفة ومريحة.',
        },
        {
          type: 'error',
          ar: 'الطقس جيد ودافئ.',
          options: ['天気 が よくて、 暖かい です。', '天気 が いくて、 暖かい です。', '天気 が いいくて、 暖かい です。'],
          answer: '天気 が よくて、 暖かい です。',
        },
      ],
    },
    {
      title: 'صفة な + で — الوصف المتعدد للصفات な',
      pattern: 'صفة な + で + جملة أخرى',
      particle: 'で',
      howItWorks: 'صفات な والأسماء تستخدم で (بدلا من くて) لربط جملتين، بنفس معنى الوصف المتعدد أو السبب.',
      explanation: 'مثال: ここ は 静か で、 きれい です (هنا هادئ ونظيف). أو: 病気 で、 学校 を 休みました (تغيبت عن المدرسة بسبب المرض).',
      example: { jp: '彼女 は 親切 で、 きれい です。', romaji: 'Kanojo wa shinsetsu de, kirei desu.', ar: 'هي لطيفة وجميلة.' },
      exercises: [
        {
          type: 'build',
          ar: 'هذه المدينة هادئة وجميلة.',
          words: ['この', '町', 'は', '静か', 'で', '、', 'きれい', 'です', '。'],
          particles: ['は'],
          answer: 'この 町 は 静か で 、 きれい です 。',
        },
        {
          type: 'fill',
          ar: 'تغيبت عن المدرسة بسبب المرض.',
          sentence: '病気 ___、 学校 を 休みました。',
          options: ['で', 'くて', 'から', 'ので'],
          answer: 'で',
        },
        {
          type: 'meaning',
          sentence: 'この 仕事 は 簡単 で、 楽 です。',
          particle: 'で',
          options: ['هذا العمل بسيط ومريح.', 'هذا العمل صعب ومتعب.', 'هذا العمل بسيط لكنه متعب.', 'هذا العمل ليس بسيطا.'],
          answer: 'هذا العمل بسيط ومريح.',
        },
        {
          type: 'error',
          ar: 'هو طالب ونشيط.',
          options: ['彼 は 学生 で、 元気 です。', '彼 は 学生 くて、 元気 です。', '彼 は 学生 だ で、 元気 です。'],
          answer: '彼 は 学生 で、 元気 です。',
        },
      ],
    },
    {
      title: '〜くなります／〜になります — التغير',
      pattern: 'صفة い (بدون い) + くなります ／ صفة な/اسم + になります',
      particle: 'なります',
      howItWorks: 'تستخدم なります للتعبير عن "يصبح/تصبح". مع صفات い نحذف い ونضيف くなります. مع صفات な والأسماء نضيف になります مباشرة.',
      explanation: 'استثناء: いい → よくなります. مثال: 寒く なりました (أصبح الجو باردا)، 先生 に なりました (أصبح معلما).',
      example: { jp: '日本語 が 上手 に なりました。', romaji: 'Nihongo ga jouzu ni narimashita.', ar: 'أصبحت ماهرا في اليابانية.' },
      exercises: [
        {
          type: 'build',
          ar: 'الطقس أصبح دافئا.',
          words: ['天気', 'が', '暖かく', 'なりました', '。'],
          particles: ['が'],
          answer: '天気 が 暖かく なりました 。',
        },
        {
          type: 'fill',
          ar: 'أصبح طبيبا.',
          sentence: '彼 は 医者 ___ なりました。',
          options: ['に', 'く', 'が', 'で'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: 'この 町 は にぎやか に なりました。',
          particle: 'になります',
          options: ['أصبحت هذه المدينة صاخبة.', 'كانت هذه المدينة صاخبة دائما.', 'هذه المدينة هادئة الآن.', 'هذه المدينة لم تتغير.'],
          answer: 'أصبحت هذه المدينة صاخبة.',
        },
        {
          type: 'error',
          ar: 'الجو أصبح باردا.',
          options: ['寒く なりました。', '寒い に なりました。', '寒に なりました。'],
          answer: '寒く なりました。',
        },
      ],
    },
    {
      title: '〜すぎます と 〜まえに — الإفراط وقبل الفعل',
      pattern: 'فعل (ます‐stem) + すぎます ／ فعل (dictionary form) + まえに',
      particle: 'すぎ・まえに',
      howItWorks: 'すぎます تُضاف إلى جذع الفعل (ます‐stem) أو إلى أصل الصفة للدلالة على الإفراط "أكثر من اللازم". まえに تأتي بعد الفعل بصيغته الأساسية (القاموسية) للدلالة على "قبل أن...".',
      explanation: 'مع الأسماء: اسم + の + まえに (مثل 食事の前に - قبل الوجبة). مع الأفعال: الفعل بصيغته الأساسية + まえに (مثل 寝るまえに - قبل النوم).',
      example: { jp: '寝る まえに 歯 を 磨きます。', romaji: 'Neru mae ni ha o migakimasu.', ar: 'أغسل أسناني قبل النوم.' },
      exercises: [
        {
          type: 'build',
          ar: 'أكلت كثيرا (بإفراط) أمس.',
          words: ['昨日', '食べすぎました', '。'],
          particles: [],
          answer: '昨日 食べすぎました 。',
        },
        {
          type: 'fill',
          ar: 'قبل الخروج، أتحقق من الطقس.',
          sentence: '出かける ___、 天気 を 見ます。',
          options: ['まえに', 'あとで', 'から', 'てから'],
          answer: 'まえに',
        },
        {
          type: 'meaning',
          sentence: 'お酒 を 飲みすぎて、 頭 が 痛い です。',
          particle: 'すぎ',
          options: ['شربت الكحول بإفراط، ولذلك رأسي يؤلمني.', 'لم أشرب الكحول إطلاقا.', 'الكحول لذيذ جدا.', 'رأسي يؤلمني رغم أنني لم أشرب.'],
          answer: 'شربت الكحول بإفراط، ولذلك رأسي يؤلمني.',
        },
        {
          type: 'error',
          ar: 'قبل الوجبة، أغسل يدي.',
          options: ['食事 の まえに、 手 を 洗います。', '食事 まえ の に、 手 を 洗います。', '食事 する まえに の、 手 を 洗います。'],
          answer: '食事 の まえに、 手 を 洗います。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'この カメラ は 軽くて、 便利 です。', romaji: 'Kono kamera wa karukute, benri desu.', ar: 'هذه الكاميرا خفيفة ومريحة.', en: 'This camera is light and convenient.' },
    { jp: '京都 は 静か で、 古い 町 です。', romaji: 'Kyouto wa shizuka de, furui machi desu.', ar: 'كيوتو مدينة هادئة وقديمة.', en: 'Kyoto is a quiet, old town.' },
    { jp: '最近 、 寒く なりました。', romaji: 'Saikin, samuku narimashita.', ar: 'أصبح الجو باردا مؤخرا.', en: 'It’s gotten cold recently.' },
    { jp: '日本語 が 上手 に なりました ね。', romaji: 'Nihongo ga jouzu ni narimashita ne.', ar: 'أصبحت ماهرا في اليابانية، أليس كذلك؟', en: 'You’ve become good at Japanese, haven’t you?' },
    { jp: '昨日 は 働きすぎました。', romaji: 'Kinou wa hatarakisugimashita.', ar: 'عملت بإفراط أمس.', en: 'I worked too much yesterday.' },
    { jp: '食事 の まえに、 手 を 洗いましょう。', romaji: 'Shokuji no mae ni, te o araimashou.', ar: 'لنغسل أيدينا قبل الوجبة.', en: 'Let’s wash our hands before the meal.' },
    { jp: '寝る まえに 本 を 読みます。', romaji: 'Neru mae ni hon o yomimasu.', ar: 'أقرأ كتابا قبل النوم.', en: 'I read a book before sleeping.' },
    { jp: 'お酒 を 飲みすぎないで ください。', romaji: 'Osake o nomisuginaide kudasai.', ar: 'لا تشرب الكحول بإفراط من فضلك.', en: 'Please don’t drink too much alcohol.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: この 店 は 安くて、 おいしい です。', answer: 'هذا المتجر رخيص ولذيذ.', hint: 'くて للوصف المتعدد' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 彼女 は 元気 で、 明るい です。', answer: 'هي نشيطة ومرحة.', hint: 'で للوصف المتعدد' },
    { type: 'complete', prompt: 'أكمل: 暑___ なりました。 (يصبح حارا)', answer: 'く', hint: 'تحويل صفة い' },
    { type: 'complete', prompt: 'أكمل: 彼 は 歌手 ___ なりました。', answer: 'に', hint: 'التغير مع الأسماء' },
    { type: 'complete', prompt: 'أكمل: 食べ___、 おなか が 痛い です。 (إفراط)', answer: 'すぎて', hint: 'すぎます + て' },
    { type: 'order', prompt: 'رتب: 軽くて / 便利 / は / この / かばん / です', answer: 'この かばん は 軽くて 便利 です。', hint: 'الوصف المتعدد بـ くて' },
    { type: 'order', prompt: 'رتب: まえに / 寝る / 磨きます / 歯 / を', answer: '寝る まえに 歯 を 磨きます。', hint: 'まえに قبل الفعل' },
    { type: 'answer', prompt: '日本語 は どう です か。 (面白くて、難しい)', answer: '面白くて、 難しい です。', hint: 'الإجابة بالوصف المتعدد' },
    { type: 'answer', prompt: '最近 、 天気 は どう なりました か。 (寒い)', answer: '寒く なりました。', hint: 'الإجابة بالتغير' },
  ],
  videos: [],
}
