export const lessonNine = {
  id: 9,
  title: { ar: 'الوجود والمواقع', en: 'Existence and Location' },
  focus: 'あります/います لوصف الوجود، に للمكان، や〜など للتعداد غير الشامل، وكلمات الموقع',
  dialogue: {
    titleAr: 'أين القطة؟ — البحث عن الأشياء',
    lines: [
      { speaker: 'ميلر', jp: 'さとうさん、猫は どこに いますか。', romaji: 'Satou-san, neko wa doko ni imasu ka.', ar: 'ساتو، أين القطة؟' },
      { speaker: 'ساتو', jp: 'ベッドの 上に います。', romaji: 'Beddo no ue ni imasu.', ar: 'إنها فوق السرير.' },
      { speaker: 'ميلر', jp: '私の 財布は どこに ありますか。', romaji: 'Watashi no saifu wa doko ni arimasu ka.', ar: 'وأين محفظتي؟' },
      { speaker: 'ساتو', jp: '机の 下に あります。', romaji: 'Tsukue no shita ni arimasu.', ar: 'تحت المكتب.' },
      { speaker: 'ميلر', jp: 'この 近くに コンビニが ありますか。', romaji: 'Kono chikaku ni konbini ga arimasu ka.', ar: 'هل يوجد متجر قريب من هنا؟' },
      { speaker: 'ساتو', jp: 'はい、銀行の 隣に あります。', romaji: 'Hai, ginkou no tonari ni arimasu.', ar: 'نعم، بجانب البنك.' },
      { speaker: 'ميلر', jp: 'どうもありがとうございます。', romaji: 'Doumo arigatou gozaimasu.', ar: 'شكرًا جزيلًا.' },
    ],
  },
  reading: {
    titleAr: 'ما حولي — وصف المكان',
    sentences: [
      { jp: '机の 上に コンピューターが あります。', romaji: 'Tsukue no ue ni konpyuutaa ga arimasu.', ar: 'فوق المكتب حاسوب.' },
      { jp: '机の 下に 箱が あります。', romaji: 'Tsukue no shita ni hako ga arimasu.', ar: 'وتحت المكتب صندوق.' },
      { jp: '箱の 中に 本や 写真などが あります。', romaji: 'Hako no naka ni hon ya shashin nado ga arimasu.', ar: 'في داخل الصندوق كتب وصور وغيرها.' },
      { jp: '窓の 前に 鳥が います。', romaji: 'Mado no mae ni tori ga imasu.', ar: 'أمام النافذة طائر.' },
      { jp: 'ドアの 後ろに 猫が います。', romaji: 'Doa no ushiro ni neko ga imasu.', ar: 'وخلف الباب قطة.' },
    ],
    questions: [
      { q: 'ماذا يوجد فوق المكتب؟', options: ['حاسوب', 'صندوق', 'قطة'], answer: 'حاسوب' },
      { q: 'ماذا في داخل الصندوق؟', options: ['كتب وصور', 'ثلاجة', 'طائر'], answer: 'كتب وصور' },
      { q: 'أين القطة؟', options: ['خلف الباب', 'فوق السرير', 'أمام النافذة'], answer: 'خلف الباب' },
    ],
  },
  vocab: [
    { id: 'arimasu2', type: 'verb', jp: 'あります', kanji: 'あります', hiragana: 'あります', reading: 'arimasu', meaning: 'يوجد (لغير الحي)' },
    { id: 'imasu', type: 'verb', jp: 'います', kanji: 'います', hiragana: 'います', reading: 'imasu', meaning: 'يوجد (للحي)' },
    { id: 'tsukue', type: 'object', jp: '机', kanji: '机', hiragana: 'つくえ', reading: 'tsukue', meaning: 'مكتب (طاولة)' },
    { id: 'isu', type: 'object', jp: 'いす', hiragana: 'いす', reading: 'isu', meaning: 'كرسي' },
    { id: 'beddo', type: 'object', jp: 'ベッド', hiragana: 'ベッド', reading: 'beddo', meaning: 'سرير' },
    { id: 'tana', type: 'object', jp: '棚', kanji: '棚', hiragana: 'たな', reading: 'tana', meaning: 'رف' },
    { id: 'reizouko', type: 'object', jp: '冷蔵庫', kanji: '冷蔵庫', hiragana: 'れいぞうこ', reading: 'reizouko', meaning: 'ثلاجة' },
    { id: 'doa', type: 'object', jp: 'ドア', hiragana: 'ドア', reading: 'doa', meaning: 'باب' },
    { id: 'mado', type: 'object', jp: '窓', kanji: '窓', hiragana: 'まど', reading: 'mado', meaning: 'نافذة' },
    { id: 'hako', type: 'object', jp: '箱', kanji: '箱', hiragana: 'はこ', reading: 'hako', meaning: 'صندوق' },
    { id: 'saifu', type: 'object', jp: '財布', kanji: '財布', hiragana: 'さいふ', reading: 'saifu', meaning: 'محفظة' },
    { id: 'neko', type: 'animal', jp: '猫', kanji: '猫', hiragana: 'ねこ', reading: 'neko', meaning: 'قطة' },
    { id: 'tori', type: 'animal', jp: '鳥', kanji: '鳥', hiragana: 'とり', reading: 'tori', meaning: 'طائر' },
    { id: 'kodomo', type: 'person', jp: '子供', kanji: '子供', hiragana: 'こども', reading: 'kodomo', meaning: 'طفل' },
    { id: 'ginkou', type: 'place', jp: '銀行', kanji: '銀行', hiragana: 'ぎんこう', reading: 'ginkou', meaning: 'بنك' },
    { id: 'konbini', type: 'place', jp: 'コンビニ', hiragana: 'コンビニ', reading: 'konbini', meaning: 'متجر صغير (كومبيني)' },
    { id: 'yuubinkyoku', type: 'place', jp: '郵便局', kanji: '郵便局', hiragana: 'ゆうびんきょく', reading: 'yuubinkyoku', meaning: 'مكتب بريد' },
    { id: 'kouen', type: 'place', jp: '公園', kanji: '公園', hiragana: 'こうえん', reading: 'kouen', meaning: 'حديقة عامة' },
    { id: 'ue', type: 'position', jp: '上', kanji: '上', hiragana: 'うえ', reading: 'ue', meaning: 'فوق' },
    { id: 'shita', type: 'position', jp: '下', kanji: '下', hiragana: 'した', reading: 'shita', meaning: 'تحت' },
    { id: 'naka', type: 'position', jp: '中', kanji: '中', hiragana: 'なか', reading: 'naka', meaning: 'داخل' },
    { id: 'mae', type: 'position', jp: '前', kanji: '前', hiragana: 'まえ', reading: 'mae', meaning: 'أمام' },
    { id: 'ushiro', type: 'position', jp: '後ろ', kanji: '後ろ', hiragana: 'うしろ', reading: 'ushiro', meaning: 'خلف' },
    { id: 'tonari', type: 'position', jp: '隣', kanji: '隣', hiragana: 'となり', reading: 'tonari', meaning: 'بجانب (مجاور)' },
    { id: 'chikaku', type: 'position', jp: '近く', kanji: '近く', hiragana: 'ちかく', reading: 'chikaku', meaning: 'بالقرب من' },
  ],
  grammar: [
    {
      title: 'あります — وجود الأشياء غير الحية',
      pattern: 'مكان + に + شيء + が + あります。',
      particle: 'に・が',
      howItWorks: 'تستخدم あります للتعبير عن وجود الأشياء وغير الحي (كتب، أثاث، مباني، نباتات). المكان يُعلَّم بـ に والشيء الموجود بـ が.',
      explanation: 'الترتيب يمكن أن يتغير: 机の上に本があります (على المكتب يوجد كتاب) أو 本は机の上にあります (الكتاب على المكتب) - الأخيرة تستخدم は لأن الشيء معروف مسبقا.',
      example: { jp: '机 の 上 に 本 が あります。', romaji: 'Tsukue no ue ni hon ga arimasu.', ar: 'يوجد كتاب على المكتب.' },
      exercises: [
        {
          type: 'build',
          ar: 'يوجد صندوق تحت الكرسي.',
          words: ['いす', 'の', '下', 'に', '箱', 'が', 'あります', '。'],
          particles: ['の', 'に', 'が'],
          answer: 'いす の 下 に 箱 が あります 。',
        },
        {
          type: 'fill',
          ar: 'يوجد بنك أمام محطة القطار.',
          sentence: '駅 の 前 ___ 銀行 が あります。',
          options: ['に', 'で', 'を', 'へ'],
          answer: 'に',
        },
        {
          type: 'meaning',
          sentence: '冷蔵庫 の 中 に 卵 が あります。',
          particle: 'あります',
          options: ['يوجد بيض داخل الثلاجة.', 'الثلاجة بجانب البيض.', 'البيض أكبر من الثلاجة.', 'لا يوجد بيض في الثلاجة.'],
          answer: 'يوجد بيض داخل الثلاجة.',
        },
        {
          type: 'error',
          ar: 'يوجد متجر بالقرب من المنزل.',
          options: ['家 の 近く に 店 が あります。', '家 の 近く で 店 が います。', '店 が 家 の 近く を あります。'],
          answer: '家 の 近く に 店 が あります。',
        },
      ],
    },
    {
      title: 'います — وجود الكائنات الحية',
      pattern: 'مكان + に + كائن حي + が + います。',
      particle: 'に・が',
      howItWorks: 'تستخدم います للتعبير عن وجود البشر والحيوانات. باقي القاعدة مطابقة لـ あります (المكان + に، الفاعل + が).',
      explanation: 'لا تُستخدم います للنباتات أو الأشياء الجامدة. مثال: 木があります (توجد شجرة) لكن 鳥がいます (يوجد طائر).',
      example: { jp: '公園 に 子供 が います。', romaji: 'Kouen ni kodomo ga imasu.', ar: 'يوجد أطفال في الحديقة.' },
      exercises: [
        {
          type: 'build',
          ar: 'توجد قطة تحت السرير.',
          words: ['ベッド', 'の', '下', 'に', '猫', 'が', 'います', '。'],
          particles: ['の', 'に', 'が'],
          answer: 'ベッド の 下 に 猫 が います 。',
        },
        {
          type: 'fill',
          ar: 'هل يوجد طائر على الشجرة؟',
          sentence: '木 の 上 に 鳥 が ___ か。',
          options: ['います', 'あります', 'です', 'いません'],
          answer: 'います',
        },
        {
          type: 'meaning',
          sentence: '部屋 の 中 に だれも いません。',
          particle: 'いません',
          options: ['لا يوجد أحد داخل الغرفة.', 'يوجد شخص ما في الغرفة.', 'الغرفة فارغة من الأثاث.', 'الغرفة كبيرة جدا.'],
          answer: 'لا يوجد أحد داخل الغرفة.',
        },
        {
          type: 'error',
          ar: 'يوجد كلب أمام المتجر.',
          options: ['店 の 前 に 犬 が います。', '店 の 前 に 犬 が あります。', '犬 は 店 の 前 が います。'],
          answer: '店 の 前 に 犬 が います。',
        },
      ],
    },
    {
      title: 'や〜など — التعداد غير الشامل',
      pattern: 'اسم1 + や + اسم2 + (など)',
      particle: 'や',
      howItWorks: 'تستخدم や لذكر بعض الأمثلة من قائمة دون حصرها بالكامل، بعكس と التي تذكر كل العناصر. تأتي など (إلخ/وغيرها) غالبا في نهاية القائمة.',
      explanation: 'مقارنة: 机 と いす が あります (يوجد مكتب وكرسي فقط - حصري) مقابل 机 や いす が あります (يوجد مكتب وكرسي وأشياء أخرى - غير حصري).',
      example: { jp: '机 の 上 に 本 や ノート など が あります。', romaji: 'Tsukue no ue ni hon ya nooto nado ga arimasu.', ar: 'على المكتب يوجد كتب ودفاتر وأشياء أخرى.' },
      exercises: [
        {
          type: 'build',
          ar: 'في الحديقة توجد قطط وطيور وغيرها.',
          words: ['公園', 'に', '猫', 'や', '鳥', 'など', 'が', 'います', '。'],
          particles: ['に', 'や', 'が'],
          answer: '公園 に 猫 や 鳥 など が います 。',
        },
        {
          type: 'fill',
          ar: 'في الحقيبة يوجد محفظة وقاموس وغيرها.',
          sentence: 'かばん の 中 に 財布 ___ 辞書 など が あります。',
          options: ['や', 'と', 'も', 'は'],
          answer: 'や',
        },
        {
          type: 'meaning',
          sentence: '冷蔵庫 に 卵 や 牛乳 など が あります。',
          particle: 'や',
          options: ['في الثلاجة يوجد بيض وحليب وأشياء أخرى.', 'في الثلاجة يوجد بيض وحليب فقط لا غير.', 'الثلاجة فارغة.', 'البيض والحليب في المتجر.'],
          answer: 'في الثلاجة يوجد بيض وحليب وأشياء أخرى.',
        },
        {
          type: 'error',
          ar: 'في الفصل توجد طاولات وكراسي وغيرها.',
          options: ['教室 に 机 や いす など が あります。', '教室 に 机 と いす など が あります。', '教室 に 机 や いす が など あります。'],
          answer: '教室 に 机 や いす など が あります。',
        },
      ],
    },
    {
      title: 'كلمات الموقع (位置語)',
      pattern: 'اسم + の + كلمة موقع',
      particle: 'の',
      howItWorks: 'لتحديد موقع شيء بالنسبة لآخر، نستخدم: اسم + の + (上/下/中/前/後ろ/隣/近く...) ثم に + あります/います.',
      explanation: '上 (فوق)،下 (تحت)،中 (داخل)،前 (أمام)،後ろ (خلف)،隣 (بجانب/مجاور)،近く (بالقرب من). كلها تتبع نفس النمط: A の [موقع] に B があります/います.',
      example: { jp: '銀行 は 郵便局 の 隣 に あります。', romaji: 'Ginkou wa yuubinkyoku no tonari ni arimasu.', ar: 'البنك بجانب مكتب البريد.' },
      exercises: [
        {
          type: 'build',
          ar: 'القطة خلف الباب.',
          words: ['猫', 'は', 'ドア', 'の', '後ろ', 'に', 'います', '。'],
          particles: ['は', 'の', 'に'],
          answer: '猫 は ドア の 後ろ に います 。',
        },
        {
          type: 'fill',
          ar: 'الكومبيني بالقرب من المحطة.',
          sentence: 'コンビニ は 駅 の ___ に あります。',
          options: ['近く', '中', '上', '下'],
          answer: '近く',
        },
        {
          type: 'meaning',
          sentence: 'いす の 上 に かばん が あります。',
          particle: '上',
          options: ['الحقيبة فوق الكرسي.', 'الحقيبة تحت الكرسي.', 'الكرسي بجانب الحقيبة.', 'لا توجد حقيبة.'],
          answer: 'الحقيبة فوق الكرسي.',
        },
        {
          type: 'error',
          ar: 'الحديقة أمام البنك.',
          options: ['公園 は 銀行 の 前 に あります。', '公園 は 銀行 の 前 が あります。', '公園 銀行 の 前 に は あります。'],
          answer: '公園 は 銀行 の 前 に あります。',
        },
      ],
    },
  ],
  examples: [
    { jp: '部屋 に テレビ が あります。', romaji: 'Heya ni terebi ga arimasu.', ar: 'يوجد تلفاز في الغرفة.', en: 'There is a TV in the room.' },
    { jp: '庭 に 犬 が います。', romaji: 'Niwa ni inu ga imasu.', ar: 'يوجد كلب في الحديقة (الفناء).', en: 'There is a dog in the yard.' },
    { jp: 'テーブル の 上 に コップ や 皿 など が あります。', romaji: 'Teeburu no ue ni koppu ya sara nado ga arimasu.', ar: 'على الطاولة توجد أكواب وأطباق وغيرها.', en: 'On the table there are cups, plates, and other things.' },
    { jp: '銀行 の 隣 に 郵便局 が あります。', romaji: 'Ginkou no tonari ni yuubinkyoku ga arimasu.', ar: 'بجانب البنك يوجد مكتب بريد.', en: 'Next to the bank there is a post office.' },
    { jp: '木 の 下 に 猫 が います。', romaji: 'Ki no shita ni neko ga imasu.', ar: 'توجد قطة تحت الشجرة.', en: 'There is a cat under the tree.' },
    { jp: 'かばん の 中 に 何 が あります か。', romaji: 'Kaban no naka ni nani ga arimasu ka.', ar: 'ماذا يوجد داخل الحقيبة؟', en: 'What is inside the bag?' },
    { jp: '財布 や 携帯 が あります。', romaji: 'Saifu ya keitai ga arimasu.', ar: 'توجد محفظة وهاتف وأشياء أخرى.', en: 'There is a wallet, a phone, and other things.' },
    { jp: '駅 の 近く に コンビニ が あります。', romaji: 'Eki no chikaku ni konbini ga arimasu.', ar: 'يوجد متجر صغير بالقرب من المحطة.', en: 'There is a convenience store near the station.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 机 の 上 に ノート が あります。', answer: 'يوجد دفتر على المكتب.', hint: 'あります للأشياء' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 公園 に 子供 が います。', answer: 'يوجد أطفال في الحديقة.', hint: 'います للكائنات الحية' },
    { type: 'complete', prompt: 'أكمل: 棚 の 上 ___ 本 が あります。', answer: 'に', hint: 'علامة المكان' },
    { type: 'complete', prompt: 'أكمل: かばん の 中 に 財布 ___ かぎ など が あります。', answer: 'や', hint: 'التعداد غير الحصري' },
    { type: 'complete', prompt: 'أكمل: 猫 は いす の ___ に います。 (تحت)', answer: '下', hint: 'كلمة موقع' },
    { type: 'order', prompt: 'رتب: が / に / 鳥 / 木 / 上 / の / います', answer: '木 の 上 に 鳥 が います。', hint: 'الموقع + が + います' },
    { type: 'order', prompt: 'رتب: 隣 / に / 銀行 / コンビニ / の / が / あります', answer: 'コンビニ の 隣 に 銀行 が あります。', hint: 'الموقع النسبي' },
    { type: 'answer', prompt: '部屋 に 何 が あります か。 (机と いす)', answer: '机 と いす が あります。', hint: 'الإجابة بـ あります' },
    { type: 'answer', prompt: 'だれ が います か。 (誰もいません)', answer: 'だれも いません。', hint: 'النفي الشامل' },
  ],
  videos: [],
}
