export const lessonSeventeen = {
  id: 17,
  title: { ar: 'صيغة القاموس والقدرة والتسلسل', en: 'Dictionary Form, Ability, and Sequence' },
  focus: 'تكوين صيغة القاموس، ことができます للقدرة، まえに/あとで مع صيغة القاموس، و〜と (الشرط التلقائي)',
  vocab: [
    { id: 'kotogadekimasu', type: 'expression', jp: '〜ことができます', hiragana: '〜ことができます', reading: '~koto ga dekimasu', meaning: 'يستطيع أن...' },
    { id: 'unten_shimasu', type: 'verb', jp: '運転します', kanji: '運転します', hiragana: 'うんてんします', reading: 'unten shimasu', meaning: 'يقود (سيارة)' },
    { id: 'piano_hikimasu', type: 'expression', jp: 'ピアノを弾きます', kanji: 'ピアノを弾きます', hiragana: 'ピアノをひきます', reading: 'piano o hikimasu', meaning: 'يعزف البيانو' },
    { id: 'oyogu', type: 'verb', jp: '泳ぐ', kanji: '泳ぐ', hiragana: 'およぐ', reading: 'oyogu', meaning: 'يسبح (قاموسي)' },
    { id: 'taberu', type: 'verb', jp: '食べる', kanji: '食べる', hiragana: 'たべる', reading: 'taberu', meaning: 'يأكل (قاموسي)' },
    { id: 'kuru', type: 'verb', jp: '来る', kanji: '来る', hiragana: 'くる', reading: 'kuru', meaning: 'يأتي (قاموسي)' },
    { id: 'suru', type: 'verb', jp: 'する', hiragana: 'する', reading: 'suru', meaning: 'يفعل (قاموسي)' },
    { id: 'shumi', type: 'noun', jp: '趣味', kanji: '趣味', hiragana: 'しゅみ', reading: 'shumi', meaning: 'هواية' },
    { id: 'unten_menkyo', type: 'noun', jp: '運転免許', kanji: '運転免許', hiragana: 'うんてんめんきょ', reading: 'unten menkyo', meaning: 'رخصة قيادة' },
    { id: 'kanji', type: 'noun', jp: '漢字', kanji: '漢字', hiragana: 'かんじ', reading: 'kanji', meaning: 'كانجي (الرموز اليابانية)' },
    { id: 'kuukou3', type: 'place', jp: '空港', kanji: '空港', hiragana: 'くうこう', reading: 'kuukou', meaning: 'مطار' },
    { id: 'magarimasu', type: 'verb', jp: '曲がります', kanji: '曲がります', hiragana: 'まがります', reading: 'magarimasu', meaning: 'ينعطف' },
    { id: 'massugu', type: 'adverb', jp: 'まっすぐ', hiragana: 'まっすぐ', reading: 'massugu', meaning: 'مباشرة (دون انعطاف)' },
    { id: 'shingou', type: 'noun', jp: '信号', kanji: '信号', hiragana: 'しんごう', reading: 'shingou', meaning: 'إشارة مرور' },
    { id: 'oshimasu', type: 'verb', jp: '押します', kanji: '押します', hiragana: 'おします', reading: 'oshimasu', meaning: 'يضغط' },
    { id: 'botan', type: 'object', jp: 'ボタン', hiragana: 'ボタン', reading: 'botan', meaning: 'زر' },
    { id: 'mizu_ga_demasu', type: 'expression', jp: '水が出ます', kanji: '水が出ます', hiragana: 'みずがでます', reading: 'mizu ga demasu', meaning: 'يخرج الماء' },
    { id: 'biza', type: 'noun', jp: 'ビザ', hiragana: 'ビザ', reading: 'biza', meaning: 'تأشيرة' },
    { id: 'hitori_de', type: 'expression', jp: '一人で', kanji: '一人で', hiragana: 'ひとりで', reading: 'hitori de', meaning: 'بمفرده' },
    { id: 'jouzu_ni', type: 'adverb', jp: '上手に', kanji: '上手に', hiragana: 'じょうずに', reading: 'jouzu ni', meaning: 'بمهارة' },
    { id: 'mainichi3', type: 'adverb', jp: '毎日', kanji: '毎日', hiragana: 'まいにち', reading: 'mainichi', meaning: 'كل يوم' },
    { id: 'gaikoku', type: 'noun', jp: '外国', kanji: '外国', hiragana: 'がいこく', reading: 'gaikoku', meaning: 'بلد أجنبي' },
    { id: 'sukii', type: 'noun', jp: 'スキー', hiragana: 'スキー', reading: 'sukii', meaning: 'تزلج' },
    { id: 'ryouri_shimasu', type: 'verb', jp: '料理します', kanji: '料理します', hiragana: 'りょうりします', reading: 'ryouri shimasu', meaning: 'يطبخ' },
  ],
  grammar: [
    {
      title: 'تكوين صيغة القاموس (辞書形)',
      pattern: 'ます‐form → 辞書形',
      particle: '辞書形',
      howItWorks: 'صيغة القاموس هي الشكل الأساسي للفعل كما يظهر في القاموس. للأفعال من المجموعة 2 (る-verbs): نستبدل ます بـ る. للمجموعة 1 (う-verbs): نستبدل い (قبل ます) بحرف من عمود う المقابل (مثل きます→く، みます→む).',
      explanation: 'الأفعال الشاذة: します→する، 来ます→来る (くる). مثال تحويل: 飲みます→飲む، 待ちます→待つ، 書きます→書く، 食べます→食べる، 見ます→見る.',
      example: { jp: '飲みます → 飲む', romaji: 'nomimasu → nomu', ar: 'يشرب → (صيغة القاموس)' },
      exercises: [
        {
          type: 'build',
          ar: 'حول 食べます إلى صيغة القاموس.',
          words: ['食べます', '→', '食べる'],
          particles: [],
          answer: '食べます → 食べる',
        },
        {
          type: 'fill',
          ar: '読みます في صيغة القاموس هي؟',
          sentence: '読みます → ___',
          options: ['読む', '読みる', '読く', '読みむ'],
          answer: '読む',
        },
        {
          type: 'meaning',
          sentence: '来ます → 来る (くる)',
          particle: '辞書形',
          options: ['来ます فعل شاذ، صيغة القاموس هي 来る (くる).', '来ます من المجموعة الأولى مثل 飲みます.', '来ます لا تتغير في صيغة القاموس.', '来ます تصبح 来ます る.'],
          answer: '来ます فعل شاذ، صيغة القاموس هي 来る (くる).',
        },
        {
          type: 'error',
          ar: 'حول 話します إلى صيغة القاموس.',
          options: ['話す', '話する', '話します る', '話さ'],
          answer: '話す',
        },
      ],
    },
    {
      title: '〜ことができます — التعبير عن القدرة',
      pattern: 'فعل (辞書形) + ことができます。',
      particle: 'ことができます',
      howItWorks: 'تستخدم لوصف القدرة أو المهارة في فعل شيء. الفعل يكون بصيغة القاموس متبوعا بـ ことができます (حرفيا: "يمكن فعل أمر...").',
      explanation: 'مع الأسماء التي تدل على نشاط (مثل 運転、料理)، يمكن الاختصار إلى اسم + が できます مباشرة دون こと.',
      example: { jp: '私 は 漢字 を 読む ことが できます。', romaji: 'Watashi wa kanji o yomu koto ga dekimasu.', ar: 'أستطيع قراءة الكانجي.' },
      exercises: [
        {
          type: 'build',
          ar: 'أستطيع قيادة السيارة.',
          words: ['私', 'は', '車', 'を', '運転する', 'ことが', 'できます', '。'],
          particles: ['は', 'を', 'が'],
          answer: '私 は 車 を 運転する ことが できます 。',
        },
        {
          type: 'fill',
          ar: 'أستطيع عزف البيانو.',
          sentence: '私 は ピアノ ___ 弾く ことが できます。',
          options: ['を', 'が', 'に', 'は'],
          answer: 'を',
        },
        {
          type: 'meaning',
          sentence: '弟 は まだ 一人 で 食べる ことが できません。',
          particle: 'ことができます',
          options: ['أخي الصغير لا يستطيع الأكل بمفرده بعد.', 'أخي الصغير يأكل بسرعة.', 'أخي الصغير لا يحب الأكل.', 'أخي الصغير يأكل بمفرده دائما.'],
          answer: 'أخي الصغير لا يستطيع الأكل بمفرده بعد.',
        },
        {
          type: 'error',
          ar: 'هل تستطيع السباحة؟',
          options: ['泳ぐ ことが できます か。', '泳ぎ ことが できます か。', '泳ぐ こと できますが か。'],
          answer: '泳ぐ ことが できます か。',
        },
      ],
    },
    {
      title: '辞書形 + まえに／あとで — قبل وبعد بصيغة القاموس',
      pattern: 'فعل (辞書形) + まえに ／ فعل (た形) + あとで',
      particle: 'まえに・あとで',
      howItWorks: 'まえに تأتي بعد الفعل في صيغة القاموس دائما (حتى لو كان السياق ماضيا). أما あとで فتأتي بعد الفعل في صيغة الماضي العادي (た形).',
      explanation: 'مقارنة: 食べる まえに (قبل الأكل) - صيغة قاموس دائما. 食べた あとで (بعد الأكل) - صيغة ماضي عادي.',
      example: { jp: '日本 へ 来る まえに、 日本語 を 勉強しました。', romaji: 'Nihon e kuru mae ni, nihongo o benkyou shimashita.', ar: 'قبل أن آتي إلى اليابان، درست اليابانية.' },
      exercises: [
        {
          type: 'build',
          ar: 'بعد أن أصل إلى المطار، سأتصل بك.',
          words: ['空港', 'に', '着いた', 'あとで', '、', '電話', 'します', '。'],
          particles: ['に', 'あとで'],
          answer: '空港 に 着いた あとで 、 電話 します 。',
        },
        {
          type: 'fill',
          ar: 'قبل أن أنام، أقرأ كتابا.',
          sentence: '寝る ___、 本 を 読みます。',
          options: ['まえに', 'あとで', 'まえ', 'からに'],
          answer: 'まえに',
        },
        {
          type: 'meaning',
          sentence: '映画 を 見た あとで、 晩ご飯 を 食べました。',
          particle: 'あとで',
          options: ['تناولت العشاء بعد مشاهدة الفيلم.', 'شاهدت الفيلم بعد العشاء.', 'لم أشاهد الفيلم ولم آكل.', 'أشاهد الفيلم أثناء الأكل.'],
          answer: 'تناولت العشاء بعد مشاهدة الفيلم.',
        },
        {
          type: 'error',
          ar: 'قبل السفر، أحصل على التأشيرة.',
          options: ['旅行 する まえに、 ビザ を もらいます。', '旅行 した まえに、 ビザ を もらいます。', '旅行 する あとで、 ビザ を もらいます まえに。'],
          answer: '旅行 する まえに、 ビザ を もらいます。',
        },
      ],
    },
    {
      title: '〜と — الشرط التلقائي/الإجراء',
      pattern: 'فعل/جملة (辞書形) + と + نتيجة (ثابتة/تلقائية)',
      particle: 'と',
      howItWorks: 'تستخدم と لربط شرط بنتيجة تحدث تلقائيا أو دائما عند تحقق الشرط، مثل التعليمات والقوانين الطبيعية والاتجاهات.',
      explanation: 'لا تستخدم と عندما تكون النتيجة إرادية أو أمرا أو دعوة (في تلك الحالات نستخدم たら أو ば في دروس لاحقة).',
      example: { jp: 'この ボタン を 押す と、 切符 が 出ます。', romaji: 'Kono botan o osu to, kippu ga demasu.', ar: 'إذا ضغطت هذا الزر، تخرج التذكرة.' },
      exercises: [
        {
          type: 'build',
          ar: 'إذا انعطفت يمينا، يوجد البنك.',
          words: ['右', 'に', '曲がる', 'と', '、', '銀行', 'が', 'あります', '。'],
          particles: ['に', 'と', 'が'],
          answer: '右 に 曲がる と 、 銀行 が あります 。',
        },
        {
          type: 'fill',
          ar: 'إذا ضغطت هذا الزر، يخرج الماء.',
          sentence: 'この ボタン を 押す ___、 水 が 出ます。',
          options: ['と', 'なら', 'ても', 'から'],
          answer: 'と',
        },
        {
          type: 'meaning',
          sentence: 'まっすぐ 行く と、 信号 が あります。',
          particle: 'と',
          options: ['إذا سرت مباشرة، توجد إشارة مرور.', 'لا توجد إشارة مرور في الطريق المستقيم.', 'سر مباشرة بعد الإشارة.', 'الإشارة معطلة.'],
          answer: 'إذا سرت مباشرة، توجد إشارة مرور.',
        },
        {
          type: 'error',
          ar: 'إذا شربت الكثير من القهوة، لا أستطيع النوم.',
          options: ['コーヒー を たくさん 飲む と、 寝られません。', 'コーヒー を たくさん 飲む たら、 寝られません。', 'コーヒー を たくさん 飲みます と、 寝られません。'],
          answer: 'コーヒー を たくさん 飲む と、 寝られません。',
        },
      ],
    },
  ],
  examples: [
    { jp: '私 の 趣味 は 料理 を する ことです。', romaji: 'Watashi no shumi wa ryouri o suru koto desu.', ar: 'هوايتي هي الطبخ.', en: 'My hobby is cooking.' },
    { jp: '田中さん は 中国語 を 話す ことが できます。', romaji: 'Tanaka-san wa chuugokugo o hanasu koto ga dekimasu.', ar: 'السيد تاناكا يستطيع التحدث بالصينية.', en: 'Mr. Tanaka can speak Chinese.' },
    { jp: '私 は スキー が できます。', romaji: 'Watashi wa sukii ga dekimasu.', ar: 'أستطيع التزلج.', en: 'I can ski.' },
    { jp: '出かける まえに、 窓 を 閉めました。', romaji: 'Dekakeru mae ni, mado o shimemashita.', ar: 'قبل الخروج، أغلقت النافذة.', en: 'Before going out, I closed the window.' },
    { jp: '勉強した あとで、 ゲーム を します。', romaji: 'Benkyou shita ato de, geemu o shimasu.', ar: 'بعد أن أدرس، ألعب لعبة.', en: 'After studying, I’ll play a game.' },
    { jp: 'この 道 を まっすぐ 行く と、 駅 が あります。', romaji: 'Kono michi o massugu iku to, eki ga arimasu.', ar: 'إذا سرت مباشرة في هذا الطريق، توجد المحطة.', en: 'If you go straight on this road, there’s the station.' },
    { jp: '春 に なる と、 花 が 咲きます。', romaji: 'Haru ni naru to, hana ga sakimasu.', ar: 'عندما يأتي الربيع، تتفتح الزهور.', en: 'When spring comes, flowers bloom.' },
    { jp: '私 は まだ 漢字 を 書く ことが できません。', romaji: 'Watashi wa mada kanji o kaku koto ga dekimasen.', ar: 'لا أستطيع كتابة الكانجي بعد.', en: 'I can’t write kanji yet.' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 私 は 泳ぐ ことが できます。', answer: 'أستطيع السباحة.', hint: 'ことができます للقدرة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 食べる まえに、 手 を 洗います。', answer: 'أغسل يدي قبل الأكل.', hint: 'まえに بصيغة القاموس' },
    { type: 'complete', prompt: 'أكمل: 飲みます → ___ (辞書形)', answer: '飲む', hint: 'تحويل إلى صيغة القاموس' },
    { type: 'complete', prompt: 'أكمل: 私 は ピアノ を 弾く こと ___ できます。', answer: 'が', hint: 'علامة القدرة' },
    { type: 'complete', prompt: 'أكمل: 左 に 曲がる ___、 学校 が あります。', answer: 'と', hint: 'الشرط التلقائي' },
    { type: 'order', prompt: 'رتب: できます / が / 運転する / こと / 私 / は / 車 / を', answer: '私 は 車 を 運転する ことが できます。', hint: 'القدرة' },
    { type: 'order', prompt: 'رتب: あとで / レポート / 書いた / 寝ます / を', answer: 'レポート を 書いた あとで 寝ます。', hint: 'あとで بصيغة الماضي' },
    { type: 'answer', prompt: '何 が できます か。 (日本語を話すこと)', answer: '日本語 を 話す ことが できます。', hint: 'الإجابة بالقدرة' },
    { type: 'answer', prompt: 'いつ 手 を 洗いますか。 (食べるまえに)', answer: '食べる まえに 手 を 洗います。', hint: 'الإجابة بـ まえに' },
  ],
  videos: [],
}
