export const lessonTen = {
  id: 10,
  title: { ar: 'الأرقام وأدوات العد', en: 'Numbers and Counters' },
  focus: 'الأرقام، أدوات العد (つ/人/枚/本/冊)، وأداة الحصر だけ',
  vocab: [
    { id: 'hitotsu', type: 'counter', jp: 'ひとつ', kanji: '一つ', hiragana: 'ひとつ', reading: 'hitotsu', meaning: 'واحد (شيء عام)' },
    { id: 'futatsu', type: 'counter', jp: 'ふたつ', kanji: '二つ', hiragana: 'ふたつ', reading: 'futatsu', meaning: 'اثنان (شيء عام)' },
    { id: 'mittsu', type: 'counter', jp: 'みっつ', kanji: '三つ', hiragana: 'みっつ', reading: 'mittsu', meaning: 'ثلاثة (شيء عام)' },
    { id: 'yottsu', type: 'counter', jp: 'よっつ', kanji: '四つ', hiragana: 'よっつ', reading: 'yottsu', meaning: 'أربعة (شيء عام)' },
    { id: 'itsutsu', type: 'counter', jp: 'いつつ', kanji: '五つ', hiragana: 'いつつ', reading: 'itsutsu', meaning: 'خمسة (شيء عام)' },
    { id: 'muttsu', type: 'counter', jp: 'むっつ', kanji: '六つ', hiragana: 'むっつ', reading: 'muttsu', meaning: 'ستة (شيء عام)' },
    { id: 'nanatsu', type: 'counter', jp: 'ななつ', kanji: '七つ', hiragana: 'ななつ', reading: 'nanatsu', meaning: 'سبعة (شيء عام)' },
    { id: 'yattsu', type: 'counter', jp: 'やっつ', kanji: '八つ', hiragana: 'やっつ', reading: 'yattsu', meaning: 'ثمانية (شيء عام)' },
    { id: 'kokonotsu', type: 'counter', jp: 'ここのつ', kanji: '九つ', hiragana: 'ここのつ', reading: 'kokonotsu', meaning: 'تسعة (شيء عام)' },
    { id: 'tou', type: 'counter', jp: 'とお', kanji: '十', hiragana: 'とお', reading: 'tou', meaning: 'عشرة (شيء عام)' },
    { id: 'ikutsu', type: 'question-word', jp: 'いくつ', hiragana: 'いくつ', reading: 'ikutsu', meaning: 'كم (للعدد العام)' },
    { id: 'hitori', type: 'counter', jp: '一人', kanji: '一人', hiragana: 'ひとり', reading: 'hitori', meaning: 'شخص واحد' },
    { id: 'futari', type: 'counter', jp: '二人', kanji: '二人', hiragana: 'ふたり', reading: 'futari', meaning: 'شخصان' },
    { id: 'sannin', type: 'counter', jp: '三人', kanji: '三人', hiragana: 'さんにん', reading: 'sannin', meaning: 'ثلاثة أشخاص' },
    { id: 'nannin', type: 'question-word', jp: '何人', kanji: '何人', hiragana: 'なんにん', reading: 'nannin', meaning: 'كم شخصا' },
    { id: 'ichimai', type: 'counter', jp: '一枚', kanji: '一枚', hiragana: 'いちまい', reading: 'ichimai', meaning: 'ورقة/قطعة مسطحة واحدة' },
    { id: 'nanmai', type: 'question-word', jp: '何枚', kanji: '何枚', hiragana: 'なんまい', reading: 'nanmai', meaning: 'كم ورقة/قطعة مسطحة' },
    { id: 'ippon', type: 'counter', jp: '一本', kanji: '一本', hiragana: 'いっぽん', reading: 'ippon', meaning: 'شيء أسطواني واحد (قلم/زجاجة)' },
    { id: 'nanbon', type: 'question-word', jp: '何本', kanji: '何本', hiragana: 'なんぼん', reading: 'nanbon', meaning: 'كم شيئا أسطوانيا' },
    { id: 'issatsu', type: 'counter', jp: '一冊', kanji: '一冊', hiragana: 'いっさつ', reading: 'issatsu', meaning: 'كتاب واحد' },
    { id: 'nansatsu', type: 'question-word', jp: '何冊', kanji: '何冊', hiragana: 'なんさつ', reading: 'nansatsu', meaning: 'كم كتابا' },
    { id: 'dake', type: 'particle', jp: 'だけ', hiragana: 'だけ', reading: 'dake', meaning: 'فقط' },
    { id: 'zenbu', type: 'noun', jp: '全部で', kanji: '全部で', hiragana: 'ぜんぶで', reading: 'zenbu de', meaning: 'بالمجموع' },
    { id: 'kitte', type: 'object', jp: '切手', kanji: '切手', hiragana: 'きって', reading: 'kitte', meaning: 'طابع بريد' },
    { id: 'kami', type: 'object', jp: '紙', kanji: '紙', hiragana: 'かみ', reading: 'kami', meaning: 'ورق' },
  ],
  grammar: [
    {
      title: 'العدّ العام (ひとつ〜とお)',
      pattern: 'اسم + を/が + عدد عام (ひとつ〜とお)',
      particle: 'いくつ',
      howItWorks: 'تستخدم الأعداد اليابانية الأصلية ひとつ، ふたつ، みっつ... عند عد الأشياء العامة دون أداة عد محددة، خصوصا في المحادثة وعند التسوق.',
      explanation: 'هذه الأعداد تأتي بعد المفعول مباشرة دون を في العادة (りんごをふたつください）، أو تستبدل を بالكامل.',
      example: { jp: 'りんご を ふたつ ください。', romaji: 'Ringo o futatsu kudasai.', ar: 'أعطني تفاحتين من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'كم تفاحة لديك؟',
          words: ['りんご', 'は', 'いくつ', 'あります', 'か', '。'],
          particles: [],
          answer: 'りんご は いくつ あります か 。',
        },
        {
          type: 'fill',
          ar: 'أعطني ثلاث برتقالات من فضلك.',
          sentence: 'みかん を ___ ください。',
          options: ['みっつ', 'さんにん', '三枚', 'さんさつ'],
          answer: 'みっつ',
        },
        {
          type: 'meaning',
          sentence: 'パン を いつつ 買いました。',
          particle: 'いつつ',
          options: ['اشتريت خمس قطع من الخبز.', 'اشتريت خبزا واحدا فقط.', 'بعت خمس قطع من الخبز.', 'الخبز يكفي لخمسة أشخاص.'],
          answer: 'اشتريت خمس قطع من الخبز.',
        },
        {
          type: 'error',
          ar: 'لدي ست بيضات.',
          options: ['卵 が むっつ あります。', '卵 が 六人 あります。', '卵 が むっつ います。'],
          answer: '卵 が むっつ あります。',
        },
      ],
    },
    {
      title: '助数詞 (人) — عدّ الأشخاص',
      pattern: 'عدد + 人 + います／の + اسم',
      particle: '人',
      howItWorks: 'لعد الأشخاص نستخدم 人. الاستثناءات: 一人 (hitori) و 二人 (futari)، ومن ثلاثة فما فوق نضيف 人 إلى الرقم الصيني العادي (三人، 四人...).',
      explanation: 'السؤال يكون بـ 何人 (كم شخصا).',
      example: { jp: '家族 は 何人 です か。 ／ 四人 です。', romaji: 'Kazoku wa nannin desu ka. / Yonin desu.', ar: 'كم عدد أفراد عائلتك؟ / أربعة أشخاص.' },
      exercises: [
        {
          type: 'build',
          ar: 'يوجد طالبان في الفصل.',
          words: ['教室', 'に', '学生', 'が', '二人', 'います', '。'],
          particles: ['に', 'が'],
          answer: '教室 に 学生 が 二人 います 。',
        },
        {
          type: 'fill',
          ar: 'كم عدد الأشخاص في عائلتك؟',
          sentence: '家族 は ___ です か。',
          options: ['何人', 'いくつ', '何枚', '何冊'],
          answer: '何人',
        },
        {
          type: 'meaning',
          sentence: '兄弟 は 三人 います。',
          particle: '人',
          options: ['لدي ثلاثة إخوة وأخوات.', 'عمري ثلاث سنوات.', 'لدي ثلاثة كتب.', 'وصل ثلاثة أشخاص.'],
          answer: 'لدي ثلاثة إخوة وأخوات.',
        },
        {
          type: 'error',
          ar: 'يوجد شخص واحد فقط.',
          options: ['一人 だけ います。', '一つ だけ います。', '一人 だけ あります。'],
          answer: '一人 だけ います。',
        },
      ],
    },
    {
      title: '助数詞 (枚・本) — الأشياء المسطحة والأسطوانية',
      pattern: 'عدد + 枚／本',
      particle: '枚・本',
      howItWorks: '枚 (まい) للأشياء المسطحة الرقيقة (ورق، طوابع، تذاكر، قمصان). 本 (ほん/ぼん/ぽん) للأشياء الطويلة الأسطوانية (أقلام، زجاجات، أشجار، أفلام).',
      explanation: 'تنبيه على تغير النطق في 本: 一本(いっぽん)、三本(さんぼん)、何本(なんぼん) - تغيرات صوتية يجب حفظها.',
      example: { jp: '切手 を 三枚 ください。', romaji: 'Kitte o sanmai kudasai.', ar: 'أعطني ثلاثة طوابع من فضلك.' },
      exercises: [
        {
          type: 'build',
          ar: 'اشتريت قلمين.',
          words: ['ペン', 'を', '二本', '買いました', '。'],
          particles: ['を'],
          answer: 'ペン を 二本 買いました 。',
        },
        {
          type: 'fill',
          ar: 'كم ورقة تحتاج؟',
          sentence: '紙 が ___ 要ります か。',
          options: ['何枚', '何本', '何人', '何冊'],
          answer: '何枚',
        },
        {
          type: 'meaning',
          sentence: 'ビール を 一本 もらいました。',
          particle: '本',
          options: ['استلمت زجاجة بيرة واحدة.', 'استلمت بيرة كل يوم.', 'بعت زجاجة بيرة.', 'أحب البيرة.'],
          answer: 'استلمت زجاجة بيرة واحدة.',
        },
        {
          type: 'error',
          ar: 'هناك تذكرتان على الطاولة.',
          options: ['テーブル の 上 に 切符 が 二枚 あります。', 'テーブル の 上 に 切符 が 二本 あります。', 'テーブル の 上 に 切符 が 二人 います。'],
          answer: 'テーブル の 上 に 切符 が 二枚 あります。',
        },
      ],
    },
    {
      title: '助数詞 (冊) と だけ — الكتب والحصر',
      pattern: 'عدد + 冊 ／ اسم + だけ',
      particle: '冊・だけ',
      howItWorks: '冊 (さつ) يُستخدم لعد الكتب والمجلات والدفاتر. أما だけ فتعني "فقط" وتأتي بعد الاسم مباشرة (أو بعد عدد + أداة عد) للدلالة على الحصر.',
      explanation: 'مثال: 本 を 一冊 だけ 買いました (اشتريت كتابا واحدا فقط). だけ يمكن أن تحل محل を/が أحيانا.',
      example: { jp: '本 を 三冊 読みました。', romaji: 'Hon o sansatsu yomimashita.', ar: 'قرأت ثلاثة كتب.' },
      exercises: [
        {
          type: 'build',
          ar: 'لدي قاموس واحد فقط.',
          words: ['辞書', 'が', '一冊', 'だけ', 'あります', '。'],
          particles: ['が', 'だけ'],
          answer: '辞書 が 一冊 だけ あります 。',
        },
        {
          type: 'fill',
          ar: 'كم كتابا قرأت هذا الشهر؟',
          sentence: '今月 本 を ___ 読みました か。',
          options: ['何冊', '何枚', '何本', 'いくつ'],
          answer: '何冊',
        },
        {
          type: 'meaning',
          sentence: '今日 は コーヒー だけ 飲みました。',
          particle: 'だけ',
          options: ['شربت القهوة فقط اليوم.', 'لم أشرب القهوة اليوم.', 'القهوة فقط لذيذة.', 'شربت القهوة والشاي.'],
          answer: 'شربت القهوة فقط اليوم.',
        },
        {
          type: 'error',
          ar: 'اشتريت دفترين فقط.',
          options: ['ノート を 二冊 だけ 買いました。', 'ノート を 二枚 だけ 買いました。', 'ノート だけ を 二冊 買いました。'],
          answer: 'ノート を 二冊 だけ 買いました。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'りんご を みっつ ください。', romaji: 'Ringo o mittsu kudasai.', ar: 'أعطني ثلاث تفاحات من فضلك.', en: 'Three apples, please.' },
    { jp: '家族 は 五人 です。', romaji: 'Kazoku wa gonin desu.', ar: 'عائلتي مكونة من خمسة أشخاص.', en: 'My family has five people.' },
    { jp: '紙 を 二枚 もらいました。', romaji: 'Kami o nimai moraimashita.', ar: 'استلمت ورقتين.', en: 'I received two sheets of paper.' },
    { jp: '木 が 三本 あります。', romaji: 'Ki ga sanbon arimasu.', ar: 'توجد ثلاث أشجار.', en: 'There are three trees.' },
    { jp: '雑誌 を 二冊 買いました。', romaji: 'Zasshi o nisatsu kaimashita.', ar: 'اشتريت مجلتين.', en: 'I bought two magazines.' },
    { jp: '今日 は パン を 一つ だけ 食べました。', romaji: 'Kyou wa pan o hitotsu dake tabemashita.', ar: 'أكلت قطعة خبز واحدة فقط اليوم.', en: 'I only ate one piece of bread today.' },
    { jp: '全部 で 五千円 です。', romaji: 'Zenbu de gosen-en desu.', ar: 'المجموع خمسة آلاف ين.', en: 'That’s 5000 yen in total.' },
    { jp: '切符 は 何枚 要ります か。', romaji: 'Kippu wa nanmai irimasu ka.', ar: 'كم تذكرة تحتاج؟', en: 'How many tickets do you need?' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: みかん を ふたつ ください。', answer: 'أعطني برتقالتين من فضلك.', hint: 'العدد العام' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 兄弟 が 二人 います。', answer: 'لدي أخوان (إخوة).', hint: 'عدّ الأشخاص' },
    { type: 'complete', prompt: 'أكمل: ビール を 一___ ください。 (زجاجة)', answer: '本', hint: 'عدّ الأشياء الأسطوانية' },
    { type: 'complete', prompt: 'أكمل: 本 が 何___ あります か。', answer: '冊', hint: 'عدّ الكتب' },
    { type: 'complete', prompt: 'أكمل: 今日 は 一時間 ___ 勉強 しました。 (فقط)', answer: 'だけ', hint: 'الحصر' },
    { type: 'order', prompt: 'رتب: ください / りんご / みっつ / を', answer: 'りんご を みっつ ください。', hint: 'الطلب بالعدد العام' },
    { type: 'order', prompt: 'رتب: です / 家族 / は / 何人 / か', answer: '家族 は 何人 です か。', hint: 'السؤال عن عدد الأشخاص (لاحظ か)' },
    { type: 'answer', prompt: 'りんご を いくつ 買いました か。 (5)', answer: 'りんご を いつつ 買いました。', hint: 'الإجابة بالعدد العام' },
    { type: 'answer', prompt: '兄弟 は 何人 です か。 (3)', answer: '三人 です。', hint: 'الإجابة بعدّ الأشخاص' },
  ],
  videos: [],
}
