export const lessonTwenty = {
  id: 20,
  title: { ar: 'الشرح والاحتمال والتوقيت', en: 'Explanation, Probability, and Timing' },
  focus: '普通形 + んです للشرح، でしょう للاحتمال، و〜とき للتعبير عن "عندما"',
  vocab: [
    { id: 'kaze_hikimasu', type: 'expression', jp: '風邪をひきます', kanji: '風邪をひきます', hiragana: 'かぜをひきます', reading: 'kaze o hikimasu', meaning: 'يصاب بالزكام' },
    { id: 'kaoiro', type: 'noun', jp: '顔色', kanji: '顔色', hiragana: 'かおいろ', reading: 'kaoiro', meaning: 'لون الوجه (الحالة الصحية الظاهرة)' },
    { id: 'genki_ga_nai', type: 'expression', jp: '元気がない', kanji: '元気がない', hiragana: 'げんきがない', reading: 'genki ga nai', meaning: 'لا يبدو نشيطا' },
    { id: 'saifu_otoshimasu', type: 'expression', jp: '財布を落とします', kanji: '財布を落とします', hiragana: 'さいふをおとします', reading: 'saifu o otoshimasu', meaning: 'يُسقط محفظته' },
    { id: 'atama_itai', type: 'expression', jp: '頭が痛い', kanji: '頭が痛い', hiragana: 'あたまがいたい', reading: 'atama ga itai', meaning: 'رأسه يؤلمه' },
    { id: 'deshou', type: 'expression', jp: 'でしょう', hiragana: 'でしょう', reading: 'deshou', meaning: 'على الأرجح / أليس كذلك' },
    { id: 'toki', type: 'particle', jp: 'とき', kanji: '時', hiragana: 'とき', reading: 'toki', meaning: 'عندما / وقت' },
    { id: 'kodomo_no_toki', type: 'expression', jp: '子供のとき', kanji: '子供のとき', hiragana: 'こどものとき', reading: 'kodomo no toki', meaning: 'عندما كنت طفلا' },
    { id: 'samui_toki', type: 'expression', jp: '寒いとき', kanji: '寒いとき', hiragana: 'さむいとき', reading: 'samui toki', meaning: 'عندما يكون الجو باردا' },
    { id: 'tenkiyohou', type: 'noun', jp: '天気予報', kanji: '天気予報', hiragana: 'てんきよほう', reading: 'tenkiyohou', meaning: 'نشرة الطقس' },
    { id: 'haremasu', type: 'verb', jp: '晴れます', kanji: '晴れます', hiragana: 'はれます', reading: 'haremasu', meaning: 'يصبح صحوا (الطقس)' },
    { id: 'kumorimasu', type: 'verb', jp: '曇ります', kanji: '曇ります', hiragana: 'くもります', reading: 'kumorimasu', meaning: 'يصبح غائما' },
    { id: 'amefuru', type: 'expression', jp: '雨が降ります', kanji: '雨が降ります', hiragana: 'あめがふります', reading: 'ame ga furimasu', meaning: 'تمطر' },
    { id: 'guai_ga_warui', type: 'expression', jp: '具合が悪い', kanji: '具合が悪い', hiragana: 'ぐあいがわるい', reading: 'guai ga warui', meaning: 'حالته الصحية سيئة' },
    { id: 'byouin2', type: 'place', jp: '病院', kanji: '病院', hiragana: 'びょういん', reading: 'byouin', meaning: 'مستشفى' },
    { id: 'kusuri2', type: 'noun', jp: '薬', kanji: '薬', hiragana: 'くすり', reading: 'kusuri', meaning: 'دواء' },
    { id: 'isogashisou', type: 'expression', jp: '忙しそう', kanji: '忙しそう', hiragana: 'いそがしそう', reading: 'isogashisou', meaning: 'يبدو مشغولا' },
    { id: 'doushita', type: 'expression', jp: 'どうしたんですか', hiragana: 'どうしたんですか', reading: 'doushitan desu ka', meaning: 'ماذا حدث؟ ما الخطب؟' },
    { id: 'jiko', type: 'noun', jp: '事故', kanji: '事故', hiragana: 'じこ', reading: 'jiko', meaning: 'حادث' },
    { id: 'jikan2', type: 'noun', jp: '時間', kanji: '時間', hiragana: 'じかん', reading: 'jikan', meaning: 'وقت' },
    { id: 'hima', type: 'na-adjective', jp: '暇', kanji: '暇', hiragana: 'ひま', reading: 'hima', meaning: 'فارغ (وقت)' },
    { id: 'umaretokoro', type: 'noun', jp: '生まれたところ', kanji: '生まれたところ', hiragana: 'うまれたところ', reading: 'umareta tokoro', meaning: 'مكان الولادة' },
    { id: 'apaato', type: 'place', jp: 'アパート', hiragana: 'アパート', reading: 'apaato', meaning: 'شقة' },
    { id: 'denwa_shimasu', type: 'verb', jp: '電話します', kanji: '電話します', hiragana: 'でんわします', reading: 'denwa shimasu', meaning: 'يتصل هاتفيا' },
  ],
  grammar: [
    {
      title: '普通形 + んです — السؤال عن السبب وتقديم تفسير',
      pattern: 'جملة (普通形) + んです。',
      particle: 'んです',
      howItWorks: 'تستخدم んです (اختصار の+です) لإضافة لمسة من التفسير أو طلب توضيح حول موقف ملاحظ. تأتي بعد الجملة بصيغتها العادية (普通形)، مع إضافة な قبل んです في حالة الأسماء وصفات な.',
      explanation: 'تستخدم غالبا في الأسئلة عند ملاحظة شيء غير معتاد: 顔色 が 悪い ですね。 どうしたんですか。 (لونك شاحب، ماذا حدث؟). والإجابة أيضا تأخذ んです: 風邪 を ひいたんです (أصبت بالزكام).',
      example: { jp: 'A: 元気 が ないですね。 どうしたんですか。 B: 財布 を 落としたんです。', romaji: 'Genki ga nai desu ne. Doushitan desu ka. / Saifu o otoshitan desu.', ar: 'تبدو غير نشيط، ماذا حدث؟ / أسقطت محفظتي.' },
      exercises: [
        {
          type: 'build',
          ar: 'لماذا تأخرت؟ (السؤال بـ んです)',
          words: ['どうして', '遅れた', 'んです', 'か', '。'],
          particles: [],
          answer: 'どうして 遅れた んです か 。',
        },
        {
          type: 'fill',
          ar: 'أنا مشغول لأن لدي اجتماع. (تفسير)',
          sentence: '会議 が ある ___、 忙しい んです。',
          options: ['から', 'ので', 'のに', 'まで'],
          answer: 'から',
        },
        {
          type: 'meaning',
          sentence: 'A: 今日 は 学校 を 休む んです か。 B: ええ、頭 が 痛い んです。',
          particle: 'んです',
          options: ['نعم، رأسي يؤلمني (لذلك سأتغيب).', 'نعم، سأذهب إلى المدرسة كالعادة.', 'لا، رأسي لا يؤلمني.', 'المدرسة مغلقة اليوم.'],
          answer: 'نعم، رأسي يؤلمني (لذلك سأتغيب).',
        },
        {
          type: 'error',
          ar: 'هذا المكان هادئ (تفسير لماذا أحبه).',
          options: ['ここ は 静か な んです。', 'ここ は 静か んです。', 'ここ は 静か だ んです。'],
          answer: 'ここ は 静か な んです。',
        },
      ],
    },
    {
      title: '〜でしょう — التعبير عن الاحتمال',
      pattern: 'جملة (普通形) + でしょう。',
      particle: 'でしょう',
      howItWorks: 'تستخدم でしょう للتعبير عن توقع أو احتمال "على الأرجح/ربما". غالبا تأتي مع たぶん في بداية الجملة. عند ارتفاع التنغيم في النهاية (でしょう؟)، تصبح بمعنى "أليس كذلك؟" لتأكيد معلومة.',
      explanation: 'مقارنة: と思います رأي شخصي مبني على تفكير، أما でしょう فهي توقع مبني على معلومات (مثل نشرة الطقس) أو حدس عام.',
      example: { jp: '明日 は たぶん 晴れる でしょう。', romaji: 'Ashita wa tabun hareru deshou.', ar: 'غدا سيكون الجو صحوا على الأرجح.' },
      exercises: [
        {
          type: 'build',
          ar: 'سيأتي السيد تاناكا غدا على الأرجح.',
          words: ['田中さん', 'は', '明日', '来る', 'でしょう', '。'],
          particles: ['は'],
          answer: '田中さん は 明日 来る でしょう 。',
        },
        {
          type: 'fill',
          ar: 'سيمطر غدا غالبا.',
          sentence: '明日 は 雨 が ___ でしょう。',
          options: ['降る', '降ります', '降った', '降って'],
          answer: '降る',
        },
        {
          type: 'meaning',
          sentence: 'A: 今日 は 寒い でしょう？ B: ええ、寒い です ね。',
          particle: 'でしょう',
          options: ['الجو بارد اليوم، أليس كذلك؟ / نعم، بارد فعلا.', 'هل سيكون الجو باردا غدا؟', 'الجو ليس باردا أبدا.', 'متى سيصبح الجو باردا؟'],
          answer: 'الجو بارد اليوم، أليس كذلك؟ / نعم، بارد فعلا.',
        },
        {
          type: 'error',
          ar: 'هذا الاختبار صعب على الأرجح.',
          options: ['この 試験 は 難しい でしょう。', 'この 試験 は 難しい です でしょう。', 'この 試験 は 難しいでしょう です。'],
          answer: 'この 試験 は 難しい でしょう。',
        },
      ],
    },
    {
      title: '〜とき — عندما',
      pattern: 'فعل/صفة (普通形) + とき ／ اسم + の + とき',
      particle: 'とき',
      howItWorks: 'تأتي とき بعد جملة فرعية للدلالة على "عندما/وقت...". إذا كان قبلها فعل في صيغة القاموس، فالحدث الرئيسي يحدث في نفس وقت أو بعد الفعل الفرعي. إذا كان فعلا في صيغة الماضي، فالحدث الفرعي يكتمل أولا.',
      explanation: 'مع الأسماء وصفات な: اسم/صفة な + の + とき (例: 暇 な とき - عندما أكون فارغا). مع صفات い: صفة い + とき مباشرة (寒い とき).',
      example: { jp: '日本 へ 行った とき、 富士山 を 見ました。', romaji: 'Nihon e itta toki, Fujisan o mimashita.', ar: 'عندما ذهبت إلى اليابان، رأيت جبل فوجي.' },
      exercises: [
        {
          type: 'build',
          ar: 'عندما كنت طفلا، كنت أعيش في أوساكا.',
          words: ['子供', 'の', 'とき', '、', '大阪', 'に', '住んで', 'いました', '。'],
          particles: ['の', 'に'],
          answer: '子供 の とき 、 大阪 に 住んで いました 。',
        },
        {
          type: 'fill',
          ar: 'عندما يكون الجو باردا، أشرب الشاي الساخن.',
          sentence: '寒い ___、 熱い お茶 を 飲みます。',
          options: ['とき', 'のとき', 'なとき', 'だとき'],
          answer: 'とき',
        },
        {
          type: 'meaning',
          sentence: '暇 な とき、 映画 を 見ます。',
          particle: 'とき',
          options: ['عندما أكون فارغا، أشاهد فيلما.', 'لا أشاهد الأفلام أبدا لأنني مشغول.', 'الفيلم يستغرق وقتا فراغا.', 'سأشاهد فيلما غدا فقط.'],
          answer: 'عندما أكون فارغا، أشاهد فيلما.',
        },
        {
          type: 'error',
          ar: 'عندما أذهب إلى المدرسة، آخذ القطار. (عادة)',
          options: ['学校 へ 行く とき、 電車 に 乗ります。', '学校 へ 行った とき、 電車 に 乗ります。', '学校 へ 行きます とき、 電車 に 乗ります。'],
          answer: '学校 へ 行く とき、 電車 に 乗ります。',
        },
      ],
    },
    {
      title: 'مراجعة شاملة: んです・でしょう・とき',
      pattern: 'مزج القواعد الثلاث في حوار',
      particle: 'مراجعة',
      howItWorks: 'هذه القواعد الثلاث شائعة جدا في المحادثات اليومية: んです للشرح والسؤال عن السبب، でしょう للتوقع، و とき لربط الأحداث بالزمن. التدرب على دمجها في حوارات قصيرة يقوي الفهم.',
      explanation: 'مثال حواري: A: 顔色 が 悪い ですね。どうしたんですか。 B: ちょっと 風邪 を ひいた みたい です。 A: 早く 寝た ほうが いい でしょう。',
      example: { jp: '疲れた とき、 早く 寝た ほうが いい でしょう。', romaji: 'Tsukareta toki, hayaku neta hou ga ii deshou.', ar: 'عندما تكون متعبا، من الأفضل أن تنام مبكرا على الأرجح.' },
      exercises: [
        {
          type: 'build',
          ar: 'عندما أكون متعبا، أشرب الشاي. (تفسير)',
          words: ['疲れた', 'とき', '、', 'お茶', 'を', '飲む', 'んです', '。'],
          particles: ['を'],
          answer: '疲れた とき 、 お茶 を 飲む んです 。',
        },
        {
          type: 'fill',
          ar: 'الاجتماع سينتهي قريبا على الأرجح.',
          sentence: '会議 は もうすぐ 終わる ___。',
          options: ['でしょう', 'んです', 'とき', 'なら'],
          answer: 'でしょう',
        },
        {
          type: 'meaning',
          sentence: 'A: どうして 元気 が ない んです か。 B: 仕事 が 忙しい んです。',
          particle: 'んです',
          options: ['لأن العمل مزدحم (مشغول).', 'لأنني لا أحب العمل.', 'لأنني سأترك العمل.', 'لأن العمل انتهى.'],
          answer: 'لأن العمل مزدحم (مشغول).',
        },
        {
          type: 'error',
          ar: 'عندما أكون مريضا، أذهب إلى المستشفى.',
          options: ['病気 の とき、 病院 へ 行きます。', '病気 とき、 病院 へ 行きます。', '病気 だ とき、 病院 へ 行きます。'],
          answer: '病気 の とき、 病院 へ 行きます。',
        },
      ],
    },
  ],
  examples: [
    { jp: 'A: 顔色 が 悪い です ね。 どうしたんですか。 B: 頭 が 痛い んです。', romaji: 'Kaoiro ga warui desu ne. Doushitan desu ka. / Atama ga itain desu.', ar: 'لون وجهك شاحب، ماذا حدث؟ / رأسي يؤلمني.', en: 'You look pale. What’s wrong? / I have a headache.' },
    { jp: '田中さん は たぶん 知らない でしょう。', romaji: 'Tanaka-san wa tabun shiranai deshou.', ar: 'السيد تاناكا لا يعرف على الأرجح.', en: 'Mr. Tanaka probably doesn’t know.' },
    { jp: '日本 に いた とき、 よく 旅行 しました。', romaji: 'Nihon ni ita toki, yoku ryokou shimashita.', ar: 'عندما كنت في اليابان، كنت أسافر كثيرا.', en: 'When I was in Japan, I traveled a lot.' },
    { jp: 'どうして 来なかった んです か。', romaji: 'Doushite konakattan desu ka.', ar: 'لماذا لم تأت؟', en: 'Why didn’t you come?' },
    { jp: '電車 が 遅れた んです。', romaji: 'Densha ga okuretan desu.', ar: 'تأخر القطار (لهذا السبب).', en: 'The train was late.' },
    { jp: '彼 は きっと 来る でしょう。', romaji: 'Kare wa kitto kuru deshou.', ar: 'هو سيأتي بالتأكيد على الأرجح.', en: 'He’ll definitely come, probably.' },
    { jp: '安い とき、 たくさん 買います。', romaji: 'Yasui toki, takusan kaimasu.', ar: 'عندما تكون الأسعار رخيصة، أشتري الكثير.', en: 'When things are cheap, I buy a lot.' },
    { jp: '暇 な とき、 何 を しますか。', romaji: 'Hima na toki, nani o shimasu ka.', ar: 'ماذا تفعل عندما تكون فارغا؟', en: 'What do you do when you’re free?' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 風邪 を ひいた んです。', answer: 'أصبت بالزكام (لهذا السبب).', hint: 'んです للتفسير' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 明日 は 雨 が 降る でしょう。', answer: 'سيمطر غدا على الأرجح.', hint: 'でしょう للاحتمال' },
    { type: 'complete', prompt: 'أكمل: どうして 食べない ___ か。', answer: 'んです', hint: 'السؤال بـ んです' },
    { type: 'complete', prompt: 'أكمل: 来週 は 忙しい ___。 (احتمال)', answer: 'でしょう', hint: 'でしょう' },
    { type: 'complete', prompt: 'أكمل: 雨 の ___、 傘 を 持って いきます。', answer: 'とき', hint: 'とき' },
    { type: 'order', prompt: 'رتب: んです / どうした / か', answer: 'どうした んです か。', hint: 'السؤال عن السبب' },
    { type: 'order', prompt: 'رتب: でしょう / 明日 / 晴れる / は', answer: '明日 は 晴れる でしょう。', hint: 'الاحتمال' },
    { type: 'answer', prompt: 'どうして 遅れた んです か。 (電車が遅れた)', answer: '電車 が 遅れた んです。', hint: 'الإجابة بـ んです' },
    { type: 'answer', prompt: '子供 の とき、 どこ に 住んで いましたか。 (大阪)', answer: '子供 の とき、 大阪 に 住んで いました。', hint: 'الإجابة بـ とき' },
  ],
  videos: [],
}
