export const lessonFour = {
  id: 4,
  title: { ar: 'الوقت والروتين اليومي', en: 'Time and Daily Routine' },
  focus: 'قول الوقت بالساعة والدقيقة، والتعبير عن الروتين اليومي بـ に و から〜まで و それから',
  dialogue: {
    titleAr: 'كم الساعة؟ — ميلر يسأل عن مواعيد العمل',
    lines: [
      { speaker: 'ميلر', jp: 'すみません。今 何時ですか。', romaji: 'Sumimasen. Ima nanji desu ka.', ar: 'عفوًا، كم الساعة الآن؟' },
      { speaker: 'ساتو', jp: '9時半です。', romaji: 'Ku-ji han desu.', ar: 'التاسعة والنصف.' },
      { speaker: 'ميلر', jp: '会社は 何時に 始まりますか。', romaji: 'Kaisha wa nanji ni hajimarimasu ka.', ar: 'متى يبدأ دوام الشركة؟' },
      { speaker: 'ساتو', jp: '10時に 始まります。', romaji: 'Juu-ji ni hajimarimasu.', ar: 'يبدأ الساعة العاشرة.' },
      { speaker: 'ميلر', jp: '何時に 終わりますか。', romaji: 'Nanji ni owarimasu ka.', ar: 'ومتى ينتهي؟' },
      { speaker: 'ساتو', jp: '午後 6時に 終わります。', romaji: 'Gogo roku-ji ni owarimasu.', ar: 'ينتهي السادسة مساءً.' },
      { speaker: 'ميلر', jp: '毎日 働きますか。', romaji: 'Mainichi hatarakimasu ka.', ar: 'هل تعملين كل يوم؟' },
      { speaker: 'ساتو', jp: 'いいえ、日曜日は 休みです。', romaji: 'Iie, nichiyoubi wa yasumi desu.', ar: 'لا، يوم الأحد عطلة.' },
    ],
  },
  reading: {
    titleAr: 'يومي — روتين موظف',
    sentences: [
      { jp: '私は 毎日 6時に 起きます。', romaji: 'Watashi wa mainichi roku-ji ni okimasu.', ar: 'أستيقظ كل يوم الساعة السادسة.' },
      { jp: '午前 9時から 午後 5時まで 働きます。', romaji: 'Gozen ku-ji kara gogo go-ji made hatarakimasu.', ar: 'أعمل من التاسعة صباحًا إلى الخامسة مساءً.' },
      { jp: 'それから、7時に 晩ご飯です。', romaji: 'Sorekara, shichi-ji ni bangohan desu.', ar: 'بعد ذلك، العشاء الساعة السابعة.' },
      { jp: '今晩も 勉強します。', romaji: 'Konban mo benkyou shimasu.', ar: 'هذا المساء أيضًا سأدرس.' },
      { jp: '12時に 寝ます。', romaji: 'Juuni-ji ni nemasu.', ar: 'أنام الساعة الثانية عشرة.' },
    ],
    questions: [
      { q: 'متى يستيقظ الكاتب؟', options: ['الساعة السادسة', 'الساعة التاسعة', 'الساعة العاشرة'], answer: 'الساعة السادسة' },
      { q: 'من أي ساعة إلى أي ساعة يعمل؟', options: ['من 9 إلى 5', 'من 10 إلى 6', 'من 6 إلى 12'], answer: 'من 9 إلى 5' },
      { q: 'متى ينام؟', options: ['الثانية عشرة', 'السابعة', 'الخامسة'], answer: 'الثانية عشرة' },
    ],
  },
  vocab: [
    { id: 'ima', type: 'time', jp: '今', kanji: '今', hiragana: 'いま', reading: 'ima', meaning: 'الآن' },
    { id: 'nanji', type: 'question-word', jp: '何時', kanji: '何時', hiragana: 'なんじ', reading: 'nan-ji', meaning: 'أي ساعة / كم الساعة' },
    { id: 'nanpun', type: 'question-word', jp: '何分', kanji: '何分', hiragana: 'なんぷん', reading: 'nan-pun', meaning: 'كم دقيقة' },
    { id: 'han', type: 'time', jp: '半', kanji: '半', hiragana: 'はん', reading: 'han', meaning: 'النصف (والنصف)' },
    { id: 'okimasu', type: 'verb', jp: '起きます', kanji: '起きます', hiragana: 'おきます', reading: 'okimasu', meaning: 'يستيقظ' },
    { id: 'nemasu', type: 'verb', jp: '寝ます', kanji: '寝ます', hiragana: 'ねます', reading: 'nemasu', meaning: 'ينام' },
    { id: 'hatarakimasu', type: 'verb', jp: '働きます', kanji: '働きます', hiragana: 'はたらきます', reading: 'hatarakimasu', meaning: 'يعمل' },
    { id: 'yasumimasu', type: 'verb', jp: '休みます', kanji: '休みます', hiragana: 'やすみます', reading: 'yasumimasu', meaning: 'يستريح / يأخذ إجازة' },
    { id: 'benkyoushimasu', type: 'verb', jp: '勉強します', kanji: '勉強します', hiragana: 'べんきょうします', reading: 'benkyou shimasu', meaning: 'يدرس' },
    { id: 'owarimasu', type: 'verb', jp: '終わります', kanji: '終わります', hiragana: 'おわります', reading: 'owarimasu', meaning: 'ينتهي' },
    { id: 'hajimarimasu', type: 'verb', jp: '始まります', kanji: '始まります', hiragana: 'はじまります', reading: 'hajimarimasu', meaning: 'يبدأ' },
    { id: 'gozen', type: 'time', jp: '午前', kanji: '午前', hiragana: 'ごぜん', reading: 'gozen', meaning: 'صباحا (ق.ظ)' },
    { id: 'gogo', type: 'time', jp: '午後', kanji: '午後', hiragana: 'ごご', reading: 'gogo', meaning: 'مساءً (ب.ظ)' },
    { id: 'mainichi', type: 'time', jp: '毎日', kanji: '毎日', hiragana: 'まいにち', reading: 'mainichi', meaning: 'كل يوم' },
    { id: 'kyou', type: 'time', jp: '今日', kanji: '今日', hiragana: 'きょう', reading: 'kyou', meaning: 'اليوم' },
    { id: 'ashita', type: 'time', jp: '明日', kanji: '明日', hiragana: 'あした', reading: 'ashita', meaning: 'غدا' },
    { id: 'kinou', type: 'time', jp: '昨日', kanji: '昨日', hiragana: 'きのう', reading: 'kinou', meaning: 'أمس' },
    { id: 'konban', type: 'time', jp: '今晩', kanji: '今晩', hiragana: 'こんばん', reading: 'konban', meaning: 'هذا المساء' },
    { id: 'kesa', type: 'time', jp: '今朝', kanji: '今朝', hiragana: 'けさ', reading: 'kesa', meaning: 'هذا الصباح' },
    { id: 'bangohan', type: 'food', jp: '晩ご飯', kanji: '晩ご飯', hiragana: 'ばんごはん', reading: 'bangohan', meaning: 'عشاء' },
    { id: 'tanjoubi', type: 'event', jp: '誕生日', kanji: '誕生日', hiragana: 'たんじょうび', reading: 'tanjoubi', meaning: 'عيد ميلاد' },
    { id: 'yasumi', type: 'time', jp: '休み', kanji: '休み', hiragana: 'やすみ', reading: 'yasumi', meaning: 'إجازة / عطلة' },
    { id: 'getsuyoubi', type: 'day', jp: '月曜日', kanji: '月曜日', hiragana: 'げつようび', reading: 'getsuyoubi', meaning: 'الإثنين' },
    { id: 'doyoubi', type: 'day', jp: '土曜日', kanji: '土曜日', hiragana: 'どようび', reading: 'doyoubi', meaning: 'السبت' },
    { id: 'nichiyoubi', type: 'day', jp: '日曜日', kanji: '日曜日', hiragana: 'にちようび', reading: 'nichiyoubi', meaning: 'الأحد' },
  ],
  grammar: [
    {
      title: '今 何時ですか — السؤال عن الوقت',
      pattern: '今 + 何時 ですか。 ／ 〜時〜分 です。',
      particle: '何時',
      howItWorks: 'نسأل عن الوقت بـ 今 何時 ですか (كم الساعة الآن)، ونجيب بالساعة + 分 (دقيقة). لاحظ النطق الخاص لبعض الأرقام مع 分 (يبن، سان بن...).',
      explanation: '何時 = أي ساعة، 何分 = كم دقيقة. الجملة لا تحتاج فعلا — فقط رقم + です.',
      example: { jp: '今 何時 です か。 ／ 9時 半 です。', romaji: 'Ima nanji desu ka. / Kuji han desu.', ar: 'كم الساعة الآن؟ / التاسعة والنصف.' },
      exercises: [
        {
          type: 'build',
          ar: 'كم الساعة الآن؟',
          words: ['今', '何時', 'です', 'か', '。'],
          particles: ['何時'],
          answer: '今 何時 です か 。',
        },
        {
          type: 'fill',
          ar: 'الساعة الثالثة وخمس عشرة دقيقة.',
          sentence: '3時 15 ___ です。',
          options: ['分', '時', '半', 'ぷん'],
          answer: '分',
        },
        {
          type: 'meaning',
          sentence: '今 7時 です。',
          particle: '今',
          options: ['الساعة الآن السابعة.', 'كم الساعة؟', 'الساعة السابعة والنصف.', 'كانت الساعة السابعة.'],
          answer: 'الساعة الآن السابعة.',
        },
        {
          type: 'error',
          ar: 'الساعة العاشرة والنصف.',
          options: ['10時 半 です。', '10時 半 が です。', '半 10時 です。'],
          answer: '10時 半 です。',
        },
      ],
    },
    {
      title: 'に — الزمن المحدد مع الأفعال',
      pattern: 'وقت محدد + に + فعل',
      particle: 'に',
      howItWorks: 'تأتي に بعد الأوقات المحددة بالأرقام (الساعة، التاريخ، اليوم) قبل الفعل، مثل 6時に起きます (أستيقظ الساعة 6). لكن لا تُستخدم مع كلمات مثل 今日/明日/毎日 (بدون に).',
      explanation: 'القاعدة العامة: إذا كان الوقت رقما (ساعة محددة، يوم بالأسبوع، تاريخا) نضيف に، أما الكلمات النسبية مثل 今日 و 毎日 فلا تأخذ に.',
      example: { jp: '私 は 6時 に 起きます。', romaji: 'Watashi wa rokuji ni okimasu.', ar: 'أنا أستيقظ الساعة 6.' },
      exercises: [
        {
          type: 'build',
          ar: 'أنام الساعة 11 مساء.',
          words: ['私', 'は', '11時', 'に', '寝ます', '。'],
          particles: ['に'],
          answer: '私 は 11時 に 寝ます 。',
        },
        {
          type: 'fill',
          ar: 'أعمل كل يوم. (بدون に)',
          sentence: '私 は 毎日 ___ 働きます。',
          options: ['', 'に', 'は', 'の'],
          answer: '',
        },
        {
          type: 'meaning',
          sentence: '会議 は 9時 に 始まります。',
          particle: 'に',
          options: ['الاجتماع يبدأ الساعة 9.', 'الاجتماع انتهى الساعة 9.', 'متى يبدأ الاجتماع؟', 'الاجتماع كل يوم.'],
          answer: 'الاجتماع يبدأ الساعة 9.',
        },
        {
          type: 'error',
          ar: 'أدرس اليابانية الساعة 8 مساء.',
          options: ['私 は 晩 8時 に 日本語 を 勉強します。', '私 は 8時 に 日本語 を 勉強します。', '私 は 8時 日本語 に を 勉強します。'],
          answer: '私 は 8時 に 日本語 を 勉強します。',
        },
      ],
    },
    {
      title: 'から〜まで — من... إلى...',
      pattern: 'وقت 1 + から + وقت 2 + まで + فعل',
      particle: 'から',
      howItWorks: 'から تعني "من" و まで تعني "إلى/حتى". تستخدمان معا لتحديد فترة زمنية (أو مكانية) من بداية إلى نهاية.',
      explanation: 'يمكن استخدام から وحدها (من...) أو まで وحدها (حتى...)، أو الاثنين معا لتحديد بداية ونهاية الفترة.',
      example: { jp: '9時 から 5時 まで 働きます。', romaji: 'Kuji kara goji made hatarakimasu.', ar: 'أعمل من الساعة 9 إلى الساعة 5.' },
      exercises: [
        {
          type: 'build',
          ar: 'أدرس من الساعة 1 إلى الساعة 3.',
          words: ['1時', 'から', '3時', 'まで', '勉強します', '。'],
          particles: ['から', 'まで'],
          answer: '1時 から 3時 まで 勉強します 。',
        },
        {
          type: 'fill',
          ar: 'البنك مفتوح من الإثنين إلى الجمعة.',
          sentence: '銀行 は 月曜日 ___ 金曜日 まで です。',
          options: ['から', 'まで', 'に', 'と'],
          answer: 'から',
        },
        {
          type: 'meaning',
          sentence: '休み は 土曜日 から です。',
          particle: 'から',
          options: ['الإجازة تبدأ من السبت.', 'الإجازة تنتهي يوم السبت.', 'هل الإجازة يوم السبت؟', 'لا إجازة يوم السبت.'],
          answer: 'الإجازة تبدأ من السبت.',
        },
        {
          type: 'error',
          ar: 'أعمل من الساعة 9 صباحا إلى الساعة 6 مساء.',
          options: ['午前 9時 から 午後 6時 まで 働きます。', '午前 9時 まで 午後 6時 から 働きます。', '9時 午前 から 6時 午後 まで 働きます。'],
          answer: '午前 9時 から 午後 6時 まで 働きます。',
        },
      ],
    },
    {
      title: 'それから・も — الترتيب والإضافة الزمنية',
      pattern: '... 。 それから、...。  ／  وقت + も + فعل',
      particle: 'それから',
      howItWorks: 'それから تربط جملتين بمعنى "وبعد ذلك"، تأتي في بداية الجملة الثانية. أما も مع الأوقات فتعني "أيضا" (مثل: 土曜日 も 働きます = أعمل يوم السبت أيضا).',
      explanation: 'それから تستخدم لسرد الأحداث بالترتيب الزمني، بينما も تضيف معلومة مشابهة لمعلومة سابقة.',
      example: { jp: '6時 に 起きます。 それから、シャワーを 浴びます。', romaji: 'Rokuji ni okimasu. Sorekara, shawaa o abimasu.', ar: 'أستيقظ الساعة 6. وبعد ذلك آخذ دشا.' },
      exercises: [
        {
          type: 'build',
          ar: 'أعمل يوم السبت أيضا.',
          words: ['土曜日', 'も', '働きます', '。'],
          particles: ['も'],
          answer: '土曜日 も 働きます 。',
        },
        {
          type: 'fill',
          ar: 'أتناول الإفطار. وبعد ذلك أذهب إلى الشركة.',
          sentence: '朝ご飯 を 食べます。 ___、会社 へ 行きます。',
          options: ['それから', 'から', 'まで', 'も'],
          answer: 'それから',
        },
        {
          type: 'meaning',
          sentence: '日曜日 も 休み です。',
          particle: 'も',
          options: ['يوم الأحد إجازة أيضا.', 'يوم الأحد ليس إجازة.', 'متى الإجازة؟', 'الإجازة يوم الأحد فقط.'],
          answer: 'يوم الأحد إجازة أيضا.',
        },
        {
          type: 'error',
          ar: 'أنام الساعة 12. وقبل ذلك أدرس.',
          options: ['12時 に 寝ます。 それから、勉強します。', '勉強します。 それから、12時 に 寝ます。', '12時 それから に 寝ます。'],
          answer: '勉強します。 それから、12時 に 寝ます。',
        },
      ],
    },
  ],
  examples: [
    { jp: '今 何時 です か。', romaji: 'Ima nanji desu ka.', ar: 'كم الساعة الآن؟', en: 'What time is it now?' },
    { jp: '7時 10分 です。', romaji: 'Shichiji juppun desu.', ar: 'الساعة السابعة وعشر دقائق.', en: 'It is 7:10.' },
    { jp: '私 は 毎朝 6時 に 起きます。', romaji: 'Watashi wa maiasa rokuji ni okimasu.', ar: 'أستيقظ كل صباح الساعة 6.', en: 'I wake up at 6 every morning.' },
    { jp: '銀行 は 9時 から 3時 まで です。', romaji: 'Ginkou wa kuji kara sanji made desu.', ar: 'البنك من الساعة 9 إلى الساعة 3.', en: 'The bank is open from 9 to 3.' },
    { jp: '昨日 は 休み でした。', romaji: 'Kinou wa yasumi deshita.', ar: 'أمس كان إجازة.', en: 'Yesterday was a holiday.' },
    { jp: '今晩 勉強します。 それから、寝ます。', romaji: 'Konban benkyou shimasu. Sorekara, nemasu.', ar: 'سأدرس الليلة. وبعد ذلك سأنام.', en: 'I will study tonight. Then I will sleep.' },
    { jp: '土曜日 も 仕事 です か。', romaji: 'Doyoubi mo shigoto desu ka.', ar: 'هل يوم السبت أيضا عمل؟', en: 'Is Saturday also a workday?' },
    { jp: 'いいえ、土曜日 は 休み です。', romaji: 'Iie, doyoubi wa yasumi desu.', ar: 'لا، يوم السبت إجازة.', en: 'No, Saturday is a holiday.' },
    { jp: 'お誕生日 は いつ です か。', romaji: 'Otanjoubi wa itsu desu ka.', ar: 'متى عيد ميلادك؟', en: 'When is your birthday?' },
  ],
  exercises: [
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 今 9時 半 です。', answer: 'الساعة الآن التاسعة والنصف.', hint: 'ترجمة الجملة' },
    { type: 'choose', prompt: 'اختر المعنى الصحيح: 9時 から 5時 まで 働きます。', answer: 'أعمل من الساعة 9 إلى الساعة 5.', hint: 'ترجمة الجملة' },
    { type: 'complete', prompt: 'أكمل: 私 は 7時 ___ 起きます。', answer: 'に', hint: 'وقت محدد + فعل' },
    { type: 'complete', prompt: 'أكمل: 私 は 毎日 ___ 勉強します。 (بدون أداة)', answer: '', hint: 'الأوقات النسبية بدون に' },
    { type: 'complete', prompt: 'أكمل: 月曜日 ___ 金曜日 まで 仕事 です。', answer: 'から', hint: 'بداية الفترة' },
    { type: 'order', prompt: 'رتب: です / 半 / 9時 / 今', answer: '今 9時 半 です。', hint: 'قول الوقت' },
    { type: 'order', prompt: 'رتب: 起きます / 私 / に / は / 6時', answer: '私 は 6時 に 起きます。', hint: 'وقت + に + فعل' },
    { type: 'answer', prompt: '今 何時 です か。 (10:30)', answer: '10時 半 です。', hint: 'قول الوقت' },
    { type: 'answer', prompt: '銀行 は 何時 から 何時 まで です か。 (9時-3時)', answer: '9時 から 3時 まで です。', hint: 'الفترة الزمنية' },
  ],
  videos: [],
}
