const makeQuestions = (items) =>
  items.map(([kana, answer, ...alts]) => ({
    kana,
    answer,
    options: [...new Set([answer, ...alts])].slice(0, 4),
  }))

const kanaRows = {
  hiragana: [
    ['あ', 'a', 'i', 'u', 'e'], ['い', 'i', 'a', 'ki', 'e'], ['う', 'u', 'o', 'a', 'ku'], ['え', 'e', 'i', 'o', 'ne'], ['お', 'o', 'a', 'u', 'ko'],
    ['か', 'ka', 'ki', 'sa', 'ta'], ['き', 'ki', 'ka', 'shi', 'ni'], ['く', 'ku', 'su', 'tsu', 'nu'], ['け', 'ke', 'se', 'te', 'ne'], ['こ', 'ko', 'so', 'to', 'no'],
    ['さ', 'sa', 'ka', 'ta', 'na'], ['し', 'shi', 'chi', 'ki', 'ji'], ['す', 'su', 'ku', 'tsu', 'zu'], ['せ', 'se', 'ke', 'te', 'ze'], ['そ', 'so', 'ko', 'to', 'zo'],
    ['た', 'ta', 'sa', 'na', 'ka'], ['ち', 'chi', 'shi', 'ni', 'ji'], ['つ', 'tsu', 'su', 'ku', 'zu'], ['て', 'te', 'se', 'ke', 'de'], ['と', 'to', 'so', 'ko', 'do'],
    ['な', 'na', 'ta', 'sa', 'ma'], ['に', 'ni', 'chi', 'mi', 'ki'], ['ぬ', 'nu', 'su', 'mu', 'ku'], ['ね', 'ne', 'te', 'me', 'se'], ['の', 'no', 'to', 'mo', 'so'],
    ['は', 'ha', 'na', 'ma', 'ra'], ['ひ', 'hi', 'ni', 'mi', 'ri'], ['ふ', 'fu', 'su', 'mu', 'nu'], ['へ', 'he', 'se', 'me', 'ne'], ['ほ', 'ho', 'no', 'mo', 'so'],
    ['ま', 'ma', 'ha', 'na', 'ra'], ['み', 'mi', 'hi', 'ni', 'ri'], ['む', 'mu', 'fu', 'nu', 'su'], ['め', 'me', 'he', 'ne', 'se'], ['も', 'mo', 'ho', 'no', 'to'],
    ['や', 'ya', 'ma', 'ra', 'wa'], ['ゆ', 'yu', 'mu', 'ru', 'fu'], ['よ', 'yo', 'mo', 'ro', 'no'],
    ['ら', 'ra', 'ya', 'ma', 'wa'], ['り', 'ri', 'mi', 'hi', 'ni'], ['る', 'ru', 'mu', 'yu', 'fu'], ['れ', 're', 'me', 'he', 'ne'], ['ろ', 'ro', 'mo', 'yo', 'no'],
    ['わ', 'wa', 'ya', 'ra', 'ma'], ['を', 'wo', 'wa', 'yo', 'ro'], ['ん', 'n', 'wa', 'no', 'mu'],
    ['が', 'ga', 'ka', 'da', 'za'], ['ぎ', 'gi', 'ki', 'ji', 'zi'], ['ぐ', 'gu', 'ku', 'zu', 'du'], ['げ', 'ge', 'ke', 'ze', 'de'], ['ご', 'go', 'ko', 'zo', 'do'],
    ['ざ', 'za', 'sa', 'ga', 'da'], ['じ', 'ji', 'shi', 'chi', 'gi'], ['ず', 'zu', 'su', 'gu', 'du'], ['ぜ', 'ze', 'se', 'ge', 'de'], ['ぞ', 'zo', 'so', 'go', 'do'],
    ['だ', 'da', 'ta', 'ga', 'za'], ['ぢ', 'ji', 'chi', 'di', 'gi'], ['づ', 'zu', 'tsu', 'du', 'gu'], ['で', 'de', 'te', 'ge', 'ze'], ['ど', 'do', 'to', 'go', 'zo'],
    ['ば', 'ba', 'ha', 'pa', 'ma'], ['び', 'bi', 'hi', 'pi', 'mi'], ['ぶ', 'bu', 'fu', 'pu', 'mu'], ['べ', 'be', 'he', 'pe', 'me'], ['ぼ', 'bo', 'ho', 'po', 'mo'],
    ['ぱ', 'pa', 'ba', 'ha', 'ma'], ['ぴ', 'pi', 'bi', 'hi', 'mi'], ['ぷ', 'pu', 'bu', 'fu', 'mu'], ['ぺ', 'pe', 'be', 'he', 'me'], ['ぽ', 'po', 'bo', 'ho', 'mo'],
    ['きゃ', 'kya', 'kyu', 'kyo', 'gya'], ['きゅ', 'kyu', 'kya', 'kyo', 'gyu'], ['きょ', 'kyo', 'kya', 'kyu', 'gyo'],
    ['ぎゃ', 'gya', 'kya', 'bya', 'ja'], ['ぎゅ', 'gyu', 'kyu', 'byu', 'ju'], ['ぎょ', 'gyo', 'kyo', 'byo', 'jo'],
    ['しゃ', 'sha', 'shu', 'sho', 'cha'], ['しゅ', 'shu', 'sha', 'sho', 'chu'], ['しょ', 'sho', 'sha', 'shu', 'cho'],
    ['ちゃ', 'cha', 'sha', 'ja', 'kya'], ['ちゅ', 'chu', 'shu', 'ju', 'kyu'], ['ちょ', 'cho', 'sho', 'jo', 'kyo'],
    ['にゃ', 'nya', 'mya', 'rya', 'kya'], ['にゅ', 'nyu', 'myu', 'ryu', 'kyu'], ['にょ', 'nyo', 'myo', 'ryo', 'kyo'],
    ['ひゃ', 'hya', 'bya', 'pya', 'mya'], ['ひゅ', 'hyu', 'byu', 'pyu', 'myu'], ['ひょ', 'hyo', 'byo', 'pyo', 'myo'],
    ['みゃ', 'mya', 'nya', 'rya', 'hya'], ['みゅ', 'myu', 'nyu', 'ryu', 'hyu'], ['みょ', 'myo', 'nyo', 'ryo', 'hyo'],
    ['りゃ', 'rya', 'nya', 'mya', 'kya'], ['りゅ', 'ryu', 'nyu', 'myu', 'kyu'], ['りょ', 'ryo', 'nyo', 'myo', 'kyo'],
    ['じゃ', 'ja', 'sha', 'cha', 'gya'], ['じゅ', 'ju', 'shu', 'chu', 'gyu'], ['じょ', 'jo', 'sho', 'cho', 'gyo'],
    ['びゃ', 'bya', 'pya', 'hya', 'mya'], ['びゅ', 'byu', 'pyu', 'hyu', 'myu'], ['びょ', 'byo', 'pyo', 'hyo', 'myo'],
    ['ぴゃ', 'pya', 'bya', 'hya', 'mya'], ['ぴゅ', 'pyu', 'byu', 'hyu', 'myu'], ['ぴょ', 'pyo', 'byo', 'hyo', 'myo'],
  ],
  katakana: [
    ['ア', 'a', 'i', 'u', 'e'], ['イ', 'i', 'a', 'ki', 'e'], ['ウ', 'u', 'o', 'a', 'ku'], ['エ', 'e', 'i', 'o', 'ne'], ['オ', 'o', 'a', 'u', 'ko'],
    ['カ', 'ka', 'ki', 'sa', 'ta'], ['キ', 'ki', 'ka', 'shi', 'ni'], ['ク', 'ku', 'su', 'tsu', 'nu'], ['ケ', 'ke', 'se', 'te', 'ne'], ['コ', 'ko', 'so', 'to', 'no'],
    ['サ', 'sa', 'ka', 'ta', 'na'], ['シ', 'shi', 'chi', 'ki', 'ji'], ['ス', 'su', 'ku', 'tsu', 'zu'], ['セ', 'se', 'ke', 'te', 'ze'], ['ソ', 'so', 'ko', 'to', 'zo'],
    ['タ', 'ta', 'sa', 'na', 'ka'], ['チ', 'chi', 'shi', 'ni', 'ji'], ['ツ', 'tsu', 'su', 'ku', 'zu'], ['テ', 'te', 'se', 'ke', 'de'], ['ト', 'to', 'so', 'ko', 'do'],
    ['ナ', 'na', 'ta', 'sa', 'ma'], ['ニ', 'ni', 'chi', 'mi', 'ki'], ['ヌ', 'nu', 'su', 'mu', 'ku'], ['ネ', 'ne', 'te', 'me', 'se'], ['ノ', 'no', 'to', 'mo', 'so'],
    ['ハ', 'ha', 'na', 'ma', 'ra'], ['ヒ', 'hi', 'ni', 'mi', 'ri'], ['フ', 'fu', 'su', 'mu', 'nu'], ['ヘ', 'he', 'se', 'me', 'ne'], ['ホ', 'ho', 'no', 'mo', 'so'],
    ['マ', 'ma', 'ha', 'na', 'ra'], ['ミ', 'mi', 'hi', 'ni', 'ri'], ['ム', 'mu', 'fu', 'nu', 'su'], ['メ', 'me', 'he', 'ne', 'se'], ['モ', 'mo', 'ho', 'no', 'to'],
    ['ヤ', 'ya', 'ma', 'ra', 'wa'], ['ユ', 'yu', 'mu', 'ru', 'fu'], ['ヨ', 'yo', 'mo', 'ro', 'no'],
    ['ラ', 'ra', 'ya', 'ma', 'wa'], ['リ', 'ri', 'mi', 'hi', 'ni'], ['ル', 'ru', 'mu', 'yu', 'fu'], ['レ', 're', 'me', 'he', 'ne'], ['ロ', 'ro', 'mo', 'yo', 'no'],
    ['ワ', 'wa', 'ya', 'ra', 'ma'], ['ヲ', 'wo', 'wa', 'yo', 'ro'], ['ン', 'n', 'wa', 'no', 'mu'],
    ['ガ', 'ga', 'ka', 'da', 'za'], ['ギ', 'gi', 'ki', 'ji', 'zi'], ['グ', 'gu', 'ku', 'zu', 'du'], ['ゲ', 'ge', 'ke', 'ze', 'de'], ['ゴ', 'go', 'ko', 'zo', 'do'],
    ['ザ', 'za', 'sa', 'ga', 'da'], ['ジ', 'ji', 'shi', 'chi', 'gi'], ['ズ', 'zu', 'su', 'gu', 'du'], ['ゼ', 'ze', 'se', 'ge', 'de'], ['ゾ', 'zo', 'so', 'go', 'do'],
    ['ダ', 'da', 'ta', 'ga', 'za'], ['ヂ', 'ji', 'chi', 'di', 'gi'], ['ヅ', 'zu', 'tsu', 'du', 'gu'], ['デ', 'de', 'te', 'ge', 'ze'], ['ド', 'do', 'to', 'go', 'zo'],
    ['バ', 'ba', 'ha', 'pa', 'ma'], ['ビ', 'bi', 'hi', 'pi', 'mi'], ['ブ', 'bu', 'fu', 'pu', 'mu'], ['ベ', 'be', 'he', 'pe', 'me'], ['ボ', 'bo', 'ho', 'po', 'mo'],
    ['パ', 'pa', 'ba', 'ha', 'ma'], ['ピ', 'pi', 'bi', 'hi', 'mi'], ['プ', 'pu', 'bu', 'fu', 'mu'], ['ペ', 'pe', 'be', 'he', 'me'], ['ポ', 'po', 'bo', 'ho', 'mo'],
    ['キャ', 'kya', 'kyu', 'kyo', 'gya'], ['キュ', 'kyu', 'kya', 'kyo', 'gyu'], ['キョ', 'kyo', 'kya', 'kyu', 'gyo'],
    ['ギャ', 'gya', 'kya', 'bya', 'ja'], ['ギュ', 'gyu', 'kyu', 'byu', 'ju'], ['ギョ', 'gyo', 'kyo', 'byo', 'jo'],
    ['シャ', 'sha', 'shu', 'sho', 'cha'], ['シュ', 'shu', 'sha', 'sho', 'chu'], ['ショ', 'sho', 'sha', 'shu', 'cho'],
    ['チャ', 'cha', 'sha', 'ja', 'kya'], ['チュ', 'chu', 'shu', 'ju', 'kyu'], ['チョ', 'cho', 'sho', 'jo', 'kyo'],
    ['ニャ', 'nya', 'mya', 'rya', 'kya'], ['ニュ', 'nyu', 'myu', 'ryu', 'kyu'], ['ニョ', 'nyo', 'myo', 'ryo', 'kyo'],
    ['ヒャ', 'hya', 'bya', 'pya', 'mya'], ['ヒュ', 'hyu', 'byu', 'pyu', 'myu'], ['ヒョ', 'hyo', 'byo', 'pyo', 'myo'],
    ['ミャ', 'mya', 'nya', 'rya', 'hya'], ['ミュ', 'myu', 'nyu', 'ryu', 'hyu'], ['ミョ', 'myo', 'nyo', 'ryo', 'hyo'],
    ['リャ', 'rya', 'nya', 'mya', 'kya'], ['リュ', 'ryu', 'nyu', 'myu', 'kyu'], ['リョ', 'ryo', 'nyo', 'myo', 'kyo'],
    ['ジャ', 'ja', 'sha', 'cha', 'gya'], ['ジュ', 'ju', 'shu', 'chu', 'gyu'], ['ジョ', 'jo', 'sho', 'cho', 'gyo'],
    ['ビャ', 'bya', 'pya', 'hya', 'mya'], ['ビュ', 'byu', 'pyu', 'hyu', 'myu'], ['ビョ', 'byo', 'pyo', 'hyo', 'myo'],
    ['ピャ', 'pya', 'bya', 'hya', 'mya'], ['ピュ', 'pyu', 'byu', 'hyu', 'myu'], ['ピョ', 'pyo', 'byo', 'hyo', 'myo'],
  ],
}

export const hiragana = makeQuestions(kanaRows.hiragana)
export const katakana = makeQuestions(kanaRows.katakana)

const kanjiRows = [
  ['一', 'ichi'], ['二', 'ni'], ['三', 'san'], ['四', 'yon'], ['五', 'go'],
  ['六', 'roku'], ['七', 'nana'], ['八', 'hachi'], ['九', 'kyuu'], ['十', 'juu'],
  ['百', 'hyaku'], ['千', 'sen'], ['万', 'man'], ['円', 'en'], ['日', 'nichi'],
  ['月', 'getsu'], ['火', 'ka'], ['水', 'sui'], ['木', 'moku'], ['金', 'kin'],
  ['土', 'do'], ['曜', 'you'], ['年', 'nen'], ['時', 'ji'], ['分', 'fun'],
  ['半', 'han'], ['今', 'ima'], ['毎', 'mai'], ['何', 'nani'], ['人', 'hito'],
  ['男', 'otoko'], ['女', 'onna'], ['子', 'ko'], ['父', 'chichi'], ['母', 'haha'],
  ['友', 'tomo'], ['先', 'sen'], ['生', 'sei'], ['学', 'gaku'], ['校', 'kou'],
  ['本', 'hon'], ['語', 'go'], ['国', 'kuni'], ['会', 'kai'], ['社', 'sha'],
  ['店', 'mise'], ['駅', 'eki'], ['車', 'kuruma'], ['電', 'den'], ['気', 'ki'],
  ['天', 'ten'], ['雨', 'ame'], ['空', 'sora'], ['山', 'yama'], ['川', 'kawa'],
  ['花', 'hana'], ['魚', 'sakana'], ['口', 'kuchi'], ['目', 'me'], ['耳', 'mimi'],
  ['手', 'te'], ['足', 'ashi'], ['力', 'chikara'], ['上', 'ue'], ['下', 'shita'],
  ['中', 'naka'], ['外', 'soto'], ['右', 'migi'], ['左', 'hidari'], ['前', 'mae'],
  ['後', 'ato'], ['北', 'kita'], ['南', 'minami'], ['東', 'higashi'], ['西', 'nishi'],
  ['大', 'oo'], ['小', 'chii'], ['少', 'suku'], ['多', 'oo'], ['長', 'naga'],
  ['高', 'taka'], ['安', 'yasu'], ['新', 'atara'], ['古', 'furu'], ['白', 'shiro'],
  ['赤', 'aka'], ['青', 'ao'], ['行', 'iku'], ['来', 'kuru'], ['見', 'mi'],
  ['聞', 'kiku'], ['食', 'tabe'], ['飲', 'nomi'], ['読', 'yomi'], ['書', 'kaki'],
  ['話', 'hana'], ['買', 'kai'], ['休', 'yasu'], ['出', 'de'], ['入', 'hai'],
  ['立', 'tachi'], ['名', 'na'], ['道', 'michi'], ['週', 'shuu'], ['間', 'aida'],
]

export const kanjiN5 = makeQuestions(
  kanjiRows.map(([kana, answer], index) => {
    const alts = kanjiRows
      .filter((_, altIndex) => altIndex !== index)
      .slice(index + 1)
      .concat(kanjiRows.slice(0, index))
      .map(([, reading]) => reading)
    return [kana, answer, ...alts]
  })
)

export const characterGroups = {
  hiragana: [
    { label: 'あ', chars: kanaRows.hiragana.slice(0, 5) },
    { label: 'か', chars: kanaRows.hiragana.slice(5, 10) },
    { label: 'さ', chars: kanaRows.hiragana.slice(10, 15) },
    { label: 'た', chars: kanaRows.hiragana.slice(15, 20) },
    { label: 'な', chars: kanaRows.hiragana.slice(20, 25) },
    { label: 'は', chars: kanaRows.hiragana.slice(25, 30) },
    { label: 'ま', chars: kanaRows.hiragana.slice(30, 35) },
    { label: 'や', chars: kanaRows.hiragana.slice(35, 38) },
    { label: 'ら', chars: kanaRows.hiragana.slice(38, 43) },
    { label: 'わ', chars: kanaRows.hiragana.slice(43, 46) },
    { label: 'Dakuten', chars: kanaRows.hiragana.slice(46, 71) },
    { label: 'Combinations', chars: kanaRows.hiragana.slice(71) },
  ],
  katakana: [
    { label: 'ア', chars: kanaRows.katakana.slice(0, 5) },
    { label: 'カ', chars: kanaRows.katakana.slice(5, 10) },
    { label: 'サ', chars: kanaRows.katakana.slice(10, 15) },
    { label: 'タ', chars: kanaRows.katakana.slice(15, 20) },
    { label: 'ナ', chars: kanaRows.katakana.slice(20, 25) },
    { label: 'ハ', chars: kanaRows.katakana.slice(25, 30) },
    { label: 'マ', chars: kanaRows.katakana.slice(30, 35) },
    { label: 'ヤ', chars: kanaRows.katakana.slice(35, 38) },
    { label: 'ラ', chars: kanaRows.katakana.slice(38, 43) },
    { label: 'ワ', chars: kanaRows.katakana.slice(43, 46) },
    { label: 'Dakuten', chars: kanaRows.katakana.slice(46, 71) },
    { label: 'Combinations', chars: kanaRows.katakana.slice(71) },
  ],
  kanji: [
    { label: 'Numbers', chars: kanjiN5.slice(0, 13).map(({ kana, answer }) => [kana, answer]) },
    { label: 'Nature', chars: kanjiN5.slice(13, 22).map(({ kana, answer }) => [kana, answer]) },
    { label: 'People', chars: kanjiN5.slice(22, 30).map(({ kana, answer }) => [kana, answer]) },
    { label: 'Description', chars: kanjiN5.slice(30, 35).map(({ kana, answer }) => [kana, answer]) },
    { label: 'General', chars: kanjiN5.slice(35).map(({ kana, answer }) => [kana, answer]) },
  ],
}

export const vocab = [
  { jp: '水', reading: 'mizu', meaning: 'ماء' },
  { jp: '食べる', reading: 'taberu', meaning: 'يأكل' },
  { jp: '学校', reading: 'gakkou', meaning: 'مدرسة' },
  { jp: '友達', reading: 'tomodachi', meaning: 'صديق' },
  { jp: '電車', reading: 'densha', meaning: 'قطار' },
  { jp: 'ありがとう', reading: 'arigatou', meaning: 'شكرا' },
  { jp: 'すみません', reading: 'sumimasen', meaning: 'عذرا' },
  { jp: 'はい', reading: 'hai', meaning: 'نعم' },
  { jp: 'いいえ', reading: 'iie', meaning: 'لا' },
  { jp: '先生', reading: 'sensei', meaning: 'أستاذ' },
]

export const lessons = [
  {
    id: 1,
    title: { ar: 'تحية وتعارف', en: 'Greetings and Introductions' },
    focus: 'بناء جمل بسيطة للتعريف عن النفس',
    vocab: [
      { jp: '私', kanji: '私', hiragana: 'わたし', reading: 'watashi', meaning: 'أنا' },
      { jp: '私たち', kanji: '私たち', hiragana: 'わたしたち', reading: 'watashitachi', meaning: 'نحن' },
      { jp: '貴方', kanji: '貴方', hiragana: 'あなた', reading: 'anata', meaning: 'أنت' },
      { jp: 'あの人', kanji: 'あの人', hiragana: 'あのひと', reading: 'ano hito', meaning: 'ذلك الشخص / تلك السيدة' },
      { jp: 'あの方', kanji: 'あの方', hiragana: 'あのかた', reading: 'ano kata', meaning: 'تلك الجهة (صيغة مهذبة)' },
      { jp: '皆さん', kanji: '皆さん', hiragana: 'みなさん', reading: 'minna-san', meaning: 'الجميع' },
      { jp: '～さん', hiragana: '～さん', reading: '~san', meaning: 'السيد / السيدة' },
      { jp: '～ちゃん', hiragana: '～ちゃん', reading: '~chan', meaning: 'لاحقة للأطفال أو المقربين' },
      { jp: '～くん', hiragana: '～くん', reading: '~kun', meaning: 'لاحقة للشباب أو الأولاد' },
      { jp: '～じん', hiragana: '～じん', reading: '~jin', meaning: 'لاحقة رسمية محترمة' },
      { jp: '先生', kanji: '先生', hiragana: 'せんせい', reading: 'sensei', meaning: 'أستاذ / معلم' },
      { jp: '教師', kanji: '教師', hiragana: 'きょうし', reading: 'kyoushi', meaning: 'مدرس' },
      { jp: '学生', kanji: '学生', hiragana: 'がくせい', reading: 'gakusei', meaning: 'طالب' },
      { jp: '会社員', kanji: '会社員', hiragana: 'かいしゃいん', reading: 'kaishain', meaning: 'موظف شركة' },
      { jp: '社員', kanji: '社員', hiragana: 'しゃいん', reading: 'shain', meaning: 'موظف' },
      { jp: '銀行員', kanji: '銀行員', hiragana: 'ぎんこういん', reading: 'ginkouin', meaning: 'موظف بنك' },
      { jp: '医者', kanji: '医者', hiragana: 'いしゃ', reading: 'isha', meaning: 'طبيب' },
      { jp: '研究者', kanji: '研究者', hiragana: 'けんきゅうしゃ', reading: 'kenkyuusha', meaning: 'باحث' },
      { jp: 'エンジニア', hiragana: 'エンジニア', reading: 'enjinia', meaning: 'مهندس' },
      { jp: '大学', kanji: '大学', hiragana: 'だいがく', reading: 'daigaku', meaning: 'جامعة' },
      { jp: '病院', kanji: '病院', hiragana: 'びょういん', reading: 'byouin', meaning: 'مستشفى' },
      { jp: '電気', kanji: '電気', hiragana: 'でんき', reading: 'denki', meaning: 'كهرباء' },
      { jp: '誰', kanji: '誰', hiragana: 'だれ', reading: 'dare', meaning: 'من' },
      { jp: 'どなた', hiragana: 'どなた', reading: 'donata', meaning: 'من (صيغة مهذبة)' },
      { jp: '何歳ですか', kanji: '何歳ですか', hiragana: 'なんさいですか', reading: 'nan-sai desu ka', meaning: 'كم عمرك؟' },
      { jp: '歳', kanji: '歳', hiragana: 'さい', reading: 'sai', meaning: 'سنة (عمر)' },
      { jp: 'はい', hiragana: 'はい', reading: 'hai', meaning: 'نعم' },
      { jp: 'いいえ', hiragana: 'いいえ', reading: 'iie', meaning: 'لا' },
    ],
    grammar: [
      { title: 'は (wa) — أداة الموضوع', pattern: 'الاسم 1 + は + الاسم 2 + です', explanation: 'تستخدم は لتحديد موضوع الجملة، أي الشيء أو الشخص الذي نتحدث عنه.', example: { jp: 'わたし は ミラー です。', romaji: 'Watashi wa Mirā desu.', ar: 'أنا ميرا.' } },
      { title: 'です (desu) — فعل الكينونة', pattern: 'الاسم + です', explanation: 'تأتي في نهاية الجملة الاسمية وتعطي معنى يكون / هو / هي.', example: { jp: 'わたし は エンジニア です。', romaji: 'Watashi wa enjinia desu.', ar: 'أنا مهندس.' } },
      { title: 'じゃありません — النفي', pattern: 'الاسم 1 + は + الاسم 2 + じゃありません', explanation: 'تستخدم لنفي الجملة الاسمية وتعني ليس.', example: { jp: 'サントスさん は がくせい じゃありません。', romaji: 'Santos-san wa gakusei ja arimasen.', ar: 'السيد سانتوس ليس طالبا.' } },
      { title: 'か (ka) — أداة السؤال', pattern: 'جملة + か', explanation: 'توضع في نهاية الجملة لتحويلها إلى سؤال.', example: { jp: 'あなた は がくせい ですか。', romaji: 'Anata wa gakusei desu ka.', ar: 'هل أنت طالب؟' } },
      { title: 'الإجابة على السؤال', pattern: 'はい、〜です。 / いいえ、〜じゃありません。', explanation: 'はい تعني نعم، وいいえ تعني لا.', example: { jp: 'はい、がくせい です。', romaji: 'Hai, gakusei desu.', ar: 'نعم، أنا طالب.' } },
      { title: 'どなたですか — من هو؟', pattern: 'الشخص + は + どなた ですか', explanation: 'تستخدم للسؤال عن هوية شخص باحترام.', example: { jp: 'あの かた は どなた ですか。', romaji: 'Ano kata wa donata desu ka.', ar: 'من ذلك الشخص؟' } },
      { title: 'も (mo) — أيضا', pattern: 'الاسم 1 + も + الاسم 2 + です', explanation: 'تستبدل は عندما تريد قول أيضا.', example: { jp: 'クプタさん も かいしゃいん です。', romaji: 'Kupta-san mo kaishain desu.', ar: 'السيد كوبتا موظف شركة أيضا.' } },
      { title: 'の (no) — الملكية أو الانتماء', pattern: 'الاسم 1 + の + الاسم 2', explanation: 'تربط اسمين وتعطي معنى التابع لـ أو الخاص بـ.', example: { jp: 'ミラーさん は IMC の しゃいん です。', romaji: 'Mirā-san wa IMC no shain desu.', ar: 'السيد ميرا موظف في شركة IMC.' } },
      { title: 'さん (san) — لاحقة الاحترام', pattern: 'الاسم + さん', explanation: 'تستخدم بعد أسماء الأشخاص للدلالة على الاحترام.', example: { jp: 'ミラーさん は せんせい です。', romaji: 'Mirā-san wa sensei desu.', ar: 'السيد ميرا أستاذ.' } },
      { title: 'حذف الاسم المكرر', pattern: 'يمكن حذف الاسم إذا كان واضحا من السياق', explanation: 'في اليابانية لا يكرر الاسم إذا كان معروفا من سياق الحديث.', example: { jp: 'いいえ、かいしゃいん です。', romaji: 'Iie, kaishain desu.', ar: 'لا، موظف شركة.' } },
    ],
    examples: [
      { jp: 'わたし は がくせい です。', ar: 'أنا طالب.', en: 'I am a student.' },
      { jp: 'あなた は せんせい ですか。', ar: 'هل أنت أستاذ؟', en: 'Are you a teacher?' },
    ],
    exercises: [
      { type: 'choose', prompt: 'اختر الترجمة الصحيحة: 私 は 学生 です。', answer: 'أنا طالب.', hint: 'نوع: اختيار معنى الجملة' },
      { type: 'complete', prompt: 'أكمل الجملة: あなた は がくせい ___ か。', answer: 'です', hint: 'نوع: إكمال القاعدة' },
      { type: 'order', prompt: 'رتب الجملة: です / わたし / エンジニア / は', answer: 'わたし は エンジニア です。', hint: 'نوع: ترتيب كلمات' },
    ],
    videos: [],
  },
  {
    id: 2,
    title: { ar: 'الأشياء حولنا', en: 'Things Around Us' },
    focus: 'これ / それ / あれ',
    vocab: [
      { jp: 'これ', reading: 'kore', meaning: 'هذا' },
      { jp: 'それ', reading: 'sore', meaning: 'ذلك' },
      { jp: 'あれ', reading: 'are', meaning: 'ذاك' },
      { jp: 'ほん', reading: 'hon', meaning: 'كتاب' },
      { jp: 'かばん', reading: 'kaban', meaning: 'حقيبة' },
      { jp: 'えんぴつ', reading: 'enpitsu', meaning: 'قلم رصاص' },
    ],
    grammar: { ar: 'これ は X です — هذا هو X', en: 'これ は X です — This is X' },
    examples: [
      { jp: 'これはほんです。', ar: 'هذا كتاب.', en: 'This is a book.' },
      { jp: 'それはなんですか。', ar: 'ما هذا؟', en: 'What is that?' },
    ],
  },
  {
    id: 3,
    title: { ar: 'الأرقام والوقت', en: 'Numbers & Time' },
    focus: 'なんじ',
    vocab: [
      { jp: 'いち', reading: 'ichi', meaning: 'واحد' },
      { jp: 'に', reading: 'ni', meaning: 'اثنان' },
      { jp: 'さん', reading: 'san', meaning: 'ثلاثة' },
      { jp: 'よん', reading: 'yon', meaning: 'أربعة' },
      { jp: 'ご', reading: 'go', meaning: 'خمسة' },
      { jp: 'なんじ', reading: 'nanji', meaning: 'كم الساعة؟' },
    ],
    grammar: { ar: 'X じ です — الساعة X', en: 'X じ です — It is X o clock' },
    examples: [
      { jp: 'いまなんじですか。', ar: 'كم الساعة الآن؟', en: 'What time is it now?' },
      { jp: 'くじです。', ar: 'الساعة التاسعة.', en: 'It is nine.' },
    ],
  },
  {
    id: 4,
    title: { ar: 'الأنشطة اليومية', en: 'Daily Activities' },
    focus: 'ます',
    vocab: [
      { jp: 'たべます', reading: 'tabemasu', meaning: 'يأكل' },
      { jp: 'のみます', reading: 'nomimasu', meaning: 'يشرب' },
      { jp: 'みます', reading: 'mimasu', meaning: 'يشاهد' },
      { jp: 'ききます', reading: 'kikimasu', meaning: 'يسمع' },
      { jp: 'よみます', reading: 'yomimasu', meaning: 'يقرأ' },
      { jp: 'かきます', reading: 'kakimasu', meaning: 'يكتب' },
    ],
    grammar: { ar: 'فعل + ます — صيغة مهذبة للفعل', en: 'Verb + ます — polite verb form' },
    examples: [
      { jp: 'まいあさごはんをたべます。', ar: 'آكل الفطور كل صباح.', en: 'I eat breakfast every morning.' },
      { jp: 'なんじにねますか。', ar: 'في كم تنام؟', en: 'What time do you sleep?' },
    ],
  },
  {
    id: 5,
    title: { ar: 'المواصلات والتنقل', en: 'Transportation' },
    focus: 'で / に',
    vocab: [
      { jp: 'いきます', reading: 'ikimasu', meaning: 'يذهب' },
      { jp: 'きます', reading: 'kimasu', meaning: 'يأتي' },
      { jp: 'かえります', reading: 'kaerimasu', meaning: 'يرجع' },
      { jp: 'でんしゃ', reading: 'densha', meaning: 'قطار' },
      { jp: 'バス', reading: 'basu', meaning: 'باص' },
      { jp: 'えき', reading: 'eki', meaning: 'محطة' },
    ],
    grammar: { ar: 'X で Y に いきます — أذهب إلى Y بواسطة X', en: 'X で Y に いきます — Go to Y by X' },
    examples: [
      { jp: 'でんしゃでがっこうにいきます。', ar: 'أذهب إلى المدرسة بالقطار.', en: 'I go to school by train.' },
      { jp: 'どこにいきますか。', ar: 'إلى أين تذهب؟', en: 'Where are you going?' },
    ],
  },
]
