export const hiragana = [
  // あ行
  { kana: 'あ', answer: 'a',   options: ['a','i','u','e'] },
  { kana: 'い', answer: 'i',   options: ['a','i','ka','ki'] },
  { kana: 'う', answer: 'u',   options: ['u','e','o','a'] },
  { kana: 'え', answer: 'e',   options: ['i','e','u','o'] },
  { kana: 'お', answer: 'o',   options: ['o','a','e','u'] },
  // か行
  { kana: 'か', answer: 'ka',  options: ['ka','ki','sa','ta'] },
  { kana: 'き', answer: 'ki',  options: ['ka','ki','ku','shi'] },
  { kana: 'く', answer: 'ku',  options: ['ku','ka','su','tsu'] },
  { kana: 'け', answer: 'ke',  options: ['ke','ka','se','te'] },
  { kana: 'こ', answer: 'ko',  options: ['ko','ku','so','to'] },
  // さ行
  { kana: 'さ', answer: 'sa',  options: ['sa','ka','ta','na'] },
  { kana: 'し', answer: 'shi', options: ['shi','chi','si','ki'] },
  { kana: 'す', answer: 'su',  options: ['su','ku','tsu','nu'] },
  { kana: 'せ', answer: 'se',  options: ['se','ke','te','ne'] },
  { kana: 'そ', answer: 'so',  options: ['so','ko','to','no'] },
  // た行
  { kana: 'た', answer: 'ta',  options: ['ta','sa','na','ka'] },
  { kana: 'ち', answer: 'chi', options: ['chi','shi','ni','ki'] },
  { kana: 'つ', answer: 'tsu', options: ['tsu','su','ku','nu'] },
  { kana: 'て', answer: 'te',  options: ['te','se','ke','ne'] },
  { kana: 'と', answer: 'to',  options: ['to','so','ko','no'] },
  // な行
  { kana: 'な', answer: 'na',  options: ['na','ta','sa','ma'] },
  { kana: 'に', answer: 'ni',  options: ['ni','chi','mi','ki'] },
  { kana: 'ぬ', answer: 'nu',  options: ['nu','su','mu','ku'] },
  { kana: 'ね', answer: 'ne',  options: ['ne','te','me','se'] },
  { kana: 'の', answer: 'no',  options: ['no','to','mo','so'] },
  // は行
  { kana: 'は', answer: 'ha',  options: ['ha','na','ma','ra'] },
  { kana: 'ひ', answer: 'hi',  options: ['hi','ni','mi','ri'] },
  { kana: 'ふ', answer: 'fu',  options: ['fu','su','mu','nu'] },
  { kana: 'へ', answer: 'he',  options: ['he','se','me','ne'] },
  { kana: 'ほ', answer: 'ho',  options: ['ho','no','mo','so'] },
  // ま行
  { kana: 'ま', answer: 'ma',  options: ['ma','ha','na','ra'] },
  { kana: 'み', answer: 'mi',  options: ['mi','hi','ni','ri'] },
  { kana: 'む', answer: 'mu',  options: ['mu','fu','nu','su'] },
  { kana: 'め', answer: 'me',  options: ['me','he','ne','se'] },
  { kana: 'も', answer: 'mo',  options: ['mo','ho','no','to'] },
  // や行
  { kana: 'や', answer: 'ya',  options: ['ya','ma','ra','wa'] },
  { kana: 'ゆ', answer: 'yu',  options: ['yu','mu','ru','fu'] },
  { kana: 'よ', answer: 'yo',  options: ['yo','mo','ro','no'] },
  // ら行
  { kana: 'ら', answer: 'ra',  options: ['ra','ya','ma','wa'] },
  { kana: 'り', answer: 'ri',  options: ['ri','mi','hi','ni'] },
  { kana: 'る', answer: 'ru',  options: ['ru','mu','yu','fu'] },
  { kana: 'れ', answer: 're',  options: ['re','me','he','ne'] },
  { kana: 'ろ', answer: 'ro',  options: ['ro','mo','yo','no'] },
  // わ行
  { kana: 'わ', answer: 'wa',  options: ['wa','ya','ra','ma'] },
  { kana: 'を', answer: 'wo',  options: ['wo','wa','yo','ro'] },
  { kana: 'ん', answer: 'n',   options: ['n','wa','no','mu'] },
  // が行 (dakuten)
  { kana: 'が', answer: 'ga',  options: ['ga','ka','da','za'] },
  { kana: 'ぎ', answer: 'gi',  options: ['gi','ki','di','zi'] },
  { kana: 'ぐ', answer: 'gu',  options: ['gu','ku','zu','du'] },
  { kana: 'げ', answer: 'ge',  options: ['ge','ke','ze','de'] },
  { kana: 'ご', answer: 'go',  options: ['go','ko','zo','do'] },
  // ざ行
  { kana: 'ざ', answer: 'za',  options: ['za','sa','ga','da'] },
  { kana: 'じ', answer: 'ji',  options: ['ji','shi','gi','di'] },
  { kana: 'ず', answer: 'zu',  options: ['zu','su','gu','du'] },
  { kana: 'ぜ', answer: 'ze',  options: ['ze','se','ge','de'] },
  { kana: 'ぞ', answer: 'zo',  options: ['zo','so','go','do'] },
  // だ行
  { kana: 'だ', answer: 'da',  options: ['da','ta','ga','za'] },
  { kana: 'ぢ', answer: 'di',  options: ['di','chi','ji','gi'] },
  { kana: 'づ', answer: 'du',  options: ['du','tsu','zu','gu'] },
  { kana: 'で', answer: 'de',  options: ['de','te','ge','ze'] },
  { kana: 'ど', answer: 'do',  options: ['do','to','go','zo'] },
  // ば行
  { kana: 'ば', answer: 'ba',  options: ['ba','ha','pa','ma'] },
  { kana: 'び', answer: 'bi',  options: ['bi','hi','pi','mi'] },
  { kana: 'ぶ', answer: 'bu',  options: ['bu','fu','pu','mu'] },
  { kana: 'べ', answer: 'be',  options: ['be','he','pe','me'] },
  { kana: 'ぼ', answer: 'bo',  options: ['bo','ho','po','mo'] },
  // ぱ行
  { kana: 'ぱ', answer: 'pa',  options: ['pa','ba','ha','ma'] },
  { kana: 'ぴ', answer: 'pi',  options: ['pi','bi','hi','mi'] },
  { kana: 'ぷ', answer: 'pu',  options: ['pu','bu','fu','mu'] },
  { kana: 'ぺ', answer: 'pe',  options: ['pe','be','he','me'] },
  { kana: 'ぽ', answer: 'po',  options: ['po','bo','ho','mo'] },
  // きゃ行 (combinations)
  { kana: 'きゃ', answer: 'kya', options: ['kya','kyu','kyo','gya'] },
  { kana: 'きゅ', answer: 'kyu', options: ['kyu','kya','kyo','gyu'] },
  { kana: 'きょ', answer: 'kyo', options: ['kyo','kya','kyu','gyo'] },
  { kana: 'しゃ', answer: 'sha', options: ['sha','shu','sho','cha'] },
  { kana: 'しゅ', answer: 'shu', options: ['shu','sha','sho','chu'] },
  { kana: 'しょ', answer: 'sho', options: ['sho','sha','shu','cho'] },
  { kana: 'ちゃ', answer: 'cha', options: ['cha','sha','cha','ja'] },
  { kana: 'ちゅ', answer: 'chu', options: ['chu','shu','ju','cha'] },
  { kana: 'ちょ', answer: 'cho', options: ['cho','sho','jo','cha'] },
  { kana: 'にゃ', answer: 'nya', options: ['nya','mya','rya','kya'] },
  { kana: 'にゅ', answer: 'nyu', options: ['nyu','myu','ryu','kyu'] },
  { kana: 'にょ', answer: 'nyo', options: ['nyo','myo','ryo','kyo'] },
  { kana: 'ひゃ', answer: 'hya', options: ['hya','bya','pya','mya'] },
  { kana: 'ひゅ', answer: 'hyu', options: ['hyu','byu','pyu','myu'] },
  { kana: 'ひょ', answer: 'hyo', options: ['hyo','byo','pyo','myo'] },
  { kana: 'みゃ', answer: 'mya', options: ['mya','nya','rya','hya'] },
  { kana: 'みゅ', answer: 'myu', options: ['myu','nyu','ryu','hyu'] },
  { kana: 'みょ', answer: 'myo', options: ['myo','nyo','ryo','hyo'] },
  { kana: 'りゃ', answer: 'rya', options: ['rya','nya','mya','kya'] },
  { kana: 'りゅ', answer: 'ryu', options: ['ryu','nyu','myu','kyu'] },
  { kana: 'りょ', answer: 'ryo', options: ['ryo','nyo','myo','kyo'] },
  { kana: 'ぎゃ', answer: 'gya', options: ['gya','kya','bya','ja'] },
  { kana: 'ぎゅ', answer: 'gyu', options: ['gyu','kyu','byu','ju'] },
  { kana: 'ぎょ', answer: 'gyo', options: ['gyo','kyo','byo','jo'] },
  { kana: 'じゃ', answer: 'ja',  options: ['ja','sha','cha','gya'] },
  { kana: 'じゅ', answer: 'ju',  options: ['ju','shu','chu','gyu'] },
  { kana: 'じょ', answer: 'jo',  options: ['jo','sho','cho','gyo'] },
  { kana: 'びゃ', answer: 'bya', options: ['bya','pya','hya','mya'] },
  { kana: 'びゅ', answer: 'byu', options: ['byu','pyu','hyu','myu'] },
  { kana: 'びょ', answer: 'byo', options: ['byo','pyo','hyo','myo'] },
  { kana: 'ぴゃ', answer: 'pya', options: ['pya','bya','hya','mya'] },
  { kana: 'ぴゅ', answer: 'pyu', options: ['pyu','byu','hyu','myu'] },
  { kana: 'ぴょ', answer: 'pyo', options: ['pyo','byo','hyo','myo'] },
]

export const katakana = [
  // ア行
  { kana: 'ア', answer: 'a',   options: ['a','i','u','e'] },
  { kana: 'イ', answer: 'i',   options: ['a','i','ka','ki'] },
  { kana: 'ウ', answer: 'u',   options: ['u','e','o','a'] },
  { kana: 'エ', answer: 'e',   options: ['i','e','u','o'] },
  { kana: 'オ', answer: 'o',   options: ['o','a','e','u'] },
  // カ行
  { kana: 'カ', answer: 'ka',  options: ['ka','ki','sa','ta'] },
  { kana: 'キ', answer: 'ki',  options: ['ka','ki','ku','shi'] },
  { kana: 'ク', answer: 'ku',  options: ['ku','ka','su','tsu'] },
  { kana: 'ケ', answer: 'ke',  options: ['ke','ka','se','te'] },
  { kana: 'コ', answer: 'ko',  options: ['ko','ku','so','to'] },
  // サ行
  { kana: 'サ', answer: 'sa',  options: ['sa','ka','ta','na'] },
  { kana: 'シ', answer: 'shi', options: ['shi','chi','si','ki'] },
  { kana: 'ス', answer: 'su',  options: ['su','ku','tsu','nu'] },
  { kana: 'セ', answer: 'se',  options: ['se','ke','te','ne'] },
  { kana: 'ソ', answer: 'so',  options: ['so','ko','to','no'] },
  // タ行
  { kana: 'タ', answer: 'ta',  options: ['ta','sa','na','ka'] },
  { kana: 'チ', answer: 'chi', options: ['chi','shi','ni','ki'] },
  { kana: 'ツ', answer: 'tsu', options: ['tsu','su','ku','nu'] },
  { kana: 'テ', answer: 'te',  options: ['te','se','ke','ne'] },
  { kana: 'ト', answer: 'to',  options: ['to','so','ko','no'] },
  // ナ行
  { kana: 'ナ', answer: 'na',  options: ['na','ta','sa','ma'] },
  { kana: 'ニ', answer: 'ni',  options: ['ni','chi','mi','ki'] },
  { kana: 'ヌ', answer: 'nu',  options: ['nu','su','mu','ku'] },
  { kana: 'ネ', answer: 'ne',  options: ['ne','te','me','se'] },
  { kana: 'ノ', answer: 'no',  options: ['no','to','mo','so'] },
  // ハ行
  { kana: 'ハ', answer: 'ha',  options: ['ha','na','ma','ra'] },
  { kana: 'ヒ', answer: 'hi',  options: ['hi','ni','mi','ri'] },
  { kana: 'フ', answer: 'fu',  options: ['fu','su','mu','nu'] },
  { kana: 'ヘ', answer: 'he',  options: ['he','se','me','ne'] },
  { kana: 'ホ', answer: 'ho',  options: ['ho','no','mo','so'] },
  // マ行
  { kana: 'マ', answer: 'ma',  options: ['ma','ha','na','ra'] },
  { kana: 'ミ', answer: 'mi',  options: ['mi','hi','ni','ri'] },
  { kana: 'ム', answer: 'mu',  options: ['mu','fu','nu','su'] },
  { kana: 'メ', answer: 'me',  options: ['me','he','ne','se'] },
  { kana: 'モ', answer: 'mo',  options: ['mo','ho','no','to'] },
  // ヤ行
  { kana: 'ヤ', answer: 'ya',  options: ['ya','ma','ra','wa'] },
  { kana: 'ユ', answer: 'yu',  options: ['yu','mu','ru','fu'] },
  { kana: 'ヨ', answer: 'yo',  options: ['yo','mo','ro','no'] },
  // ラ行
  { kana: 'ラ', answer: 'ra',  options: ['ra','ya','ma','wa'] },
  { kana: 'リ', answer: 'ri',  options: ['ri','mi','hi','ni'] },
  { kana: 'ル', answer: 'ru',  options: ['ru','mu','yu','fu'] },
  { kana: 'レ', answer: 're',  options: ['re','me','he','ne'] },
  { kana: 'ロ', answer: 'ro',  options: ['ro','mo','yo','no'] },
  // ワ行
  { kana: 'ワ', answer: 'wa',  options: ['wa','ya','ra','ma'] },
  { kana: 'ヲ', answer: 'wo',  options: ['wo','wa','yo','ro'] },
  { kana: 'ン', answer: 'n',   options: ['n','wa','no','mu'] },
  // ガ行
  { kana: 'ガ', answer: 'ga',  options: ['ga','ka','da','za'] },
  { kana: 'ギ', answer: 'gi',  options: ['gi','ki','di','zi'] },
  { kana: 'グ', answer: 'gu',  options: ['gu','ku','zu','du'] },
  { kana: 'ゲ', answer: 'ge',  options: ['ge','ke','ze','de'] },
  { kana: 'ゴ', answer: 'go',  options: ['go','ko','zo','do'] },
  // ザ行
  { kana: 'ザ', answer: 'za',  options: ['za','sa','ga','da'] },
  { kana: 'ジ', answer: 'ji',  options: ['ji','shi','gi','di'] },
  { kana: 'ズ', answer: 'zu',  options: ['zu','su','gu','du'] },
  { kana: 'ゼ', answer: 'ze',  options: ['ze','se','ge','de'] },
  { kana: 'ゾ', answer: 'zo',  options: ['zo','so','go','do'] },
  // ダ行
  { kana: 'ダ', answer: 'da',  options: ['da','ta','ga','za'] },
  { kana: 'ヂ', answer: 'di',  options: ['di','chi','ji','gi'] },
  { kana: 'ヅ', answer: 'du',  options: ['du','tsu','zu','gu'] },
  { kana: 'デ', answer: 'de',  options: ['de','te','ge','ze'] },
  { kana: 'ド', answer: 'do',  options: ['do','to','go','zo'] },
  // バ行
  { kana: 'バ', answer: 'ba',  options: ['ba','ha','pa','ma'] },
  { kana: 'ビ', answer: 'bi',  options: ['bi','hi','pi','mi'] },
  { kana: 'ブ', answer: 'bu',  options: ['bu','fu','pu','mu'] },
  { kana: 'ベ', answer: 'be',  options: ['be','he','pe','me'] },
  { kana: 'ボ', answer: 'bo',  options: ['bo','ho','po','mo'] },
  // パ行
  { kana: 'パ', answer: 'pa',  options: ['pa','ba','ha','ma'] },
  { kana: 'ピ', answer: 'pi',  options: ['pi','bi','hi','mi'] },
  { kana: 'プ', answer: 'pu',  options: ['pu','bu','fu','mu'] },
  { kana: 'ペ', answer: 'pe',  options: ['pe','be','he','me'] },
  { kana: 'ポ', answer: 'po',  options: ['po','bo','ho','mo'] },
  // キャ行
  { kana: 'キャ', answer: 'kya', options: ['kya','kyu','kyo','gya'] },
  { kana: 'キュ', answer: 'kyu', options: ['kyu','kya','kyo','gyu'] },
  { kana: 'キョ', answer: 'kyo', options: ['kyo','kya','kyu','gyo'] },
  { kana: 'シャ', answer: 'sha', options: ['sha','shu','sho','cha'] },
  { kana: 'シュ', answer: 'shu', options: ['shu','sha','sho','chu'] },
  { kana: 'ショ', answer: 'sho', options: ['sho','sha','shu','cho'] },
  { kana: 'チャ', answer: 'cha', options: ['cha','sha','ja','kya'] },
  { kana: 'チュ', answer: 'chu', options: ['chu','shu','ju','kyu'] },
  { kana: 'チョ', answer: 'cho', options: ['cho','sho','jo','kyo'] },
  { kana: 'ニャ', answer: 'nya', options: ['nya','mya','rya','kya'] },
  { kana: 'ニュ', answer: 'nyu', options: ['nyu','myu','ryu','kyu'] },
  { kana: 'ニョ', answer: 'nyo', options: ['nyo','myo','ryo','kyo'] },
  { kana: 'ヒャ', answer: 'hya', options: ['hya','bya','pya','mya'] },
  { kana: 'ヒュ', answer: 'hyu', options: ['hyu','byu','pyu','myu'] },
  { kana: 'ヒョ', answer: 'hyo', options: ['hyo','byo','pyo','myo'] },
  { kana: 'ミャ', answer: 'mya', options: ['mya','nya','rya','hya'] },
  { kana: 'ミュ', answer: 'myu', options: ['myu','nyu','ryu','hyu'] },
  { kana: 'ミョ', answer: 'myo', options: ['myo','nyo','ryo','hyo'] },
  { kana: 'リャ', answer: 'rya', options: ['rya','nya','mya','kya'] },
  { kana: 'リュ', answer: 'ryu', options: ['ryu','nyu','myu','kyu'] },
  { kana: 'リョ', answer: 'ryo', options: ['ryo','nyo','myo','kyo'] },
  { kana: 'ギャ', answer: 'gya', options: ['gya','kya','bya','ja'] },
  { kana: 'ギュ', answer: 'gyu', options: ['gyu','kyu','byu','ju'] },
  { kana: 'ギョ', answer: 'gyo', options: ['gyo','kyo','byo','jo'] },
  { kana: 'ジャ', answer: 'ja',  options: ['ja','sha','cha','gya'] },
  { kana: 'ジュ', answer: 'ju',  options: ['ju','shu','chu','gyu'] },
  { kana: 'ジョ', answer: 'jo',  options: ['jo','sho','cho','gyo'] },
  { kana: 'ビャ', answer: 'bya', options: ['bya','pya','hya','mya'] },
  { kana: 'ビュ', answer: 'byu', options: ['byu','pyu','hyu','myu'] },
  { kana: 'ビョ', answer: 'byo', options: ['byo','pyo','hyo','myo'] },
  { kana: 'ピャ', answer: 'pya', options: ['pya','bya','hya','mya'] },
  { kana: 'ピュ', answer: 'pyu', options: ['pyu','byu','hyu','myu'] },
  { kana: 'ピョ', answer: 'pyo', options: ['pyo','byo','hyo','myo'] },
]

export const kanjiN5 = [
  { kana: '一', answer: 'ichi', meaning: 'واحد / one',      options: ['ichi','ni','san','shi'] },
  { kana: '二', answer: 'ni',   meaning: 'اثنان / two',     options: ['ni','ichi','san','yon'] },
  { kana: '三', answer: 'san',  meaning: 'ثلاثة / three',   options: ['san','ni','shi','go'] },
  { kana: '四', answer: 'shi',  meaning: 'أربعة / four',    options: ['shi','san','go','roku'] },
  { kana: '五', answer: 'go',   meaning: 'خمسة / five',     options: ['go','shi','roku','nana'] },
  { kana: '六', answer: 'roku', meaning: 'ستة / six',       options: ['roku','go','nana','hachi'] },
  { kana: '七', answer: 'nana', meaning: 'سبعة / seven',    options: ['nana','roku','hachi','ku'] },
  { kana: '八', answer: 'hachi',meaning: 'ثمانية / eight',  options: ['hachi','nana','ku','juu'] },
  { kana: '九', answer: 'ku',   meaning: 'تسعة / nine',     options: ['ku','hachi','juu','nana'] },
  { kana: '十', answer: 'juu',  meaning: 'عشرة / ten',      options: ['juu','ku','hyaku','nana'] },
  { kana: '百', answer: 'hyaku',meaning: 'مئة / hundred',   options: ['hyaku','juu','sen','man'] },
  { kana: '千', answer: 'sen',  meaning: 'ألف / thousand',  options: ['sen','hyaku','man','juu'] },
  { kana: '万', answer: 'man',  meaning: 'عشرة آلاف / ten thousand', options: ['man','sen','hyaku','oku'] },
  { kana: '日', answer: 'nichi',meaning: 'يوم / sun / day', options: ['nichi','tsuki','hi','mizu'] },
  { kana: '月', answer: 'tsuki',meaning: 'قمر / شهر / moon / month', options: ['tsuki','nichi','hi','yama'] },
  { kana: '火', answer: 'hi',   meaning: 'نار / fire',      options: ['hi','mizu','ki','tsuchi'] },
  { kana: '水', answer: 'mizu', meaning: 'ماء / water',     options: ['mizu','hi','ki','kaze'] },
  { kana: '木', answer: 'ki',   meaning: 'شجرة / tree',     options: ['ki','mizu','tsuchi','kawa'] },
  { kana: '金', answer: 'kin',  meaning: 'ذهب / gold',      options: ['kin','gin','dou','ki'] },
  { kana: '土', answer: 'tsuchi',meaning: 'تراب / earth',   options: ['tsuchi','mizu','ki','ishi'] },
  { kana: '山', answer: 'yama', meaning: 'جبل / mountain',  options: ['yama','kawa','umi','sora'] },
  { kana: '川', answer: 'kawa', meaning: 'نهر / river',     options: ['kawa','yama','umi','ike'] },
  { kana: '人', answer: 'hito', meaning: 'شخص / person',    options: ['hito','ko','oya','te'] },
  { kana: '口', answer: 'kuchi',meaning: 'فم / mouth',      options: ['kuchi','me','mimi','te'] },
  { kana: '手', answer: 'te',   meaning: 'يد / hand',       options: ['te','ashi','kuchi','me'] },
  { kana: '目', answer: 'me',   meaning: 'عين / eye',       options: ['me','mimi','kuchi','hana'] },
  { kana: '耳', answer: 'mimi', meaning: 'أذن / ear',       options: ['mimi','me','kuchi','hana'] },
  { kana: '子', answer: 'ko',   meaning: 'طفل / child',     options: ['ko','hito','oya','otoko'] },
  { kana: '女', answer: 'onna', meaning: 'امرأة / woman',   options: ['onna','otoko','ko','hito'] },
  { kana: '男', answer: 'otoko',meaning: 'رجل / man',       options: ['otoko','onna','ko','hito'] },
  { kana: '大', answer: 'oo',   meaning: 'كبير / big',      options: ['oo','chii','naga','futo'] },
  { kana: '小', answer: 'chii', meaning: 'صغير / small',    options: ['chii','oo','naga','hoso'] },
  { kana: '中', answer: 'naka', meaning: 'وسط / middle',    options: ['naka','soto','ue','shita'] },
  { kana: '上', answer: 'ue',   meaning: 'فوق / above',     options: ['ue','shita','naka','yoko'] },
  { kana: '下', answer: 'shita',meaning: 'تحت / below',     options: ['shita','ue','naka','mae'] },
  { kana: '本', answer: 'hon',  meaning: 'كتاب / book',     options: ['hon','kami','ki','mizu'] },
  { kana: '年', answer: 'nen',  meaning: 'سنة / year',      options: ['nen','tsuki','hi','jikan'] },
  { kana: '時', answer: 'toki', meaning: 'وقت / time',      options: ['toki','nen','tsuki','hi'] },
  { kana: '国', answer: 'kuni', meaning: 'بلد / country',   options: ['kuni','machi','mura','shima'] },
  { kana: '語', answer: 'go',   meaning: 'لغة / language',  options: ['go','ji','bun','wa'] },
]

export const vocab = [
  { jp: '水', reading: 'mizu',       meaning: 'ماء' },
  { jp: '食べる', reading: 'taberu', meaning: 'يأكل' },
  { jp: '学校', reading: 'gakkou',   meaning: 'مدرسة' },
  { jp: '友達', reading: 'tomodachi',meaning: 'صديق' },
  { jp: '電車', reading: 'densha',   meaning: 'قطار' },
  { jp: 'ありがとう', reading: 'arigatou', meaning: 'شكراً' },
  { jp: 'すみません', reading: 'sumimasen', meaning: 'عفواً' },
  { jp: 'はい', reading: 'hai',      meaning: 'نعم' },
  { jp: 'いいえ', reading: 'iie',    meaning: 'لا' },
  { jp: '先生', reading: 'sensei',   meaning: 'أستاذ' },
]