export const ICON_PACK = {
  gems: { src: '/assets/icons/gems.png', used: 'topbar gems' },
  achievement: { src: '/assets/icons/achievement.png', used: 'profile and achievements' },
  profile: { src: '/assets/icons/profile.png', used: 'profile navigation and account' },
  streak: { src: '/assets/icons/streak.png', used: 'topbar streak' },
  life: { src: '/assets/icons/life.png', used: 'battery/hearts' },
  coins: { src: '/assets/icons/coins.png', used: 'subscription and payments' },
  gift: { src: '/assets/icons/gift.png', used: 'donation/support rewards' },
  calendar: { src: '/assets/icons/calendar.png', used: 'daily challenge' },
  settings: { src: '/assets/icons/settings.png', used: 'settings' },
  home: { src: '/assets/icons/home.png', used: 'home navigation' },
  lessons: { src: '/assets/icons/lessons.png', used: 'lesson path' },
  vocabulary: { src: '/assets/icons/vocabulary.png', used: 'vocabulary sections' },
  quiz: { src: '/assets/icons/quiz.png', used: 'quiz and practice buttons' },
  writing: { src: '/assets/icons/writing.png', used: 'letters and writing practice' },
  listening: { src: '/assets/icons/listening.png', used: 'listening/audio practice' },
  speaking: { src: '/assets/icons/speaking.png', used: 'community and speaking' },
  progress: { src: '/assets/icons/progress.png', reserved: true },
  ranking: { src: '/assets/icons/ranking.png', used: 'leaderboard' },
  star: { src: '/assets/icons/star.png', used: 'completion highlights' },
  locked: { src: '/assets/icons/locked.png', used: 'locked content' },
  unlocked: { src: '/assets/icons/unlocked.png', used: 'unlocked/friends state' },
  search: { src: '/assets/icons/search.png', reserved: true },
  filter: { src: '/assets/icons/filter.png', used: 'customization/settings filters' },
  save: { src: '/assets/icons/save.png', reserved: true },
  share: { src: '/assets/icons/share.png', used: 'community share/repost' },
  messages: { src: '/assets/icons/messages.png', used: 'messages inbox' },
  notifications: { src: '/assets/icons/notifications.png', used: 'notifications inbox' },
  back: { src: '/assets/icons/back.png', used: 'back controls' },
  next: { src: '/assets/icons/next.png', reserved: true },
  play: { src: '/assets/icons/play.png', reserved: true },
  pause: { src: '/assets/icons/pause.png', reserved: true },
  correct: { src: '/assets/icons/correct.png', used: 'correct state' },
  wrong: { src: '/assets/icons/wrong.png', used: 'wrong state / close buttons' },
  info: { src: '/assets/icons/info.png', used: 'policy/info' },
  help: { src: '/assets/icons/help.png', used: 'support/help' },
  hint: { src: '/assets/icons/hint.png', reserved: true },
  files: { src: '/assets/icons/files.png', reserved: true },
  download: { src: '/assets/icons/download.png', reserved: true },
  upload: { src: '/assets/icons/upload.png', reserved: true },
  camera: { src: '/assets/icons/camera.png', used: 'profile photo camera' },
  gallery: { src: '/assets/icons/gallery.png', used: 'profile photo gallery' },
  'night-mode': { src: '/assets/icons/night-mode.png', used: 'theme toggle' },
  language: { src: '/assets/icons/language.png', used: 'language setting' },
  sound: { src: '/assets/icons/sound-clean.svg', used: 'sound setting and pronunciation playback' },
  mute: { src: '/assets/icons/mute.png', used: 'sound setting (off state)' },
  store: { src: '/assets/icons/store.png', reserved: true },
  map: { src: '/assets/icons/map.png', reserved: true },
  explore: { src: '/assets/icons/explore.png', reserved: true },
  grammar: { src: '/assets/icons/grammar.png', used: 'grammar sections' },
  culture: { src: '/assets/icons/culture.png', used: 'culture/study groups' },
  levels: { src: '/assets/icons/levels.png', reserved: true },
  goal: { src: '/assets/icons/goal.png', used: 'exercise finish state (keep practicing)' },
  timer: { src: '/assets/icons/timer.png', used: 'pending friend request state' },
  'streak-7': { src: '/assets/icons/streak-7.png', reserved: true },
}
